### ISSUE TITLE
Console: awkwardness when console is waiting for or has accepted user input

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#1028]
I have been experiencing some awkwardness around user input in the console, such as when devtools or usethis ask for user input. I haven't quite hammered out the specifics of when problems arise, so I am going to start collecting them here.

Here I chose "1" when it was waiting at "Selection:" but then "Selection:" hung around while the code was executing.

![Screenshot 2023-08-10 at 12 52 23 PM](https://github.com/rstudio/positron/assets/12505835/09946da9-7493-4026-abe5-1a8caf43f161)

It went away once the code was done.

**Comment by juliasilge** [comment]
We addressed a number of related issues here, for example with #1761 and #1701, and we no longer have the specific problems outlined in this issue. I'll close this and we can open new issues if we observe problems moving forward with the console as it is waiting for user input.

**Comment by lionel-** [comment]
The remaining issue mentioned in https://github.com/posit-dev/positron/issues/1028#issuecomment-1710276910 has been fixed too!

https://github.com/user-attachments/assets/8182605c-c547-4ec0-8890-d7ea76552339
