### ISSUE TITLE
Error after shutting down running (but not selected) R interpreter

### ISSUE THREAD

**Issue by jgutman** [posit-dev/positron#1110]
Positron Version: 2023.08.0 build 173

Steps to Reproduce:

1. Start up a new Positron session, no workspace. I am detected as an RStudio user, so my R interpreter is automatically started, with the message
```INFO Language runtime d6ea515ec747ac1c67c7239097e5d5b9 (language: R name: R (System) version: 4.3) automatically starting. Source: An extension requested the runtime to be started immediately.```
2. User decides to start Python instead, selects Python interpreter from drop down menu. Console switches to Python, and I get the message
```
INFO Starting language runtime eef6917b6c04ea97b76a6e74a60086d9 (language: Python name: Python 3.9.9 64-bit ('3.9.9') (ipykernel) version: 3.9.9) (Source: User-requested startup from the Positron top action bar)
```
Both interpreters have the green dot indicating they are running in the drop down.

3. Shut down the R interpreter. This doesn't appear to cause any user-facing issues, but I see the following errors from the extension host
<img width="754" alt="image" src="https://github.com/rstudio/positron/assets/7817881/0a721cf3-6dbc-48f4-bbee-635a810d49dd">

**Comment by juliasilge** [comment]
We've changed _a lot_ since this issue was opened, including using a whole new kernel supervisor. I no longer can reproduce these errors in any logs.

## QA Notes

Can you all confirm you also don't see this error at the current time?

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-88
    OS Version          : OSX

### Test scenario(s) 

I can no longer reproduce this error on shutdown of R.

Link(s) to TestRail test cases run or created:
