### ISSUE TITLE
Reloading with busy runtime looks frozen, breaks LSP

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#1243]
To reproduce:

1. Start R
2. Run `Sys.sleep(60)` or another long-running command
3. Reload the Positron window (Cmd+R or _Reload Window_)
4. Attempt to run another R command

It _looks_ like you can run another R command, but you can't. The runtime appears to be frozen.

https://github.com/posit-dev/positron/assets/470418/d214ba80-fb11-4b78-b0b7-c1ff349c9de6

Shortly after reload, the LSP also fails to start:

<img width="495" alt="image" src="https://github.com/posit-dev/positron/assets/470418/14f6d8fa-faf7-45f8-bf38-a17ebbb6ce31">

The source of both of these problems is that Positron is trying to reconnect to a runtime that is busy running code, but Positron doesn't _know_ it's busy running code. Consequently we don't show any busy UI, we offer an input prompt, and we try to start the LSP (which is not something you can do during a computation, at least not in R). 

The right solution to this probably requires an intermediary layer (as in #1155), but perhaps as a stopgap we can implement it directly in the language packs in some way.

**Comment by jmcphers** [comment]
I have a change on a branch that addresses this using the new Jupyter kernel supervisor.

**Comment by jmcphers** [comment]
Update: In my testing this works OK for Python. R is _better_ -- it does wait to reattach the LSP until R isn't busy -- but when it does reattach the LSP it crashes ark. This may be an ark bug or may be an ordering issue we can/should resolve on the Positron side.

**Comment by jonvanausdeln** [comment]
With the new supervisor enabled, it now waits for the running command to finish, and pops a toast message .
