### ISSUE TITLE
Make "source file" less prominent in package development mode

### ISSUE THREAD

**Issue by hadley** [posit-dev/positron#1359]
Positron Version:

Steps to reproduce the issue:

1. Open a package
2. Press Cmd + Shift + Enter
3. Current file is sourced

What did you expect to happen?

Ideally (I think), nothing, since sourcing the current file is rarely what you want when in package development mode. Should probably also remove "Source file" button from navbar.

Were there any error messages in the output or Developer Tools console?

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-8
    OS Version          : OSX

### Test scenario(s) 

Cmd + Shift + Enter no longer sources current file in R package.

Link(s) to TestRail test cases run or created: 
N/A
