### ISSUE TITLE
positron CLI returns VS Code version

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#1373]
Positron Version: Positron Version: 2023.09.0 (Universal) build 203
Code - OSS Version: 1.79.0
Commit: 519fbc791a60d21275cb20c3b8214202b99605a2
Date: 2023-09-22T02:37:21.484Z
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0

Steps to reproduce the issue:

1. call `positron --version`
2. get back `1.79.0`

What did you expect to happen?

Get the Positron version rather than VS Code version:
IE: 2023.09.0 (Universal) build 203

I'd also prefer this over having to go to About and copying the Positron version manually

Were there any error messages in the output or Developer Tools console?

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-103
    OS Version          : ubuntu

### Test scenario(s) 

positron --version
works now on ubuntu

Link(s) to TestRail test cases run or created:
