### ISSUE TITLE
Better UX for unsupported R versions

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#1397]
## Positron Version:

```
Positron Version: 2023.09.0 (Universal) build 3750
Code - OSS Version: 1.82.0
Commit: 02bfc1e31b0bf6ed389ece3f50343eebda448718
Date: 2023-09-24T21:13:03.474Z
Electron: 25.8.0
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```

## Steps to reproduce the issue:

Install R 4.0.3 on your machine. Open Positron, start R, and attempt to produce any plot. 

This results in the R kernel crashing with the following error (reported by Ferit):

```
thread 'ark-r-main-thread' panicked at 'R graphics engine version 12 is not supported by this version of Positron.',
crates/ark/src/plots/graphics_device.rs:514:5
stack backtrace:
[... 60 level backtrace follows ...]
```

## What did you expect to happen?

- The R kernel should not crash if the graphics engine isn't supported. It should print a warning to the console and continue.
- Unsupported versions of R should either (a) not be registered at all, or (b) registered but with a user-friendly warning about degraded experience (assuming that, like 4.0.3, basic code execution does work).

**Comment by juliasilge** [comment]
Do we have an issue for the similar problem for Python? Related to #5166

Can we create a consistent treatment for this across Python and R?

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2025.01.0-71](https://github.com/posit-dev/positron-builds/releases/tag/2025.01.0-71)
OS Version(s) : Windows 11

### Test scenario(s) 
Installed only R 4.1.2 and correctly recognized no install would work

<img src="https://github.com/user-attachments/assets/d66d4a7f-c2a4-43f3-94a6-1d2851e0bbe7" width=50%>


### Link(s) to TestRail test cases run or created:
