### ISSUE TITLE
Support SSL for Positron in server mode

### ISSUE THREAD

**Issue by MariaSemple** [posit-dev/positron#1424]
In order to support end-to-end encryption in Workbench, Positron's server mode will need to support SSL. These two PRs are what were required to get plain VS Code server to support SSL:
https://github.com/rstudio/vscode-server/pull/13
https://github.com/rstudio/vscode-server/pull/10

**Comment by jmcphers** [comment]
This should be addressed by https://github.com/posit-dev/positron/issues/4273, but of course we'll need to be sure that Positron-specific code works under HTTPs, too.
