### ISSUE TITLE
Remember editor choice for `.qmd` files when navigating away or renaming files

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [posit-dev/positron#1436]
## Steps to reproduce the issue:

1. Open a `.qmd` file and choose Edit in visual editor.
2. Navigate to another file and then come back to the original `.qmd` file. Editor switches to source editor, so Positron doesn't remember that the choice of editor was visual.
3. Switch back to visual and then rename the file, editor switches to source editor again.

## What did you expect to happen?

I expected Positron to remember my choice of editor while the file remains open.

## Were there any error messages in the output or Developer Tools console?

No.

**Comment by isabelizimm** [comment]
For QAing this, it's a bit of an extensive process! Let me know if you have questions. It's also NOT related to the Positron build for `2024.11`, so does not necessarily need to be prioritized for that release.

1. Go to https://github.com/quarto-dev/quarto/actions/runs/11618391284/artifacts/2130165489 to download the ZIP file of the quarto extension
2. Unzip
3. Open the command palette and select `Install from VSIX`. 
4. Navigate to and install the `.vsix` file you unzipped
5. Navigate to the extensions page and reload extension host. This button appeared for me and I could just click it. If it does NOT appear, you can use `Developer: Restart extension host` from the Command Palette. ![Image](https://github.com/user-attachments/assets/fa2368b2-fa0e-42c9-96a1-63fa7cb0ef11)
6. create 2 files (the content of the document doesn't really matter here, just the topmatter YAML)

`test-1.qmd`
```
---
editor: visual
---

# hello there
```

`test-2.qmd`
```
---
editor: source
---

# hello there
```

The editor selection in yaml should be respected.

7. create 3 more files

`_quarto.yml`
```
editor: visual
```

`test-3.qmd`
```
---
title: my beautiful file
---

# hello there
```

`test-4.qmd`
```
---
title: my beautiful file
editor: source
---

# hello there
```

When opening `test-3.qmd`, it should open in the visual editor. And `test-4.qmd` should open with the source editor.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-140
    OS Version          : OSX

### Test scenario(s) 

Followed validation instructions... looks great!

Link(s) to TestRail test cases run or created:
