### ISSUE TITLE
Promote language settings in settings UI; title and organize them consistently

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#1487]
Currently the R settings are under "Positron R Language Pack" and the Python settings are under "Python".

<img width="785" alt="image" src="https://github.com/posit-dev/positron/assets/470418/4938be9a-9b6d-40f9-87a2-a7ca1ee6e855">

These should be named consistently. The same applies for the settings themselves; the R language pack namespaces them all beneath Positron, but Python doesn't:

<img width="457" alt="image" src="https://github.com/posit-dev/positron/assets/470418/36683316-1144-497e-bbf3-c5a984665a94">

It's also a little much to have to dig into these settings underneath _Extensions_. Though they are, indeed, provided by extensions, I don't think most users will think of R and Python as "extensions" to Positron -- they should feel built in, even though they are powered by extensions. 

I think these should be promoted to a new top-level group (alongside Window, Workbench, etc.); maybe "Interpreters".

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2025.01.0-141](https://github.com/posit-dev/positron-builds/releases/tag/2025.01.0-141)
OS Version(s) : Windows 11

### Test scenario(s) 
Extension settings are now organized as expected.  The relevant settings all work as expected.

### Link(s) to TestRail test cases run or created:
