### ISSUE TITLE
Quarto: Autocomplete works differently in quarto chunk vs Positron editor/console

### ISSUE THREAD

**Issue by DavisVaughan** [posit-dev/positron#1572]
Quarto uses the exposed API for accessing quick suggestions, but this doesn't do any kind of sorting or filtering, it just gives you a very raw list of completion possibilities, which ends up being extremely overwhelming.

The quick suggestions path used for the editor/console end up calling roughly the same thing, but then go through this extra sorting/filtering step that really refines the potential completions down quite a bit.

You can see an example of this extracted from this video. Notice how bad the completions for `lib` are, especially in visual mode
https://github.com/posit-dev/positron/issues/1352#issuecomment-1743599276

https://github.com/posit-dev/positron/assets/10009758/4ba77872-cb1e-450d-8377-f1f03a719b04

I believe this is where quarto calls the exposed API:
https://github.com/quarto-dev/quarto/blob/542a50f5067cbc8db23f342280085e8bf36899f7/apps/vscode/src/vdoc/vdoc-completion.ts#L32

Which maps to
https://github.com/posit-dev/positron/blob/83fe2930d837a0041a0d9c805f667fdb66e36ff6/src/vs/workbench/api/common/extHostApiCommands.ts#L241

and https://github.com/posit-dev/positron/blob/83fe2930d837a0041a0d9c805f667fdb66e36ff6/src/vs/editor/contrib/suggest/browser/suggest.ts#L389

I think the core of it is `provideSuggestionItems()`, which is also used by this core quick suggestions `trigger()` function. But `trigger()` follows this up with a lot of sorting a filtering and fuzzy matching / scoring.
https://github.com/posit-dev/positron/blob/1f32d5b39a385663c13b6a96cf857bbcddcab7db/src/vs/editor/contrib/suggest/browser/suggestModel.ts#L517

Maybe we can give Quarto a new API command that is better aligned with what the editor / console do.

**Comment by juliasilge** [comment]
As of today, the completions in a Quarto chunk (source editing) look much the same as the completions in a regular `.R` or `.py` file or the console:

## R

![Image](https://github.com/user-attachments/assets/f50dadd3-3220-4810-bdff-1470d229da2e)

![Image](https://github.com/user-attachments/assets/d0f61250-e043-4f86-aa97-9c3fb253bf63)


## Python

![Image](https://github.com/user-attachments/assets/12573b20-e728-4b3b-b008-0739c664bcdb)

![Image](https://github.com/user-attachments/assets/5f75d476-a161-4eb9-b94d-9334087e6f39)


- We are _not_ providing snippets yet.
- The completions in visual mode are truly a mess.

Let's use this issue to track providing **snippets** and add completions to the pile of things not working well in visual mode tracked in #1805.

**Comment by juliasilge** [comment]
We are providing the snippets, they are just at the bottom of the list:

![Image](https://github.com/user-attachments/assets/cfcf6abd-0128-4fcd-a1a7-7cad2eb3e981)

**Comment by juliasilge** [comment]
They are being put there... ON PURPOSE 👁️👄👁️

https://github.com/quarto-dev/quarto/blob/d818dd022d803ea93db34d1a6ccca56a05d54348/apps/vscode/package.json#L899

**Comment by juliasilge** [comment]
## QA Notes

We can now verify that we offer the sample completions in Quarto as in the console or a regular `.R` or `.py` file. To do this, [get the current development version of the Quarto extension](https://github.com/quarto-dev/quarto/actions/runs/12035651963) (download, unzip, install `.vsix`, restart Positron) and use it in a current release build such as 2024.12.0-80.

Compare completions offered in a Quarto file to a regular source code file. Here are some ideas of what to check:

## R

- `lib` and `fun` (snippets and other completions)
- `mtcars$` (column names)

## Python

- `from pand` (library name completion)
- `obj`
- Column names should also complete, such as with the cursor in between the quotes in `df['']` if `df` is a dataframe

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-88
    OS Version          : OSX

### Test scenario(s) 

Verified by comparing completions for R and Python between quarto doc and source file as recommended by Julia.

Link(s) to TestRail test cases run or created:
