### ISSUE TITLE
Epic: Positron Server on Posit Workbench

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#1617]
This epic aggregates issues that need to be resolved for Positron to work correctly in the context of Posit Workbench.

### Runtimes in Workbench

These issues must be addressed in order for R and Python to run successfully in the Workbench environment. Broadly, the main work to do is to make sure the runtimes and their dependencies are compatible with the broad spectrum of Linux distributions supported by Workbench, and to wrap the runtimes in a supervisor so that they can be disconnected/reconnected from the browser safely.

- [x] #1155
- [x] #1243
- [x] #1411
- [x] #1619
- [x] #4506
- [x] #4507
- [x] #2057

### Workbench Integration

These issues must be addressed in order for Positron itself to be hosted in the Workbench environment. They concern the machinery needed for Workbench to bundle Positron, start Positron sessions, and connect to them.

- [x] #961]
- [x] #1424
- [x] #1618
- [x] #1373
- [x] #4273
- [x] #4274
- [x] #4864
- [x] #4769
    - [x] #5027 
    - [ ] #5026 
    - [x] #5028 

### Status Reporting

RStudio sessions report various metrics back to Workbench, which allows Workbench to implement features like showing busy/idle status on the user dashboard and code auditing. These features could be implemented for Positron, too.

- [ ] #3148
- [ ] #2238

### Admin Environment Control

These features could help admins control the environments available to users.

- [ ] #3574
- [ ] #3575

### UI/Front End

- [ ] #3172
- [x] #4893 

### Other

- [x] #4081
- [x] #4082
- [ ] #1402
- [ ] #4276
- [ ] #4278

**Comment by juliasilge** [comment]
We got a ton done here this milestone! 🎉

There are some remaining issues related to this work that are now in other milestones
