### ISSUE TITLE
Consider making output channel names consistent

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#1707]
In #1544 I said:

> I don't know if it would be less confusing in the long run if there was more consistency in the names of these output channels? For example, "Python" vs. "Positron R Extension" and "Python Language Server" vs. "Positron R Language Server (4.3.1)"?

![Screenshot 2023-10-27 at 12 39 51 PM](https://github.com/posit-dev/positron/assets/12505835/d997a0bd-79f0-4988-b53b-f9c7109a701c)

And @jennybc said:

> Yeah I was a bit perplexed about how to name this channel. Just calling it "R" felt weird and possibly confusing, even though that would be most consistent with "Python" (being the channel for the python extension). So I followed the "Positron This, Positron That" convention.

Let's consider making these channel names more consistent to reduce confusion.

**Comment by jmcphers** [comment]
This doesn't feel exactly the same as https://github.com/posit-dev/positron/issues/5063 to me, but they're related.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2025.01.0-141](https://github.com/posit-dev/positron-builds/releases/tag/2025.01.0-141)

OS Version(s) : Windows 11

### Test scenario(s) 
New Output Channel names show as expected!

### Link(s) to TestRail test cases run or created:
