### ISSUE TITLE
Python: Add support for additional widget types (in viewer or plots pane)

### ISSUE THREAD

**Issue by isabelizimm** [posit-dev/positron#1924]
Once #1918 is merged, we will have basic support for the widgets such as ipywidgets, ipydatagrid, and ipyleaflet in the plot pane. Still not working ❌  is:

- %matplotlib widget mode
- bqplot
- ipycanvas
- pythreejs
- ipytree

Here is a [gist of all the different widgets, for testing purposes](https://gist.github.com/isabelizimm/02f7ba16dc74b202935f6d3e9ed6b892)

CC: @jgutman

**Comment by peekxc** [comment]
Does this cover plotly / bokeh plots?

**Comment by juliasilge** [comment]
@peekxc I believe that plotly works:

![plotly](https://github.com/posit-dev/positron/assets/12505835/4e58911b-4289-491d-9218-a2e935a24272)

Are you observing something different?

For bokeh, I do not believe we have that working correctly right now (the plot opens in an external browser).

**Comment by peekxc** [comment]
> For bokeh, I do not believe we have that working correctly right now (the plot opens in an external browser).

Ahh, I was talking about bokeh; sorry, I assumed the behavior would be identical 

<img width="1479" alt="Screenshot 2024-07-06 at 9 21 29 AM" src="https://github.com/posit-dev/positron/assets/11429028/2932c266-5fc6-4b89-ae9f-a5f5c780eb2d">

**Comment by seeM** [comment]
https://github.com/posit-dev/positron/pull/4172 and https://github.com/posit-dev/positron/pull/4208 should get the following widgets working:

* `anywidget`
* `bqplot`
* `drawdata`
* `ipydatagrid`
* `ipyleaflet`
* `ipympl`
* `ipytree`
* `ipywidgets` – all widget types except `Output` which needs special handling
* `pythreejs`

There may be smaller issues with those, which we can log separately.

I haven't yet figured out why `ipycanvas` isn't working.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-24
    OS Version          : OSX

### Test scenario(s) 

Validated with everything here: https://gist.github.com/isabelizimm/02f7ba16dc74b202935f6d3e9ed6b892
Everything looks good except ipycanvas, which is noted above

Link(s) to TestRail test cases run or created:
N/A
