### ISSUE TITLE
Support language keyboard shortcuts in Quarto chunks

### ISSUE THREAD

**Issue by blairj09** [posit-dev/positron#1955]
With an open R file, `cmd+shift+m` will automatically insert R pipe (`|>`). However, in an R code chunk within a Quarto document, the same shortcut instead opens the `PROBLEMS` panel. The VS Code [keyboard shorcuts doc](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf) indicates that this is the expected behavior for this keybinding in VS Code:
![image](https://github.com/posit-dev/positron/assets/10444878/e2326c62-25c1-407d-ac9b-97ee0ef14d8f)
However, it feels like Quarto chunks should prioritize language-specific key bindings. I intentionally left this issue title a bit vague in case there are other bindings that don't function as expected from within quarto chunks.

**Comment by kv9898** [comment]
In the source mode it currently works like a charm! However, as noted in #4368, it still doesn't work in the visual mode

**Comment by melimelo24** [comment]
Quick hack around: modify the shortcuts directly (change when expression) to `editorTextFocus && editorLangId == 'quarto' || editorTextFocus && editorLangId == 'r'`. Works nicely for the pipe shortcut at least :)

**Comment by kv9898** [comment]
> Quick hack around: modify the shortcuts directly (change when expression) to `editorTextFocus && editorLangId == 'quarto' || editorTextFocus && editorLangId == 'r'`. Works nicely for the pipe shortcut at least :)

Thank you for your suggestion! I tried your proposed solution but sadly it didn't work for me (in the source mode it works as before, but in visual mode nothing happens)

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.12.0-96](https://github.com/posit-dev/positron-builds/releases/tag/2024.12.0-96)
Workbench Version(s):
OS Version(s) : Windows 11

### Test scenario(s) 

Keyboard shortcuts now work in Quarto document as expected.

### Link(s) to TestRail test cases run or created:
