### ISSUE TITLE
R: Create function to get a package version (and use it in `checkInstalled()`)

### ISSUE THREAD

**Issue by jennybc** [posit-dev/positron#1957]
In #1930, we got `runtime.checkInstalled(pkgName: string, pkgVersion?: string)` and that's working well, including the minimum version check. However, in the case of "package A is installed but at insufficient version", the *messaging* is a bit confusing.

Example: I'm wiring `checkInstalled()` into the test explorer which needs very recent testthat to run an individual `test_that()` test. If I downgrade testthat and attempt to run a single test, I see this:

<img width="403" alt="Screenshot 2023-12-15 at 2 36 06 PM" src="https://github.com/posit-dev/positron/assets/599454/2d797d74-a278-4046-8bdb-2a6121ddf9a2">

testthat is definitely installed, so I think it would be better to surface the current version of testthat vs. the minimum version required by the feature doing the check.

I also think having a function to get a package's version will just be useful in general, by itself. And the first place we would use it is inside `checkInstalled(pkgName: string, pkgVersion?: string)`.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.12.0-44](https://github.com/posit-dev/positron-builds/releases/tag/2024.12.0-44)
OS Version(s) : Windows 11

### Test scenario(s) 

* Prompted to install missing packages
* Prompted to upgrade needed packages (such as correct version of renv

-- see PR for details in QA Notes section

### Link(s) to TestRail test cases run or created: 

None
