### ISSUE TITLE
R: Some htmlwidgets don't work in the Plots pane

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#2023]
In #1742 we worked on adding support for R htmlwidgets in the Plots pane, including getting the needed external libraries. With that initial work, plotly and leaflet work 🎉 but there are some remaining problems. As of Positron 2024.01.0 (Universal) build 30, I see problems with:

- highcharter

```r
library(highcharter)
hchart(mtcars, "scatter", hcaes(wt, mpg, z = drat, color = hp)) 
```

- threejs

```r
library(threejs)
z <- seq(-10, 10, 0.01)
x <- cos(z)
y <- sin(z)
scatterplot3js(x,y,z, color=rainbow(length(z)))
```

What I observe is that the new plot that gets generated looks empty/blank and there are errors like this:

![Screenshot 2024-01-08 at 9 18 28 AM](https://github.com/posit-dev/positron/assets/12505835/77f4a887-bd3b-43b1-a9c2-284646e08ee1)

**Comment by gadenbuie** [comment]
Some additional feedback that sending html widgets to the Plots pane misses the "open in browser" affordance of the Viewer pane: https://github.com/posit-dev/positron/discussions/3686#discussioncomment-9905639

**Comment by gadenbuie** [comment]
Also of note, some HTML outputs get sent to the Viewer pane, e.g. `gt::gt(mtcars)`, but don't get the "open in browser" affordance or toolbar. https://github.com/posit-dev/positron/discussions/3686#discussioncomment-9905734

**Comment by juliasilge** [comment]
Additional feedback from someone who prefers that htmlwidgets go to the Viewer pane (not Plots): https://github.com/posit-dev/positron/issues/3750

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-107
    OS Version          : OSX

### Test scenario(s) 

Verified with both examples from the original filing.

Link(s) to TestRail test cases run or created: 
N/A
