### ISSUE TITLE
Server: Scrolling with a mouse or trackpad doesn't seem to work in the Console

### ISSUE THREAD

**Issue by DavisVaughan** [posit-dev/positron#2056]
https://github.com/posit-dev/positron/assets/19150088/52f601b7-00b6-4d2f-bf1d-11f2f3e0ce9f

**Comment by sharon-wang** [comment]
Linking for possible relevance: a similar issue with mouse wheel / trackpad scrolling on web was fixed for our custom dropdowns/popups:
- Issue: https://github.com/posit-dev/positron/issues/4888
- PR: https://github.com/posit-dev/positron/pull/5070/files

**Comment by jmcphers** [comment]
Triage: This can get bumped if needed.

**Comment by timtmok** [comment]
https://github.com/posit-dev/positron/issues/5472

We should think about wrapping UI that requires scrolling in a Scrollable to ensure it works in web.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : Main on 11/25/24 at 12:00 PM MST
    OS Version          : 

### Test scenario(s) 

Scrolling in console with mouse is working with web.

Link(s) to TestRail test cases run or created:
