### ISSUE TITLE
Server: A reload seems to be required to get the interpreters to load

### ISSUE THREAD

**Issue by DavisVaughan** [posit-dev/positron#2057]
This seems to be 100% reproducible

https://github.com/posit-dev/positron/assets/19150088/e3c11d34-f254-4c05-af62-6495f7c210c6

When testing, make sure the `Run code server` build task is completely shut down between test iterations. If it is alive then the interpreters will load even if you close the Chrome window and relaunch the debug target

**Comment by jmcphers** [comment]
If this still repro's, we may need to fix it for Workbench so that Positron works on first boot.

**Comment by jmcphers** [comment]
I haven't been able to reproduce this in months; can someone confirm it's fixed?

**Comment by DavisVaughan** [comment]
Looks like it is working to me

https://github.com/user-attachments/assets/70d503f7-f7e0-49ca-b2a9-8e7af80b3b40
