### ISSUE TITLE
Windows Taskbar Icon is electron default

### ISSUE THREAD

**Issue by jonvanausdeln** [posit-dev/positron#2089]
## Positron Version: 
2024.01.0-173

## Steps to reproduce the issue:

1. Install on Windows
2. Start Positron

## What did you expect to happen?
The taskbar icon to be Positron, instead it's the default electron icon
![image](https://github.com/posit-dev/positron/assets/6433789/cb54c071-bfa7-4259-b396-71603c4eccb4)

**Comment by juliasilge** [comment]
Seems like this may have regressed at least for some users: https://github.com/posit-dev/positron/discussions/3979

I am reopening to send back to triage.

**Comment by petetronic** [comment]
That is a slightly different issue, this issue was about the application icon and corresponding process icon in the system tray. I'll file a different issue for that in-app icon.
