### ISSUE TITLE
Ark: Jupyter: Verbose logging makes jupyter-console unusable

### ISSUE THREAD

**Issue by lionel-** [posit-dev/positron#2098]
By default (i.e. `--log` option not supplied) we stream log messages to stdout/stderr. This makes jupyter-console unusable when verbosity is high because jupyter-client, used by jupyter-console, launches the kernel with [`subprocess.Popen()`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen) without stdout capture, which causes the kernel streams to be inherited by the jupyter-console REPL process.

To fix this we could add a `--log-temp` option that would create log files in `$TEMPDIR/ark-logs`. These would be time-stamped to make it easy to find the relevant log file when debugging. Supplying both `--log` and `--log-temp` would be an error. We would supply that option by default in our `kernel.json` file.

**Comment by DavisVaughan** [comment]
Looks like things are pretty quiet now on Mac and Windows, I even checked the reprex from #4382 too

<img width="1386" alt="Screenshot 2024-09-30 at 4 02 18 PM" src="https://github.com/user-attachments/assets/956d6e3f-0b8e-4da6-88b8-d1b561576dd2">
<img width="1482" alt="Screenshot 2024-09-30 at 4 10 22 PM" src="https://github.com/user-attachments/assets/57032366-f533-4c54-95de-1e7c024d09ec">
<img width="367" alt="Screenshot 2024-09-30 at 4 12 03 PM" src="https://github.com/user-attachments/assets/9b3dc749-0b70-49a2-8814-180324944558">

Probably worth looking into this at some point

```r
D:\Users\davis-vaughan\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_console\ptshell.py:136: UserWarning: No lexer found for language ''. Treating as plain text.
  warn("No lexer found for language %r. Treating as plain text." % name)
```
