### ISSUE TITLE
R: If `R_HOME` isn't set, try `R RHOME` command

### ISSUE THREAD

**Issue by DavisVaughan** [posit-dev/positron#2111]
> I think it'd be very useful to retrieve R_HOME from the R found in PATH, if not already set. This will make the usage of Ark as a Jupyter kernel easy and frictionless.

From @lionel- 

To be done as a follow up to https://github.com/posit-dev/amalthea/pull/205

We already do this for the testing variant of `start_r()`, so we should be able to unify the approach with our "real" `start_r()`

**Comment by lionel-** [comment]
This has been the case for a while now: https://github.com/posit-dev/ark/blob/586df407ef05dd99e83770825f282fe4b47ecbab/crates/ark/src/interface.rs#L359-L374
