### ISSUE TITLE
Even Better TOML extension doesn't work in Positron

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/positron#2154]
## Positron Version:

Positron Version: 2024.01.0 (Universal) build 223
Code - OSS Version: 1.85.0
Commit: 20518f2f1097ce4125c43a3b36b17a854fdbb39a
Date: 2024-01-26T03:12:36.174Z
Electron: 25.9.7
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 23.2.0

## Steps to reproduce the issue:

1. Install the `Even Better TOML` extension
2. Open a TOML file

## What did you expect to happen?

The TOML extension loads, and its LSP gives me tooltips and error information about the file I'm viewing.

The new publishing client we are developing uses TOML config files, and we're publishing a jsonschema for them so that schema-aware editors can give you useful feedback. This seems to be the top TOML extension for VSCode, so we were planning to recommend it be installed along with the publishing client.

## Were there any error messages in the output or Developer Tools console?

An alert:
<img width="532" alt="image" src="https://github.com/posit-dev/positron/assets/2903390/4cee2732-74f7-4a46-bf3d-68ad4e5cce6f">

and the Output panel shows a lof of JS code, ending with the message
```
[Error - 2:25:55 PM] The Even Better TOML LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

Up above the big block of JS code, it says:

```
 INFO registered notification handler method="taplo/associateSchema"
panicked at 'getrandom::getrandom() failed.: Error { internal_code: 2147483660, description: "Node.js crypto module is unavailable" }', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.3/src/random_state.rs:81:51

Stack:

Error
    at PA.i.wbg.__wbg_new_693216e109162396 (/Users/mike/.positron/extensions/tamasfe.even-better-toml-0.19.1-universal/dist/server.js:2:4646)
    at wasm://wasm/00fb2f8a:wasm-function[2518]:0x2e8066
    at wasm://wasm/00fb2f8a:wasm-function[4393]:0x328a27
    at wasm://wasm/00fb2f8a:wasm-function[3073]:0x303105
    at wasm://wasm/00fb2f8a:wasm-function[1499]:0x29f415
    at wasm://wasm/00fb2f8a:wasm-function[1019]:0x263047
    at wasm://wasm/00fb2f8a:wasm-function[274]:0x155b0c
    at wasm://wasm/00fb2f8a:wasm-function[362]:0x1910fd
    at wasm://wasm/00fb2f8a:wasm-function[3286]:0x30a999
    at wasm://wasm/00fb2f8a:wasm-function[889]:0x23ea21
```

**Comment by jmcphers** [comment]
![Image](https://github.com/user-attachments/assets/5b91f67e-7fc2-49b9-bb3c-865384192a67)

This might have been a Node 18 thing. I'm not able to reproduce with the most recent 2024.12 build (Node 20).

@mmarchetti please feel free to reopen if it's still happening for you!
