### ISSUE TITLE
Epic: Data Explorer support for Polars

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#2185]
- [x] #3449 
- [x] #3451
- [x] #3452 
- [x] #3453
- [x] #3454 
- [x] #3761

**Comment by wesm** [comment]
All the issues in the epic have been completed, so this can be closed if others agree that we have sufficient feature coverage

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-97
    OS Version          : OSX

### Test scenario(s) 

Verified all issues in epic are validated and closed.

Link(s) to TestRail test cases run or created: 
N/A
