### ISSUE TITLE
Request: Fully user configurable directory for specifying where to find interpreters

### ISSUE THREAD

**Issue by DavisVaughan** [posit-dev/positron#2235]
@dskard has a case where a tool he uses puts R versions in `~/.renv/` rather than the "standard location" that R (and rig) typically use.

Rather than including this as a possible place to look for R, I think we should just add a global option that allows users to specify a location to look for R interpreters in. I imagine this is a setting that lives under `positron-r`, and is just a plain text field corresponding to a directory that we look through.

**Comment by jmcphers** [comment]
I'm going to suggest we re-triage this for R, because there's a _very_ long thread of people for whom our automated discovery doesn't work for one reason or another, and just allowing you to tell us where R live would give all of them a way to move forward.

**Comment by juliasilge** [comment]
It would be useful to look at the Python extension's "Select Interpreter" UI experience, which is IMO very good.

This could help us with other alternative ways of installing R like conda, pixi, etc.

**Comment by jennybc** [comment]
A PR for this will land today. We'll discuss if/how to track these sorts of documentation requests.

**Comment by jennybc** [comment]
#5222 now tracks documentation of R discovery

**Comment by juliasilge** [comment]
#5223 now tracks providing UI affordance similar to "Python: Select Interpreter"

**Comment by dskard** [comment]
I used test environments to confirm that I was able to install R in non-standard locations like `/home/ubuntu/.renv/versions` on Ubuntu and `C:/local/R` on Windows and use the new settings in Extensions > R > Positron R Language Pack (advanced) to set the location of my R installations.

On Linux, paths like these worked:
* `/home/ubuntu/.renv/versions/4.4.2/bin/R`
* `./.renv/versions/4.4.2/bin/R`
* `./nonstadard_r_installation/../.renv/versions/4.4.2/bin/R`
* `/home/ubuntu/.renv/versions`
Using `~` and `${HOME}` was not recognized. I'll add a note to the documentation issue to mention this.

On Windows, paths like these worked:
* `C:/local/R/R-4.4.2/bin/x64/R.exe`
* `C:/local/R/R-4.4.1/bin/x64/R.exe`
* `C:/local/R`

Used Positron 2024.11.0-140 for testing.
