### ISSUE TITLE
View plot in editor space

### ISSUE THREAD

**Issue by timtmok** [posit-dev/positron#2270]
Add a way to allow a user to view a plot as an editor. This allows a larger view without altering the size of the plots pane and leverages the editor's ability to float as its own window or tile along other editors/plots.

**Comment by jmcphers** [comment]
Relevant Mastodon thread:

> The only weird thing is no zoom option for plotting.

https://mastodon.online/@rmflight@mastodon.social/112695382560885990

**Comment by seeM** [comment]
Sort of requested in https://github.com/posit-dev/positron/issues/3884.

**Comment by nstrayer** [comment]
I think as long as we have a really good encapsulation of the `IPositronPlotClient` class it should be _relatively_ straightforward to write an `EditorPane`/`EditorInput` class that can act as the front-end. 

Work done for #1713 will probably make this easier as it will involve making the front-end as stateless as possible.

**Comment by factorialmap** [comment]
In RStudio there is a very useful option to show data/plots/viewer/console without having to split panels, it just expands the panels using shortcut keys. 

Tools>Modify Keyboard Shortcuts>Zoom. It's really fast.

I think it might be really cool if we had that on the Positron.


https://github.com/user-attachments/assets/5051bd09-7b7c-4bb9-9bb1-47e711d00640

**Comment by juliasilge** [comment]
I'll start some QA notes for the initial version of this! 🎉 

## QA Notes

- The new ability to open a plot in editor space should be behind a feature flag where the default is _off_.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-27
    OS Version          : OSX

### Test scenario(s) 

Open in editor works well.  No controls yet in editor I assume is expected.

Link(s) to TestRail test cases run or created: 
N/A
