### ISSUE TITLE
Save buttons on menu bar don't work

### ISSUE THREAD

**Issue by jonvanausdeln** [posit-dev/positron#2276]
## Positron Version:
Positron Version: 2024.02.0 (system setup) build 2024.02.0-1535
Code - OSS Version: 1.86.0
Commit: 1478e597a716c434509a1ff8f7e0e43dbf420cb2
Date: 2024-02-15T02:51:08.089Z
Electron: 27.2.3
ElectronBuildId: undefined
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631
       Also on MacOS

## Steps to reproduce the issue:

1. Start Positron and create a new file (any type)
2. Click the Save button
![image](https://github.com/posit-dev/positron/assets/6433789/e567b7eb-f70b-4e90-a86c-d81301de8289)

Observe that nothing happens, as if the buttons were inactive

## What did you expect to happen?
The OS save file dialog to save the file

## Notes
The command palette, `Ctrl + s` and `File -> Save` all work as expected.  The buttons also don't work if you modify an existing file and attempt to save with the buttons.

**Comment by petetronic** [comment]
@sharon-wang would you be able to take a look at this?

**Comment by ryjohnson09** [comment]
Not sure if it's because the icons are deactivated, but it would be nice to have a tooltip show up when hovering the mouse over each icon.
