### ISSUE TITLE
Untrusted HTML output support

### ISSUE THREAD

**Issue by nstrayer** [posit-dev/positron#2351]
Support for arbitrary html output from things like widgets. Will need to be put into a webview.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-88
    OS Version          : OSX

### Test scenario(s) 

Notebooks still working as before, including bokeh and hvplot.  We do have at least one known hvplot bug, but it is filed separately.

Link(s) to TestRail test cases run or created:
