### ISSUE TITLE
Kernel chooser interface

### ISSUE THREAD

**Issue by nstrayer** [posit-dev/positron#2355]
Right now we just grab the nearest positron kernel for the language of the notebook, this is unideal. How this works is a bit up in the air though, especially with the multi-session notebooks work.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-81
    OS Version          : OSX

### Test scenario(s) 

Kernel choser interface works well.

Link(s) to TestRail test cases run or created: 
N/A.. not adding positron notebook tests yet
