### ISSUE TITLE
Jupyter Keymaps Pt 1

### ISSUE THREAD

**Issue by nstrayer** [posit-dev/positron#2357]
Need to leverage the VSCode-way of doing keyboard shortcuts for the notebooks.

For this part one issue we will support the following actions/ keybindings:

- Move selection up (`K` or up arrow)
- Move selection down (`J` or down arrow)
- Insert cell above selection (`A`)
- Insert cell below selection (`B`)
- Delete selected cell (`D D` or `Delete`)
- Save file (`S`)
- Execute and stay on current cell (`Ctrl/Cmd + Enter`)
- Execute and move to the next cell (`Shift + Enter`)

Will be followed by #3014 when the functionality is available.

**Comment by nstrayer** [comment]
Moving this back to in progress because we had to revert behavior because I inadvertently broke the keybindings for non-positron notebooks.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.07.0-21](https://github.com/posit-dev/positron/releases/tag/2024.07.0-21)
OS Version(s) : Windows 11

### Test scenario(s) 

All mentioned keyboard shortcuts work as expected (R, Python, & Markdown cells)

### Link(s) to TestRail test cases run or created: 

None -- but might considering adding some in the future
