### ISSUE TITLE
Overlap between R shortcuts / keybindings and positron ones

### ISSUE THREAD

**Issue by EmilHvitfeldt** [posit-dev/positron#2423]
## Positron Version:

Positron Version: 2024.03.0 (Universal) build 893
Code - OSS Version: 1.87.0
Commit: 864257d0a5e7131c1c3bbe891deefc09b3811f47
Date: 2024-03-05T03:24:32.501Z
Electron: 27.3.2
ElectronBuildId: undefined
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0

## Steps to reproduce the issue:

1. try different keybindings, Explorer Cmd + Shift + E, Run and debug Cmd + Shift + D

https://github.com/posit-dev/positron/assets/14034784/8ec3c921-16aa-4b29-bf27-14aa6f7aa11b

## What did you expect to happen?

Some of the listed keybindings on hover doesn't work because they are superseded by R package development commands. 

I don't know if it would possible to hide the incorrect shortcuts.

As far as I can tell, I don't have any custom keybindings, so this is vanilla

## Were there any error messages in the output or Developer Tools console?

Nope

**Comment by juliasilge** [comment]
We have collected a number of issues that are related to this problem where the UI always shows a built-in keybinding, even when that keybinding _does not apply_ to that action. The user might end up looking at the UI and trying that keybinding, but it does something completely different. Let's use #2150 to track this problem.
