### ISSUE TITLE
Show Notebook session variables when executing cells in a Notebook

### ISSUE THREAD

**Issue by petetronic** [posit-dev/positron#2452]
Now that issue #1625 has been implemented, it would be great if we could bring the Variables pane for the active Notebook session into view when we run cells in that notebook.

**Comment by seeM** [comment]
We may also want to do the same thing for console sessions. So:

1. If you execute a notebook cell, bring the notebook session into view in the variables pane.
2. If you execute in the console, bring the console session into view in the variables pane.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-104
    OS Version          : OSX

### Test scenario(s) 

Verified and automation updated to no longer need some workarounds on web from when this did not work.

Link(s) to TestRail test cases run or created:
