### ISSUE TITLE
IPyKernel may fail to install in conda environments

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#2504]
## Positron Version:
Positron 2024.03.0 (Universal) build 1089
## Steps to reproduce the issue:

1. Update conda in case it's old.
2. Create a new conda env: `conda create --name test06-env python=3.11 `.
3. Choose the new env in Positron.
4. It prompts to install ipykernel, agree.
5. The installation fails.

Also see the discussion following https://github.com/posit-dev/positron/issues/2002#issuecomment-2004567621 for more details.

## What did you expect to happen?
The installation should succeed and a Python console should start.

## Were there any error messages in the output or Developer Tools console?
In the console:

```
Could not start runtime: failed to install ipykernel for Python 3.11.8 ('test06-env')
```

**Comment by danieltomasz** [comment]
I have the error when ipykernel is installed in the conda environment (that was installed by pyenv-virtualenv)

**Comment by juliasilge** [comment]
@danieltomasz do you know how you installed conda?

**Comment by danieltomasz** [comment]
hi @juliasilge 
basically I used pyenv to install this specific environment `pyenv virtualenv    miniforge3-latest  test  --name=test --file=local.yml` ; I don't use conda to manage my environment, only as a source of packages

I use `makefile` to install and update my environment, the content of `Makefile`
```
.ONESHELL:


VENV=test
VENV_DIR=$(shell pyenv root)/versions/${VENV}
PYTHON=${VENV_DIR}/bin/python

VARS = PYDEVD_DISABLE_FILE_VALIDATION=1


SHELL = /bin/bash
CONDA_ACTIVATE = source $$(conda info --base)/etc/profile.d/conda.sh ; conda activate ; conda activate


#.ONESHELL:
install:
	$(eval PYTHON_DIST := miniforge3-latest)
	$(eval CONDA_BIN := ~/.pyenv/versions/${PYTHON_DIST}/bin/conda)
	$(eval PYTHON := ~/.pyenv/versions/${VENV}/bin/python)
	@echo "Installing $(VENV) with $(PYTHON_DIST)"
	env PYTHON_CONFIGURE_OPTS=--enable-shared pyenv install --skip-existing ${PYTHON_DIST}
	${CONDA_BIN} update -n base -c conda-forge conda
	pyenv uninstall ${VENV} || true
	pyenv virtualenv  ${PYTHON_DIST} ${VENV} || true;
	${CONDA_BIN} config --env --set channel_priority strict &&\
	${CONDA_BIN}  env update --name ${VENV}  --file local.yml --prune -v
	@eval "$$(pyenv init -)" && \
	pyenv activate ${VENV}; \
	pyenv local ${VENV}; \
	PYDEVD_DISABLE_FILE_VALIDATION=1 ${PYTHON} -m ipykernel install --user --name ${VENV}

```

with the content of `local.yml`

```
channels:
  - conda-forge
dependencies:
  - conda-forge::python>=3.12.2
  - conda-forge::ipykernel
```

Basically I don't use conda outside installation of packages (some  `pip` specific packages for numeric computation doesnt play well with my machine), I am on mac M1 Mac Sonama 14.5

**Comment by sharon-wang** [comment]
While working on the Project Wizard, I encountered something related where interpreters with aliased python paths were causing trouble for me.

Here's the comment I wrote:

https://github.com/posit-dev/positron/blob/203958161106d234eaa85556293c1be8f8b395b3/src/vs/workbench/browser/positronNewProjectWizard/newProjectWizardState.ts#L709-L715

I noticed that in Julia and Daniel's comments, aliased paths seem to be present. Maybe something we can try is to resolve the full path from the aliased path before we try to install ipykernel?

**Comment by danieltomasz** [comment]
Maybe this is know but pyenv environnement installed via pip (similar way) works without any problems

**Comment by joelem** [comment]
Hi! Thank y'all for Positron, I love it so far.

Just wanted to chime in that ipykernel is also failing to install for me on Python 3.10.8, miniforge conda (can't remember the route i used to install it, it was a while ago) & Positron Version: 2024.07.0 (Universal) build 21

The interpreter path is ~/miniforge3/bin/python

The console just says the following, there is no additional info in the console or output:
Python 3.10.8 (Conda: base) starting.
Could not start runtime: failed to install ipykernel for Python 3.10.8 ('base').

**Comment by isabelizimm** [comment]
I am able to repro this using conda installed via pyenv 👀 

```
pyenv install anaconda3-2024.02-1
pyenv virtualenv anaconda3-2024.02-1 pyenvcondatest
```

Then find the `pyenvcondatest` interpreter and try to start up in Positron. It will fail with these messages:



![Image](https://github.com/user-attachments/assets/f93e086d-737e-41c7-b090-47393316dfc7)

**Comment by eduardokapp** [comment]
Also able to reproduce this.

Using a mac M1. Conda miniforge. Ipykernel is installed.

<img width="1225" alt="image" src="https://github.com/user-attachments/assets/6ec8cf63-101c-499f-85c8-cee0039f3907">

Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11) 
[Clang 14.0.6 ] on darwin
conda 4.14.0

When trying to select the associated interpreter, positron says ipykernel needs to be installed, but even after clicking on "install" it doesn't solve the problem. When I look into the python output channel, I see this:

<img width="1850" alt="image" src="https://github.com/user-attachments/assets/53afc5ae-d7b2-451e-920d-319d8c7b9f0a">

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-107
    OS Version          : OSX

### Test scenario(s) 

Verified with Wasim's original instructions.  I did have to use the 'Python: Select Interpreter' command to find the new conda env post restart, but we have a separate issue regarding the environment picker not finding all new envs.

Link(s) to TestRail test cases run or created: 
N/A
