### ISSUE TITLE
UI: menu button tooltip remains visible behind drop down

### ISSUE THREAD

**Issue by petetronic** [posit-dev/positron#2525]
Tool tip should dismiss when Plots zoom control is opened from the action bar.

![Image](https://github.com/posit-dev/positron/assets/1178561/c22aa5ad-db11-468a-b8a3-745d7c971762)

**Comment by GCRev** [comment]
This seems to be endemic to the Code OSS's hover manager -- `hoverService.ts` -- which means this behavior affects all menu buttons with tooltips. I can reproduce this but only with specific timing like Tim said, and I can reproduce it for every other menu button with a drop down in the "Plots" pane, "Variables" pane, and even the "New" and "Open" buttons in the top bar.

![Image](https://github.com/user-attachments/assets/cac65633-d4dc-4441-acc1-12b31c2f96d4)

![Image](https://github.com/user-attachments/assets/541987dc-1591-46c6-a2a8-c7a5dbe3a23d)

![Image](https://github.com/user-attachments/assets/aef0eb36-3fe3-4991-b937-5a739d9343c3)

I haven't checked this behavior on windows.

**Comment by GCRev** [comment]
Never mind, this was a simpler fix than I originally thought.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-11
    OS Version          : OSX

### Test scenario(s) 

Unable to repro tooltip remaining while menu is in use.

Link(s) to TestRail test cases run or created: 
N/A
