### ISSUE TITLE
Data Explorer: Reactive column width

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#2527]
It would be great if columns were sized according to the width of the column name rather than all being one width. We can fit a lot more columns per page, especially with shorter column names. We may want to support double-click on the column border to shrink to minimum otherwise.

![image](https://github.com/posit-dev/positron/assets/29187501/776524ca-e5f3-4e73-a9cb-2e2bd4ca5e21)

![image](https://github.com/posit-dev/positron/assets/29187501/fb545ef3-c712-4710-b615-f403001ce9b4)

**Comment by jthomasmock** [comment]
Our initial plan here is to automatically calculate the width of each column based on the just the initial data pull and the longest value within each column which should be a cheap operation.

**Comment by jonvanausdeln** [comment]
Is double click on the column border being implemented as part of this? (from initial comment of this issue)

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.08.0-31](https://github.com/posit-dev/positron-builds/releases/tag/2024.08.0-31)
OS Version(s) : windows 11

### Test scenario(s) 



See TestRail Test case. Columns react as expected

### Link(s) to TestRail test cases run or created: 
[TestRail case C704566](https://posit.testrail.io/index.php?/cases/view/704566)
