### ISSUE TITLE
Display local HTML files in Viewer

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#2559]
We're starting to gather more examples of folks wanting/expecting to see local HTML files in the Viewer:

- reprex, as reported in the private beta: https://github.com/posit-dev/positron-beta/issues/25
- Quarto output, as reported in Slack: https://positpbc.slack.com/archives/C05M2EZCPGR/p1711592538988499

For clarity, the recent work on the Viewer such as #2502 only handles HTTP URLs.

**Comment by jmcphers** [comment]
Came up again in #3716. The main thing to note there is that when we have the ability to display local HTML files, we'll want to implement the RStudio API function `viewer` which some packages use to trigger files to open in the Viewer pane.

**Comment by vincentarelbundock** [comment]
Thanks for opening this issue. I just wanted to confirm that https://github.com/posit-dev/positron/issues/3716, which was closed in favor the present issue, is indeed driven by the fact that `rstudioapi::viewer()` does not work in Positron. 

For what it's worth, two of my packages are affected by this (`modelsummary` and `tinytable`), and users of both packages have been asking me for support in-Positron viewer panes for HTML documents/tables.

Thanks for considering this feature. 

I appreciate your work!

**Comment by jmcphers** [comment]
I'm working on this!

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-107
    OS Version          : OSX

### Test scenario(s) 

``` r
x <- rnorm(100)
plot(x, sin(x))
```

Link(s) to TestRail test cases run or created: 
N/A
