### ISSUE TITLE
Positron notebooks should show file name in editor tab

### ISSUE THREAD

**Issue by nstrayer** [posit-dev/positron#2628]
Currently, the editor tab for notebooks just shows the title "Positron Notebook" which is pretty useless. Should be straightforward to show the file name.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-66
    OS Version          : OSX

### Test scenario(s) 

Filename is now in editor tab

Link(s) to TestRail test cases run or created:
