### ISSUE TITLE
R: Diagnostics crash related to passing tree sitter nodes back and forth with R

### ISSUE THREAD

**Issue by DavisVaughan** [posit-dev/positron#2630]
```r
library(abind, package = )
```

Just put that code in an editor, it should crash immediately. I see something like:

https://github.com/posit-dev/positron/assets/19150088/4b2e8d26-f03d-4e5a-835d-88363343b115

```
Likely caused by: Error: RAW() can only be applied to a 'raw', not a 'NULL'
```

this error is pretty telling, as there is only one real place we use `RAW()`, and thats when we pass the raw tree sitter node back and forth with R.

I think it is coming from here, where I think `node` here is `NULL`
https://github.com/posit-dev/amalthea/blob/dc47a8f671521dcc1e17f0d3f67ea5d5b6493a29/crates/ark/src/modules/positron/diagnostics.R#L49-L51

I think the matched call here really does have `NULL` as the `package =` arg
https://github.com/posit-dev/amalthea/blob/dc47a8f671521dcc1e17f0d3f67ea5d5b6493a29/crates/ark/src/modules/positron/diagnostics.R#L86-L92

**Comment by lionel-** [comment]
We have removed the offending code a while ago.
