### ISSUE TITLE
Documentation/guide theme

### ISSUE THREAD

**Issue by AshleyHenry15** [posit-dev/positron#2663]
I created Posit Product Documentation theme so our product docs stay aligned with company branding and standards.

Marketing has signed off on the theme and it can be easily implemented via quarto extension: https://github.com/posit-dev/product-doc-theme

**Comment by juliasilge** [comment]
Starting a checklist for documentation needs here:

- [ ] Document supported versions for OSes as requested in https://github.com/posit-dev/positron/discussions/3670

**Comment by juliasilge** [comment]
## QA Notes

What we want to confirm here is that we have [our new site](https://positron.posit.co/) up 🎉 and our supported OSes are outlined in the release notes on GitHub, i.e. https://github.com/posit-dev/positron-builds/pull/120.

**Comment by jonvanausdeln** [comment]
Release notes now match the new website!
