### ISSUE TITLE
Suppress verbose R startup in package dev tasks like testing and checking

### ISSUE THREAD

**Issue by jennybc** [posit-dev/positron#2715]
From @hadley:

> I like how test/build etc are now run in a separate pane. Do you think it would be possible to run R with `--quiet` there to avoid the lengthy startup message? (I assume the build pane is still eventually in the works, but I think this would be a cheap but meaningful improvement)

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-17
    OS Version          : OSX

### Test scenario(s) 

R: Test R Package no longer produces startup message.

Link(s) to TestRail test cases run or created: 
N/A
