### ISSUE TITLE
testthat::set_max_fails() not working anymore

### ISSUE THREAD

**Issue by EmilHvitfeldt** [posit-dev/positron#2723]
## Positron Version:

Positron Version: 2024.04.0 (Universal) build 29
Code - OSS Version: 1.87.0
Commit: 6c41dddd853aa3f36b47296a42ec2672c5a523de
Date: 2024-04-04T03:32:13.676Z
Electron: 27.3.2
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.4.0

## Steps to reproduce the issue:

1. run `testthat::set_max_fails(1000)`
2. run test R package command
3. have many failures

https://github.com/posit-dev/positron/assets/14034784/8e42fd91-6a13-4429-881b-c0413c7d5f2c

## What did you expect to happen?

I feel like this used to work (although, didn't check)

## Were there any error messages in the output or Developer Tools console?

Nope

**Comment by juliasilge** [comment]
I've got QA notes available here: <https://github.com/posit-dev/positron/pull/4606#issue-2511299222>

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-33
    OS Version          : OSX

### Test scenario(s) 

Hit:
Maximum number of failures exceeded; quitting at end of file.
After setting: 
testthat::set_max_fails(1)

Link(s) to TestRail test cases run or created:
N/A
