### ISSUE TITLE
Fix flaky ANSIOutput test in CI

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#2734]
Periodically I see this test failure in CI:

```

  1) ANSIOutout
       Test ANSIOutput with 100 lines separated by LF and CRLF:

      AssertionError [ERR_ASSERTION]: 9 == 10
      + expected - actual

      -9
      +10
      
      at testOutputLines (out/vs/base/test/common/ansiOutput.test.js:1528:20)
      at Context.<anonymous> (out/vs/base/test/common/ansiOutput.test.js:507:13)
      at process.processImmediate (node:internal/timers:476:21)
```

e.g. https://github.com/posit-dev/positron/actions/runs/8637498014/job/23679815359

Re-running the job usually fixes it, but this appears to be consistently flaky

**Comment by sharon-wang** [comment]
Saw this test failure again here: https://github.com/posit-dev/positron/actions/runs/10602026326/job/29383161816?pr=4515. It didn't fail when re-run.

**Comment by jonvanausdeln** [comment]
The tests passed in last few CI runs, so good enough for me!
