### ISSUE TITLE
Add spinner/waiting state to column profile null percentages and detailed summary stats

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#2740]
When working with small datasets, these will compute more or less instantaneously. But for larger or possibly even remote datasets, we should implement a "loading" state in the React components to make it clear that the UI is waiting on an asychronous computation before updating/re-rendering.

**Comment by jthomasmock** [comment]
One example for our upcoming sparklines:

![Image](https://github.com/user-attachments/assets/8f264096-7fa3-4af6-931a-d916678e31e0)

**Comment by softwarenerd** [comment]
This issue was addressed during work that was done to improve the sparklines and the table summary cache. Now, when column profiles are loading, the UI is painted with a "loading" state thusly:

![Image](https://github.com/user-attachments/assets/29e8ecc4-b2e1-4e77-9293-5858b04be61d)

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.09.0-27](https://github.com/posit-dev/positron-builds/releases/tag/2024.09.0-27)
OS Version(s) : Windows 11

### Test scenario(s) 



The spinner in the lower left shows busy while a large dataframe is loading.

### Link(s) to TestRail test cases run or created:
