### ISSUE TITLE
include images from www in Shiny app preview

### ISSUE THREAD

**Issue by jeremy-allen** [posit-dev/positron#2762]
In the RStudio IDE, previewing (clicking Run App) opens the R Shiny app in the viewer pane, and the app UI includes images found in the www directory. In Positron, the app opens in the viewer pane but the image is not in the UI. [Reprex repo is here.](https://github.com/jeremy-allen/shiny-assets-test.git) Using full and relative paths for the image did not change the behavior in Positron.

Expected behavior: assets in www show in the UI.

Gif of behavior in both IDEs:

![CleanShot 2024-04-14 at 16 16 07](https://github.com/posit-dev/positron/assets/18430826/41760db1-94fd-494c-83fa-b87ace0eb62d)

**Positron version:**

Positron Version: 2024.04.0 (Universal) build 29
Code - OSS Version: 1.87.0
Commit: 6c41dddd853aa3f36b47296a42ec2672c5a523de
Date: 2024-04-04T03:32:13.676Z
Electron: 27.3.2
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.4.0

**Comment by jmcphers** [comment]
Closing since this is really an issue w/ Shiny rather than Positron.
