### ISSUE TITLE
New Folder Dialog allows blank folder name

### ISSUE THREAD

**Issue by jonvanausdeln** [posit-dev/positron#2777]
## Positron Version:
[2024.04.0-1505](https://github.com/posit-dev/positron/releases/tag/2024.04.0-1505)
Windows 11, MacOS

## Steps to reproduce the issue:

1. Select `File -> New Folder` or `New -> New Folder`
2. Do not enter a Folder name (leave blank)
3. Click OK
<img width="304" alt="image" src="https://github.com/posit-dev/positron/assets/6433789/65f3ce95-b875-462e-9646-1b8fd0807ea5">  
<br></br>
Positron just opens the parent folder (in this case, C:\Users\Jon).  This is unexpected, and has the potential to cause problems. In my case, it then started to go through (index) all the files/folders in my OneDrive (cloud storage) and started to download them all, which I did NOT want to happen.
<br></br>
This happens also with "New Folder From Git .."

## What did you expect to happen?
I would expect it to either throw an error that no folder name was given, or disable the "OK" button when no folder name is given.

## Were there any error messages in the output or Developer Tools console?
N/A

**Comment by midleman** [comment]
### Verified Fixed
Positron Version(s) : 2024.11.0-140
OS Version(s) : Windows 11, MacOS

### Test scenario(s) 

Confirmed on both Windows and Mac was unable to create folder for either "new folder" or "new git folder" menu options:

![Image](https://github.com/user-attachments/assets/27327490-d28e-4a71-83a6-14478da5c18b)
![Image](https://github.com/user-attachments/assets/952e16c4-c6ae-4e8d-bfc4-73d5329327d8)

### Link(s) to TestRail test cases run or created: 

n/a
