### ISSUE TITLE
"Trigger Parameter Hints" shows argument defaults for Python but not for R

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#2779]
### Discussed in https://github.com/posit-dev/positron-beta/discussions/118

<div type='discussions-op-text'>

<sup>Originally posted by **JosiahParry** April 15, 2024</sup>
Here i was using the hints to fill out required arguments. I found it odd that error_call and error_arg didnt have defaults. Turns out that wasn't the case. 

<img width="454" alt="image" src="https://github.com/posit-dev/positron-beta/assets/13534508/dc28845a-ec46-45d8-8610-509f5deaa944">
</div>

**Comment by DavisVaughan** [comment]
QA notes:

The verification is something like this video. You accept a completion for a function name, and that automatically calls `Trigger Parameter Hints` (this is a command you can run manually). The parameter hints should now show the default values for arguments - like `values = NULL` and `error_call = caller_env()` here)

https://github.com/user-attachments/assets/bc220352-f6e3-436c-b467-3c86ee44c8ac

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-88
    OS Version          : OSX

### Test scenario(s) 

Tested according to video at end of issue.

Link(s) to TestRail test cases run or created:
N/A
