### ISSUE TITLE
Data Explorer: Provide a nearby affordance for collapsing the Columns panel

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#2823]
Today, the Columns panel takes up about a third of the Data Explorer at typical IDE/screen widths. 

<img width="778" alt="image" src="https://github.com/posit-dev/positron/assets/470418/bb72aa27-c79b-45e5-9a7b-7bf59562e6af">

It is possible to hide it, but it's not obvious (you need to drill into Layout in a menu that's on the opposite side of the Explorer).

<img width="261" alt="image" src="https://github.com/posit-dev/positron/assets/470418/44e2c27e-e1d7-41fb-b812-6f98bed5c640">

Beta users can't find this and think that the Columns view cannot be hidden: https://github.com/posit-dev/positron-beta/discussions/113.

I propose that we provide an affordance for collapsing the Columns view that can be found on the Columns view itself -- e.g. a chevron on the divider bar, or an "x" button in the upper right of the view.

**Comment by juliasilge** [comment]
We have a request here to provide a setting to always have this panel hidden by default: https://github.com/posit-dev/positron/discussions/3987

(I do find myself fairly disrupted by this panel in my real interactive work. 😬 )

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-27
    OS Version          : OSX

### Test scenario(s) 

Verified with flights, R and Python

Link(s) to TestRail test cases run or created: 
N/A
