### ISSUE TITLE
Python: Altair plots show unusable "save" menu

### ISSUE THREAD

**Issue by isabelizimm** [posit-dev/positron#2829]
## Positron Version:

dev

## Steps to reproduce the issue:

Run: 
```
import altair as alt
import pandas as pd

source = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]
})

alt.Chart(source).mark_bar().encode(
    x='a',
    y='b'
)
```

## What did you expect to happen?

Altair has their own "save" menu on the interactive plots that are used to save the plots in notebook environments. I'd expect this menu to either work or be suppressed.

![Screenshot 2024-04-22 at 10 07 07 AM](https://github.com/posit-dev/positron/assets/54685329/d97928c3-bda0-4b6f-99b6-559345296590)

## Were there any error messages in the output or Developer Tools console?

Nope!

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-113
    OS Version          : OSX

### Test scenario(s) 

I was able to save the sample plot shared in the original filing.

Link(s) to TestRail test cases run or created: 
N/A
