### ISSUE TITLE
Improve performance of opening data explorer for a large pandas data frame

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#2851]
## Positron Version:

main branch as of April 22, 2024

Currently the data explorer does not display anything until the initial set of schema, data, and column null count requests go through. For a 33M row data frame, for example, this results in a delay of several seconds while these things compute

[Screencast from 2024-04-22 17-30-28.webm](https://github.com/posit-dev/positron/assets/329591/186923ba-3e19-4c48-be99-2dd737f38669)

A few things to consider:

* The DataExplorerCache.doUpdateCache method serially requests schemas, null counts, and data and does not fire an update event until all three have returned. These requests should be broken up and computed asynchronously
* In Python, expensive computations should probably be moved into coroutines so they don't block cheap computations (like raw data requests)
* Computing the null counts should definitely compute asynchronously rather than blocking 
* It should be possible to render the data waffle before knowing the column schemas, and since with large pandas schemas, getting the schemas can actually be expensive

**Comment by wesm** [comment]
I returned to this after the introduction of asynchronous column profiles. For a 33M row data frame, on my computer the data loads instantly now but the `get_column_profiles` call times out because it takes longer than 10 seconds to compute the profiles, even though asynchronously:

https://github.com/user-attachments/assets/5cc641d2-a76a-47ba-bd57-e639790ef8a3

This issue was discussed in #4629 so I will see if I can fix this and address both issues in the process.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-111
    OS Version          : OSX

### Test scenario(s) 

33M row data frame loads quickly... sparklines come in more slowly but initial data frame view loading is very rapid

Added https://github.com/posit-dev/qa-example-content/blob/main/workspaces/nyc-flights-data-py/flights-33million.py

Link(s) to TestRail test cases run or created:
