### ISSUE TITLE
Data Explorer: Distinguish between NA, NULL, None, and similar string literals in the Waffle

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#2860]
## Positron Version:

```
Positron Version: 2024.04.0 (Universal) build 1522
Code - OSS Version: 1.88.0
Commit: 02906e46e1563260ba30ea7acd2d4081cfad7e61
Date: 2024-04-18T03:26:08.743Z
Electron: 28.2.8
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

## Steps to reproduce the issue:

Run this Python code:

```python
df = pd.DataFrame([['ant', 'bee', None], ['None', None, 'fly']])
```

Then view the `df` data frame. The frame contains some missing values and some strings with the value `None`, but they are impossible to tell apart; they are both rendered as `None`.

<img width="750" alt="image" src="https://github.com/posit-dev/positron/assets/470418/9c1bf492-20ca-4dc1-9e28-f689b88d5df7">

Same deal with NA values in R, and could also be an issue with e.g. NULL values in SQL tables. This is an important distinction because some data sets are very likely to have misrepresentations of these values.

## What did you expect to happen?

When a string is used to represent a missing value, the string should be given a visual treatment to differentiate it from an ordinary value. Here's how RStudio's data viewer does it:

```r
df <- data.frame(a = c("one", "two", NA), b = c("NA", NA, "three"))
View(df)
```

<img width="176" alt="image" src="https://github.com/posit-dev/positron/assets/470418/f4efb070-e7ee-45d0-908f-d69d7216c6b9">

Note that, while the string `NA` and a literal NA value are present in the second column, it's easy to tell them apart.

**Comment by softwarenerd** [comment]
Addressed in https://github.com/posit-dev/positron/pull/4064

**Comment by petetronic** [comment]
Tested examples above for R and Python in Light and Dark themes in Positron 2024.07.0 build 81 on MacOS:
<img width="457" alt="Screenshot 2024-07-19 at 10 34 55 AM" src="https://github.com/user-attachments/assets/c104dcbf-fc53-47d5-a618-ab4111d6213b">
<img width="665" alt="Screenshot 2024-07-19 at 10 34 49 AM" src="https://github.com/user-attachments/assets/377c7ba2-2666-46e2-bab9-6f9fbb3ad64d">
<img width="663" alt="Screenshot 2024-07-19 at 10 34 28 AM" src="https://github.com/user-attachments/assets/6f6c59a9-2c11-445b-acb4-2d580620d1ab">
<img width="460" alt="Screenshot 2024-07-19 at 10 34 16 AM" src="https://github.com/user-attachments/assets/39e95355-43e8-40e2-addb-b0183d2b0151">

**Comment by jthomasmock** [comment]
Definitely looking good across a number of different data types 🎉 

```python
import pandas as pd
import numpy as np

# Creating a dataframe with various types of missing data
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': ['foo', np.nan, 'bar', 'baz', None],
    'C': [np.nan, 2.5, 3.1, None, 4.8],
    'D': [np.nan, pd.NaT, pd.Timestamp('2023-01-01'), pd.NaT, pd.Timestamp('2023-02-01')],
    'E': [None, 'text', 'more text', np.nan, 'even more text']
}

df = pd.DataFrame(data)

%view df
```

<img width="1261" alt="image" src="https://github.com/user-attachments/assets/8361cd85-0218-4cc6-9f90-b6d7556b6b64">

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-89
    OS Version          : OSX

### Test scenario(s) 

Validated with all examples in issue.

Link(s) to TestRail test cases run or created: 
Will add to test backlog
