### ISSUE TITLE
Data Explorer: Rendering glitch when column has 100% missing values

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#2861]
## Positron Version: 

```
Positron Version: 2024.04.0 (Universal) build 1522
Code - OSS Version: 1.88.0
Commit: 02906e46e1563260ba30ea7acd2d4081cfad7e61
Date: 2024-04-18T03:26:08.743Z
Electron: 28.2.8
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

## Steps to reproduce the issue:

Run this Python code:

```python
import pandas as pd
df = pd.DataFrame([[None, None, None]])
%view df
```

Look at the summary stats:

<img width="268" alt="image" src="https://github.com/posit-dev/positron/assets/470418/08ffd5a6-f39e-4ec0-b192-a5abe06e83cc">

There's still a bit of a bar clipped. Here's a closer look at a higher zoom:

<img width="177" alt="image" src="https://github.com/posit-dev/positron/assets/470418/47caaa16-e88e-42e7-b943-360e4b0bc2da">

## What did you expect to happen?

The bar showing 100% missing values should be 100% red.

**Comment by softwarenerd** [comment]
Addressed in https://github.com/posit-dev/positron/pull/4295.

**Comment by softwarenerd** [comment]
This issue is superseded by https://github.com/posit-dev/positron/issues/4291 which is larger in scope and is addressed in https://github.com/posit-dev/positron/pull/4295.

**Comment by softwarenerd** [comment]
Closed as duplicate.
