### ISSUE TITLE
Quarto: Add an API to set preferred editor (for respecting visual mode preference)

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#2933]
Currently, Quarto cannot set the visual editor as the default. A user can set it here, by right-clicking on a Quarto file `.qmd` file in the Explorer tab and choosing _Open with..._:

<img width="800" alt="image" src="https://github.com/posit-dev/positron/assets/470418/db9e8869-5a03-4a3d-903a-1c4d35eef8e1">

However, extensions can't change these. We want Quarto to have control over this behavior so that it can e.g. respect the `editor` YAML preference:

```yaml
---
editor: 
  mode: visual
---
```

This will likely need to take the form of a Positron API.

**Comment by mine-cetinkaya-rundel** [comment]
Just adding that preferred editor information can come from a single document or, in the case of a Quarto project, from the `_quarto.yml` file.

**Comment by isabelizimm** [comment]
I'm going to go ahead and close this issue, since we ended up NOT having to add any new code on the Positron side for supporting preferred editors in the quarto extension. See https://github.com/quarto-dev/quarto/pull/577 for more info.
