### ISSUE TITLE
Ark: `getOption("viewer")` issue with temp directory file paths

### ISSUE THREAD

**Issue by DavisVaughan** [posit-dev/positron#3018]
When you run `reprex::reprex()`, for most of us it opens in the browser, but for Hadley and Jenny it opens in the plot pane. Turns out they have this environment variable set: `TMPDIR = /tmp`, which is used by `tempdir()`.

That is relevant because this is our viewer hook:

```r
> getOption("viewer")
function(url, height = NULL, ...) {
    # Is the URL a temporary file?
    if (startsWith(url, tempdir())) {
        # If so, open it in the HTML viewer.
        .ps.Call("ps_html_viewer", url)
        # TODO: handle `height` for HTML viewer
    } else {
        # If not, open it in the system browser.
        utils::browseURL(url, ...)
    }
}
```

Note `startsWith(url, tempdir())`. On a Mac, this is what `tempdir()` gives me by default:

```r
> tempdir()
[1] "/var/folders/by/4wf2qrmn4_j93s5k5k5fzrx00000gp/T//RtmpZHeZR0"
```

Note the double slashes with `T//` there.

_In the normal case_, when reprex constructs that `url` that gets passed in, for some reason it doesn't actually get the double slashes, it only gets 1 of them, so for everyone except Hadley and Jenny, that `startsWith()` call oddly returns `FALSE`, and we go through the system browser. That's actually a bug, and kind of shows that for Hadley and Jenny it is actually working as expected. Using the `/tmp` directory somehow avoids that double slash issue, and `startsWith()` works for them.

We should probably try and fix this by calling `normalizePath()` on both the `url` and the `tempdir()` before using `startsWith()`, as that seems to align them.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-107
    OS Version          : OSX

### Test scenario(s) 

Got some help from Jenny to validate!  Looks good.

Link(s) to TestRail test cases run or created: 
N/A
