### ISSUE TITLE
Prompt to install Quarto extension when working with Qmd or Rmd files

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#3019]
Via @wch 

> It would be great if the user didn’t have to go out and find an extension for Positron to recognize Rmd files. Or at least Positron should direct the user to download the appropriate extension if they open the file.

I am pretty sure we could do this cheaply because there is already infrastructure to prompt users to install an extension to handle the file type they just opened.

https://github.com/posit-dev/positron/blob/4e94ea8e51bc63072ad4e97a1b78a6287547e7a3/src/vs/workbench/contrib/extensions/browser/fileBasedRecommendations.ts#L134-L141

**Comment by juliasilge** [comment]
We bundle the Quarto extension now so this is no longer a problem.
