### ISSUE TITLE
python: support `streamlit` applications in Viewer pane

### ISSUE THREAD

**Issue by isabelizimm** [posit-dev/positron#3023]
To fully support [streamlit](https://streamlit.io/gallery), we want to be able to:

- recognize `streamlit` Python files and have a gesture to click "Play" and run in terminal
- automatically open  application on "Play" in Viewer pane

Notes:

Running `streamlit` apps uses the CLI `streamlit run app_name.py`, powered by `asyncio.run()`.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-95
    OS Version          : OSX

### Test scenario(s) 

Verified by adding streamlit example to qa-example-content

Link(s) to TestRail test cases run or created:
