### ISSUE TITLE
Python: support `fastapi` APIs in Viewer Pane

### ISSUE THREAD

**Issue by isabelizimm** [posit-dev/positron#3024]
To fully support [fastapi](https://fastapi.tiangolo.com/), we would want to be able to:

- recognize `fastapi` Python files and have a gesture to click "Play" and run in terminal
- automatically open running APIs in Viewer pane

Notes:

We might want to have Play options for `fastapi dev app.py` as well as `fastapi run app.py`; running fastapi in dev mode will auto-reload the API endpoint and is convenient for iterating on a file. FastAPI uses a lot of `starlette` under the hood, so we might be able to get `starlette` support for free when implementing `fastapi`.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-95
    OS Version          : OSX

### Test scenario(s) 

Added fastapi example to qa-example-content and ran with customized menu

Link(s) to TestRail test cases run or created:
