### ISSUE TITLE
Python: support `dash` applications in Viewer pane

### ISSUE THREAD

**Issue by isabelizimm** [posit-dev/positron#3025]
To fully support [Dash](https://dash.plotly.com), we want to be able to:

- recognize Dash Python files and have a gesture to click "Play" and run in terminal
- automatically open application on "Play" in Viewer pane

Notes:

Dash does not use a special CLI command, you currently run `python app.py` for a Dash app. It is powered by Flask (and also has modes to be run inside a Jupyter notebook environment).

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-95
    OS Version          : OSX

### Test scenario(s) 

Verified by adding dash example to qa-example-content

Link(s) to TestRail test cases run or created:
