### ISSUE TITLE
Python: support `gradio` applications in Viewer Pane

### ISSUE THREAD

**Issue by isabelizimm** [posit-dev/positron#3027]
To fully support [gradio](https://www.gradio.app/), we would want to be able to:

- recognize gradio Python scripts and have a gesture to click "Play" and run in terminal
- automatically open running APIs in Viewer pane

Notes:

Gradio can be embedded in ipynb or run from a Python script. Gradio does not have a dedicated CLI, use `python app.py` to run

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-95
    OS Version          : OSX

### Test scenario(s) 

Verified by adding gradio sample to qa-example-content

Link(s) to TestRail test cases run or created:
