### ISSUE TITLE
Diagnostics: No symbol in scope when assigning variables in function calls

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#3048]
### Discussed in https://github.com/posit-dev/positron-beta/discussions/175

<div type='discussions-op-text'>

<sup>Originally posted by **jeffkeller-einc** May  7, 2024</sup>

<img width="301" alt="Screenshot 2024-05-07 at 10 04 29 AM" src="https://github.com/posit-dev/positron-beta/assets/113363108/60dee46b-3af3-4126-9283-18a029a3538c">

I don't know what this pattern is called, but I do it a lot to modularize my non-package R projects.

```r
source("helper_functions.R", local = helpers <- new.env())
helpers$myfun(...)
```</div>

**Comment by jennybc** [comment]
I just came across a variant of this in cli, except it's a variable assignment in an `if()` condition.

The general form that's problematic:

```r
if (nzchar(ASDF <- Sys.getenv("ASDF"))) {
  if (ASDF == "whatever") {
    message("hi")
  }
}
```

In Positron, the `ASDF` inside the `if` body gets the diagnostic "No symbol named 'ASDF' in scope."

The real world example: https://github.com/r-lib/cli/blob/7ca06ff9c1c881359b562ecb98a1414e44d78fb8/R/ansi-hyperlink.R#L347-L355

**Comment by lionel-** [comment]
I'm now thinking we should be overly optimistic about potential assignments instead of overly cautious.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-2
    OS Version          : OSX

### Test scenario(s) 

Verified with Julia's example

Link(s) to TestRail test cases run or created:
