### ISSUE TITLE
Data Explorer tabs not restored on reload/resume tab

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#3172]
## Positron Version:

```
Positron Version: 2024.05.0 (Universal) build 1255
Code - OSS Version: 1.89.0
Commit: a60c905e786adc4cfccae02d538c5a2ac5ad9b01
Date: 2024-05-16T03:42:49.370Z
Electron: 28.2.8
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

## Steps to reproduce the issue:

1. Open two editors and two data explorer windows.
2. Use the _Developer -> Reload Window_ command.

The data explorer windows disappear and aren't restored on reload. 

## What did you expect to happen?

The data explorers should be restored.

Just as we do with Plots, we should ask the backend to list its open comms to discover the set of data explorers that are still open, and restore tabs for each one.

This is an important feature for Posit Workbench; without it, you'll lose all your open explorers (and any filter/sort state you accumulated in them) if you close your browser tab.

**Comment by sharon-wang** [comment]
## QA Notes

- PR: #5475 
- Follow-up issue: #5489

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.12.0-80](https://github.com/posit-dev/positron-builds/releases/tag/2024.12.0-80)
Workbench Version(s):[2024.12.0+456.pro3](https://dailies.rstudio.com/version/2024.12.0+456.pro3)
OS Version(s) : Ubuntu 24

### Test scenario(s) 

Data explorer tabs reload as expected. With the notable exception of date explorer tabs opened directly from the datafile (aka headless, duckdb based).  See #5523 

### Link(s) to TestRail test cases run or created:
