### ISSUE TITLE
`rstudioapi::documentSaveAll()` should be blocking

### ISSUE THREAD

**Issue by hadley** [posit-dev/positron#3256]
## Positron Version:

Positron Version: 2024.05.0 (Universal) build 3
Code - OSS Version: 1.88.0
Commit: f42bdc6400fb18fb5ca4a4ae0fc49c7a4046d6d3
Date: 2024-05-03T05:46:37.316Z
Electron: 28.2.8
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

## Steps to reproduce the issue:

1. Open a large package
2. Change a file
3. Press `Cmd + Shift + L`
4. If you inspect the source code, the change isn't reflected in the loaded package

## What did you expect to happen?

`devtools::load_all()` calls `rstudioapi::documentSaveAll()` which should block until all files are saved.

## Were there any error messages in the output or Developer Tools console?

No

**Comment by juliasilge** [comment]
I outlined [some possible QA steps here](https://github.com/posit-dev/positron/pull/4228#issue-2445860612), but another easier option would be to use `rstudioapi::executeCommand("saveAllSourceDocs")` with an untitled file. The R session will be blocked until you choose a filename for the untitled file.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.08.0-31](https://github.com/posit-dev/positron-builds/releases/tag/2024.08.0-31)
OS Version(s) : Windows 11, MacOS

### Test scenario(s) 



Following Julia's steps, it blocks as expected.

### Link(s) to TestRail test cases run or created:
