### ISSUE TITLE
Support two-way communication in ipywidgets

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#3276]
Currently, if you create a widget with ipywidgets:

```python
import ipywidgets as widgets
a = widgets.FloatSlider()
display(a)
```

And adjust the slider, the state is not updated in the kernel:

```python
print(a.value)
# 0
```

Similarly, if you set the state in the kernel, the widget view doesn't update:

```python
a.value = 100
# Nothing happens in the frontend
```

This is because we're not handling messages over the widget comm between its frontend and backend.

**Comment by seeM** [comment]
For verification, the following widget libraries should work in the latest release:

* `ipywidgets` – all widget types except `Output` and `Image`
* `ipytree`
* `ipyleaflet`
* `anywidget`
* `drawdata`
* `pythreejs`

These widgets libraries will not yet work:

* `bqplot`
* `ipycanvas`
* `ipydatagrid`
* `ipympl`

**Comment by testlabauto** [comment]
Seeing
Error loading renderer 'positron-ipywidgets'
Failed to fetch dynamically imported module: https://file+.vscode-resource.vscode-cdn.net/Applications/Positron.app/Contents/Resources/app/extensions/positron-ipywidgets/renderer/dist/index.js

Note that the t/Applications/Positron.app/Contents/Resources/app/extensions/positron-ipywidgets/renderer/dist dir doesn't exist.

**Comment by testlabauto** [comment]
Sorry to report that a similar error is still appearing:

```
Error loading renderer 'positron-ipywidgets'
Failed to fetch dynamically imported module: https://file+.vscode-resource.vscode-cdn.net/Applications/Positron.app/Contents/Resources/app/extensions/positron-ipywidgets/renderer/media/index.js
```

If I check the filesystem:
```
ls /Applications/Positron.app/Contents/Resources/app/extensions/positron-ipywidgets/renderer/
package.json  src           tsconfig.json yarn.lock
```

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-24
    OS Version          : OSX

### Test scenario(s) 

>>> import ipywidgets as widgets
... a = widgets.FloatSlider()
... display(a)

# Manually move slider

>>> print(a.value)
62.7


Link(s) to TestRail test cases run or created:
N/A

**Comment by manzt** [comment]
Sweet!!! Can confirm anywidget is working:

<img alt="image" src="https://github.com/user-attachments/assets/65d0f68a-d3fc-4e78-abc3-5d24310625ee">
