### ISSUE TITLE
Data Explorer: Layout button tooltip is clipped

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#3290]
## Positron Version:

```
Positron Version: 2024.05.0 (Universal) build 1307
Code - OSS Version: 1.89.0
Commit: a32eab640724ad6257adc4f7636986afe7c73467
Date: 2024-05-27T03:48:23.965Z
Electron: 28.2.8
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

## Steps to reproduce the issue:

1. Open the Data Explorer
2. Hover over the _Layout_ button

The tooltip appears, but you can't read the whole thing.

<img width="322" alt="image" src="https://github.com/posit-dev/positron/assets/470418/dfcc56eb-f5f9-450a-9c2b-845fc565381c">

## What did you expect to happen?

The tooltip should be positioned so that all the text is readable.

**Comment by softwarenerd** [comment]
This problem was fixed in https://github.com/posit-dev/positron/pull/3609 and is ready for review.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-81
    OS Version          : OSX

### Test scenario(s) 

Tooltip text is now fully legible

Link(s) to TestRail test cases run or created: 
N/A
