### ISSUE TITLE
Refine display of datetime summary stats in data explorer profile pane

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#3341]
By default, the statistics appear with the time zone and null count chopped off, you have to expand the summary pane for them to be visible. Perhaps the font should be made smaller for the date statistics or the text should wrap so it isn't cut off like this

![image](https://github.com/posit-dev/positron/assets/329591/51f1501c-cf55-4bcb-b94e-bf562155b1b2)

follow up work to #3324

**Comment by softwarenerd** [comment]
This issue was fixed by other work that was done in the Data Explorer table summary component.

<img width="1530" alt="image" src="https://github.com/user-attachments/assets/345ad068-08c3-4a8d-af6d-47605c91fd8c">
