### ISSUE TITLE
Reduce code duplication in data explorer summary stats React components

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#3342]
The profileXXX.tsx files share substantial amounts of boilerplate code. We should try to refactor to improve code reuse and maintainability

follow up to #3324

**Comment by softwarenerd** [comment]
This work has been completed.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-55
    OS Version          : OSX

### Test scenario(s) 

Marking verified based on Brian's comment.  No obvious verification strategy available besides seeing that profile data is still working.

Link(s) to TestRail test cases run or created:
