### ISSUE TITLE
Add/update unit tests for project wizard python extension updates

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#3433]
#### PythonRuntimeManager
- code: https://github.com/posit-dev/positron/blob/main/extensions/positron-python/src/client/positron/manager.ts
    - `registerLanguageRuntimeFromPath` has been updated to return a different type in #3385 
    - `validateMetadata` has been updated as well. Some new tests can be added
- test file: https://github.com/posit-dev/positron/blob/main/extensions/positron-python/src/test/positron/manager.unit.test.ts

#### createEnvApi
- code: https://github.com/posit-dev/positron/blob/main/extensions/positron-python/src/client/pythonEnvironments/creation/createEnvApi.ts
    - `registerCreateEnvironmentFeatures` has been updated in #3385 and prior PRs to include new python commands for retrieving environment providers, conda python versions, and creating and registering a new environment
- test file: https://github.com/posit-dev/positron/blob/main/extensions/positron-python/src/test/pythonEnvironments/creation/createEnvApi.unit.test.ts
    - we can also add some quickpick-less versions of the existing create environment tests
    - we may want to create separate test files for the introduced commands: https://github.com/posit-dev/positron/tree/main/extensions/positron-python/src/test/pythonEnvironments/creation

---

### PR: https://github.com/posit-dev/positron/pull/4540

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : main on Sep6 at 1:00 PM MST
    OS Version          : OSX

### Test scenario(s) 

New unit tests pass.

Link(s) to TestRail test cases run or created: 
N/A
