### ISSUE TITLE
Data Explorer: Inf in Pandas throw a warning in console

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#3437]
## Positron Version: 2024.06.0 (Universal) build 29
Code - OSS Version: 1.89.0
Commit: 582778182a85ad1786b329edd10f7ad0ac445792
Date: 2024-06-06T03:49:05.811Z
Electron: 28.2.8
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

## Steps to reproduce the issue:

1. Create a DataFrame with some infinite values

```python
import pandas as pd
import numpy as np

data = {
    'A': [1, 2, np.inf, 4],
    'B': [5, np.inf, 7, 8],
    'C': [9, 10, 11, np.nan]
}

df = pd.DataFrame(data)

print(df)

%view df
```

2. Notice a warning in the console, which will print the first time a calculation is attempted for columns with `np.inf`.

```python
/Users/thomasmock/data-explorer/.venv/lib/python3.12/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
```

I'm not 100% sure if it is related, but I also noticed that the Data Explorer was blank until I resized the tab.

https://github.com/posit-dev/positron/assets/29187501/7bd7c6cb-b140-4592-a444-567748f69041

## What did you expect to happen?

It still works, but the warning shouldn't be displayed in the console.

## Were there any error messages in the output or Developer Tools console?

```
/Users/thomasmock/data-explorer/.venv/lib/python3.12/site-packages/pandas/core/nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
```

**Comment by wesm** [comment]
This had been addressed, but I moved it into verification so it can be closed out

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.07.0-27](https://github.com/posit-dev/positron/releases/tag/2024.07.0-27)
OS Version(s) : Windows 11

### Test scenario(s) 

Example runs without any errors or warnings as expected

### Link(s) to TestRail test cases run or created: 

None
