### ISSUE TITLE
Change required renv version to 1.0.8(?)

### ISSUE THREAD

**Issue by timtmok** [posit-dev/positron#3439]
Once https://github.com/rstudio/renv/pull/1915 merges and `renv` releases a new version, the `renv::init` part of project initialization should change to require that version. This would improve the experience for `renv` users in Positron.

**Comment by jennybc** [comment]
renv 1.0.8 was accepted on CRAN today (2024-09-20), so this is unblocked now.

https://cloud.r-project.org/web/packages/renv/index.html

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.10.0-5
    OS Version          : OSX

### Test scenario(s) 

Verified to be 1.0.9 by watching project wizard automated cases run.

Link(s) to TestRail test cases run or created:
