### ISSUE TITLE
Summary statistics support for polars in the data explorer

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#3453]
Part of epic #2185

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-97
    OS Version          : OSX

### Test scenario(s) 

Verified with https://github.com/posit-dev/qa-example-content/blob/main/workspaces/polars-dataframe-py/polars_basic.py and with slight variations on it.

Link(s) to TestRail test cases run or created: 
N/A
