### ISSUE TITLE
Copy-paste support for polars in the data explorer

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#3454]
This is implementing the `export_data_selection` RPC. Part of epic #2185

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-15
    OS Version          : OS X

### Test scenario(s) 

Tested with https://github.com/posit-dev/qa-example-content/blob/main/workspaces/polars-dataframe-py/polars_basic.py

Link(s) to TestRail test cases run or created: 
N/A
