### ISSUE TITLE
add "Reset Layout" command

### ISSUE THREAD

**Issue by kevinushey** [posit-dev/positron#346]
After dragging different views around, it's tough to "revert" to the default view in some cases. It would be helpful if we had a command that reset the layout to the defaults.

**Comment by juliasilge** [comment]
The UI layout presets that we created for #3038 allow the user to snap to a couple of default views:

![Screenshot 2024-09-03 at 8 11 59 PM](https://github.com/user-attachments/assets/0b3b4f76-1fb6-4104-aba0-1429c18def39)

The actions are available as commands as well.
