### ISSUE TITLE
Intermittent `Request textDocument/completion failed` from R LSP 

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#3467]
As I am working on various projects, I am noticing that occasionally I see this error:

![Screenshot 2024-06-10 at 8 39 06 AM](https://github.com/posit-dev/positron/assets/12505835/c3b7a976-b3c4-4db2-972e-aef2b4868b55)

I have no idea what I am doing that prompts this. Just now, I was typing in a `.R` file but I have also observed in while working in Quarto.

Here are the LSP logs, which were what that "Go to output" prompts me to go to:

[lsp.log](https://github.com/user-attachments/files/15775006/lsp.log)

**Comment by lionel-** [comment]
I haven't seen this in a while, thanks for the fixes!
