### ISSUE TITLE
On Windows and Linux, keyboard shortcuts in custom menus are displayed incorrectly

### ISSUE THREAD

**Issue by softwarenerd** [posit-dev/positron#3472]
## Steps to reproduce the issue:

![image](https://github.com/posit-dev/positron/assets/853239/0bab82f6-d3bf-49a4-982e-cd86b659b485)

On Windows, keyboard shortcuts in custom menus are displayed incorrectly as, for example, C t r l + C.

## What did you expect to happen?

Keyboard shortcuts in custom menus should look like Ctrl + C.

## Were there any error messages in the output or Developer Tools console?

No.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.09.0-27](https://github.com/posit-dev/positron-builds/releases/tag/2024.09.0-27)
OS Version(s) : Windows 11, Ubuntu 22

### Test scenario(s) 



The text now appears as expected.

### Link(s) to TestRail test cases run or created:
