### ISSUE TITLE
Add Positron theme colors from unspecified VS Code theme colors

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#3473]
VS Code's themes have grown a few new colors that are not yet defined in Positron. Diffing our copy of the themes with VS Code's, I found the following colors that are defined by VS Code but not Positron (in e.g. `light_modern.json`):

```javascript
[
  'editorIndentGuide.background1',
  'list.focusAndSelectionOutline',
  'menu.selectionBackground',
  'menu.selectionForeground',
  'tab.selectedBorderTop',
  'terminal.inactiveSelectionBackground',
  'textPreformat.background',
  'textPreformat.foreground'
]
```

In addition, the following colors are defined in Positron but not VS Code (can/should we remove them?)

```javascript
[
  'activityBar.activeBackground',
  'editorIndentGuide.background',
  'list.inactiveSelectionBackground',
  'scrollbar.shadow',
  'scrollbarSlider.activeBackground',
  'scrollbarSlider.background',
  'scrollbarSlider.hoverBackground',
  'terminal.background'
]
```

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-81
    OS Version          : OSX

### Test scenario(s) 

Spot checked new integration test baseline.

Link(s) to TestRail test cases run or created:
