### ISSUE TITLE
Project Wizard: Enter key doesn't work without tabbing past selection of a project type

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#3491]
## Steps to reproduce the issue:

1. Start to create a project with the project wizard 
2. Select an R or Python project using TAB and arrow keys
3. Hit Enter
4. Note that it won't function without tabbing over to the Next button

## What did you expect to happen?
The enter key would immediately work after selecting a project type (when Next becomes active)

## Were there any error messages in the output or Developer Tools console?
No

**Comment by sharon-wang** [comment]
Another test case: https://github.com/posit-dev/positron/issues/4203

**Comment by petetronic** [comment]
Thomas also mentioned Enter was not working for the Missing R Package dialog, my assumption is there's something missing in the base modal components for these cases.

**Comment by sharon-wang** [comment]
Yes, we disabled the default key `Enter` behaviour in https://github.com/posit-dev/positron/pull/3442 as it was causing [incorrect behaviour in some modals](https://github.com/posit-dev/positron/issues/3217) where pressing `Enter` would accept and close the modal, however the default button is not always for accepting and closing the modal (e.g. the default button could be a <kbd>Next</kbd> or <kbd>Browse</kbd> button).

We figured it was more disruptive for the `Enter` key to accept/close a modal whose default button is not <kbd>OK</kbd> (which can cause undefined behaviour and loss of user progress) than for the user to have to click the default button, at least until we add support for the default button action.

**Comment by softwarenerd** [comment]
This issue is addressed in https://github.com/posit-dev/positron/pull/4739.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-81
    OS Version          : OSX

### Test scenario(s) 

Enter key functions as expected in project wizard

Link(s) to TestRail test cases run or created:
