### ISSUE TITLE
Improve how Python objects passed via reticulate to R are presented in Variables pan

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#3502]
When you create an R object representing a Python object via reticulate, it is not represented well in the Variables pane:

![image](https://github.com/posit-dev/positron/assets/12505835/7a53bbc2-41f4-47be-925a-7667a1879c84)

cc @t-kalinowski 

QA:

Please install reticulate from GitHub:

```
remotes::install_github("rstudio/reticulate")
```

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-41
    OS Version          : OSX

### Test scenario(s) 

mtcars <- reticulate::r_to_py(mtcars)

Looks great!

Link(s) to TestRail test cases run or created:
