### ISSUE TITLE
New Project Wizard long directory names cause issues

### ISSUE THREAD

**Issue by jonvanausdeln** [posit-dev/positron#3561]
## Positron Version:
[2024.06.0-770](https://github.com/posit-dev/positron/releases/tag/2024.06.0-770)
## Steps to reproduce the issue:

1. Start New Project wizard
2. Use a VERY long folder name
3. Create new project

Project and folder created, but the UI hangs.

See https://github.com/posit-dev/positron/issues/2781#issuecomment-2166544760

## What did you expect to happen?
Warning/error message not letting me create something with that long of a name

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.06.1-54
    OS Version          : OS X

### Test scenario(s) 

Warning now displayed if your path is too long such as Jon's in the link in the initial filing.


Link(s) to TestRail test cases run or created: 
N/A
