### ISSUE TITLE
Python: Variables pane shows type+number in `numpy==2.0.0`

### ISSUE THREAD

**Issue by isabelizimm** [posit-dev/positron#3582]
## Positron Version:

positron dev

## Steps to reproduce the issue:

1. `pip install numpy==2.0.0` (recommended in fresh environment as many packages do not yet have 2.0 support)
2. In Console, 
 
```python
import numpy as np
y = np.float16(3.5)
x = np.array([1, 2, 3])
```
![Screenshot 2024-06-18 at 2 59 03 PM](https://github.com/posit-dev/positron/assets/54685329/ba40effc-70af-41de-87b4-555e783457ba)

FWIW: I had originally installed numpy 2.0 and then did NOT restart my kernel and the variables pane did not show arrays at all. I don't think we should fix this as restarting kernel _should_ be done by the user when they install a new package, but in case others run into the same issue.

## What did you expect to happen?

Variables pane to function as normal and display number, not type and number

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.07.0-21](https://github.com/posit-dev/positron/releases/tag/2024.07.0-21)
OS Version(s) : Windows 11, MacOS 14

### Test scenario(s) 

Repro now works as expected. Variable show correctly.

### Link(s) to TestRail test cases run or created: 

N/A
