### ISSUE TITLE
Add positron layout service

### ISSUE THREAD

**Issue by nstrayer** [posit-dev/positron#3586]
Right now custom layouts are done via a command that dispatches methods on two separate services (`IWorkbenchLayoutService` and `IViewDescriptorService`). This is fine if we assume that we only ever want to run layout updates via a command, but causes leaking of implementation details when we want to use the same layouts in other parts of the IDE where it's not convenient to call the action. 

The proposed solution is to make a new service for layouts that will at start just the setting of a predefined layout. E.g. 
```ts
IPositronLayoutService.setLayout(stackedDsLayout)
```

But in the future could be expanded to things like tweaking the existing layout E.g. 
```ts
IPositronLayoutService.setSidebarWidth('20%')
```

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.06.1-54
    OS Version          : OS X

### Test scenario(s) 

Implicitly tested with smoke test update variables automation which resizes the variables pane.

Link(s) to TestRail test cases run or created: 
N/A
