### ISSUE TITLE
Remove handling for Quarto hash pipe comments

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#3595]
We have `onEnterRules` for Quarto comments:

https://github.com/posit-dev/positron/blob/bbddf9e2075659eca07bc2078ade2d40475c0cc7/extensions/positron-r/language-configuration/r-language-configuration.json#L52-L56

However, this doesn't work quite right. As @hfrick points out, when you press enter a couple of times, it continues adding more `#|` instead of switching to an empty line after you don't add any content. The behavior is correct with the Quarto extension in VS Code so I think we just need to remove this rule.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.07.0-21](https://github.com/posit-dev/positron/releases/tag/2024.07.0-21)
OS Version(s) : Windows 11, MacOS 14

### Test scenario(s) 

`#|` - will switch to empty line if no content after pipe

 `#*` - continues "forever" as expected.


### Link(s) to TestRail test cases run or created: 

None
