### ISSUE TITLE
pydantic errors in Python 3.12.4

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#3605]
Per https://github.com/pydantic/pydantic/issues/9637, we are seeing this failure https://github.com/posit-dev/positron/actions/runs/9604457780/job/26489992926 and I believe can be resolved by upgrading to the maintenance release of pydantic just released https://pypi.org/project/pydantic/1.10.17/

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-81
    OS Version          : OSX

### Test scenario(s) 

Marking as verified as there have been many successful runs of Positron Python CI since 518.

Link(s) to TestRail test cases run or created: 
N/A
