### ISSUE TITLE
Add smoke tests for help/viewer pane collapse/expand logic

### ISSUE THREAD

**Issue by nstrayer** [posit-dev/positron#3623]
There's been a lot of code written around handling special collapse and resize behavior for the help and viewer panes. (See 
#3534, #3445, #3263,...)

We should really have a smoke test written to ensure we don't cause regressions like some of those PR's have. 

Since this relies on a specific pane layout we'll want to wait for #3616 to be merged so we can create the layout we want without a bunch of playwright drag-and-drop code.

**Comment by jonvanausdeln** [comment]
PR merged and tests running in CI successfully.
