### ISSUE TITLE
Positron doesn't seem to understand `..1` syntax

### ISSUE THREAD

**Issue by DavisVaughan** [posit-dev/positron#3632]
### Discussed in https://github.com/posit-dev/positron/discussions/3631

<div type='discussions-op-text'>

<sup>Originally posted by **mikemahoney218** June 24, 2024</sup>
Hi all! The syntax highlighting in Positron appears to not recognize the `..1` syntax used to get the first element of `...`:

![image](https://github.com/posit-dev/positron-beta/assets/38229299/e0422467-044d-47a8-8f11-4df920e1b997)
</div>

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-95
    OS Version          : OSX

### Test scenario(s) 

Syntax highlighting no longer considers ..1 to be invalid.

Link(s) to TestRail test cases run or created:
