### ISSUE TITLE
Data Explorer does not indicate where focus is inside of the component

### ISSUE THREAD

**Issue by softwarenerd** [posit-dev/positron#3634]
`DataExplorer` does not indicate where focus is inside of the component.

When a user focuses the table summary `DataGrid` component or the table data `DataGrid` component in the `DataExplorer` component, nothing in the user interface changes to indicate which component is focused.

In this movie, I'm moving focus between the table summary `DataGrid` component an the table data `DataGrid` component. This is no visual indication that anything is happening.

https://github.com/posit-dev/positron/assets/853239/622320fc-ddb5-49c6-b34c-8496cbe3d3ac

**Comment by softwarenerd** [comment]
This has been fixed through several PRs, the most recent of which is https://github.com/posit-dev/positron/pull/4696.

Here's a screen recording of focus tracking within a Data Explorer.

https://github.com/user-attachments/assets/5bb3f766-7d95-4826-8729-045e3f81553e

**Comment by midleman** [comment]
### Verified Fixed
Positron Version(s) : [2024.09.0-62](https://github.com/posit-dev/positron-builds/releases/tag/2024.09.0-62)
OS Version(s) : MacOS 14

### Test scenario(s) 
Confirmed that when user navigates between table summary and table data the UI indicates a focus change.

### Link(s) to TestRail test cases run or created: 

n/a
