### ISSUE TITLE
Ark: Set `R_INCLUDE_DIR` and `R_SHARE_DIR` envvars?

### ISSUE THREAD

**Issue by lionel-** [posit-dev/positron#3637]
These are set by the R launcher shell script but not by ark, resulting in a different environment. RStudio sets them too.

One consequence is that running `make -f $R_HOME/etc/Makeconf` from inside Ark results in an error because these variables expand to `""`.

**Comment by juliasilge** [comment]
@lionel- what scenarios does this break?

**Comment by lionel-** [comment]
The compilation-database generator in pkgload had to work around the absence of these envvars (and introduced another bug by doing so https://github.com/r-lib/pkgload/pull/288).

**Comment by kevinushey** [comment]
RStudio also does this; see e.g.

https://github.com/rstudio/rstudio/blob/74696236366342008aeda8da21beefb502c8c4a9/src/cpp/core/r_util/REnvironmentPosix.cpp#L506-L515

I think `ark` will want to read and set these as well.

**Comment by DavisVaughan** [comment]
And `R_DOC_DIR`, see below

```r
> R.home
function (component = "home")
{
    rh <- .Internal(R.home())
    switch(component, home = rh, bin = if (.Platform$OS.type ==
        "windows" && nzchar(p <- .Platform$r_arch)) file.path(rh,
        component, p) else file.path(rh, component), share = if (nzchar(p <- Sys.getenv("R_SHARE_DIR"))) p else file.path(rh,
        component), doc = if (nzchar(p <- Sys.getenv("R_DOC_DIR"))) p else file.path(rh,
        component), include = if (nzchar(p <- Sys.getenv("R_INCLUDE_DIR"))) p else file.path(rh,
        component), modules = if (nzchar(p <- .Platform$r_arch)) file.path(rh,
        component, p) else file.path(rh, component), file.path(rh,
        component))
}
```

**Comment by lionel-** [comment]
See also https://github.com/posit-dev/positron/issues/4133 for a likely consequence of not setting the include envvar.

**Comment by shikokuchuo** [comment]
Strange, it doesn't work for me even if I include in ~/.Renviron:
```
R_INCLUDE_DIR=/usr/share/R/include
R_SHARE_DIR=/usr/share/R/share
```
I can see these are set from within Positron using `Sys.getenv()`. However I still get the error on hover over an R API function in a C file:

```
'R.h' file not found clang(pp_file_not_found)
```
System details:

```
Positron Version: 2024.09.0 build 1
Code - OSS Version: 1.92.0
Commit: f37f4f5044a2a619e73d5db61a31e37fbd3faf18
Date: 2024-09-03T02:28:43.515Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-40-generic
```

**Comment by kevinushey** [comment]
My understanding is that `clangd` works best if you can generate a `compile_commands.json` file, which it can then use to figure out how your project is structured. https://clangd.llvm.org/installation#project-setup

For R specifically, I think you can use [bear](https://github.com/rizsotto/Bear) to generate that file; you could then do something like:

```
bear -- R CMD INSTALL --preclean .
```

in your R package directory.

**Comment by DavisVaughan** [comment]
@shikokuchuo see https://github.com/posit-dev/positron/discussions/4534#discussioncomment-10501168 for how to use pkgload to auto generate a `compile_commands.json` file for use with clangd, you _must_ create one otherwise clangd basically doesn't work

**Comment by shikokuchuo** [comment]
Thanks @kevinushey and @DavisVaughan! It worked after I made a change to `pkgload` - have submitted [this PR](https://github.com/r-lib/pkgload/pull/297#issue-2507407445).

The `compile_commands.json` isn't generated for all projects though - probably due to https://github.com/r-lib/pkgload/issues/289#issue-2382200347 I haven't investigated yet.

**Comment by lionel-** [comment]
Since this is coming up regularly I prioritised this to the December release.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-2
    OS Version          : OSX

### Test scenario(s) 
```
stopifnot(
  nzchar(Sys.getenv('R_SHARE_DIR')),
  nzchar(Sys.getenv('R_INCLUDE_DIR')),
  nzchar(Sys.getenv('R_DOC_DIR'))
)
```
passes

Link(s) to TestRail test cases run or created:
