### ISSUE TITLE
Python: `plotnine` titles and legends not showing in plots pane

### ISSUE THREAD

**Issue by isabelizimm** [posit-dev/positron#3638]
## Positron Version:

```
Positron Version: 2024.06.1 (Universal) build 10
Code - OSS Version: 1.90.0
Commit: 2ee647c28f932ea3032d6275664c6a8494baacb4
Date: 2024-06-24T03:50:10.276Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

## Steps to reproduce the issue:
run
 
```python
from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap, labs
from plotnine.data import mtcars

(
    ggplot(mtcars, aes("wt", "mpg", color="factor(gear)"))
    + geom_point()
    + stat_smooth(method="lm")
    + facet_wrap("gear")
    + labs(
        title = "mtcars"
    )
)
```
in jupyter notebook (left, correct output) and console/plots pane (right, incorrect output)

<img width="1581" alt="Screenshot 2024-06-25 at 10 04 45 AM" src="https://github.com/posit-dev/positron/assets/54685329/5d35eee5-4b79-46fb-b85b-444de051356d">

## What did you expect to happen?

The plot in the plots pane should look like the one on the left

## Were there any error messages in the output or Developer Tools console?

None

**Comment by nstrayer** [comment]
<img width="816" alt="image" src="https://github.com/user-attachments/assets/9c3bdc12-d433-4101-be31-461813fb20d9">
This appears to be due to improper positioning of the image within the available output space. The right components are there, just hidden and not able to be scrolled to.

**Comment by seeM** [comment]
I'm not able to repro this in Positron Version: 2024.07.0 (Universal) build 125. @isabelizimm @nstrayer could you please try again?

<img width="639" alt="image" src="https://github.com/user-attachments/assets/95954202-e5f1-4b24-b4aa-8f729eb1ec8f">

**Comment by isabelizimm** [comment]
I am no longer able to repro on Positron dev, nor `Positron Version: 2024.07.0 (Universal) build 125` + `plotnine==0.13.4` 👀 going to go ahead and close this, but we can reopen if it pops up again!
