### ISSUE TITLE
Not recognising jupyter notebook cell type is now raw

### ISSUE THREAD

**Issue by dkgaraujo** [posit-dev/positron#3668]
## Positron Version:
2024.06.1 Build 27 (Mac)

## Steps to reproduce the issue:

1. Open jupyter notebook with first cell of type raw with yaml content, as used for rendering via quarto
2. Positron thinks the cell is actually python
3. Even when changing the type back to raw, the error does not go away

<img width="1377" alt="Screenshot 2024-06-27 at 23 43 13" src="https://github.com/posit-dev/positron/assets/16483074/55ba3f4c-6b99-4d67-956f-4faa4418445d">

## What did you expect to happen?

I expected Positron to either recognise the raw cell right away, or at least to recognise it as raw after the cell type was changed to raw.

## Were there any error messages in the output or Developer Tools console?

No.

**Comment by petetronic** [comment]
Thank you for reporting this, I'm able to reproduce this issue.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-113
    OS Version          : OSX

### Test scenario(s) 

Verified with same raw cell contents as in original filing.

Link(s) to TestRail test cases run or created: 
N/A
