### ISSUE TITLE
Shortcuts, snippets and addins dropdowns are essential

### ISSUE THREAD

**Issue by iamYannC** [posit-dev/positron#3669]
Hey there.

I use these three drop-downs all the times for various use-cases.
The addins window (mostly styler), the edit shortcuts and the great snippets.

Are you expected to add those to fixed dropdowns anytime soon?
Thanks for the efforts

**Comment by juliasilge** [comment]
Thanks for this feedback! 🙌 Overall in Positron, you'll mostly go to the command palette for these kinds of steps (as opposed to more dropdown menus that are used in RStudio).

- We are tracking support for addins in #1313. For styler specifically, check out the commands "Format Document" and "Format Selection" which currently use styler for R code.
- By shortcuts, do you mean keyboard shortcuts? You can [customize keyboard shortcuts extensively](https://code.visualstudio.com/docs/getstarted/keybindings), or you may be interested in opting in to the RStudio Keymap for shortcuts that come from RStudio.
- You can bring up snippets such as `fun` or `if`, etc, from a source editor and accept with <kbd>Tab</kbd>. You can also [create your own snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets).

Let us know if you have followup questions on this!

**Comment by juliasilge** [comment]
Let us know if you have followup questions!
