### ISSUE TITLE
Reactable HTML widget not showing up in Viewer Pane

### ISSUE THREAD

**Issue by vladtarko** [posit-dev/positron#3678]
## Positron Version:

Positron Version: 2024.06.1 build 27
Code - OSS Version: 1.90.0
Commit: a893e5b282612ccb2200102957ac38d3c14e5196
Date: 2024-06-26T01:22:29.024Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.9.3-76060903-generic

## Steps to reproduce the issue:

1. `mtcars |> reactable::reactable()`
2. The following is shown in the console: `<reactable HTML widget>`, and the Viewer pane gets focused, but nothing shows up.

## What did you expect to happen?

The interactive `reactable` should show up in the Viewer Pane. This works both in VS Code and in RStudio. This is how it looks in VS Code:

![image](https://github.com/posit-dev/positron/assets/25965922/b3589430-0411-466f-9837-3dbc69643fba)

## Were there any error messages in the output or Developer Tools console?

No.

**Comment by juliasilge** [comment]
Thanks for this feedback; I can reproduce this problem.

**Comment by juliasilge** [comment]
Related #2023 but this is for the Viewer (not Plots)

**Comment by jmcphers** [comment]
Should be resolved in #4151:

<img width="769" alt="image" src="https://github.com/user-attachments/assets/b5f0e670-311d-41f0-a07e-622e18eff885">

**Comment by vladtarko** [comment]
Awesome!

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-107
    OS Version          : OSX

### Test scenario(s) 

mtcars |> reactable::reactable()

Link(s) to TestRail test cases run or created: 
N/A
