### ISSUE TITLE
R: Excessive highlighting of identifiers

### ISSUE THREAD

**Issue by lionel-** [posit-dev/positron#3688]
With a dark theme here is how R code looks like:

![Screenshot 2024-06-24 at 20 28 52 (1)](https://github.com/posit-dev/positron/assets/4465050/5b6e346f-a67c-4919-a1c8-5897f69f5200)

Compare this to the same theme with Rust code:

![Screenshot 2024-06-24 at 20 28 47 (1)](https://github.com/posit-dev/positron/assets/4465050/d61c4069-7aa7-43c1-802f-c5d3c92384a3)

The highlighting in the R file seems excessive because every single token is styled with a colour. I think that suggests something is off with our tm grammar?

Here is the tm info (obtained with `editor.action.inspectTMScopes`) for an R identifier:

<img width="528" alt="Screenshot 2024-06-28 at 11 23 19" src="https://github.com/posit-dev/positron/assets/4465050/846745d9-2fcb-4263-8fcd-cc0315e5e467">

And for a Rust one:

<img width="981" alt="Screenshot 2024-06-28 at 11 22 52" src="https://github.com/posit-dev/positron/assets/4465050/f13bead5-615e-4521-8a17-dccf2f2b785b">

I don't know much about these grammars but the `keyword.operator` scope stands out to me in the R case.

**Comment by ntluong95** [comment]
Yes Positron currently highlights normal identifiers as keywords, which is strange

**Comment by gvelasq** [comment]
Adding here for consideration, as mentioned [here](https://github.com/posit-dev/positron/discussions/3686#discussioncomment-9911459), since this issue tracks syntax highlighting for Positron.

It would be great if the 'classic' RStudio themes were available in Positron. A good example is RStudio's Tomorrow Night Bright, which is better suited for R code than Microsoft's VS Code extension.

**Comment by strengejacke** [comment]
I think some changes should be made to the syntax highlighting in R, to better distinguish tokens/symbols. Take this code for example:

```r
  lapply(l, function(component) {
    unlist(sapply(
      parameters,
      function(pattern) {
        grep(pattern = pattern, x = component, perl = TRUE, value = TRUE)
      },
      simplify = FALSE
    ), use.names = FALSE)
  })
```

At least I use colored brackets, else these would probably also all be in one color:

![image](https://github.com/user-attachments/assets/b55d4da4-e277-45b5-ab6a-bee1386693d7)

Here are some suggestions, actually order of importance (for me personally):

1. I think, argument _names_ should have a different color than reserved words (`FALSE`, `function`, `if`, ...).
2. Maybe `+`, `-`, `=` etc. should get a different color than the default grey that also get variables
3. Maybe function definitions / functions names where these are defined could get a separate color, not default grey.
   ![image](https://github.com/user-attachments/assets/5ac2579e-1325-41ab-9ca3-401aa2df1442)

3rd point is also not found in VSCode, but the first two points can be found in the syntax highlight of VSCode:

## Positron

![image](https://github.com/user-attachments/assets/7ca39917-0eef-48b3-bb4c-e10cd11a47c5)

## VSCode

![image](https://github.com/user-attachments/assets/e417acfd-338c-4e4f-8265-4517f3a5d0f7)

**Comment by lionel-** [comment]
Tentatively bumping this to the 2024.10 milestone as I think the R experience can be currently quite bad with certain themes.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-60
    OS Version          : OSX

### Test scenario(s) 

Confirmed that sample code in original filing has much less color highlighting now (in dark mode).

Link(s) to TestRail test cases run or created:
