### ISSUE TITLE
Variables in r notebooks (.ipynb) don't show up in the variables pane

### ISSUE THREAD

**Issue by MichelNivard** [posit-dev/positron#3689]
When I run an R chunk in a .ipynb file the variables dont show up in the variables pane, when I run the same chunk in a .qmd document the variables do show up in the variables pane, Screen shots attached,

in .ipynb:
<img width="1214" alt="image" src="https://github.com/posit-dev/positron/assets/11858442/b7852e50-3469-4248-9710-ddf532e9e076">

in .qmd:
<img width="1216" alt="image" src="https://github.com/posit-dev/positron/assets/11858442/b5400adc-7f2d-4660-be34-2c598104aefe">

Obviously this might just be desired behaviour in which case apologies for the noise.

**Comment by seeM** [comment]
Variables from notebook sessions should show in the variables pane.

If you click the dropdown currently displaying “R 4.4.1” at the top of the variables pane, and select the session named after the notebook, do your variables then show?

If so, this might be issue #2452.

**Comment by MichelNivard** [comment]
YEs same issue, closing now!
