### ISSUE TITLE
Error when trying to reformat code or a document

### ISSUE THREAD

**Issue by wasdoff** [posit-dev/positron#3690]
## Positron Version: 

Positron Version: 2024.06.1 (system setup) build 2024.06.1-27
Code - OSS Version: 1.90.0
Commit: a893e5b282612ccb2200102957ac38d3c14e5196
Date: 2024-06-26T01:33:58.809Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

## Steps to reproduce the issue:

1. Open an R script file
2. Select some R code (optional)
3. Right click -> **Format Selection** or **Format Code**

I suspect this has something to do with me using Windows 11 and the backslashes in Windows file paths, as the same error appeared in a different bug [here](https://github.com/posit-dev/positron/issues/1808#issuecomment-1920164409). 

## What did you expect to happen?
The code to be reformatted. The first time it failed as I hadn't yet installed the {`styler`} package. Thereafter (also following software/system restart) it returns the error below.

## Were there any error messages in the output or Developer Tools console?

```
Error:
! '\U' used without hex digits in character string (<input>:1:24)
```

**Comment by DavisVaughan** [comment]
Could you please provide us the contents of a minimal file that fails for you, so we can reproduce?

**Comment by wasdoff** [comment]
Of course! I should have mentioned that it actually fails on _every_ file (including empty ones).

So just to give an example, a file containing just this gives the exact same error (including the `<input>:1:24` part, the number 24 does not seem to refer to the exact file I use):

```r
some_function_with_weird_spacing <- function(x, y,
                                    z) {
  x +
  y +            z
}

```

This test file existed at the path `C:\Positron_Projects\2580\DELETE_ME.R`.

**Comment by DavisVaughan** [comment]
Ah I see what you’re saying now, that’s helpful thanks!

**Comment by jennybc** [comment]
I recognize this error and suspect it's the same as I encountered and fixed in test explorer work:

https://github.com/posit-dev/positron/pull/2194

**Comment by wasdoff** [comment]
The latest update fixed this for me!

Positron Version: 2024.06.1 (system setup) build 2024.06.1-54
Code - OSS Version: 1.90.0
Commit: 5115c73e0670f39139e55eeedf0717b468a0658d
Date: 2024-07-03T03:17:46.140Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
