### ISSUE TITLE
`..1` and friends not recognised as symbols in scope

### ISSUE THREAD

**Issue by hadley** [posit-dev/positron#3699]
## Positron Version:

Positron Version: 2024.06.0 (Universal) build 781
Code - OSS Version: 1.90.0
Commit: 40b28521f344dab6f71aaf85c121685a7109067f
Date: 2024-06-17T16:55:57.275Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.4.0
## Steps to reproduce the issue:

1. Create this function

    ```R
    f <- function(...) {
      ..1
    }```

2. `..1` is underlined with "no symbol in scope problem"

## What did you expect to happen?

It should be ok because `f()` has `...`

## Were there any error messages in the output or Developer Tools console?

No

**Comment by DavisVaughan** [comment]
Dup of https://github.com/posit-dev/positron/issues/3632
