### ISSUE TITLE
Window menu shows keyboard shortcut that doesn't work

### ISSUE THREAD

**Issue by hadley** [posit-dev/positron#3700]
## Positron Version:

Positron Version: 2024.06.0 (Universal) build 781
Code - OSS Version: 1.90.0
Commit: 40b28521f344dab6f71aaf85c121685a7109067f
Date: 2024-06-17T16:55:57.275Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.4.0

## Steps to reproduce the issue:

1. Turn on RStudio keymapping
2. Press Cmd + Shift + N - a new tab opens, not a new folder

![Screenshot 2024-06-28 at 09 49 38](https://github.com/posit-dev/positron/assets/4196/7df444b9-8d4e-4a31-b252-835540be32db)

## What did you expect to happen?

The keyboard shortcut shouldn't appear in the window menu. 

## Were there any error messages in the output or Developer Tools console?

No

**Comment by juliasilge** [comment]
Related to #3847 
Related to #2423

**Comment by juliasilge** [comment]
We have collected a number of issues that are related to this problem where the UI always shows a built-in keybinding, even when that keybinding _does not apply_ to that action. The user might end up looking at the UI and trying that keybinding, but it does something completely different. Let's use #2150 to track this problem.
