### ISSUE TITLE
Look on the PATH to discover R installations on Windows

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#3702]
Followup from https://github.com/posit-dev/positron/discussions/3677.

Positron enumerates the registry to find R on Windows, which successfully discovers R installations that were installed in the traditional way (i.e. with the R installer). However, it's common on Windows to manually install R someplace else and put it on the `$PATH`.

This corresponds to this TODO:

https://github.com/posit-dev/positron/blob/c929d52f6635bd35e6fa773e3b397fde32f53097/extensions/positron-r/src/provider.ts#L340-L341

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.08.0-5](https://github.com/posit-dev/positron-builds/releases/tag/2024.08.0-5)
OS Version(s) : Windows 11

### Test scenario(s) 



Verified on a normal user account (non-admin) with R installed in several non-standard locations. 

Before adding to PATH, no R versions discovered.  After adding to PATH, all were discovered.

Also verified with admin account. And local user PATH vs system PATH.

### Link(s) to TestRail test cases run or created:
