### ISSUE TITLE
Allow Positron to be installed without admin rights on Windows

### ISSUE THREAD

**Issue by olivroy** [posit-dev/positron#3703]
VScode is installable without admin rights. Is it possible that Positron does the same? (on June 27, it didn't)

**Comment by petetronic** [comment]
Should be possible, thanks for logging the ask!

**Comment by averyrobbins** [comment]
Any update on this? Just wondering (I know it was barely asked so no worries) because I'm getting an error when trying to install packages and I'm thinking it might be related.
![Screenshot 2024-07-01 161206](https://github.com/posit-dev/positron/assets/96895112/323ffb35-6fa3-4ecc-a614-761303557e3b)

**Comment by jennybc** [comment]
@averyrobbins I suspect your problem may be different? On my Windows VM, the library paths are:

``` r
.libPaths()
#> [1] "D:/Users/jenny/AppData/Local/R/win-library/4.3"
#> [2] "C:/Program Files/R/R-4.3.3/library"
```

<sup>Created on 2024-07-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Note that the first place a new package will be installed is in my user library. And I feel like this (including the creation of this library) is the default behaviour on Windows. So I would try to figure out why you don't have a user library. (And then, yes, it does seem like you don't have permission to write to the system library, but I suppose that is expected for you.)

**Comment by averyrobbins** [comment]
Thank you for your response, @jennybc. You were right, a different issue. I'm currently using Windows 11, where it seems like R wanted to be installed in "C:/Program Files..." I reinstalled it in "C:/Users/username..." where I have write permissions and that solved the problem. Excited to try Positron (great name btw). Thanks.

**Comment by jennybc** [comment]
I'm glad you are unstuck. For others who come by:

> ... it seems like R wanted to be installed in "C:/Program Files..."

yes, that is the usual place for R installation on Windows and will "just work" for lots of people. But it sounds like your machine is locked down in such a way that you need to depart from the default.

**Comment by juliasilge** [comment]
@petetronic can we address some of the problems raised in https://github.com/posit-dev/positron/discussions/3874 with changes to our Windows build as well?

**Comment by luispuerto** [comment]
I also second this! Specially with the daily releases you have… I don't have a problem to install it on my Mac with homebrew and usually I get updates every day or two days, but on my corporate computer I don't have admin rights and I need to ask if I want to update, which is a a little bit a pain in the…

**Comment by petetronic** [comment]
We're just testing a "user" level windows installer today and will push for download to Positron this week.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.07.0-134](https://github.com/posit-dev/positron-builds/releases/tag/2024.07.0-134)
OS Version(s) : Windows 11

### Test scenario(s) 



New user package correctly installs on a standard user (non-admin) account without needing UAC elevation.

As noted above, a package will be released this week.

### Link(s) to TestRail test cases run or created: 
n/a

**Comment by jonvanausdeln** [comment]
[2024.08.0-5](https://github.com/posit-dev/positron/releases/tag/2024.08.0-5)  is now available and contains a new "User" installer for windows that doesn't require elevation.

**Comment by olivroy** [comment]
I just tested this. I could install it, but Positron doesn't find my R installation (only Python) Is there a setting to specify the path to the R installation?

**Comment by jonvanausdeln** [comment]
@olivroy,  Can we get a little more information about your R installation? E.g. location, how it was installed.  Positron checks the registry, PATH, and a few default locations. (See #3702)

**Comment by olivroy** [comment]
My R is in C:\Program Files\R. It doesn't seem to be in the PATH (because it was installed by the IT) I have 4.3.2 I don't think I can manually edit the PATH (due to the lack of admin rights) I have 4.3.2

It is in C:\Program Files\R\R-4.3.2\bin\R.exe and C:\Program Files\R\R-4.3.2\bin\x64\R.exe.

**Comment by jonvanausdeln** [comment]
@olivroy , thank you for the information!  I think we should track this in a new issue, would you be able to open a new issue and include your setup, etc?  It would also be helpful include what you see at in the "Positron R Extension" in the "Output" tab.  
See our [wiki page](https://github.com/posit-dev/positron/wiki/Troubleshooting#python-and-r-logs) for details.

![image](https://github.com/user-attachments/assets/a319de18-678b-4b6f-86c3-6cf159193740)

**Comment by olivroy** [comment]
Actually, I have been able to fix it by manually adding my R installation to the PATH via Modify Environment Variables for your account! Appending the R PATH to the Path variable here seems to have done the trick! https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

**Comment by jennybc** [comment]
I would have expected your installation to be discovered primarily from its totally normal location:

```
C:\Program Files\R
```

so I wouldn't expect it to be necessary to put it on the PATH. (But of course I'm glad that's working, it's fresh from the oven!)

If you'd like to pursue this, open an new issue or question. I share the R discovery bits from the Positron R Extension output channel.

**Comment by juliasilge** [comment]
@b-trochimowicz can you [open a new issue or discussion](https://github.com/posit-dev/positron/issues/new/choose) outlining the problem you are observing?
