### ISSUE TITLE
Can't pick Python interpreter from "browse your file system" in command palette

### ISSUE THREAD

**Issue by liquidcarbon** [posit-dev/positron#3710]
Not everything here may be specific to Ubuntu 24.04.

**1. Can't pick interpreter from "browse your file system" in command palette**
![image](https://github.com/posit-dev/positron/assets/47034358/b77287dc-7105-485c-b54e-99eb0cd2e3df)

**2. Unable to resize with mouse, right half of window not clickable**
Same symptoms as described here https://github.com/microsoft/vscode/issues/210624 ( Wayland problem, posting for awareness )

3. No autocomplete for paths in Code or Bash cells (would work in Jupyter) 
![image](https://github.com/posit-dev/positron/assets/47034358/13528420-3a5b-4f4c-b085-d2a0b8fe28d2)

**Comment by seeM** [comment]
1 is definitely a bug, will get that fixed shortly.

I'm unable to repro 3 on macOS. @jonvanausdeln could you please double-check on Ubuntu?

**Comment by jonvanausdeln** [comment]
> 1 is definitely a bug, will get that fixed shortly.
> 
> I'm unable to repro 3 on macOS. @jonvanausdeln could you please double-check on Ubuntu?

@seeM , I need to get my Ubuntu VM setup.. so it will be a bit before I can check

**Comment by petetronic** [comment]
On 3, using Ubuntu 24.04, I can get file completions in a Python cell when starting to type in between the quotes in `open("...")`, though it's not perfect and needs some investigation... but I do not see any file completions for shell commands (though I don't see these on Mac either).

**Comment by 7yl4r** [comment]
Running [2024.07.0-21](https://github.com/posit-dev/positron/releases/tag/2024.07.0-21) on a fresh install of ubuntu 24.04 positron is freezing up whenever an interpreter is started (python or R). No errors printed in the application or in the terminal I launched it from. Happy to provide more info if you help me find relevant logfiles.

**Comment by juliasilge** [comment]
Let's use this issue only for the problem around "Python: Select Interpreter" that was addressed in #3571.

The problem with autocomplete looks very related to #4006 so let's track autocomplete problems there. (Unfortunately no one on the team can reproduce that problem yet.)

@7yl4r That doesn't quite sound like the same problem, so we would appreciate a separate bug report. We have some [advice on troubleshooting here](https://github.com/posit-dev/positron/wiki/Troubleshooting) which includes info on logs, and we'd especially be interested in the console logs (if the interpreter does in fact start) and/or the Developer Tools log. Good luck!

**Comment by jonvanausdeln** [comment]
Just tested with [2024.07.0-81](https://github.com/posit-dev/positron/releases/tag/2024.07.0-81) on both Windows 11 and MacOS 14

Trying to select Browse file system" for an interpreter (in command palette) errors out with

![image](https://github.com/user-attachments/assets/ec167017-adce-48a8-8d64-30d2194385a2)

Same error on Windows and MacOS

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.07.0-100](https://github.com/posit-dev/positron/releases/tag/2024.07.0-100)
OS Version(s) : windows 11, MacOS 14

### Test scenario(s) 



I was able to select several different interpreters in different paths.

### Link(s) to TestRail test cases run or created:
