### ISSUE TITLE
Clicking on Links below Help returns 404

### ISSUE THREAD

**Issue by howardbaek** [posit-dev/positron#3712]
## Positron Version:

[2024.06.1-27](https://github.com/posit-dev/positron/releases/tag/2024.06.1-27)

## Steps to reproduce the issue:

1. Open Positron 
2. On the Welcome page, click on "Positron Documentation", "Positron Community", "Report a bug", seen below:

![Screenshot 2024-06-28 at 10 15 53 AM](https://github.com/posit-dev/positron/assets/50791792/df1bbedd-1002-4a71-9b4d-ddb057bd2b30)

## What did you expect to happen?

I was expecting to be taken to a working website. However, I see "Page not found". 

![Screenshot 2024-06-28 at 10 10 46 AM](https://github.com/posit-dev/positron/assets/50791792/f5dda632-1b49-4fbd-9543-3e8543b2df66)

**Comment by howardbaek** [comment]
Perhaps this PR fixes this issue? https://github.com/posit-dev/positron/pull/3708

**Comment by cpfiffer** [comment]
Yep, #3708 should fix this.
