### ISSUE TITLE
Progress bar does not update, instead append at the end

### ISSUE THREAD

**Issue by dkgaraujo** [posit-dev/positron#3723]
## Positron Version:
Positron Version: 2024.06.1 (Universal) build 27
Code - OSS Version: 1.90.0
Commit: a893e5b282612ccb2200102957ac38d3c14e5196
Date: 2024-06-26T02:08:06.673Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin x64 23.5.0
## Steps to reproduce the issue:

1. Create new notebook
2. in a python cell, pip install a package with `!pip install package`

## What did you expect to happen?

the progress bar should update automatically, and not have a new version show up below the current one with every status update (see fig)

<img width="638" alt="Screenshot 2024-06-28 at 23 05 36" src="https://github.com/posit-dev/positron/assets/16483074/b8ee7843-b239-4e65-becb-24932059cebf">

## Were there any error messages in the output or Developer Tools console?

No

**Comment by petetronic** [comment]
Thank you for reporting this, I was able to reproduce the issue. 
Note that the Console does not have this issue and correctly redraws the same line as the progress bar updates.

**Comment by seeM** [comment]
It works as expected in VSCode notebooks, so it's not an issue with the output views. I suspect it's in our notebook controllers.

**Comment by midleman** [comment]
### Verified Fixed
Positron Version(s) : [2024.11.0-49](https://github.com/posit-dev/positron-builds/releases/tag/2024.11.0-49)
OS Version(s) : MacOS

### Test scenario(s) 

Confirmed progress bar displays as expected in notebook.
![Image](https://github.com/user-attachments/assets/4a9fe590-246e-45cc-8393-17e005cd8689)


### Link(s) to TestRail test cases run or created:
