### ISSUE TITLE
Kernal Restart

### ISSUE THREAD

**Issue by michaelbschulte21** [posit-dev/positron#3726]
Type: <b>Feature Request</b>

I cannot find the kernal restart button. It's easy to find in JupyterLab. Now, I can't kill my code.

VS Code version: Positron 1.90.0 (a893e5b282612ccb2200102957ac38d3c14e5196, 2024-06-26T01:33:58.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by DavisVaughan** [comment]
It's the little highlighted button in the top right there

<img width="747" alt="Screenshot 2024-06-28 at 6 29 18 PM" src="https://github.com/posit-dev/positron/assets/19150088/2d942c77-4da6-4db4-9c4b-fd75ae89bdf9">

Also accessible in the interpreter drop down
<img width="462" alt="Screenshot 2024-06-28 at 6 29 56 PM" src="https://github.com/posit-dev/positron/assets/19150088/dc491b39-9ea1-4b9c-a099-28ab8ef2a091">
