### ISSUE TITLE
Considering adding RStudio's package management UI and addin etc.

### ISSUE THREAD

**Issue by trafficfan** [posit-dev/positron#3729]
It would be a good idea to consider adding RStudio's package management UI and addin etc. To python it might be not important, but for R it would be nessary to stay updated with developing packages

**Comment by ntluong95** [comment]
It is indeed very important. And also, a package management pane for Python is also helpful :)

**Comment by petetronic** [comment]
Thank you for logging an enhancement request! We've been discussing this as a possibility for both Python and R language packs in https://github.com/posit-dev/positron/issues/1391. It's helpful to hear from users what is important to them, as well as the upvotes, in prioritization discussions.

**Comment by juliasilge** [comment]
We're closing this in lieu of #1391, where we are addressing both installed and loaded packages.
