### ISSUE TITLE
Connect Remote R Session over SSH

### ISSUE THREAD

**Issue by jfsalzmann** [posit-dev/positron#3745]
I'm not sure whether #2307 addresses this, but I'd love to see a feature that lets me have a remote R session the same way as I would use the local R version in any context (execute one line in the editor, write a line in the console, view/inspect current variables/environments). 

That is, a feature that lets me add an (or multiple) R version(s) on a remote machine through a SSH-tunneled connection, and then allows me to access/use it the same way and in every place where I can usually switch between local R versions.

I once read about VS Code having this sort of feature for some programming language (Python?) in a blog post, and love the idea since. I was disappointed to learn that RStudio only offers this functionality in their paid pro version.

For me, being able to quickly switch to a more powerful cloud-hosted version of R just by changing a dropdown menu would be a dream. I never felt RStudioServer was what I was looking for in terms of workflow, as it essentially forced my to use a different (& buggy) browser-based IDE for all remote scripts.

**Comment by jthomasmock** [comment]
We are planning to support a Remote SSH experience in the future, for desktop to server workflows. 👍

#2307 is a good place to track for now

**Comment by juliasilge** [comment]
Let's track in #2307 👍
