### ISSUE TITLE
Overlapping status / activity bar when installing local packages.

### ISSUE THREAD

**Issue by strengejacke** [posit-dev/positron#3748]
I used the command to install a local package:

![image](https://github.com/posit-dev/positron/assets/26301769/a87a7330-9f07-4a36-8345-07b4cfdc0038)

During package installation, the terminal view is shown, but the "activity bar" is overlapping other symbols. This is no serious issue, just wanted to point out:

![image](https://github.com/posit-dev/positron/assets/26301769/218a6c5a-f5da-4616-886c-6effad00861b)

**Comment by juliasilge** [comment]
You are on Windows, it looks like? I am not able to reproduce this problem on a Mac.

**Comment by strengejacke** [comment]
Yes, windows 11.

**Comment by strengejacke** [comment]
Not sure if the pane layout is important for this issue, but here's my layout:
![image](https://github.com/posit-dev/positron/assets/26301769/69225323-8e1a-4182-b984-fd5787dd662d)

**Comment by juliasilge** [comment]
Thank you! We'll see how to track this down. 👍

**Comment by juliasilge** [comment]
I believe this is the same as #2431. Can you add any additional detail there?
