### ISSUE TITLE
Add debounce to prevent flickering of console execution indicators

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#3752]
Currently, both the activity item execution indicator (left of an item in the console history) and the interrupt button flicker, even for code that runs nearly instantly.

We've [used 250ms for the data explorer](https://github.com/posit-dev/positron/pull/3245), so maybe we can do the same here?

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.07.0-85](https://github.com/posit-dev/positron/releases/tag/2024.07.0-85)
OS Version(s) : windows 11

### Test scenario(s) 



Didn't see any flickering.

### Link(s) to TestRail test cases run or created:
