### ISSUE TITLE
Support schema / data update events for polars variable changes, and invalidate filters and sort keys when needed

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#3761]
Part of epic #2185. Providing for feature parity with pandas for polars

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.07.0-17](https://github.com/posit-dev/positron/releases/tag/2024.07.0-17)
OS Version(s) : Windows, MacOS, Ubuntu 22 (from CI)

### Test scenario(s) 

DataFrames from polars work as expected, including sorting and filtering.

### Link(s) to TestRail test cases run or created: 

Test Run in Smoke CI
