### ISSUE TITLE
Support for multiple R versions installed using RSwitch

### ISSUE THREAD

**Issue by dvanic** [posit-dev/positron#3763]
Hi! I'd love to add an issue to ask for support with using multiple R versions on a mac through RSwitch! Thanks in advance!

**Comment by juliasilge** [comment]
Since [RSwitch is archived](https://github.com/hrbrmstr/RSwitch), we are focusing on supporting multiple R versions through [rig](https://github.com/r-lib/rig). Using rig works great in Positron and we would love to hear about any problems you run into while using it! 🙌

**Comment by dvanic** [comment]
Thank you! Will give it a go! (For RStudio as well as Positron)
