### ISSUE TITLE
Positron R console behaviour when scrolling through history with large/long entries

### ISSUE THREAD

**Issue by strengejacke** [posit-dev/positron#3764]
## Positron Version:

Positron Version: 2024.06.1 (system setup) build 2024.06.1-27
Code - OSS Version: 1.90.0
Commit: a893e5b282612ccb2200102957ac38d3c14e5196
Date: 2024-06-26T01:33:58.809Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

## Steps to reproduce the issue:

1. I ran the code to create an example for https://github.com/posit-dev/positron/issues/3698
2. Then, scroll back and forth through the history in the R console (up/down arrows). For larger entries, which cannot be fully displayed in the screen, the cursor remains (invisibly) in the top of the entry, and you have to use arrow-down to get the cursor into the correct position again.

See video, in particular from second ~22 onwards.

## What did you expect to happen?

I can _always_ see the cursor and the prompt line, resp. the cursor-focus is always in the prompt line or at the *end* of the current code, at least when I use arrow up/down to scroll through entries (like in RStudio terminal).

## Were there any error messages in the output or Developer Tools console?

No.

https://github.com/posit-dev/positron/assets/26301769/6712284b-9fbd-45cb-9322-883a22d77ce7

**Comment by strengejacke** [comment]
This is how RStudio behave (expected behaviour):

https://github.com/posit-dev/positron/assets/26301769/0804b9a8-2b95-4ae0-9d25-2efd7515f01d

If I see right, the issue seems to be that if you use arrow up/down, RStudio puts the cursor _at the end of the full command._ Positron, however, puts the cursor _after the opening parenthesis._

See:
![image](https://github.com/posit-dev/positron/assets/26301769/e28ffbb5-b5c3-497c-bb6f-1fc6b81c9fe3)

This means for longer code blocks, the cursor is at the beginning of that block, and if you use arrow-down, you have to go through the complete code block line-by-line, until you reach the prompt.

**Comment by juliasilge** [comment]
It looks to me like this is the same as #2430. What do you think @strengejacke?

**Comment by strengejacke** [comment]
Yes, looks like a duplicate. thanks!
