### ISSUE TITLE
Feature Request: Open Data with Cmd/Ctrl + Left Click

### ISSUE THREAD

**Issue by truenomad** [posit-dev/positron#3768]
I would like to request a feature where users can open data by using Cmd/Ctrl + Left mouse click, similar to how it works in RStudio. This would greatly enhance the user experience by providing quick access to data in a familiar manner.

```
# Press Cmd/Ctrl + Left mous click
iris 
```

**Comment by juliasilge** [comment]
Can you share where exactly you are clicking? Perhaps with a screenshot of RStudio? I am not quite sure what kind of interaction this is, and apparently have never used this myself! 🙈

**Comment by jmcphers** [comment]
I think this is the work tracked in https://github.com/posit-dev/positron/issues/2974. @truenomad does that cover what you're describing here?

**Comment by truenomad** [comment]
Hi there!

@jmcphers @juliasilge this exactly what I meant. Sorry I didn't see this post. A feature I always use, this makes accessing recently made data very easy!
