### ISSUE TITLE
Data Explorer tab order is wrong when columns are on the right

### ISSUE THREAD

**Issue by softwarenerd** [posit-dev/positron#3778]
## Steps to reproduce the issue:

1. Put columns on right in Data Explorer.
2. Note that the tab order is wrong when tabbing through Data Explorer.

## What did you expect to happen?

I expected tabbing through Data Explorer to be aware that columns were on the right.

**Comment by softwarenerd** [comment]
This issue is addressed in https://github.com/posit-dev/positron/pull/4681.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-55
    OS Version          : OSX

### Test scenario(s) 

Tab order honors layout

Link(s) to TestRail test cases run or created:
