### ISSUE TITLE
`rstudioapi::viewer()` generates an error

### ISSUE THREAD

**Issue by Nenuial** [posit-dev/positron#3784]
## Positron Version:

Positron Version: 2024.06.1 (Universal) build 27
Code - OSS Version: 1.90.0
Commit: a893e5b282612ccb2200102957ac38d3c14e5196
Date: 2024-06-26T02:08:06.673Z (5 days ago)
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

## Steps to reproduce the issue:

1. Make a quarto document (for example test.qmd)
2. Use the following content :
````
```{r}
library(tinytable)

mtcars |>
  tt()
```
````
4. Click on *Run cell*

## What did you expect to happen?
The *mtcars* table rendered in the Viewer pane.

## Were there any error messages in the output or Developer Tools console?

Yes:
```
Error:
! Function viewer not found in RStudio
Hide Traceback
    ▆
 1. ├─methods (local) `<stndrdGn>`(`<tinytabl[,11]>`)
 2. └─tinytable (local) `<stndrdGn>`(`<tinytabl[,11]>`)
 3.   └─tinytable:::print.tinytable(...)
 4.     └─rstudioapi::viewer(htmlFile)
 5.       └─rstudioapi::callFun("viewer", url, height = height)
```

**Comment by jmcphers** [comment]
Thanks for reporting! This is tracked in #3716.
