### ISSUE TITLE
Use `@vscode/windows-registry`

### ISSUE THREAD

**Issue by jennybc** [posit-dev/positron#3787]
Two areas where there are opportunities for better R installation discovery on Windows if we give more attention to the registry:

1. Try harder to use [`@vscode/windows-registry`](https://github.com/microsoft/vscode-windows-registry) instead of [`winreg`](https://www.npmjs.com/package/winreg).

    I actually did this in #2410, but in CI we saw release builds falling over due to some unhappiness in webpack and we reverted the PR. The `winreg` npm module wraps the `reg` CLI, whereas `@vscode/windows-registry` uses N-API, which I take to mean that it uses native Windows APIs. Also, `@vscode/windows-registry` exists explicitly to support VS Code. Both of those suggest it may be a better fit for our purposes.

    We have evidence in https://github.com/posit-dev/positron/discussions/3677 that there are users whose group policy is so restrictive that it can be hard to even read from the registry. These users report that other software *can* read from the registry. This includes RStudio, which also switched to using native Windows APIs (https://github.com/rstudio/rstudio/pull/12898).

2. Discover R installations from the registry, i.e. not _just_ the current default version. I opened #4820 for this.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.09.0-95](https://github.com/posit-dev/positron-builds/releases/tag/2024.09.0-95)
OS Version(s) : Windows 11

### Test scenario(s) 



Successfully scanned registry for R:
```
2024-09-26 08:48:00.758 [info] Checking for 'InstallPath' in registry key HKEY_LOCAL_MACHINE\SOFTWARE\R-core\R64
2024-09-26 08:48:00.758 [info] Identified the current version of R from the registry: C:\Program Files\R\R-4.4.1\bin\x64\R.exe
```
### Link(s) to TestRail test cases run or created:
