### ISSUE TITLE
Differentiate methods/functions or fields in autocompletion for R6 class.

### ISSUE THREAD

**Issue by Fred-Wu** [posit-dev/positron#3793]
[mlr3](https://github.com/mlr-org/mlr3) is implemented with R6 class. However, after creating a task, all autocompletes appear to be variables 
![image](https://github.com/posit-dev/positron/assets/4111978/735f32bb-3a4e-44e0-a155-f5a5eae0593b). Some of them actually should be methods, such as `data` in the screenshot below.

![image](https://github.com/posit-dev/positron/assets/4111978/f3502e84-b849-4cab-ac77-b62d6e33b3d3)

**Comment by juliasilge** [comment]
I believe this is the same as #2936. Could you take a look and add any additional detail there?

**Comment by juliasilge** [comment]
Thanks for chiming in on #2936 @Fred-Wu! We'll track this over there.
