### ISSUE TITLE
To open a Python Virtual environment in Positron IDE

### ISSUE THREAD

**Issue by dmresearch15** [posit-dev/positron#3794]

**Comment by dmresearch15** [comment]
How can I open a Python virtual environment in Positron IDE?

**Comment by seeM** [comment]
Press Cmd+Shift+P (or Ctrl+Shift+P) to open the command palette, then choose the "Python: Select Interpreter" command, and select your virtual environment from the list.

If you don't see the environment you're looking for, choose the "Enter interpreter path..." option and choose it manually.

**Comment by juliasilge** [comment]
Also take a look at this documentation: <https://github.com/posit-dev/positron/wiki/Interpreter-Selection>

**Comment by juliasilge** [comment]
Let us know if you have further questions on using Python virtual environments in Positron!
