### ISSUE TITLE
Less "alerting" color for colored output in the console that are not warnings

### ISSUE THREAD

**Issue by strengejacke** [posit-dev/positron#3797]
On Windows 11, using the default dark theme, some output in the console is in red color. However, warnings are also in red color. Thus, "normal" output can be confused with warnings.

Maybe the console should have distinct colors for these two types of output?

### Normal output, should maybe get different color than warnings

![image](https://github.com/posit-dev/positron/assets/26301769/6ab7ffbd-f2a3-407c-9c5b-47a92029cbb1)

### Warnings ok

![image](https://github.com/posit-dev/positron/assets/26301769/ea804de8-be71-43ec-aea8-28e332109fe0)

**Comment by DavisVaughan** [comment]
The messages you get from install.packages() there require changes to upstream R that we have tracked elsewhere and will eventually do. There isn't much we can do about them right now
