### ISSUE TITLE
Console throws error on copy/paste in source editor when `formatOnPaste` is true

### ISSUE THREAD

**Issue by strengejacke** [posit-dev/positron#3798]
## Positron Version:

Positron Version: 2024.06.1 (system setup) build 2024.06.1-27
Code - OSS Version: 1.90.0
Commit: a893e5b282612ccb2200102957ac38d3c14e5196
Date: 2024-06-26T01:33:58.809Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

## Steps to reproduce the issue:

I start Positron, copy some code in the script and paste it elsewhere in the script. Then, although the console is not involved, it throws an error.

1. Open Positron, possibly you have some scripts that are restored on startup
2. Copy code from the script and paste it somewhere else in the script.

https://github.com/posit-dev/positron/assets/26301769/e0df03c9-67c4-4449-b00c-de4279765113

## What did you expect to happen?

No error message in the console when I work in the script and don't run any commands.

## Were there any error messages in the output or Developer Tools console?

No.

**Comment by strengejacke** [comment]
Ok, I possibly found the reason:

This error only occurs when I add the setting `"editor.formatOnPaste": true`. When I remove this line from the settings.json, everything works fine.

**Comment by juliasilge** [comment]
I haven't found an example that can reproduce this problem for me locally, even when I set "editor.formatOnPaste": true. Do you see this every time you copy/paste in a source editor? Or is it only specific code that you paste that causes the problem?

**Comment by strengejacke** [comment]
Indeed, I think it can be narrowed down further. When the file is saved on disk, it happens. For a new file that is not saved, nothing happens. Can you reproduce this?

**Comment by juliasilge** [comment]
To clarify, are you saying that if you have:

- `"editor.formatOnPaste": true`
- a file saved to disk, like `scratch.R`
- very simple code in the file, like `1 + 1`

Then you see errors in the console when you copy/paste `1 + 1` in the `scratch.R` file?

**Comment by strengejacke** [comment]
I cannot reproduce this behaviour any longer with the latest Positron release...

```
Positron Version: 2024.06.1 (system setup) build 2024.06.1-54
Code - OSS Version: 1.90.0
Commit: 5115c73e0670f39139e55eeedf0717b468a0658d
Date: 2024-07-03T03:17:46.140Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by juliasilge** [comment]
Let us know if you run into it again!
