### ISSUE TITLE
Notebook interrupt button can be unresponsive

### ISSUE THREAD

**Issue by ntluong95** [posit-dev/positron#3805]
## Positron Version:
Positron Version: 2024.06.1 (system setup) build 2024.06.1-27
Code - OSS Version: 1.90.0
Commit: a893e5b282612ccb2200102957ac38d3c14e5196
Date: 2024-06-26T01:33:58.809Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621
## Steps to reproduce the issue:

1. Open a Jupyter Notebook
2. Run a random cell

To be honest, I don't know how to reproduce the problem. It works fine for me before but not now
## What did you expect to happen?
The cell run

## Were there any error messages in the output or Developer Tools console?
The cell didn't run. As can be seen from the screenshot, it took 11 minutes and not yet finished package loading
![image](https://github.com/posit-dev/positron/assets/63569637/abd70ae4-6b0b-4463-a4d3-19840d271cb3)

**Comment by juliasilge** [comment]
If this happens in a reproducible way for you (or even if something seems to make it happen more often), please do share that with us!

**Comment by seeM** [comment]
One possible issue I can see from the code is that we aren't listening to and handling `session.onDidEndSession` in the `NotebookSessionService` for potential errors _after_ startup.

**Comment by petetronic** [comment]
Something like this may also be behind https://github.com/posit-dev/positron/issues/3919?

**Comment by seeM** [comment]
@petetronic yes that sounds very possible.

**Comment by midleman** [comment]
### Verified Fixed
Positron Version(s) : [2025.01.0-32](https://github.com/posit-dev/positron-builds/releases/tag/2025.01.0-32)
OS Version(s) : MacOS

### Test scenario(s) 

Confirmed that basic running and interrupting cells in the notebook works as expected. The real test of this fix will be whether it reduces the flakiness of our automated `notebook-create` tests. We’ve occasionally encountered issues where a simple cell execution hangs in CI, and hopefully this change fixes that.

### Link(s) to TestRail test cases run or created: 

n/a
