### ISSUE TITLE
NA's shouldn't be quoted when formatted for the variables pane

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#3810]
## Positron Version:

Positron Version: 2024.06.1 (Universal) build 10
Code - OSS Version: 1.90.0
Commit: 2ee647c28f932ea3032d6275664c6a8494baacb4
Date: 2024-06-24T03:50:10.276Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

## Steps to reproduce the issue:

1. Create a `data.frame` with eg:
    ```r
    x <- data.frame(x = as.POSIXlt(c(NA, "2018-01-01")), y = c(NA_real_, 1), z = c(NA, "string"))
    ```
3. Expand `x` in the variables pane.

![image](https://github.com/posit-dev/positron/assets/4706822/fd64b6f6-a447-4615-a9ea-3a9a0bbb576c)

## What did you expect to happen?

The missing values shouldn't be quoted for the columns `x` and `z` as they are explicit missing values.
Here's the output in RStudio:

![image](https://github.com/posit-dev/positron/assets/4706822/70b3fb6a-d99e-4b99-a213-df1ec2657ba2)

## Were there any error messages in the output or Developer Tools console?

NA

**Comment by juliasilge** [comment]
Related to #2860 in some ways

**Comment by petetronic** [comment]
Confirmed NA no longer quoted on Windows and Mac with Positron 2024.07.0-81
