### ISSUE TITLE
Copy-pasting a sparse subset of rows or columns from data explorer pastes them in the order they were selected

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#3819]
## Positron Version:

main as of 2024-07-02

## Steps to reproduce the issue:

1. Use ctrl/cmd-click to select a subset of columns or rows, but select them not in sequential order
2. Copy with ctrl/cmd-C, and paste into a spreadsheet of your choice. The data will be in the selection order, not in the visible order in the data grid

![image](https://github.com/posit-dev/positron/assets/329591/2b4c2015-1339-4f94-9931-d7be7757acc0)

![image](https://github.com/posit-dev/positron/assets/329591/7b4d28bd-3600-4f76-a59b-1aee3342982b)

## What did you expect to happen?

For the copy-paste selection to follow the visible order in the grid. We just need to sort the selected indices in the UI code before sending the request to the backend

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-15
    OS Version          : OS X

### Test scenario(s) 

Validated with polars and pandas data frames by selecting right to left, bottom to top and ensuring data is copied correctly.

Link(s) to TestRail test cases run or created: 
N/A
