### ISSUE TITLE
OUTLINE: No symbols found in document

### ISSUE THREAD

**Issue by chuxinyuan** [posit-dev/positron#3824]
## Positron Version:

Positron Version: 2024.06.1 build 27
Code - OSS Version: 1.90.0
Commit: a893e5b282612ccb2200102957ac38d3c14e5196
Date: 2024-06-26T01:22:29.024Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.6.34-1-MANJARO

## Steps to reproduce the issue:

1. Install the quarto extension
2. Create a `.qmd` document and enter the following information:

````markdown

# intro {#intro}

## Second level title

### third level title

````

![截图 2024-07-03 07-50-24](https://github.com/posit-dev/positron/assets/26940042/d78402c1-0f07-4aee-82b0-87c85af7b28d)

**Comment by GitHunter0** [comment]
In .py files, the outline pane is empty too.

Also, sections in .R files like below are not appearing in the outline:
```
# Section 1 -------
## Subsection 1.1 -------
```

```
Windows 10 pro
Positron 2024-06.1-27
```

**Comment by isabelizimm** [comment]
Hmmm... I am able to see outlines in `.py` files and `.qmd` files. Are you able to check in Settings (`cmd/ctrl + ,`) -> Outline to make sure the outline capabilities you'd prefer are turned on? 

For Python files, the outline will populate when you create variables/classes, not necessarily at headings. I don't believe those sections are shown in `.py` files, but they are shown in `.ipynb` files. One alternative would be to use `MARK` comments in `.py` files to have sections show on a minimap, shown on the right hand side in the screenshot. 

<img width="732" alt="Screenshot 2024-07-03 at 1 34 58 PM" src="https://github.com/posit-dev/positron/assets/54685329/4dfc2ee4-800c-409b-9982-b4a3aff06e92">

Do note that the Outline tab will only populate once you have started an interpreter, so if you do not have a Python/R runtime active, it will be empty.

**Comment by juliasilge** [comment]
> Also, sections in .R files like below are not appearing in the outline:

This is tracked in #3822 if you have more context to add there @GitHunter0.

For Quarto, we do have the outline as expected:

![outline](https://github.com/posit-dev/positron/assets/12505835/da3fd074-1287-4360-8cf9-da590e4dea38)

@chuxinyuan are you sure that is a Quarto file? It should have a little Quarto icon like this with the filename if Positron knows it is Quarto:

![Screenshot 2024-07-03 at 11 56 22 AM](https://github.com/posit-dev/positron/assets/12505835/c41ddab6-f45c-4e23-bd63-2514d8d5d8bb)

**Comment by chuxinyuan** [comment]
@juliasilge Oh, better this time.

![截图 2024-07-04 06-23-57](https://github.com/posit-dev/positron/assets/26940042/127ef63c-5c87-4a7c-9d09-c0329258fc24)

**Comment by chuxinyuan** [comment]
> Hmmm... I am able to see outlines in `.py` files and `.qmd` files. Are you able to check in Settings (`cmd/ctrl + ,`) -> Outline to make sure the outline capabilities you'd prefer are turned on?

Yes, outline capabilities is turned on by default.

**Comment by juliasilge** [comment]
I see that the outline works in untitled, unsaved Quarto files as well FYI:

![untitled-quarto](https://github.com/posit-dev/positron/assets/12505835/b460ab21-4b1a-41b1-8f26-064ae301c2b1)

@chuxinyuan do you happen to be a VS Code user as well? If so, would you open up this workspace in VS Code with the Quarto extension installed and see if you see the outline there? This could help us discover if this is a Positron-specific problem or a problem with the Quarto VS Code extension.

If you don't already use VS Code, we'll see if we can come up with a different way to debug.

**Comment by chuxinyuan** [comment]
@juliasilge Because when I installed Code OSS, the system told me that Code OSS and Positron conflicted, I had to uninstall Positron and reinstall it. After Code OSS is installed, the outline will not work properly.

![test2](https://github.com/posit-dev/positron/assets/26940042/b42c86e4-c908-4dd5-ad91-c600509b5d15)

By the way, the OUTLINE of the `.md` file in Positron and Code OSS is normal.

**Comment by GitHunter0** [comment]
Thank you, @juliasilge and @isabelizimm .

Now I got it, @isabelizimm ,  but in **.py files** I was hoping to get in the **Outline pane** a **TOC** like `Spyder IDE` provides, which is highly helpful.  It implements a hierarchical section system as below:

```
#%% Section
#%%% Subsection
#%%%% Subsubsection
````

**Comment by chuxinyuan** [comment]
@juliasilge @isabelizimm I just tried it again in Visual Studio Code and the problem still persists. I think it's a genetic disease from upstream.

![Uploading test.png…]()

**Comment by seeM** [comment]
@GitHunter0 I've created a new issue to track this enhancement request: https://github.com/posit-dev/positron/issues/3886 😄

**Comment by juliasilge** [comment]
We've got issues open for outline improvements for R (#3822) and code cells (#3886).

For the problem in Quarto that we can't quite produce, I would suggest opening an issue on the [repo for the Quarto VS Code extension](https://github.com/quarto-dev/quarto/issues). I hope we can get that fixed!
