### ISSUE TITLE
Improve discovery/usability of Data Explorer when working with dataframes

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#3825]
Currently the Data Explorer can be invoked by:
- clicking on the grid icon in the Variables pane
-  via `View(df)` in R or `%view df` in Python.

It would be nice to also have a breadcrumb or indicator in the console when printing dataframes as a indicator they can open the data in the Data Explorer.

**Comment by juliasilge** [comment]
I just got feedback that the grid icon does not look clickable at all.
