### ISSUE TITLE
Error in variables panel stucks console

### ISSUE THREAD

**Issue by jospueyo** [posit-dev/positron#3833]
## Positron Version:

Positron Version: 2024.06.1 (system setup) build 2024.06.1-54
Code - OSS Version: 1.90.0
Commit: 5115c73e0670f39139e55eeedf0717b468a0658d
Date: 2024-07-03T03:17:46.140Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

## Steps to reproduce the issue:

1. Create an sf object with 1e6 rows.
2. Try to expand it in the column viewer

## What did you expect to happen?

It shows an error, which is not ideal but it's ok. However, then console gets stucked which is not expected.

## Were there any error messages in the output or Developer Tools console?

![imagen](https://github.com/posit-dev/positron/assets/56930644/28c33d65-2418-414d-9460-8f70f785f279)

**Comment by lionel-** [comment]
Related (perhaps a duplicate) to https://github.com/posit-dev/positron/issues/1419

**Comment by jmcphers** [comment]
This is issue https://github.com/posit-dev/positron/issues/3628. Thanks for reporting, @jospueyo!
