### ISSUE TITLE
Data Explorer: UI affordance to pull Data Explorer into separate window

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#3839]
Data explorer windows can already be manually "torn" off to allow it more room, but we may want to provide a UI element to quickly move it out of the main IDE space. Especially when heavily zoomed in, the Data Explorer doesn't have enough room to view much data.

> [!NOTE]  
> The screenshot below shows the Data Explorer torn out of the main editor space into it's own window.

![image](https://github.com/posit-dev/positron/assets/29187501/18bf8059-1570-4d05-8dd8-63ebe131a592)

**Comment by jthomasmock** [comment]
Perhaps a simple open in new window icon on the far right of the Data Explorer toolbar:
![image](https://github.com/posit-dev/positron/assets/29187501/92ea113b-f897-41f2-a3b0-4bad2263f49e)

**Comment by wesm** [comment]
+1 for having a pop-out icon to click

**Comment by softwarenerd** [comment]
This is addressed in: https://github.com/posit-dev/positron/pull/4810.
