### ISSUE TITLE
Expand all connections

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#3840]
We should add a command to the Connections Pane that expands all connnections nodes in the pane.
This will make smoke testing easier as we don't need to 'click' on each node, which is essentially only testing the TreeView API

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-15
    OS Version          : OS X

### Test scenario(s) 

Tested manually and via smoke tests

Link(s) to TestRail test cases run or created:
