### ISSUE TITLE
Leaking internal commands from the connections pane

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#3841]
The connections pane registers commands that are used in the context menus for individual items, such as 'Preview table'. But these commands are appearing in command pallets, even though they can't be used without their contexts.

![image](https://github.com/posit-dev/positron/assets/4706822/ff5e5a5e-6628-44b9-beb5-c5432de5589e)

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.07.0-15](https://github.com/posit-dev/positron/releases/tag/2024.07.0-15)
OS Version(s) : Windows 11, MacOS 14

### Test scenario(s) 

The "connections" commands in the palette now show only those that can be used without context.

### Link(s) to TestRail test cases run or created: 
none
