### ISSUE TITLE
When creating a PR from the GitHub Pullrequest extension, color code is shown in commit message

### ISSUE THREAD

**Issue by strengejacke** [posit-dev/positron#3843]
When I use the GitHub pull request extension (https://open-vsx.org/extension/GitHub/vscode-pull-request-github) to create a PR from an issue, an automated commit message is created, including `Fix #<issue number>`. Since there is a `#` followed by a number, this is erroneously considered as color code and rendered as such in the commit message.

![image](https://github.com/posit-dev/positron/assets/26301769/1070a8b4-9719-4c46-9e5e-06431f5ea4df)

Expected behaviour: no rendering of the color code in the commit message.

Setup:
Positron Version: 2024.06.1 (system setup) build 2024.06.1-54
Code - OSS Version: 1.90.0
Commit: 5115c73e0670f39139e55eeedf0717b468a0658d
Date: 2024-07-03T03:17:46.140Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by jennybc** [comment]
Yes, we are already tracking this in #2315.

**Comment by strengejacke** [comment]
Great, thanks!
