### ISSUE TITLE
Smoke Tests: Install R prerequisites automatically as needed 

### ISSUE THREAD

**Issue by jonvanausdeln** [posit-dev/positron#3844]
Several smoke tests require certain Python packages. Currently they are installed in CI as part of the GitHub workflow. Locally, however, we need to do it manually whenever a new package is needed. The needed packages are listed in the README associated to the given project in the [qa-example-content repository](https://github.com/posit-dev/qa-example-content).

It would be good to:

* Keep the Github workflow as-is. This allows the install to take place 1 time at the beginning of the run. If we find a better way inside the  test that still only has to run once, then we could remove the install in the workflow
* Locally have a way to automatically install needed packages. Most likely through some type of requirements file.
* perhaps as part of the launch.json file in VSCode?
* Someway so the person running tests doesn't have to manually find what has changed and install it in the given environment.

**Comment by jennybc** [comment]
If you record the R dependencies in DESCRIPTION, as we discussed in Slack, for local development, I use `pak::local_install_dev_deps()`.

https://pak.r-lib.org/reference/local_install_dev_deps.html

**Comment by jennybc** [comment]
Here's an example of a folder (for a Quarto book) that uses DESCRIPTION in this pragmatic way:

https://github.com/hadley/r-pkgs/blob/main/DESCRIPTION

When working locally, the user does `pak::local_install_dev_deps()` periodically.

In CI, the [`r-lib/actions/setup-r-dependencies@v2`](https://github.com/hadley/r-pkgs/blob/b0a00706ebd3b70c04211f66226daf3ccc0565ec/.github/workflows/render.yaml#L47) GitHub Action sorts it all out.

**Comment by jonvanausdeln** [comment]
DESCRIPTION file added to [QA Content Examples](https://github.com/posit-dev/qa-example-content) repo.  Smoke test README and Github action both updated to use the DESCRIPTION file.
