### ISSUE TITLE
the plots in R notebook are not showing iline

### ISSUE THREAD

**Issue by mgorjis** [posit-dev/positron#3846]
## Steps to reproduce the issue:

1. Open jupyter notebook inside positron
2. Run simple R codes to plot

## What did you expect to happen?

I expected that the graphs are showing in the notebook, but instead it is showing in the "SESSION" panel

## Were there any error messages in the output or Developer Tools console?

No

![image](https://github.com/posit-dev/positron/assets/11069763/803c6bd7-e001-4fca-ad7b-aa08feee5fbe)

**Comment by juliasilge** [comment]
Thank you for this bug report! I can reproduce this problem. I see that:

- plots in a Python notebook render in the notebook 👍 
- plots in an R notebook render in the Plots pane 👎

**Comment by seeM** [comment]
Note: we currently special case on the "session mode" passed as a command line arg to the kernel to handle this in the Python kernel.

**Comment by juliasilge** [comment]
Reported again here: https://github.com/posit-dev/positron/discussions/3718#discussioncomment-10091191

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-97
    OS Version          : OSX

### Test scenario(s) 

Verified with code in screenshot of original filing.

Link(s) to TestRail test cases run or created: 
N/A
