### ISSUE TITLE
ctrl+shift+c opens terminal in ubuntu

### ISSUE THREAD

**Issue by oranwutang** [posit-dev/positron#3847]
## Positron Version:
Positron Version: 2024.06.1 build 54
Code - OSS Version: 1.90.0
Commit: 5115c73e0670f39139e55eeedf0717b468a0658d
Date: 2024-07-03T03:04:49.029Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.5.0-41-generic

Hi! 

I'm using positron on Ubuntu 22.04.4 LTS x86_64 and while trying to comment a line in code editor using the shortcut (ctrl+shift+c), what I get is a terminal window opened and the line is not commented.

FWIW, pressing ctrl+shift+c in VSCode has the same behaviour, in VSCode the shortcut for commenting is ctrl+shift+7, it also works on Positron

For obvious reason I think this is a very critical issue!

Thanks in advance for your work with Positron, I've just installed it and I'm enjoying a lot trying all the new features!

## Steps to reproduce the issue:

1. Try to use the shortut to comment a line (ctrl+sfiht+c)

## What did you expect to happen?
Get the line commented

## Were there any error messages in the output or Developer Tools console?
No

**Comment by oranwutang** [comment]
Additional info: pressing ctrl+shift+A won't do anything!

**Comment by juliasilge** [comment]
Related to #3830 

Do you have the [RStudio Keymap](https://github.com/posit-dev/positron/wiki/Keyboard-Shortcuts#rstudio-keymap) enabled? You can do that in settings:

<img width="650" alt="image" src="https://github.com/posit-dev/positron/assets/470418/70368298-a88d-45f9-b486-ee43b9de9e4e">

Without the RStudio Keymap enabled, you'll get the default VS Code behavior for this key combo, which is indeed to open a terminal.

**Comment by oranwutang** [comment]
Oh, I'm sorry, effectively it works.

Anyways, I think that a program should do what it says it does, specially after a "standard" installation. 

Let's say that a completely newbie (who doesn't know a thing about RStudio or VSCode) installs Positron, he goes to the menu edit and see this:

![image](https://github.com/posit-dev/positron/assets/6965617/6e14cc1c-2295-48e9-bdf1-adb25da2c933)

But the shortcuts stated on the menu doesn't work, unless he does some kind of trick...

I think that if the standard installation doesn't offer the RStudio keymap by default, then it should have consistency between the shortcuts mentioned in the menus and the correct corresponding keymap.

It's just my very humble opinion :)

Thanks for your prompt and kind answer, Julia!

Best regards

**Comment by juliasilge** [comment]
Oh wow, I had not noticed this before. Thanks for the report! 🙌 

I think by providing a keybinding here:
https://github.com/posit-dev/positron/blob/09eefeefd1f130080c9d48157d794573f3166c15/extensions/positron-rstudio-keymap/package.json#L82
we are overriding what shows up in the native "Edit" menu, even when the RStudio Keymap is _not_ enabled. I just tried out a dev build and if I remove this keybinding, the native "Edit" menu goes back to the VS Code default.

This is sort of related to #2423 where we have a keyboard shortcut shown in the UI which does not actually work in some situations.

**Comment by oranwutang** [comment]
Do you have a way to make RStudio keymap activated by default after a vanilla installation of Positron?
Maybe that's a solution, but I don't know if it is feasible or desirable.

**Comment by petetronic** [comment]
We won't make that keymap the default, but we should make sure a disabled RStudio Keymap mode does not show incorrect key bindings in menus.

**Comment by juliasilge** [comment]
Let's track this and related problems in #3993. Thanks! 🙌
