### ISSUE TITLE
Completion failure within select()

### ISSUE THREAD

**Issue by oranwutang** [posit-dev/positron#3857]
## Positron Version:
Positron Version: 2024.06.1 build 54
Code - OSS Version: 1.90.0
Commit: 5115c73e0670f39139e55eeedf0717b468a0658d
Date: 2024-07-03T03:04:49.029Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.5.0-41-generic  

Trying to autocomplete variable names within a select() in a pipeline crashes after entering two variables.

Is shown in the video (I'm using the tab key to get suggestions of variable names)

[Screencast from 03-07-24 23:24:17.webm](https://github.com/posit-dev/positron/assets/6965617/1e0a0314-6041-4121-b4d0-fbcde928d1d7)

## Steps to reproduce the issue:

1. type mtcars |> select( [TAB, and select "am"] , [TAB, and select any var], [TAB, it crashes completion]

## What did you expect to happen?

2. Completion should keep working

## Were there any error messages in the output or Developer Tools console?
"Request textDocument/completion failed."

**Comment by juliasilge** [comment]
I believe this is the same as #3467. Can you take a look and see if you have more to add?

**Comment by oranwutang** [comment]
Hi, Julia. Yes, I think is the same issue, please feel free to close this one. Thanks!
