### ISSUE TITLE
Running code line-by-line in .qmd file is incorrect

### ISSUE THREAD

**Issue by ntluong95** [posit-dev/positron#3866]
## Positron Version:
Positron Version: 2024.06.1 (system setup) build 2024.06.1-54
Code - OSS Version: 1.90.0
Commit: 5115c73e0670f39139e55eeedf0717b468a0658d
Date: 2024-07-03T03:17:46.140Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621
## Steps to reproduce the issue:

1. Create this code chunk
```py
import pandas as pd 
import matplotlib.pyplot as plt

data = {'Name': ['Tom', 'nick', 'krish', 'jack'],
        'Age': [20, 21, 19, 18]}

data2 = [{'a': 1, 'b': 2, 'c': 3},
        {'a': 10, 'b': 20, 'c': 30}]
```

2. Put the cursor at the first line, press `Ctrl + Enter` to execute code line-by-line

## What did you expect to happen?
The cursor run each line, and move to the next line ready to run

## Were there any error messages in the output or Developer Tools console?
No

**Comment by juliasilge** [comment]
This is the same as #1646 and specifically the detail outlined in https://github.com/posit-dev/positron/issues/1646#issuecomment-2135993785. Please add any additional context you have there!
