### ISSUE TITLE
Execute code in Jupyter Notebook does not automatically change the variable view to the Notebook

### ISSUE THREAD

**Issue by ntluong95** [posit-dev/positron#3867]
## Positron Version:
Positron Version: 2024.06.1 (system setup) build 2024.06.1-54
Code - OSS Version: 1.90.0
Commit: 5115c73e0670f39139e55eeedf0717b468a0658d
Date: 2024-07-03T03:17:46.140Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621
## Steps to reproduce the issue:

1. Create a new Jupyter Notebook
2. Write any code and run

## What did you expect to happen?
The variable pane automatically change to the view of the notebook, for example `test.ipynb`, not the Python or R global environment

## Were there any error messages in the output or Developer Tools console?
No

**Comment by coatless** [comment]
I'm going to add that old notebook sessions are not cleared: 

<img width="394" alt="Screenshot showing two versions of a Juypter notebook and a no longer present untitled-1 notebook" src="https://github.com/posit-dev/positron/assets/833642/f0b3ad76-f743-40d0-9ed2-76bb552e3511">

**Comment by seeM** [comment]
Thanks for the report. This is already tracked in https://github.com/posit-dev/positron/issues/2452.

**Comment by seeM** [comment]
@coatless This may be a regression of https://github.com/posit-dev/positron/issues/2658. Do you mind opening a new bug report?
