### ISSUE TITLE
Support geopandas dataframes as data in Variables, plus in Data Explorer

### ISSUE THREAD

**Issue by luispuerto** [posit-dev/positron#3870]
I can explore pandas dataframes, but not geopandas ones and I think they are not as different. I guess that the same goes with polars, and geopolars and perhaps with Dasks dataframes. 

Are those that different that can't be implemented in the same way? In RStudio you can easily see geopandas dataframes. If you convert dataframe to a pandas the can see the dataframe just fine.

**Comment by juliasilge** [comment]
Do you mean explore in the Data Explorer, like [this](https://github.com/posit-dev/positron/wiki/Data-Explorer)?

**Comment by luispuerto** [comment]
Yes… I don't understand why there is support for pandas, but not for geopandas. The same with polars, I guess. In the end, and geodataframe is more or less the same as a data frame but with a coordinates column. Yeah, that column can be complex, but not that different from the others.. 

Right?

**Comment by luispuerto** [comment]
Perfect, thanks a lot! 

Yeah, I've seen that I can see polars data frames and that is great and I hope that in the near future we can see more coming. 

Anyhow, I really feel that to see geopandas and geopolars you just need to add them to the list of classes you can see in the data explorer because they are the same as pandas and polars.

**Comment by wesm** [comment]
I will take a look, it should be a small fix

**Comment by luispuerto** [comment]
Thanks a lot! this would be a huge improvement in my workflow!

**Comment by luispuerto** [comment]
I think you already merged the solution to this issue in the last release (build 27), right? However, I downloaded it from the releases page and at least the macOS one is the build 21 and not the 27

Positron Version: 2024.07.0 (Universal) build 21
Code - OSS Version: 1.90.0
Commit: 82b335e27545e804b7fd806db00477a6eb49951d
Date: 2024-07-09T04:32:26.804Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

is the macOS build being built correctly?

**Comment by wesm** [comment]
We're fixing some things in the build system, please wait for the next build to land (we took down build 27 so there is just 21 for now)

**Comment by luispuerto** [comment]
Hey! 

Thanks a lot! now it works! 🙂
