### ISSUE TITLE
Plots from `hvplot` don't work

### ISSUE THREAD

**Issue by david-cortes** [posit-dev/positron#3880]
## Positron Version:
```
Positron Version: 2024.07.0 build 14
Code - OSS Version: 1.90.0
Commit: b750305d0e9079e1a6d4e0b1d78daa70964b0cb8
Date: 2024-07-04T03:06:07.448Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.1.0-22-amd64
````

## Steps to reproduce the issue:

1. Create a plot with `hvplot`.
```python
import polars as pl
import hvplot.polars
from sklearn.datasets import load_iris
df = load_iris(as_frame=True)["data"]
df = pl.DataFrame(df)
df["sepal length (cm)"].hvplot.hist()
```

## What did you expect to happen?
Should show the plot in the plotting panel and let me play with it, like in the regular Jupyter extension:
![image](https://github.com/posit-dev/positron/assets/11860098/4c1c7a23-9403-4b75-a830-2d1eb86caf00)

## Actual behavior
Generates a series of non-viewable plots in the plots pane, but the actual plot doesn't show:
![image](https://github.com/posit-dev/positron/assets/11860098/cd7dc0ff-4e6c-48f2-a377-eb430b9314e8)

## Were there any error messages in the output or Developer Tools console?
No

**Comment by seeM** [comment]
Thank you for the report! I'm able to repro this on macOS.

**Comment by nstrayer** [comment]
Once #4118 is finished, this may be taken care of since bokeh is the plotting library underpinning hvplot.

**Comment by nstrayer** [comment]
I do get errors in the webview developer tools related to missing resources. 
<img width="661" alt="image" src="https://github.com/user-attachments/assets/5228efb9-2dbe-4320-ad7b-a288ca4fa2b0">

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.08.0-48](https://github.com/posit-dev/positron-builds/releases/tag/2024.08.0-48)
OS Version(s) : Windows 11, MacOS 14

### Test scenario(s) 


Using original code, the plot shows as expected using:

* Python File
* Notebook
* in Console
* 
### Link(s) to TestRail test cases run or created:
