### ISSUE TITLE
`styler::style_pkg()` puts check-marks into next line in the console

### ISSUE THREAD

**Issue by strengejacke** [posit-dev/positron#3883]
Setup:
Positron Version: 2024.07.0 (system setup) build 2024.07.0-14
Code - OSS Version: 1.90.0
Commit: b750305d0e9079e1a6d4e0b1d78daa70964b0cb8
Date: 2024-07-04T03:20:34.533Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

See
![image](https://github.com/posit-dev/positron/assets/26301769/7f943807-79a1-4cd2-8b70-d85b673c3fcd)

**Comment by olivroy** [comment]
This is also a problem in RStudio. I tried fixing this, but wasn't very successful. https://github.com/r-lib/styler/pull/1189

**Comment by strengejacke** [comment]
Interesting, I don't see this problem in VSCode, and I'm using a simular layout for both.
![image](https://github.com/posit-dev/positron/assets/26301769/16da1256-57e8-4e15-ad4b-700731cc51d4)

**Comment by juliasilge** [comment]
I can reproduce the problem with styler but I do currently believe this is specific to how styler creates messages and uses cli. For most other packages that create messages for output with cli (like devtools, etc), we see correct output:

![Screenshot 2024-07-05 at 1 35 14 PM](https://github.com/posit-dev/positron/assets/12505835/5d8d1d10-2059-49c9-89fc-a5c07e31f4e1)

I'm going to close in the belief that the Positron console is behaving as expected (based on what we see for other R packages) but are very open to additional feedback in this area. Thanks!
