### ISSUE TITLE
[ark] Naming

### ISSUE THREAD

**Issue by Enchufa2** [posit-dev/positron#3890]
This is just to let you know that KDE's default file archiver is called [**ark**](https://apps.kde.org/ark/), and therefore a package called `ark` already exists in all Linux distros.

FYI, I provide builds Fedora of both positron and ark (as `ark-kernel` for now) here: https://copr.fedorainfracloud.org/coprs/iucar/posit-dev/

**Comment by juliasilge** [comment]
Yes, we know a three-letter name is bound to have conflicts with other tools. Using `ark-kernel` seems like a reasonable option for the time being; thanks so much! 🙌
