### ISSUE TITLE
Command "View: Toggle Connections" doesn't actually toggle

### ISSUE THREAD

**Issue by jonvanausdeln** [posit-dev/positron#3896]
## Positron Version:
[2024.07.0-15](https://github.com/posit-dev/positron/releases/tag/2024.07.0-15)
## Steps to reproduce the issue:

1. Open the command palette
3. Use the command "View: Toggle Connections"
4. Use the command "View: Toggle Connections" again

It does opens the connections pane on the first time, but using it again doesn't "toggle" back or close it.. it jsut stays open

## What did you expect to happen?

I thought it would toggle back to what was in that pane before, such as "session" or "viewer".
Perhaps even changing the to remove the "toggle" text?

This is not a big issue, just logging in case anyone else finds it.  

## Were there any error messages in the output or Developer Tools console?
No

**Comment by petetronic** [comment]
We think this is the same as #811 and #2901. It's currently the VSCode behavior, though it's not obvious. We can re-open 811 for investigation in a future release?
