### ISSUE TITLE
Jupyter tab appears on panel bar despite being inactive

### ISSUE THREAD

**Issue by coatless** [posit-dev/positron#3901]
## Positron Version:

Positron Version: 2024.07.0 (Universal) build 14
Code - OSS Version: 1.90.0
Commit: b750305d0e9079e1a6d4e0b1d78daa70964b0cb8
Date: 2024-07-04T04:17:07.822Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

## Steps to reproduce the issue:

1. Create a new Jupyter Notebook for Python
2. Some some commands and save a variable as `x`
3. Look at the Panel bar and see Jupyter tab
4. Click on the Jupyter tab and note that no variables are present but are defined under session. 

<img width="1893" alt="Screenshot 2024-07-05 at 1 08 11 PM" src="https://github.com/posit-dev/positron/assets/833642/aef443dc-6013-411d-8664-2e02b03619fe">

## What did you expect to happen?

I did not expect to see the Jupyter tab as that information is redundant in Positron since it is contained under session. 

## Were there any error messages in the output or Developer Tools console?

N/A

**Comment by juliasilge** [comment]
Thanks for this report! I also see this extraneous Jupyter tab in the bottom panel.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-49
    OS Version          : OS X

### Test scenario(s) 

Followed filing instructions, no Jupyter tab present.

Link(s) to TestRail test cases run or created: 
N/A
