### ISSUE TITLE
Sending block of codes behaves differently in R script with cell and without cell

### ISSUE THREAD

**Issue by Fred-Wu** [posit-dev/positron#3908]
Positron: 2024.07.0-15
OS: MacOS

Without cell:

Only CTRL+ENTER works, and only works when placing the cursor in the beginning or end of the function
<img width="240" alt="image" src="https://github.com/posit-dev/positron/assets/4111978/edeee9ba-97c7-416b-97e5-67a960c89e76">

When placing the cursor in the middle:
<img width="220" alt="image" src="https://github.com/posit-dev/positron/assets/4111978/feb49000-e45a-439e-ba9f-1122ef0b37ae">

With cell:
Both CTRL+ENTER and SHIFT+ENTER work. 

<img width="259" alt="image" src="https://github.com/posit-dev/positron/assets/4111978/2c691a51-1093-4635-870e-2d9fd294f5d6">

SHIFT+ENTER works when placing the cursor anywhere, but CTRL+ENTER behaves the same as the one without cell.

**Comment by juliasilge** [comment]
This is all as designed/expected for now, but we are open to feedback on what you expected to happen.

<kbd>Shift</kbd>+<kbd>Enter</kbd> is a keyboard shortcut specific to code cells. There is a whole set of keyboard shortcuts specific to these kinds of cells:

<img width="850" alt="Screenshot 2024-07-07 at 8 36 29 PM" src="https://github.com/posit-dev/positron/assets/12505835/321d0a31-f35b-4bac-87cc-116acf6660d3">


Our statement range provider for R does in fact currently identify a different statement to execute if you are in lines 1 or 3 versus line 2:

```r
test <- function(a, b) {
  a + b
}
```

If you are on line 2 of that chunk, the "current statement" is identified as `a + b`. We know some users like to be able to step line-by-line through a function body, which this behavior lets you do. We currently have the same behavior as RStudio in this situation.

**Comment by petetronic** [comment]
Closing as it appears to be behaving as expected.
