### ISSUE TITLE
GT Interactive Mode: opt_interactive Doesn't Display Correctly in Plot Pane or Viewer Pane

### ISSUE THREAD

**Issue by bassamsdata** [posit-dev/positron#3914]
## Positron Version:
Positron Version: 2024.07.0 (Universal) build 15
Code - OSS Version: 1.90.0
Commit: d8da3ec9581aa7bcb9726babedacff4e3d528503
Date: 2024-07-05T03:51:32.592Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin x64 22.6.0

## Steps to reproduce the issue:

1. create r file or qmd file.
2. execute the code below:
```r
library(gt)
towny |>
  dplyr::select(name, census_div, starts_with("population")) |>
  gt() |>
  fmt_integer() |>
  cols_label_with(fn = function(x) sub("population_", "", x)) |>
  cols_width(
    name ~ px(200),
    census_div ~ px(200)
  ) |>
  tab_header(
    title = "Populations of Municipalities",
    subtitle = "Census values from 1996 to 2021."
  ) |>
  tab_source_note(source_note = md("Data taken from the `towny` dataset.")) |>
  opt_interactive(use_search = TRUE, use_filters = TRUE, use_compact_mode = TRUE)
```
The result appears in the plot area as a static image, which I believe it shouldn't.
<img width="666" alt="Screenshot 2024-07-06 at 11 24 15 AM" src="https://github.com/posit-dev/positron/assets/105807570/e397d31d-0fcb-4080-9c8b-e2a576e410a6">

## What did you expect to happen?
Since this is an HTML render, I expected it to appear in the viewer pane. The image below is from VSCodium:
<img width="1667" alt="Screenshot 2024-07-06 at 11 28 22 AM" src="https://github.com/posit-dev/positron/assets/105807570/61c3f757-883a-435b-b80d-040cad6b3d3f">

## Were there any error messages in the output or Developer Tools console?
no.

## Other notes:
I opened this issue even though I saw some related to displaying HTML widgets in the viewer pane, but nothing specific to the gt package. though, I found this comment about gt https://github.com/posit-dev/positron/discussions/3686#discussioncomment-9905639
The problem is with the function [opt_interactive](https://gt.rstudio.com/reference/opt_interactive.html?q=opt_interactive#null). When I remove this function, the table displays again in the plot pane.

Thank you

**Comment by petetronic** [comment]
I'm able to reproduce this issue on Mac

**Comment by jmcphers** [comment]
I think this is same issue as https://github.com/posit-dev/positron/issues/4057. This widget is getting rendered as HTML in R instead of being packaged up as a structured HTML widget. That means we don't get any metadata about its dependencies (so they don't load), nor its sizing policy (so we don't know where to put it).

**Comment by jmcphers** [comment]
Should be resolved with #4151:

<img width="1389" alt="image" src="https://github.com/user-attachments/assets/5bf2e21b-5ba9-41ab-88cb-a662bb6a68d1">

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-107
    OS Version          : OSX

### Test scenario(s) 

library(gt)
towny |>
  dplyr::select(name, census_div, starts_with("population")) |>
  gt() |>
  fmt_integer() |>
  cols_label_with(fn = function(x) sub("population_", "", x)) |>
  cols_width(
    name ~ px(200),
    census_div ~ px(200)
  ) |>
  tab_header(
    title = "Populations of Municipalities",
    subtitle = "Census values from 1996 to 2021."
  ) |>
  tab_source_note(source_note = md("Data taken from the `towny` dataset.")) |>
  opt_interactive(use_search = TRUE, use_filters = TRUE, use_compact_mode = TRUE)

Link(s) to TestRail test cases run or created: 
N/A

**Comment by bassamsdata** [comment]
Thanks, it works like a charm now!
