### ISSUE TITLE
Remote explorer issue: "Error: Couldn't install vscode server on remote server" (error in the server file name)

### ISSUE THREAD

**Issue by colinbousige** [posit-dev/positron#3925]
Hello

First, many thanks for the great work on Positron : as a long time user of R and Python on VSCode, I'm super hyped about this project.

I write to report an issue when trying to connect to a remote server : since it's the first time I try to connect with Positron on my server, it wants to install Positron on it (which works flawlessly with VSCode). So it looks for the file `https://github.com/VSCodium/vscodium/releases/download/1.90.0./vscodium-reh-linux-x64-1.90.0..tar.gz` which does not exist. You can look at the available files [here](https://github.com/VSCodium/vscodium/releases) : the file it should find is https://github.com/VSCodium/vscodium/releases/download/1.90.0.24158/vscodium-reh-linux-x64-1.90.0.24158.tar.gz

So, it looks like it misses the number "24158" both in the file name and in the folder name. 

Here is the end of the error message I get when trying to connect :

```
[Trace  - 07:37:23.711] Server install command stderr:
https://github.com/VSCodium/vscodium/releases/download/1.90.0./vscodium-reh-linux-x64-1.90.0..tar.gz:
2024-07-08 09:37:17 erreur 404 : Not Found.

[Trace  - 07:37:23.711] Server install command stdout:
Error downloading server from https://github.com/VSCodium/vscodium/releases/download/1.90.0./vscodium-reh-linux-x64-1.90.0..tar.gz
3d0fddceb2a1ee8342d95e21: start
exitCode==1==
listeningOn====
connectionToken====
logFile==/home/cbousige/.positron-server/.203958161106d234eaa85556293c1be8f8b395b3.log==
osReleaseId==debian==
arch==x86_64==
platform==linux==
tmpDir==/run/user/1020==
3d0fddceb2a1ee8342d95e21: end

[Error  - 07:37:23.712] Error resolving authority
Error: Couldn't install vscode server on remote server, install script returned non-zero exit status
	at t.installCodeServer (/Users/colin/.positron/extensions/jeanp413.open-remote-ssh-0.0.46-universal/out/extension.js:1:441201)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/colin/.positron/extensions/jeanp413.open-remote-ssh-0.0.46-universal/out/extension.js:1:404941

```

Cheers,
Colin

**Comment by jfulponi** [comment]
Hello Collin, I'm doing the vscode -> positron transition and just stepped in the same problem today.

I guess the problem is in the openssh extension. I made it work by hardcoding the url in the extension.js file, where the SERVER_DOWNLOAD_URL is set. In your case, this file is in "/Users/colin/.positron/extensions/jeanp413.open-remote-ssh-0.0.46-universal/out/extension.js". 

Probably openssh doesn't know very well how to handle non-vscode vscodium platforms. Maybe later I'll do a pull request on this. 

Hope this helps. 

Best, 

Juan

**Comment by juliasilge** [comment]
We do not yet have support for using Positron remotely in this way, but it is high on our list of priorities! The main issue where we are tracking the work is #2307 but you can read more at https://github.com/posit-dev/positron/issues/3687 and [other related issues/discussions](https://github.com/search?q=repo:posit-dev/positron+ssh+remote&type=issues), as well as <https://github.com/posit-dev/positron/wiki#positron-might-not-be-a-good-fit-for-you-today-if>. As of today, Positron is only supported as a desktop app.

**Comment by colinbousige** [comment]
Alright, my bad, sorry for the duplicate post... can't wait for it to work, then ! 
Cheers,
Colin
