### ISSUE TITLE
Installation without Admin Account

### ISSUE THREAD

**Issue by blechturm** [posit-dev/positron#3926]
The public beta can't be installed without an admin account in Windows, this makes it (for me) impossible to use without the involvment of the IT department, which is a deal breaker for me and probably for many others too :D

R-Studio and VS-Code can be installed in User-Land without Admin Rights. It would be awesome if you can make this happen too once the IDE is out of Beta.

Good luck and keep up the great work!

**Comment by juliasilge** [comment]
This is tracked in #3703; please feel free to add any additional info there or to upvote!

**Comment by blechturm** [comment]
Awesome, will do!
