### ISSUE TITLE
R: Default setup for debugging C/C++ code in packages

### ISSUE THREAD

**Issue by CGMossa** [posit-dev/positron#3927]
I wanted the Console to run with `R -d lldb` for debugging purposes. There, I thought `extraArguments` would work

```json
"positron.r.extraArguments": [
        "-d lldb"
    ],
```
But it doesn't work. And the schema for this isn't appearing as a trigger in positron, so I don't know what I'm meant to do here.

**Comment by lionel-** [comment]
This method isn't supported. Instead you can go to the Debug pane, click on the small wheel icon to add a `launch.json` configuration file, and paste this:

```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "lldb",
      "request": "attach",
      "name": "Debug",
      "program": "ark",
    }
  ]
}
```

If you have more than one ark running you can add a `"pid": 1234` field with the pid retrieved from `Sys.getpid()` in your R session. We'll make all of this easier in the future.

Once this is set up, attach to the session by clicking the green arrow button in the debug pane. From then on breakpoints set in your C or C++ files should work.

Also feel free to install the clangd extension and the latest version of pkgload to maintain a compilation database, see https://github.com/r-lib/pkgload/blob/main/NEWS.md#pkgload-140. This will enable code assistance in your C/C++ files like completions or jump-to-definition.

**Comment by petetronic** [comment]
This looks like it was answered, closing. If you have any further questions let us know.

**Comment by yutannihilation** [comment]
One minor note is that Windows users need to change this line to `ark.exe`.

```json
      "program": "ark",
```
