### ISSUE TITLE
Print polars data frames formatted

### ISSUE THREAD

**Issue by botan** [posit-dev/positron#3934]
## Positron Version:
Positron Version: 2024.07.0 (Universal) build 17
Code - OSS Version: 1.90.0
Commit: 203958161106d234eaa85556293c1be8f8b395b3
Date: 2024-07-08T03:53:10.746Z (18 hrs ago)
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

## Steps to reproduce the issue:
1. Using the IDE
<img width="568" alt="image" src="https://github.com/posit-dev/positron/assets/68795444/18a52ed5-39e5-444a-b02e-6df291b3dd15">

2. Using the Python Interpreter
```python
Python 3.12.4 (main, Jul  5 2024, 13:21:21) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars as pl
>>> data = {"a": [1, 2], "b": [3, 4]}
>>> df = pl.DataFrame(data)
>>> df
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 3   │
│ 2   ┆ 4   │
└─────┴─────┘
>>> print(df)
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 3   │
│ 2   ┆ 4   │
└─────┴─────┘
```

3. Using the IPython kernel
```python
Python 3.12.4 (main, Jul  5 2024, 13:21:21) [Clang 15.0.0 (clang-1500.3.9.4)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.26.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import polars as pl

In [2]: data = {"a": [1, 2], "b": [3, 4]}

In [3]: df = pl.DataFrame(data)

In [4]: df
Out[4]:
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 3   │
│ 2   ┆ 4   │
└─────┴─────┘

In [5]: print(df)
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 3   │
│ 2   ┆ 4   │
└─────┴─────┘
```

## What did you expect to happen?
I expected to see the same formatted output in Positron without having to print explicitly.

**Comment by juliasilge** [comment]
I may not quite be understanding what you are reporting. The pretty-printed HTML table that you see in the console as output for polars or pandas data frames is currently behaving as designed and implemented in #1093:

![Screenshot 2024-07-09 at 10 30 30 AM](https://github.com/posit-dev/positron/assets/12505835/1539b321-dd77-426c-abdf-e31c0a4a3c3f)

Are you saying this pretty-printed HTML output is unexpected to you? Or rather than you expected to see it when using `print()` as well?

**Comment by botana-te** [comment]
My expectation was the opposite; I was expecting to see something like the below instead of the HTML output.
```python
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 3   │
│ 2   ┆ 4   │
└─────┴─────┘
```
Sorry, I literally didn't realise that it's a feature, and it can actually be quite handy for copying and pasting the output. Thanks, I'm happy to close the issue.

**Comment by botan** [comment]
My expectation was the opposite; I was expecting to see something like the below instead of the HTML output.
```python
shape: (2, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 3   │
│ 2   ┆ 4   │
└─────┴─────┘
```
Sorry, I literally didn't realise that it's a feature, and it can actually be quite handy for copying and pasting the output. Thanks, I'm happy to close the issue.

**Comment by juliasilge** [comment]
Ah gotcha! Yes, let's close for now but we can continue to look for feedback about this feature being undesired or confusing.

**Comment by seeM** [comment]
Positron's console is closer to a Jupyter console/notebook in that it uses HTML outputs when they're provided. I usually do `print(df)` if I want the plaintext output instead.
