### ISSUE TITLE
Data explorer histogram and summary statistics

### ISSUE THREAD

**Issue by luispuerto** [posit-dev/positron#3935]
Hey! 

I love positrons and I love that it has a data explorer out of the box. However, and taking inspiration of [Data Wrangler VSC](https://github.com/microsoft/vscode-data-wrangler) extension it would be great if you can add some summary statistics per variable and a mini histogram. And when I mean mini I mean mini. In the Data Wrangler VSC that info is taking up to much space at the top of the data frame. I think your approach is better, on the side, but I think that some "small multiple" histogram _Tufte style_ would be great, and have some additional information beyond the current missing values, like percentage of distinct values, max min median or other relevant descriptive stats. I really think that the histograms should be small and it would be cool that clicking on then you can make them slightly bigger for a quick exploration.

**Comment by juliasilge** [comment]
We definitely have plans along these lines for the Data Explorer! You can see [all issues for the Data Explorer here](https://github.com/posit-dev/positron/issues?q=is:issue+is:open+label:%22area:+data+explorer%22) and specific tracking for [initial summary statistics here](https://github.com/posit-dev/positron/issues/2161).

**Comment by wesm** [comment]
@jthomasmock I think we may be able to resolve this one with the addition of mini-sparklines and larger histograms in the summary pane?

**Comment by jthomasmock** [comment]
Agreed, I think this can be closed via https://github.com/posit-dev/positron/pull/4403
