### ISSUE TITLE
Package developing, load all functions, warnings when typing on console

### ISSUE THREAD

**Issue by rfsaldanha** [posit-dev/positron#3938]
## Positron Version
Positron Version: 2024.07.0 build 21
Code - OSS Version: 1.90.0
Commit: 82b335e27545e804b7fd806db00477a6eb49951d
Date: 2024-07-09T03:06:22.884Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.5.0-41-generic

## Steps to reproduce the issue:

When developing a package, I receive warnings after loading all functions and starting to type the function on the terminal.

1. Create a package with `usethis::create_package("testPackage")`
2. Create a new function with `usethis::use_r("test_fn")`. Fill it with something, like 

```r
test_fn <- function(x){
  res <- x^2

  return(x)
}
```
3. Load all functions with `devtools::load_all()`
4. Try to call the function at the console. When you start to type the function name and see its arguments, I receive several of these warnings on the console.

```r
Warning message:
In file(con, "r") :
  cannot open file '/usr/lib/R/share/Rd/macros/system.Rd': No such file or directory
```

## What did you expect to happen?
No warnings with a valid function.

## Were there any error messages in the output or Developer Tools console?
No errors or other messages.

**Comment by DavisVaughan** [comment]
What does `file.path(R.home("share"), "Rd", "macros", "system.Rd")` return for you?

**Comment by DavisVaughan** [comment]
That looks the same as what is in this error:

> cannot open file '/usr/lib/R/share/Rd/macros/system.Rd': No such file or directory

Does that file really not exist on your machine? That sounds strange if so. How did you install R?

**Comment by DavisVaughan** [comment]
For example, R itself uses this path, assuming it exists:
https://github.com/wch/r-source/blob/a9bc8b4fcd761cd08a77bf3c02dfc917016eb94b/src/library/tools/R/Rdtools.R#L23

**Comment by rfsaldanha** [comment]
Yep, I confirm that the file does not exist at that address.
```
raphael@rfsaldanha:~$ cat /usr/lib/R/share/Rd/macros/system.Rd
cat: /usr/lib/R/share/Rd/macros/system.Rd: No such file or directory
```
I installed R using `apt install` on Ubuntu, after adding the R binaries from CRAN

**Comment by rfsaldanha** [comment]
I have found the file. It is available at this address:
```
/usr/share/R/share/Rd/macros/system.Rd
```
and not on this one

```
/usr/lib/R/share/Rd/macros/system.Rd
```

**Comment by DavisVaughan** [comment]
Okay we are mostly convinced this is https://github.com/posit-dev/positron/issues/3637, but we will double check when we fix that one. Closing this in favor of that though. Thanks for the report!

**Comment by rfsaldanha** [comment]
You all are doing amazing work. Keep rocking!

**Comment by dheimgartner** [comment]
Can confirm this issue

Positron Version: 2024.07.0 build 41
Code - OSS Version: 1.90.0
Commit: 9f24124be55ef409fb6b6c75ee80232f298cd56b
Date: 2024-07-12T03:12:45.516Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.5.0-41-generic
