### ISSUE TITLE
Support reticulate for interactive Python + R use in the consoles

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#3942]
This request is about interactive work in R and Python consoles:

### Discussed in https://github.com/posit-dev/positron/discussions/3920

<div type='discussions-op-text'>

<sup>Originally posted by **erolbicero** July  7, 2024</sup>
Hello,

I like the IDE and its potential.  One of the powerful features of RStudio is the ability to pass variables back and forth between R and Python through the reticulate library.

Are there any plans to get this functionality in Positron?  I've tried using reticulate, and although it can run python, I can't jump back and forth between scripts like I can in RStudio.</div>

Although package development and document writing using reticulate work well, we don't yet support an interactive workflow where you can have communication between your R and Python sessions/consoles.

**Comment by dfalbel** [comment]
This has been implemented in https://github.com/posit-dev/positron/pull/4603. It can be enabled with the `positron.reticulate.enabled` feature flag, which is currently `off` by default.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.10.0-5
    OS Version          : OSX

### Test scenario(s) 

Basic variable and data frame checks

Link(s) to TestRail test cases run or created:
