### ISSUE TITLE
Set R installation from `settings.json`

### ISSUE THREAD

**Issue by roaldarbol** [posit-dev/positron#3946]
In VS Code, it's possible to set the R installation to use for the workspace in `.vscode/settings.json`, e.g. this current setup that works nicely:
```json
{
    "r.bracketedPaste": true,
    "r.plot.useHttpgd": true,
    "r.rpath.mac": "${workspaceFolder}/.pixi/envs/default/bin/R",
    "r.rterm.mac": "${workspaceFolder}/.pixi/envs/default/bin/radian",
    "r.rpath.linux": "${workspaceFolder}/.pixi/envs/default/bin/R",
    "r.rterm.linux": "${workspaceFolder}/.pixi/envs/default/bin/radian",
    "r.rpath.windows": "${workspaceFolder}/.pixi/envs/default/bin/R",
    "r.rterm.windows": "${workspaceFolder}/.pixi/envs/default/bin/radian"
}
```

Since Positron doesn't use the R extension, but your own - how could I specify this for Positron?

(This workflow means that whenever the workspace is opened, it automatically detects and chooses the R installation to use - here I've used pixi to install `r-base` from conda-forge, so I'll always have just the right R version for the project, and so will everyone else who'd like to run the project.)

**Comment by jmcphers** [comment]
We have #3724 tracking automatically discovering Pixi based R installations, and https://github.com/posit-dev/positron/issues/2235 tracking the ability to manually specify R installation locations in settings as requested here. I think those cover this scenario (but please LMK if I missed something!).

**Comment by roaldarbol** [comment]
Hi @jmcphers, Thanks for the reply! I see two issues as difference, the difference between the two issues being: 
- This issue: Automatically let Positron know which R installation to use when opening the project
- #3724: Having the ability to manually set it from within Positron (e.g. to versions installed with Pixi)

So I'd be in favour of re-opening the issue.

**Comment by jennybc** [comment]
There's also #2659. It feels like we do have enough issues open for this, so @roaldarbol if you feel like we're missing something, you can add some comments or color to one of them.

**Comment by roaldarbol** [comment]
@jennybc *That* issue definitely is spot on - I'll just add the idea of a `settings.json` file there too then. :-) 
Thanks for pointing it out!
