### ISSUE TITLE
(R) leaflet maps won't display provider tiles (`addTiles()` okay)

### ISSUE THREAD

**Issue by jack-davison** [posit-dev/positron#3949]
## Steps to reproduce the issue:

```r
leaflet::leaflet() |> leaflet::addProviderTiles("OpenStreetMap")
```

![image](https://github.com/posit-dev/positron/assets/45171616/e038fc48-0477-46d0-9ea3-ed12be8e1ed5)

## What did you expect to happen?

A basemap to appear! 

NB: `addTiles()` works fine, and `addProviderTiles()` still works in RStudio.

If you save the HTMLwidget the provider tiles will appear successfully in the browser, so it's likely a Positron issue.

## Were there any error messages in the output or Developer Tools console?

No.

Probably related to #2023.

**Comment by jmcphers** [comment]
This is tracked in https://github.com/posit-dev/positron/issues/3756.
