### ISSUE TITLE
Widget plots are recreated when the plots pane resizes

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#3961]
## Positron Version:
Positron Version: 2024.07.0 (Universal) build 21

## Steps to reproduce the issue:

1. Create a widget plot. For example, with R:
    ```r
    library(plotly)
    fig <- plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)
    fig
    ```
2. Resize the pane.
3. The plot will disappear while being resized as shown in the video below.

https://github.com/posit-dev/positron/assets/559360/91012771-53ed-4c53-b5dc-924635b69cd0

## What did you expect to happen?
The plot should stay visible while resizing.

## Were there any error messages in the output or Developer Tools console?
No related errors, but tons of logs related to the webview and loaded JS/CSS files that suggest that the webview is being recreated, which is not great for performance too.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-49
    OS Version          : OS X

### Test scenario(s) 

Tested plot scaling as described in issue.

Link(s) to TestRail test cases run or created: 
N/A
