### ISSUE TITLE
htmlwidgets do not work (leaflet)

### ISSUE THREAD

**Issue by JosiahParry** [posit-dev/positron#3968]
## Positron Version:
Positron Version: 2024.07.0 (Universal) build 21
Code - OSS Version: 1.90.0
Commit: 82b335e27545e804b7fd806db00477a6eb49951d
Date: 2024-07-09T04:32:26.804Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.4.0

## Steps to reproduce the issue:

```r
library(leaflet)
leaflet() |> 
  setView(-117.16018863360692, 32.70568725886412, 15)
```

## What did you expect to happen?

The map would be shown as it is in RStudio

**Comment by seeM** [comment]
It gets part of the way there on my side:

<img width="436" alt="image" src="https://github.com/posit-dev/positron/assets/559360/d772a0d2-f82e-4955-a1a1-19e3d4d0ab93">

And encounters an error in `proj4leaflet`:

```
Uncaught Leaflet and proj4 must be loaded first
```

Might be related to https://github.com/posit-dev/positron/issues/3969 where dependencies are also not loaded correctly.

**Comment by juliasilge** [comment]
Related to #3756

**Comment by juliasilge** [comment]
After https://github.com/posit-dev/positron/pull/4126, this now behaves the same as RStudio (blank HTML pops up in Viewer).

**Comment by JosiahParry** [comment]
> After #4126, this now behaves the same as RStudio (blank HTML pops up in Viewer).

Just came here to report another htmlwidgets related issue with mapgl. This PR will fix the blank html widget? 🙏🏼 
<img width="484" alt="image" src="https://github.com/user-attachments/assets/7e75941d-2236-413e-bfb5-6bb5c93858a9">

**Comment by juliasilge** [comment]
We can check it out! By chance, do you have a small mapgl reprex to share?

**Comment by JosiahParry** [comment]
> We can check it out! By chance, do you have a small mapgl reprex to share?
This one is missing a `library(dplyr); library(sf)` but it works! 

https://gist.github.com/ryanscharf/ad6c262f52770a1c2ddc70fa4e56dee4

You'll also need a mapbox api token—it's frightening to make one though b/c they require a credit card. Just a warning 😅

**Comment by walkerke** [comment]
@JosiahParry @juliasilge everything is working for me now with the latest Positron build, try it out!

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-107
    OS Version          : OSX

### Test scenario(s) 

library(leaflet)
leaflet() |> 
  setView(-117.16018863360692, 32.70568725886412, 15)

Now behaves the same as RStudio

Link(s) to TestRail test cases run or created: 
N/A
