### ISSUE TITLE
plotly.express charts do not display in Python Jupyter notebook

### ISSUE THREAD

**Issue by vinaychuri** [posit-dev/positron#3972]
Positron Version: 2024.07.0 (Universal) build 21
MacOS Ventura 13.6.7 
Python 3.12.4

The following code does not display at charts or errors in Jupyter Notebook with python interpreter.
```
import plotly.express as px
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species")
fig.show()
```

If the following code is executed before the charting code it displays the chart correctly.
```
import plotly.io as pio
pio.renderers.default = "notebook"

```

I checked vscode Version: 1.91.0 (Universal) and the first code displays chart without any "pio" setup

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-49
    OS Version          : OS X

### Test scenario(s) 

After installation of plotly, followed filing instructions.

Link(s) to TestRail test cases run or created: 
N/A
