### ISSUE TITLE
Support binary data in comm messages via `buffers`

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#3974]
I've always wondered what the `buffers` key was used for. It's explained really well in this comment: https://github.com/jupyter-widgets/ipywidgets/issues/2378#issuecomment-483345329. In summary:

> We use buffers to encode binary data from widgets

Here's a simple example that (I think) requires `buffers` to work:

```py
import ipywidgets
with open('image.png', 'rb') as f: image = f.read()  # you'll need an actual image file
display(ipywidgets.Image(value=image, format='png'))
```

**Comment by seeM** [comment]
This is needed for the following widget libraries:

* `bqplot`
* `ipycanvas`
* `ipydatagrid`
* `ipympl` (i.e. Matplotlib's widget backend)
* `pythreejs`

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-24
    OS Version          : OSX

### Test scenario(s) 

Works in console:

import ipywidgets
with open('/Users/christophermead/Desktop/cmeadPhoto.jpg', 'rb') as f: image = f.read()  # you'll need an actual image file
display(ipywidgets.Image(value=image, format='png'))

Link(s) to TestRail test cases run or created:
N/A
