### ISSUE TITLE
Autocomplete automatically add double quotes

### ISSUE THREAD

**Issue by EKtheSage** [posit-dev/positron#3976]
Is there a way to turn off the quotes around the selected words from autocomplete?

`data.table` doesn't really need the double quotes when performing operations and automatically adding double quotes basically made the autocomplete functionality useless for `data.table` 

![image](https://github.com/posit-dev/positron/assets/7637535/09ef555d-e71c-4eab-8962-09f63ab49c9c)
![image](https://github.com/posit-dev/positron/assets/7637535/496c5683-af69-4e53-8679-1a421f3a4a41)

**Comment by juliasilge** [comment]
Thanks for this feedback! What kind of completion would you expect to see here?

**Comment by EKtheSage** [comment]
In RStudio, this would be `result[abc]` not `result["abc"]`

**Comment by juliasilge** [comment]
This is a duplicate of #3140, which I had totally forgotten about. Apologies on that!
