### ISSUE TITLE
Filter modal interactions in data explorer window that has been popped out of the main editor window steal focus

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#3978]
## Positron Version:

main branch as of 7/11/24

## Steps to reproduce the issue:

1. Open data explorer
2. Right click on tab and pop data explorer out into new window
3. Add any filter -- multiple interactions from selecting a column, selecting a filter type, and apply filter steal focus back to the main editor window

## What did you expect to happen?

For the external data explorer window to stay in focus

## Were there any error messages in the output or Developer Tools console?

No

**Comment by softwarenerd** [comment]
This issue is addressed in https://github.com/posit-dev/positron/pull/4693.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-55
    OS Version          : OSX

### Test scenario(s) 

During sort and filter, focus remains in popped out window.

Link(s) to TestRail test cases run or created:
