### ISSUE TITLE
Command "Install R package and restart R" overwrites newer package version with older one

### ISSUE THREAD

**Issue by strengejacke** [posit-dev/positron#3983]
## Positron Version:

Positron Version: 2024.07.0 (system setup) build 2024.07.0-27
Code - OSS Version: 1.90.0
Commit: 6f3a5c852bf96a85e7cd6c7a4477ed3852e3c38f
Date: 2024-07-10T03:19:46.344Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

## Steps to reproduce the issue:

1. Install latest package version from a (local) repository (in this case, the _performance_ package)
2. You have a dependency (package _insight_), which is installed from a pull request and has the "latest" version number.
3. Run "Ctrl+Shift+I". _insight_ is overwritten by an older version (i.e. an older version is being installed)

## What did you expect to happen?

It's probably an issue with _pak_, not _Positron_, but a newer installed package is overwritten by an older version by _pak_:

```
insight     0.20.1.14 → 0.20.1.13 [bld][cmp] (GitHub: c4a33df)
```

I would expect that a package is not installed when it has an "older" version number.

**Comment by juliasilge** [comment]
Yes, this is behavior from pak, if you would like to report the behavior you'd like to see there. 

We have gotten feedback that using pak here is not great as outlined in https://github.com/posit-dev/positron/issues/2955 so we are likely going to be switching away from pak for this command.

**Comment by strengejacke** [comment]
Thanks, I'll close this as duplicate then.
