### ISSUE TITLE
It crashes when I try to run the code

### ISSUE THREAD

**Issue by Lindolfo-Cavalcanti** [posit-dev/positron#3986]
## Steps to reproduce the issue:

1. Take the Titanic Kaggle data
2.  Select  all the code you want to run
3. Maybe, it needs to be a bigger code
4. Run it

## What did you expect to happen?
I expect it to run normally and return in the console the results and variables created

## Were there any error messages in the output or Developer Tools console?
No. The console just prints the code but It doesn't run it

**Comment by Lindolfo-Cavalcanti** [comment]
That's the code I was using. It had more comments.

## TITANIC KAGGLE

library(tidyverse)
library(randomForest)

# Carregar pacotes
train_data = read.csv("/path/train.csv", stringsAsFactors = F)

test_data = read.csv("/path/train.csvtest.csv", stringsAsFactors = F)

# 2- Tratar dados
	
	# Igualar colunas

    str(c(train_data, test_data))    

    test_data$Survived = NA

    head(test_data)

	# Juntar tabelas (rbind())

    train_data$IsTrain = T

    test_data$IsTrain = F

    head(train_data$IsTrain)
    head(test_data$IsTrain)

    full_data = rbind(train_data, test_data)

    glimpse(full_data)

	# Valores NA (sem excluir linhas)
        
        table(is.na(full_data)) #682

        table(is.na(full_data$Age)) #263
        table(is.na(full_data$Fare)) #1
        table(is.na(full_data$Survived)) #418

        AgeMedian = median(full_data$Age, na.rm = T)

        full_data = full_data |> 
            mutate(Age = ifelse(is.na(Age), AgeMedian, Age))

        FareMedian = median(full_data$Fare, na.rm = T)

        full_data = full_data |> 
            mutate(Fare = ifelse(is.na(Fare), FareMedian, Fare)

**Comment by Lindolfo-Cavalcanti** [comment]
That's what the console returns when I try to run the code separately or the whole code.


ibrary(tidyverse)
library(randomForest)
library(tidyverse)
library(randomForest)

# TITANIC KAGGLE

library(tidyverse)
library(randomForest)

# Carregar dados
train_data = read.csv("/path/train.csv", stringsAsFactors = F)

test_data = read.csv("/path/train.csvtest.csv", stringsAsFactors = F)

# Tratar dados
	
	# Igualar colunas

    str(c(train_data, test_data))    

    test_data$Survived = NA

    head(test_data)

	# Juntar tabelas (rbind())

    train_data$IsTrain = T

    test_data$IsTrain = F

    head(train_data$IsTrain)
    head(test_data$IsTrain)

    full_data = rbind(train_data, test_data)

    glimpse(full_data)

	# Valores NA (sem excluir linhas)
        
        table(is.na(full_data)) #682

        table(is.na(full_data$Age)) #263
        table(is.na(full_data$Fare)) #1
        table(is.na(full_data$Survived)) #418

        AgeMedian = median(full_data$Age, na.rm = T)

        full_data = full_data |> 
            mutate(Age = ifelse(is.na(Age), AgeMedian, Age))

        FareMedian = median(full_data$Fare, na.rm = T)

        full_data = full_data |> 
            mutate(Fare = ifelse(is.na(Fare), FareMedian, Fare)

**Comment by jmcphers** [comment]
```r
    full_data = full_data |> 
        mutate(Fare = ifelse(is.na(Fare), FareMedian, Fare)
```

I'm not sure what is happening here (a screenshot would be helpful!) but it looks like the problem is that this R code is not complete -- it's missing a `)`. If you try to run code in the Console and it looks like the code isn't complete, Positron will prompt you for more code instead of running the code you entered.

Related to https://github.com/posit-dev/positron/issues/2009.

**Comment by Lindolfo-Cavalcanti** [comment]
Now I got it. Sorry! I didn't notice it when I was coding and I didn't know that the it would prompt that. When I tried to run the same code on Rstudio probably  I noticed it and fixed it but I didn't realize it was a mistyping mistake . I tried to run the final code that I end it in Rstudio in Positron and it worked. Sorry again for the mistake!

**Comment by juliasilge** [comment]
So glad you got it working!
