### ISSUE TITLE
Could not start runtime: failed to install ipykernel for Python

### ISSUE THREAD

**Issue by manirm** [posit-dev/positron#3991]
After starting Positron on my Windows 10 desktop and activating Conda environment related to my python script, it started to install ipykernel and failed with the message "Could not start runtime: failed to install ipykernel for Python"

**Comment by bhollan** [comment]
I also just installed on Windows and got this same error. I have a conda install a few places on my machine in WSL2, but nothing directly in Windows. So I tried to start the Python kernel and it ask if it could install one, but it failed.

**Comment by juliasilge** [comment]
I believe this is the same as #2504. Do you want to take a look and see if you have anything to add there?
