### ISSUE TITLE
The icon in the top left corner is suggested to be Positron's instead of Code OSS

### ISSUE THREAD

**Issue by petetronic** [posit-dev/positron#3996]
### Discussed in https://github.com/posit-dev/positron/discussions/3979

<div type='discussions-op-text'>

<sup>Originally posted by **chuxinyuan** July 11, 2024</sup>
Screenshot from discussion:

![image](https://github.com/user-attachments/assets/4d2a1dbd-5127-47fc-bfec-e6d1b8c21825)

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.07.0-81](https://github.com/posit-dev/positron/releases/tag/2024.07.0-81)
OS Version(s) : Windows 11

### Test scenario(s) 



Icon now appears as expected

### Link(s) to TestRail test cases run or created: 
N/A
