### ISSUE TITLE
Software name error

### ISSUE THREAD

**Issue by Lgz-tud** [posit-dev/positron#4001]
When I tried to click on the R file with the right mouse button to choose how to open it, I found that the software name is Electron and not Positron

![主文件夹 2024_7_13 0_37_34](https://github.com/user-attachments/assets/a5b0d3ef-98dd-4f67-a1d4-49432610785a)

**Comment by juliasilge** [comment]
I believe this is the same (or nearly the same) as #3671.

**Comment by Lgz-tud** [comment]
yes, you are right.
