### ISSUE TITLE
`devtools::test()` triggers popup alert if project directory is not a git repository

### ISSUE THREAD

**Issue by dheimgartner** [posit-dev/positron#4002]
## Positron Version:
Positron Version: 2024.07.0 build 41
Code - OSS Version: 1.90.0
Commit: 9f24124be55ef409fb6b6c75ee80232f298cd56b
Date: 2024-07-12T03:12:45.516Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.5.0-41-generic

## Steps to reproduce the issue:

1. Init new R package with `usethis::create_package("foo")`
2. Create a function in R `foo <- function() return("bar")
3. Set up test infrastructure `usethis::use_testthat()` and `usethis::use_test("foo")`
4. Write test for

```R
test_that("foo returns bar", {
  expect_equal("bar", foo())
})
```
5. Run tests with `devtools::test()` -> the following alert pops up:

![Screenshot from 2024-07-13 01-04-52](https://github.com/user-attachments/assets/48a5eb2f-e12c-4814-9fc5-37ac634874ae)

>The test runs successfully and we can simply close the popup (so this is a minor "issue" but might be confusing for users...).

6. Version the repository `git init .`
7. Run tests again `devtools::test()` -> no alert

## What did you expect to happen?

No alert popup.

## Were there any error messages in the output or Developer Tools console?

No

**Comment by juliasilge** [comment]
This is the same as #2697 and I'm going to add the example you raised to that issue. Thanks!
