### ISSUE TITLE
Can Positron be deployed on Linux servers to achieve functionality similar to Rstudio?

### ISSUE THREAD

**Issue by elegantmedstu** [posit-dev/positron#4004]

**Comment by juliasilge** [comment]
You probably [saw this caveat for now](https://github.com/posit-dev/positron/wiki#positron-might-not-be-a-good-fit-for-you-today-if) and can read about our plans for Positron on a server in a few places:

- https://github.com/posit-dev/positron/discussions/3695
- #2307 
- #3687 
- [various other places!](https://github.com/search?q=repo:posit-dev/positron+ssh+remote&type=issues)

Let us know if you have further questions after reading these!
