### ISSUE TITLE
Wrong project path when using newest version of Positron

### ISSUE THREAD

**Issue by ntluong95** [posit-dev/positron#4016]
## Positron Version:
Positron Version: 2024.07.0 (system setup) build 2024.07.0-49
Code - OSS Version: 1.90.0
Commit: 677a0d0f0a4f5f9389507c079c8b9a67699d52fd
Date: 2024-07-15T03:19:37.352Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621
## Steps to reproduce the issue:

1. Open a new .ipynb file
2. Try to import data

## What did you expect to happen?
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/b1a8686e-4431-49e5-82e1-b85337c19bd9">

## Were there any error messages in the output or Developer Tools console?
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/254c99d7-0a2f-4005-8abe-a4b350081a3c">

**Comment by seeM** [comment]
I'm able to repro this issue. We'll get it fixed shortly!

**Comment by jennybc** [comment]
@ntluong95 I know you were well-meaning when you closed this, but we actually wait to close until a second person on the dev team does some verification. So I'm re-opening this to allow that process to unfold as usual.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-81
    OS Version          : OSX

### Test scenario(s) 

1. Open project with notebook
2. add cell that checks current working directory
3. expect current working directory to match the directory of the project:

<img width="917" alt="image" src="https://github.com/user-attachments/assets/4629addd-8e86-4224-9b16-2a172e67bcc8">

Link(s) to TestRail test cases run or created:
N/A
