### ISSUE TITLE
Basic HTML output in Positron notebooks

### ISSUE THREAD

**Issue by nstrayer** [posit-dev/positron#4018]
Right now we just dont support html output at all. 

There are two tiers of html output that we should support: complext output with javascript that will need thoughtful sandboxing etc, and very basic html output. E.g. table printing. 

The first step towards support of all HTML output types should be the basic html support. 
This is what a dataframe output looks like currently in positron notebooks:
<img width="427" alt="image" src="https://github.com/user-attachments/assets/8a43d965-f953-4244-b9e5-3f05e0df4188">

Which is not great compared to the vscode notebooks:
<img width="759" alt="image" src="https://github.com/user-attachments/assets/be761bd2-0cf8-4373-b694-11c2fffa695d">

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-113
    OS Version          : OSX

### Test scenario(s) 

Used tips.csv from qa-example-content

![Image](https://github.com/user-attachments/assets/05b3cf8f-09ce-459d-a9c0-ec6c36ab5e1a)



Link(s) to TestRail test cases run or created: 
N/A
