### ISSUE TITLE
here() detects C:/ as project directory

### ISSUE THREAD

**Issue by carlosresu** [posit-dev/positron#4025]
Type: <b>Bug</b>

Create any R project
library(here)
here() detects "C:/" as project directory

VS Code version: Positron 1.90.0 (677a0d0f0a4f5f9389507c079c8b9a67699d52fd, 2024-07-15T03:19:37.352Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7800X3D 8-Core Processor            (16 x 4192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.15GB (19.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jennybc** [comment]
Can you describe precisely what you mean by this?

> Create any R project

I suspect what you are doing does not leave behind any file or folder that is recognized by the here package as declaring "THIS FOLDER is the project root".

Positron does not necessarily place anything like the `.Rproj` file that RStudio places, which is one of the features the here package picks up on. If the folder is an R package or a Git repo, for example, those use cases _will_ provide the project root info that here is looking out for (a DESCRIPTION file or a `.git/` directory, respectively).

You can always create a file named `.here` to declare a folder as being the project root, if you are concerned that none of the other implicit criteria are going to apply. The docs for `here::here()` outline what here is looking for when trying to identify the project root:

https://here.r-lib.org/reference/here.html#project-root

**Comment by carlosresu** [comment]
Yes, so I created a .here file and even included the .rproj file from rstudio. It also has .git since it is a git repo. All fail to work only in positron. The folder itself (drg-pipeline) is in C:/Users/<username>/Documents/drg-pipeline. Here() detects the project folder as C:/ in Positron.

When opening the same folder in VS Code or RStudio, here works as expected.

Regards,
Carlos Miguel C. Resurreccion
________________________________

**Comment by jennybc** [comment]
Can you show the result of `here::dr_here()`?

**Comment by carlosresu** [comment]
Hello @jennybc here are the results of here::dr_here(). It says these things even though these are in fact present in my directory.

I think it is mistakenly looking at C:/ and parents, not children.

`here() starts at [C:/.](file:///C:/)
- This directory and its parents do not satisfy any of the following criteria:
  - contains a file ".here"
  - contains a file matching "[.]Rproj$" with contents matching "^Version: " in the first line
  - contains a file "DESCRIPTION" with contents matching "^Package: "
  - contains a file "remake.yml"
  - contains a file ".projectile"
  - contains a directory ".git"
  - contains a file ".git" with contents matching "^gitdir: "
  - contains a directory ".svn"
! Call `here::i_am()` in your scripts and reports, or use `set_here()` to create a `.here` file
- Initial working directory: [C:/](file:///C:/)
- Current working directory: [C:/](file:///C:/)`

**Comment by kylebutts** [comment]
@carlosresu by chance, do you have a directory open in positron? The R session will start at the directory of the open explorer folder, not the directory of the file.
![CleanShot 2024-07-17 at 06 47 31@2x](https://github.com/user-attachments/assets/8674a2bb-f2eb-4959-9d4f-4e387d2fffc7)

**Comment by jennybc** [comment]
Yeah I think @kylebutts has a good line of inquiry. It just feels like we are not in a folder at all. What does `getwd()` return in the R console?

**Comment by jennybc** [comment]
I'd love to see the result of a little snippet like:

```r
getwd()
list.files()
```

to really verify that the files / folders you believe to be present in this directory truly are there.

**Comment by carlosresu** [comment]
I don't know how or why but the latest update (2024.07.0-81) fixed everything...

**Comment by jennybc** [comment]
Glad you are no longer experiencing an issue!
