### ISSUE TITLE
Welcome page is missing Positron logo

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#4036]
## Positron Version:

```
Positron Version: 2024.07.0 (Universal) build 52
Code - OSS Version: 1.90.0
Commit: eee2ff0fdcb422608b5181338e6204cdb5e311cd
Date: 2024-07-16T04:40:30.193Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

## Steps to reproduce the issue:

Run the _Help: Welcome_ command.

<img width="727" alt="image" src="https://github.com/user-attachments/assets/4f115357-4d91-4436-bbb9-077b105380f3">

## What did you expect to happen?

The Positron logo should appear.

Related to #3997?

**Comment by petetronic** [comment]
The new `positron-icon.svg` is missing the packaged releases, but does appear in the local out folder when building locally. Investigating.

**Comment by petetronic** [comment]
It looks like it is being inlined during build optimization because it is seen as a CSS resource.

**Comment by ntluong95** [comment]
![image](https://github.com/user-attachments/assets/a079b22f-d297-4bb3-ad90-008d16bfcfc4)

May be relevant but the logo displayed during the installation is the wrong one

**Comment by petetronic** [comment]
> May be relevant but the logo displayed during the installation is the wrong one
Thanks, so those are separate bitmaps from the InnoSetup installer resources for windows. We'll separately review the artwork in the installer and can tidy that up.

**Comment by ntluong95** [comment]
![image](https://github.com/user-attachments/assets/cecfc591-d639-4e03-97e4-6ad5d6bd8719)

If you close all script, you may also see it. Is that something also relevant?

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.07.0-81](https://github.com/posit-dev/positron/releases/tag/2024.07.0-81)
OS Version(s) : Windows 11, Ubuntu 22

### Test scenario(s) 



Logo now appears

### Link(s) to TestRail test cases run or created: 

[TestRail Welcome Screen Suite](https://posit.testrail.io/index.php?/suites/view/1591&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=25893)
