### ISSUE TITLE
Open project from command line

### ISSUE THREAD

**Issue by roaldarbol** [posit-dev/positron#4049]
It would be great to be able to open a specific project from the command line, so having the `positron` CLI command. Essentially identical behaviour to `code` for VSCode. So `positron .` opens the present folder, `positron my-project` opens my-project.

**Comment by juliasilge** [comment]
You can already do this! Run this command one time:

![Screenshot 2024-07-17 at 8 32 59 AM](https://github.com/user-attachments/assets/0216b9e9-39ae-4a30-81f1-bac4927abbb6)

And then the command will be on your path. You can do `positron .` if you are in the folder you want to use as a workspace, or `positron my-project` if you are one folder up.

**Comment by roaldarbol** [comment]
Ah, cool - thanks!🥳

**Comment by drmowinckels** [comment]
WHere does Positron install to, by default?

I cant use the solution here as I have stupid IT admin rights restricting me, so I'll need to fix this manually through my bash profile.

**Comment by drmowinckels** [comment]
right, needed to do some digging, and after remembering its a clone of vscode (whose command line is `code`), I found it.

Just in case someone is looking to manually bind or alias. I have the following on my mac

```
alias positron="/Applications/Positron.app/Contents/Resources/app/bin/code"
```

**Comment by emilyriederer** [comment]
I'm just here to say thank you because I was pining for same and huzzah!
