### ISSUE TITLE
Session gets stuck when inspecting properties of a big dataloader object

### ISSUE THREAD

**Issue by Vinnish-A** [posit-dev/positron#4053]
After I create a dataloader object, whether expanding its properties in the variable bar or accessing its properties through `.` after this object will cause the session to freeze, which does not happen in other IDEs.

This is a video I recorded when the session froze.

https://github.com/user-attachments/assets/33fd99b1-2e62-43a6-a4cb-68338e68ff14

I put the cases that can be repeated into [this repository](https://github.com/Vinnish-A/bigObjectError).

**Comment by jmcphers** [comment]
The video you attached isn't playing for me, but I think this could be the same as #3628. Is that what you're seeing?

**Comment by juliasilge** [comment]
Let's track this in #3628. 👍 

If you are able to create a reproducible example that demonstrates your problem, please do add it to that issue. Thanks!
