### ISSUE TITLE
Data explorer: long tab title when View() is called at the end of a pipe chain

### ISSUE THREAD

**Issue by weverthonmachado** [posit-dev/positron#4085]
When `View()` is called at the end of a pipe chain, it opens a Data Explorer tab whose title contains the entire pipeline. If the pipeline is long enough, the new tab can easily occupy the entire editor area, and even the tab's close icon is hidden. 

Example:
```r
library(dplyr)
mtcars |> 
  select(am, cyl, disp, hp, mpg, qsec) |> 
  mutate(a = (cyl - mean(cyl))^2,
         b = (disp - mean(disp))^2,
         c = (hp - mean(hp))^2,
         d = (mpg - mean(mpg))^2,
         e = (qsec - mean(qsec))^2) |> 
  group_by(am) |> 
  summarise(a = sum(a),
            b = sum(b),
            c = sum(c),
            d = sum(d),
            e = sum(e)) |>  
  View()
```

![image](https://github.com/user-attachments/assets/3aaa1ada-a6b0-47c2-be3e-f1c463ccb44c)

RStudio limits the amount of characters shown:

![image](https://github.com/user-attachments/assets/befbd1c1-37d8-4aff-af9e-aae2f64d19e9)

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-125
    OS Version          : OSX

### Test scenario(s) 

Verified with initial filing instructions

Link(s) to TestRail test cases run or created: 
N/A
