### ISSUE TITLE
When plot pane is closed and reopened plot does not appear until positron is resized

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#4088]
## Steps to reproduce the issue:

1. Create a plot
```
import plotly.express as px
fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
fig
```
2. Close the plots pane
3. Reopen the plots pane
4. Note that plot is not visible
5. Resize positron
6. Note that plot is visible again

## What did you expect to happen?
When plot pane is reopened plot appears without needing to resize positron.

## Were there any error messages in the Output panel or Developer Tools console?
No

https://github.com/user-attachments/assets/094a5bd6-a3f9-4f0a-9af8-4532544e6798

**Comment by jthomasmock** [comment]
I've also seen somewhat similar behavior with the data explorer cc @petetronic - maybe the same issue?

**Comment by juliasilge** [comment]
This is like the problem we had with Help in #2656.

**Comment by seeM** [comment]
Strange, this was a case I definitely manually tested. Also in Positron Version: 2024.07.0 (Universal) build 85 it works as expected for me:

https://github.com/user-attachments/assets/270315ff-147e-419b-a631-4e8535f32b11

**Comment by juliasilge** [comment]
On Positron 2024.07.0 (Universal) build 85, I see the same problem that @testlabauto observes:

https://github.com/user-attachments/assets/9ff67a30-0a48-41be-a490-eb48bee275ab

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-107
    OS Version          : OSX

### Test scenario(s) 

Test scenario from original filing.

Link(s) to TestRail test cases run or created: 
N/A
