### ISSUE TITLE
Newly created positron notebooks are non-functional

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#4089]
## Steps to reproduce the issue:

1. Enable positron notebooks in settings
2. Create a new file that is a notebook
3. Click to add Code
4. Note that nothing happens
5. Check console for errors

## What did you expect to happen?
I expected a code block to be added

## Were there any error messages in the Output panel or Developer Tools console?
Yes, see screenshot.  Note that it says "No language for notebook"

<img width="2071" alt="image" src="https://github.com/user-attachments/assets/cd81bbd8-2fdf-4de0-80d1-3333eb2a1bbf">

**Comment by sharon-wang** [comment]
Likely related to: https://github.com/posit-dev/positron/issues/3492
