### ISSUE TITLE
Data explorer: Use of "Columns" confuses me

### ISSUE THREAD

**Issue by jennybc** [posit-dev/positron#4094]
I find the way "Columns" is used in the Layout dropdown menu a bit confusing. Of course, a bit of usage clears things up, but I still wonder if we should revisit the wording.

<img width="510" alt="Screenshot 2024-07-19 at 3 05 31 PM" src="https://github.com/user-attachments/assets/0a0ee6c0-d6f1-4e52-aab3-4d37add4b631">

At first I assumed that "Columns" was referring to ... well, my actual _columns_. But it's now clear that it refers to the part of the surface that describes/summarizes the columns. What about "Column summary on left"?

**Comment by ntluong95** [comment]
I think this makes sense. I was confuse like that

**Comment by wesm** [comment]
Or even "Statistics". Agree that renaming this would be good

**Comment by juliasilge** [comment]
Another option is "Summary".

**Comment by jthomasmock** [comment]
Did a small group survey, and we should rename the "Columns on Left/Right/Hidden" to "Summary on Left/Right/Hidden".

**Comment by softwarenerd** [comment]
This is addressed in https://github.com/posit-dev/positron/pull/4302.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-31
    OS Version          : OSX

### Test scenario(s) 

Viewed dropdown text

Link(s) to TestRail test cases run or created:
N/A
