### ISSUE TITLE
Data explorer: "Columns Hidden" is hard to undo

### ISSUE THREAD

**Issue by jennybc** [posit-dev/positron#4095]
## Positron Version:

Positron Version: 2024.07.0 (Universal) build 81
Code - OSS Version: 1.91.0
Commit: f1734059e27107ccf7c9c87d97202721f432c0d4
Date: 2024-07-19T03:55:17.195Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 22.6.0

## Steps to reproduce the issue:

1. View something in the Data explorer
2. Do _Layout > Columns Hidden_
3. Change your mind
4. Do _Layout > Columns Hidden_ again, expecting that to remove the checkmark and unhide the column summaries

## What did you expect to happen?

I expected clicking on this to be like a toggle, e.g. on/off. I guess you're supposed to get the summaries back by clicking on "Columns on Left" or "Columns on Right"? But I expected to toggle this and get them to reappear "wherever they were before / whatever is the default".

**Comment by jmcphers** [comment]
See also #2823. I think that there should be a toggle button for the summary panel that is near and/or replaces the panel itself.

**Comment by jennybc** [comment]
> I think that there should be a toggle button for the summary panel that is near and/or replaces the panel itself.

Also a very good solution!

**Comment by jthomasmock** [comment]
Yah I think we'll end up with something close to: https://github.com/posit-dev/positron/issues/2823#issuecomment-2125530927 and drag to close/open

**Comment by softwarenerd** [comment]
This issue is addressed in https://github.com/posit-dev/positron/pull/4673. In this PR, the **Columns Hidden** layout feature has been removed.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-55
    OS Version          : OSX

### Test scenario(s) 

Feature has been removed.

Link(s) to TestRail test cases run or created:
