### ISSUE TITLE
Most all smoke tests failing

### ISSUE THREAD

**Issue by jonvanausdeln** [posit-dev/positron#4098]
Most all smoke tests are failing after the latest python extension upstream merge. https://github.com/posit-dev/positron/pull/3790

see
https://github.com/posit-dev/positron/actions/runs/10015806724/job/27687808295

It appears to be some change that makes `waitForReady()` hang in the console.

**Comment by jonvanausdeln** [comment]
Here is the fail
```
           "before all" hook for "Create a new R file from the Welcome page":
     Error: Timeout: get elements '.console-instance[style*="z-index: auto"] .runtime-items span' after 20 seconds.
```

**Comment by jonvanausdeln** [comment]
I was able to step through and found that this line throws the timeout error.

https://github.com/posit-dev/positron/blob/af322f25da6da36c9d9e3c2bcd9b14f87950330f/test/automation/src/positron/positronConsole.ts#L131

**Comment by testlabauto** [comment]
https://github.com/posit-dev/positron/pull/4101/files
