### ISSUE TITLE
Search in the console

### ISSUE THREAD

**Issue by ryanzomorrodi** [posit-dev/positron#4099]
Sometimes I print a bunch of text to the console so that I can easily search it. It would be nice if Control - F popped up a search bar when the console is active, as it does within the terminal.

![image](https://github.com/user-attachments/assets/f63e397e-801b-4dca-869b-4bc4e99e5a5d)

Thank you!

**Comment by juliasilge** [comment]
I believe this is the same as https://github.com/posit-dev/positron/issues/2136. Want to take a look and see if you have anything additional to add?
