### ISSUE TITLE
Lint `.test.ts` files for usage of mocha exclusive tests `.only`

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#4110]
## Background

- `.only` is helpful in running specific test suites to save time, instead of running all tests at once
- `.only` is commonly used during local dev when writing tests, such as smoke tests
- it's easy to accidentally commit test changes with `.only`, since we don't currently have precommit checks or a rule in our eslint settings to flag the usage of `.only`
- running tests in CI with `.only` can result in other intended tests to **not** run
- if tests are committed to the `main` branch with `.only`, our full test suites may only run a subset of the tests as marked by `.only`
- sometimes we deliberately commit `.only` to run a subset of tests in CI
- it's not a difficult fix to remove instances of `.only` if accidentally committed, but it would be nice to have a local dev safety net/reminder

## Solution

- Add linting for `mocha` `.only` usage in staged `.test.ts` files, failing the hygiene/pre-commit hook if `.only` is encountered
- As part of our existing hygiene/precommit hook, devs can use `--no-verify` to skip the hooks as needed
- Don't apply general mocha eslint linting rules (plugin `plugin:mocha/recommended`), as we don't currently adhere to such linting rules (there are ✨a LOT✨ of red squiggles!)
- Add the `mocha/no-exclusive-tests` as an error to `.eslintrc.json`, so that `.only` can be highlighted in the editor, as long as the ESLint extension is installed

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : N/A
    OS Version          : OSX

### Test scenario(s) 

Works great!  Thanks for adding.

Link(s) to TestRail test cases run or created:
