### ISSUE TITLE
Make it easier to re-expand right side pane

### ISSUE THREAD

**Issue by rjake** [posit-dev/positron#4112]
I notice that when I change the width of the Variables / Help / Plot pane all the way to the right, the width completely collapses and the only way to re-expand the pane is to go to View > Variables. 

Could the right pane collapse its width into something clickable like the Explorer pane collapses to the left (below)? 
I couldn't find this as an issue and hope it isn't a duplicate.

![image](https://github.com/user-attachments/assets/d859cf8f-6000-4128-8565-87f15d291481)

**Comment by juliasilge** [comment]
I _think_ this is the same as #562; that pane that is on the right by default is called the "secondary side bar". Want to take a look and see if you have anything to add there?

As a workaround for now, what I find to be the fastest to get it back is "Toggle Secondary Side Bar Visibility" from the command palette:

![Screenshot 2024-07-22 at 9 38 14 AM](https://github.com/user-attachments/assets/a0cb5408-79fd-4cd1-aa22-df55401f235b)

**Comment by rjake** [comment]
Thank you, @juliasilge, that is the same issue and I will close this one. By using `Ctrl + Alt + B` I noticed that this icon changed it's appearance and is also a shortcut. I put this info in #562. 

<img  alt="toggle sidebar icon at top of screen" src="https://github.com/user-attachments/assets/0d81adee-9ff5-4a56-95c6-e71b149042fc">
