### ISSUE TITLE
Rstudio styled Outlines in Positron

### ISSUE THREAD

**Issue by ran-codes** [posit-dev/positron#4114]
One of my favorite features of Rstudio that is not in VS-code and (so far I have nto found it  in Positron) is the ergonomic code outline syntax and display.

# Rstudio
![image](https://github.com/user-attachments/assets/69c1fe7e-cb13-4b5b-9d3a-e9bfe7771749)

**IT WOULD BE GREAT IF POSITRON HAD THIS!**

Thank you for all the great work so far.

**Comment by jmcphers** [comment]
Positron does have this! In the File Explorer tab, open the Outline view on the bottom. 

<img width="832" alt="image" src="https://github.com/user-attachments/assets/f3cf8eec-e590-4503-afb6-f772a6f99c20">

You can also drag this view over to another pane if you want an RStudio-like layout.

<img width="479" alt="image" src="https://github.com/user-attachments/assets/53b8a95f-46ce-4453-80df-501982558827">

Does that do what you want?

**Comment by ran-codes** [comment]
Perfect! Works for me in .qmd files.

But I don't see this in regular .R files?
![image](https://github.com/user-attachments/assets/a34d0209-52c8-428c-b139-97371a5b16e9)

**Comment by juliasilge** [comment]
I believe you are noticing #3822. Please add any additional info there!

**Comment by juliasilge** [comment]
Let us know if you have any further questions! 🙌
