### ISSUE TITLE
Variable Pane doesn't know how to format formulas

### ISSUE THREAD

**Issue by strengejacke** [posit-dev/positron#4119]
## Positron Version:

Positron Version: 2024.07.0 (system setup) build 2024.07.0-85
Code - OSS Version: 1.91.0
Commit: 9dfa34e1eb5a42ebbd1c1d17b55bef7e7bf0bf1f
Date: 2024-07-22T03:21:08.974Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

## Steps to reproduce the issue:

Run following code, step-by-step:

```r
ff <- "mo(gear)"
ff <- stats::as.formula(paste0("~", ff))
ff
```

First, the value of `ff` appears in the Variables view. After converting to formula, the value changes to `??`.

https://github.com/user-attachments/assets/6b6d323a-6511-4b01-9134-750a9f03e957

## What did you expect to happen?

The value of `ff` changes to `~mo(gear)`.

## Were there any error messages in the Output panel or Developer Tools console?

No.

**Comment by juliasilge** [comment]
### Notes for when we look at this:

From my perspective the main problem is that formulas and other objects like quosures have length > 1 but `base::format()` results of length 1:

``` r
x <- formula(y ~ a + b + c)
length(x)
#> [1] 3
length(base::format(x))
#> [1] 1
```

<sup>Created on 2024-08-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-2
    OS Version          : OSX

### Test scenario(s) 

Validated with filing instructions

Link(s) to TestRail test cases run or created:
