### ISSUE TITLE
Issue report form dropdowns should be updated for Positron

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#4123]
## Positron Version:
Positron Version: 2024.07.0 (Universal) build 67
Code - OSS Version: 1.91.0
Commit: 58e22e191273c6fcb403c458ddb3088b0b80dcd0
Date: 2024-07-18T04:44:17.582Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

## Steps to reproduce the issue:

1. Click on Help > Report Issue in the native menu bar or run `Help: Report Issue...` via the Command Prompt

<img width="914" src="https://github.com/user-attachments/assets/a73fc78e-30f1-41f1-9e9d-805091f98b10">

2. Click on `For *`/`Select source` dropdown

3. See that the dropdown options contain "Visual Studio Code" and "A VS Code extension" instead of "Positron" and "An OpenVSX extension"

<img width="711" src="https://github.com/user-attachments/assets/52e25f7c-61d4-4bc6-9b46-2914fd4d66ab">

## What did you expect to happen?
I expected the options to say "Positron" and "An OpenVSX extension" instead of "Visual Studio Code" and "A VS Code extension".

I think this can be fixed pretty easily by updating `setSourceOptions()` in src/vs/workbench/contrib/issue/electron-sandbox/issueReporterService.ts and src/vs/workbench/contrib/issue/browser/issue.ts with the expected strings.

Alternatively, instead of providing the issue report form, we could simply open https://github.com/posit-dev/positron/issues/new/choose or https://github.com/posit-dev/positron/discussions in the user's external browser, or display these links in the modal instead of providing a form?

## Were there any error messages in the output or Developer Tools console?
N/A

**Comment by juliasilge** [comment]
I updated this in #3358 (and again before that in #2454) but apparently not so much!

`setSourceOptions()` is already updated here and that fixed the strings as of #3358:

https://github.com/posit-dev/positron/blob/0e7a2fbedaad48768091c667e5ac8b10ae9cec00/src/vs/workbench/contrib/issue/electron-sandbox/issueReporterService.ts#L796-L798

Strings are not yet updated in `/browser/issue.ts` FWIW.

**Comment by juliasilge** [comment]
Something else that has changed is that "Loading data..." button:

![Screenshot 2024-07-23 at 10 17 09 AM](https://github.com/user-attachments/assets/bb82677a-c1cd-4cff-99d7-cdc15271dff0)

It is trying to search issues but of course we've turned all that off. 🤔

**Comment by juliasilge** [comment]
We merged #3358 on June 5 and then we have since merged 1.90 (May 2024) and 1.91 (June 2024) from VS Code. A [fair amount of stuff changed for the issue reporter](https://github.com/microsoft/vscode/pulls?q=is:pr+issue+reporter+is:closed), especially for May 2024.

**Comment by juliasilge** [comment]
Ah OK, the "Loading data..." was because my SSH key for Positron had not been authenticated with SSO today. 🙈

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-97
    OS Version          : OSX

### Test scenario(s) 

Report issue now refers to Positron and not VS Code.

Link(s) to TestRail test cases run or created: 
N/A
