### ISSUE TITLE
Add smoke tests for Top Action Bar Interpreter Dropdown

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#4124]
## Background

The [StartInterpreter](https://github.com/posit-dev/positron/blob/main/test/automation/src/positron/positronStartInterpreter.ts) automation class includes methods to interact with the Interpreter Dropdown in the smoke tests.

#### Interpreter Dropdown
<img width="389" alt="image" src="https://github.com/user-attachments/assets/9d622cf0-a053-4204-9e26-e5ad08d7b972">

`getSelectedInterpreterInfo()` was added to the automation class in [Project Wizard Smoke Tests: Python Project existing interpreter ipykernel tests #3951](https://github.com/posit-dev/positron/pull/3951), which included some modifications to the existing methods in that class.

However, no existing smoke tests seemed to be using the `StartInterpreter` automation class. Since this is a commonly used component, it would be good to have smoke tests to catch any possible regressions. We can add new smoke tests for this class alongside the [TopActionBar tests](https://github.com/posit-dev/positron/blob/main/test/smoke/src/areas/positron/top-action-bar/top-action-bar.test.ts).

## Possible test cases
- Start a primary interpreter (interpreters that show at the top-level in the dropdown)
- Restart an active interpreter
- Shutdown an active interpreter
- Start a secondary interpreter (interpreters that show when you click the `...` on a primary interpreter)
- Start interpreters for multiple languages
- Switch the active console interpreter
- Shutdown all active interpreters
- An interpreter selected via the Command Prompt is reflected correctly in the interpreter dropdown (e.g. Python: Select Interpreter)

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-31
    OS Version          : OSX

### Test scenario(s) 

Reviewed tests, ran tests, tests passing in CI.

Link(s) to TestRail test cases run or created:
N/A
