### ISSUE TITLE
Smoketests for ANSI output in the console

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#4138]
- [x] ANSI with cli/crayon
- [x] Hyperlinks (as in runnable R code, opening a file)

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : main on 7/26/24
    OS Version          : Ubuntu

### Test scenario(s) 

All these new tests passed in CI run against main.

Link(s) to TestRail test cases run or created: 
N/A
