### ISSUE TITLE
Enable "Locker" or similar GH action

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#4143]
The "Locker" action is not currently running:

https://github.com/posit-dev/positron/actions/workflows/locker.yml

It would be helpful to get this or a similar action running so we can lock older issues and get folks to open new discussions, issues, etc.

Info to check out:
https://github.com/microsoft/vscode-github-triage-actions?tab=readme-ov-file#locker

I have not yet discovered what is locking our older PRs ([see an example](https://github.com/posit-dev/positron/pull/3933)) but not our older issues.

**Comment by juliasilge** [comment]
Still not having a ton of luck finding out what is locking our PRs but not our issues. I thought maybe it was that we had "Automatically delete head branches" turned on for the repo, but I tested this out on pins by:

- Turning on "Automatically delete head branches"
- Merging a PR: https://github.com/rstudio/pins-r/pull/836

Notice that it deleted but it did not lock. I'll spend a bit more time on this but maybe in the end we just add something else that locks older issues without finding out what is happening to PRs, at least for now.

**Comment by juliasilge** [comment]
I found it! 🙌 

It's the CLA assistant: https://github.com/posit-dev/cla-assistant-github-action?tab=readme-ov-file#2-pull-request-event-triggers-cla-workflow

Specifically notice:

> When the CLA workflow is triggered on pull request closed event, it will lock the Pull Request conversation after the Pull Request merge so that the contributors cannot modify or delete the signatures (Pull Request comment) later. This feature is optional.

I think we probably want to keep this feature, and when I add a new GH action, we will just apply it to issues.

**Comment by jonvanausdeln** [comment]
Need to wait to verify this until the action has run a few times.

**Comment by juliasilge** [comment]
This search will find issues we successfully locked:
https://github.com/search?q=repo:posit-dev/positron%20is:issue%20is:locked&type=issues

After running for one day, there are 50 locked, as expected; it does 50 per day.

**Comment by jonvanausdeln** [comment]
Action ran last night, and locked as expected!
