### ISSUE TITLE
Python interpreter sometimes failed to start

### ISSUE THREAD

**Issue by ntluong95** [posit-dev/positron#4159]
## System details:

Positron and OS details:

Positron Version: 2024.07.0 (system setup) build 2024.07.0-100
Code - OSS Version: 1.91.0
Commit: 9d858046178da1bae0c31309db1a8d8f5ebc8b28
Date: 2024-07-26T03:19:27.206Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621

Interpreter details:

Python 3.12.4 

## Describe the issue:

The Python interpreter sometimes fails to start. The error is as below. I am not sure if the problem is from my end. But it happened some days ago when I clearing cache in Temp folder (I am using Windows)

![image](https://github.com/user-attachments/assets/61ea8abe-e705-4894-b5ee-2d7bb1b66bf8)

## Steps to reproduce the issue:

1. Start Positron

## Expected or desired behavior:
The Python console load successfully

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Output Python
![image](https://github.com/user-attachments/assets/0b469adc-6e7a-4754-8aa4-7864dc0e33f1)

Console log
![image](https://github.com/user-attachments/assets/37b07a32-9445-4558-9082-98c730030190)

**Comment by juliasilge** [comment]
This looks to be the same as #3779 ("socket connection timed out" when starting Python on Windows). Can you add the details you observed there? 

I especially note that you say:

> But it happened some days ago when I clearing cache in Temp folder

which may be a clue. 👀

**Comment by ntluong95** [comment]
I clear the Temp folder as below. In addition, I also go directly to folder `C:\Users\ngulu864\AppData\Local\Temp` and delete everything there

![image](https://github.com/user-attachments/assets/217c7ebd-f526-42d4-b80f-923024b26c0d)

**Comment by juliasilge** [comment]
Thank you for adding your additional details to https://github.com/posit-dev/positron/issues/3779!
