### ISSUE TITLE
using R and data table, in autocomplete selection the fields paste in the editor with quotes

### ISSUE THREAD

**Issue by pfv07** [posit-dev/positron#4162]
hi, 
using R and data.table package, is possible to disable in the auto complete, when select a field the add of  quotes in the editor

tks !!!

## System details:

Positron and OS details:

Interpreter details:

## Steps to reproduce the issue:

1.
2.

**Comment by jmcphers** [comment]
Does this issue capture what you're seeing? https://github.com/posit-dev/positron/issues/3140

**Comment by pfv07** [comment]
yes, i don't know if this is a vscode functionality or positron configuration?
tks for you comments!!

**Comment by jmcphers** [comment]
It's a Positron thing! Tracked in #3140.
