### ISSUE TITLE
Comment folding for region has wrong syntax

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#4163]
I believe our folding needs to drop the `//` from the regex to allow the region feature to work. That's more of a javascript/typescript comment syntax.

https://github.com/posit-dev/positron/blob/3d8649a40f6613645a4d2ac8a55c1fb21d5ee851/extensions/positron-r/language-configuration/r-language-configuration.json#L29-L34

Compare it to Python:

https://github.com/posit-dev/positron/blob/3d8649a40f6613645a4d2ac8a55c1fb21d5ee851/extensions/python/language-configuration.json#L43-L48

In Python:
![image](https://github.com/user-attachments/assets/095e3d74-33ad-4a0d-b05f-4543fc30ed7d)

In R:
<img width="608" alt="image" src="https://github.com/user-attachments/assets/42e86f02-89f2-4bf3-8b14-f779fc314434">

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-125
    OS Version          : OSX

### Test scenario(s) 

Validated with example on the attached PR

Link(s) to TestRail test cases run or created: 
N/A
