### ISSUE TITLE
R syntax color highlighting in the Positron console

### ISSUE THREAD

**Issue by statzhero** [posit-dev/positron#4167]
I'm sure this is somewhat trivial but how do you get code syntax / message color highlighting in the console? When I looked for help, VS Code suggests installing the R extension, but as I understand it this is not recommended for Positron.

![image](https://github.com/user-attachments/assets/a08e7563-1b82-4f36-ab52-138fea6857c5)

```
Positron Version: 2024.07.0 (Universal) build 85
Code - OSS Version: 1.91.0
Commit: 9dfa34e1eb5a42ebbd1c1d17b55bef7e7bf0bf1f
Date: 2024-07-22T04:48:59.704Z (5 days ago)
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.4.0
```

**Comment by strengejacke** [comment]
Hm, I have syntax highlighting by default:

![image](https://github.com/user-attachments/assets/59f4b1ac-2cfd-4ac5-b028-393c50c5e436)

![image](https://github.com/user-attachments/assets/e9c292cb-bfc5-4861-8e0b-23cbbac3a377)

# Setup

Positron Version: 2024.07.0 (system setup) build 2024.07.0-100
Code - OSS Version: 1.91.0
Commit: 9d858046178da1bae0c31309db1a8d8f5ebc8b28
Date: 2024-07-26T03:19:27.206Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by statzhero** [comment]
In the console? Maybe a setting got screwed up but I don’t know what to check. On Jul 28, 2024, at 17:59, Daniel ***@***.***> wrote:﻿
Hm, I have syntax highlighting by default:
image.png (view on web)
image.png (view on web)
Setup
Positron Version: 2024.07.0 (system setup) build 2024.07.0-100
Code - OSS Version: 1.91.0
Commit: 9d85804
Date: 2024-07-26T03:19:27.206Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by strengejacke** [comment]
> In the console? 

Yes, that was a screenshot from the console.

**Comment by juliasilge** [comment]
As of today, you get syntax highlighting in the console _as you type_ but already executed code does not have any syntax highlighting treatment:

https://github.com/user-attachments/assets/76b2d6cd-7d0e-46fd-8f4d-6785055e0b65

In #243 we are tracking adding some treatment for code you've already run.

@statzhero let us know if this doesn't answer your question!

**Comment by statzhero** [comment]
Aha, yes all explained!
