### ISSUE TITLE
Interactive matplotlib plots

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#4173]
We should support matplotlib's interactive mode i.e. [`ipympl`](https://matplotlib.org/ipympl/).

For example, this should produce an interactive plot:

```python
%matplotlib ipympl
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()


x = np.linspace(0, 2*np.pi, 100)
y = np.sin(3*x)
ax.plot(x, y)
```

Currently it produces a static low-res plot:

<img width="347" alt="image" src="https://github.com/user-attachments/assets/40a336d9-70c9-4f60-a58f-2fcc25165bc0">

Sub-issue of https://github.com/posit-dev/positron/issues/1924.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-24
    OS Version          : OSX

### Test scenario(s) 

Console run of:

# this works in the console
# run this first in the console:
# %matplotlib ipympl

import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()


x = np.linspace(0, 2*np.pi, 100)
y = np.sin(3*x)
ax.plot(x, y)

Link(s) to TestRail test cases run or created:
N/A
