### ISSUE TITLE
Python web mapping packages not working (leafmap, geemap)

### ISSUE THREAD

**Issue by Cidree** [posit-dev/positron#4181]
## System details:

Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

Interpreter details:

Python 3.12.4

## Describe the issue:

Some Python packages for web mapping are not correctly showing the widgets.

## Steps to reproduce the issue:

Using a Python script.

### leafmap

```python
## Import package
import leafmap

## Create and display the map
m = leafmap.Map()
m
```

The result is the text: `Map(center=[20, 0], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_text…`, but no map is shown.

### geemap

Note: needs an API token.

```python
## Import packages
import ee
import geemap

## Authenticate (needed for API token)
# ee.Authenticate()

## Initialize Earth Engine
ee.Initialize()

## Create and display the map
m = geemap.Map()
m
```

The result is the text: `Map(center=[0, 0], controls=(WidgetControl(options=['position', 'transparent_bg'], widget=SearchDataGUI(childr…`, but no map is shown.

### leafmap

![image](https://github.com/user-attachments/assets/27009049-ceb0-4244-a01f-b615f171633d)

### geemap

![image](https://github.com/user-attachments/assets/96566420-2ca6-44ac-a27b-c429ad887be4)

## Were there any error messages in the UI, Output panel, or Developer Tools console?

I didn't see anything.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-24
    OS Version          : OSX

### Test scenario(s) 

Works in console:

import leafmap
m = leafmap.Map()
m

Link(s) to TestRail test cases run or created:
N/A
