### ISSUE TITLE
Toggle line comment ctr shift C opens cmd.exe

### ISSUE THREAD

**Issue by phamdn** [posit-dev/positron#4194]
## System details:

Positron and OS details:

Positron Version: 2024.07.0 (system setup) build 2024.07.0-113
Code - OSS Version: 1.91.0
Commit: fd367e42c24e442c2e2dec07f1c5e8098f965d76
Date: 2024-07-30T03:18:54.470Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

Interpreter details:

R 4.3.3 

## Describe the issue:

Default Toggle line comment shortcut opens Command prompt

**Comment by phamdn** [comment]
Thank you very much. Enabling that fix my problem.

**Comment by jmcphers** [comment]
Great, glad that's all it was!
