### ISSUE TITLE
Data Explorer: Clicking to open the viewer doesn't bring focus back

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#4197]
### Discussed in https://github.com/posit-dev/positron/discussions/4191

<div type='discussions-op-text'>

<sup>Originally posted by **fretwurst** July 31, 2024</sup>
When I click on the table icon in VARIABLES for a loaded dataset, the data viewer opens as expected. However, when I then work on other files (data viewer open in the background) and then click on the table icon again, nothing happens—the data viewer does not open the same data in a new viewer (as it does with View(data)) or bring the already open data viewer to the foreground like in R-Studio. 

[Imagine that I click on the table icon. You can just barely see the tab for Data in the top right next to the Preview icon. If I open a qmd file further to the left, you can't even see that, and nothing happens when you click on the table icon.]
<img width="1512" alt="Bildschirmfoto 2024-07-31 um 10 37 36" src="https://github.com/user-attachments/assets/e5e5549a-5c22-4f8b-92f4-6ad09be22b48">

</div>

Clicking a second time in the icon shuld get focus back to the data editor.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.08.0-5](https://github.com/posit-dev/positron/releases/tag/2024.08.0-5)
OS Version(s) : Windows

### Test scenario(s) 



Passed in automation and manually

### Link(s) to TestRail test cases run or created: 
https://posit.testrail.io/index.php?/tests/view/759326
