### ISSUE TITLE
`input()` function in Jupyter Notebook does not provide place to give input

### ISSUE THREAD

**Issue by isabelizimm** [posit-dev/positron#4199]
### Discussed in https://github.com/posit-dev/positron/discussions/4185

<div type='discussions-op-text'>

<sup>Originally posted by **khavylo** July 30, 2024</sup>
How to get input in Jupyter Notebook on IDE Positron? I try to run input() function to get input from pop up textfield, but it goes in infinte loop.</div>

---

(Copy/pasting extra context)

if you run `input()` in a notebook in VSCode, there will be a popup at the top of the notebook to accept input. (Note `input()` does work in the console, if that is a helpful place to go for a workaround for now.)

<img width="1181" alt="Screenshot 2024-07-31 at 3 23 09 PM" src="https://github.com/user-attachments/assets/794536de-8071-489a-8558-d971c3845880">

In Positron, this does not appear, nor any other place to type in the `input()`.

<img width="1213" alt="Screenshot 2024-07-31 at 3 24 02 PM" src="https://github.com/user-attachments/assets/3568b763-a1fe-40a7-bcce-cedfbba12800">

**Comment by midleman** [comment]
### Verified Fixed
Positron Version(s) : [2024.11.0-49](https://github.com/posit-dev/positron-builds/releases/tag/2024.11.0-49)
OS Version(s) : MacOS

### Test scenario(s) 

Confirmed both Python and R are able to accept inputs in notebooks.
![Image](https://github.com/user-attachments/assets/7591041a-f1fc-492f-a794-147a3f082200)
![Image](https://github.com/user-attachments/assets/c91fadb0-9826-48ae-8158-680b2a4d5c03)


### Link(s) to TestRail test cases run or created:
