### ISSUE TITLE
Custom size dialog window in the plot pane should accept new values after hitting "enter"

### ISSUE THREAD

**Issue by strengejacke** [posit-dev/positron#4203]
## System details:

Positron and OS details:

Positron Version: 2024.07.0 (system setup) build 2024.07.0-125
Code - OSS Version: 1.91.0
Commit: cae4905332a0f41a6233e196b48a6679b832000a
Date: 2024-07-31T22:26:02.970Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

Interpreter details:

R 4.4.1

## Describe the issue:

When I change the custom size for plots in the plot pane, I need to click with the mouse on the OK button to accept. Would be nice if the "enter" key would also trigger the OK button.

**Comment by sharon-wang** [comment]
This is closely related to https://github.com/posit-dev/positron/issues/4203 and any other custom modals in Positron that have a default button (such as `OK`).

**Comment by strengejacke** [comment]
You mean #3491?

**Comment by sharon-wang** [comment]
Oops, yes that's what I meant :)

@juliasilge shall we keep just one of #3491 or #4203 open and transfer the labels and milestone as appropriate?

**Comment by juliasilge** [comment]
Let's keep them both open so we can validate the fixes for both cases. I will update so both are in 2024.09.0 Pre-Release.

**Comment by softwarenerd** [comment]
This issue is addressed in https://github.com/posit-dev/positron/pull/4739
