### ISSUE TITLE
Allow pan and zoom on dynamic plots

### ISSUE THREAD

**Issue by timtmok** [posit-dev/positron#4210]
Setting a custom size on a plot can render a plot that is difficult to view when it is scaled to fit the Plots pane. This is similar to a static plot that has a defined resolution and was enhanced to scale the image. Showing a high resolution image allows the image to be panned by dragging the image or scrolling.

See https://github.com/posit-dev/positron/issues/2330

**Comment by timtmok** [comment]
https://github.com/posit-dev/positron/tree/feature%2Fdynamic-plot-zoom Some initial work done here that reuses the existing scrollable component.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-41
    OS Version          : OSX

### Test scenario(s) 

```
import pandas as pd
import matplotlib.pyplot as plt
data_dict = {'name': ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'],
				'age': [20, 20, 21, 20, 21, 20],
				'math_marks': [100, 90, 91, 98, 92, 95],
				'physics_marks': [90, 100, 91, 92, 98, 95],
				'chem_marks': [93, 89, 99, 92, 94, 92]
				}

df = pd.DataFrame(data_dict)

df.plot(kind='scatter',
		x='math_marks',
		y='physics_marks',
		color='red')

plt.title('ScatterPlot')
plt.show()
```

Can pan around post zoom with the above.

Link(s) to TestRail test cases run or created:
N/A
