### ISSUE TITLE
R 4.4.1 

### ISSUE THREAD

**Issue by alexandergz1983** [posit-dev/positron#4216]
R 4.4.1 starting.
R 4.4.1 failed to start up (exit code 134)
Error del proceso del terminal "/Applications/Positron.app/Contents/Resources/app/extensions/jupyter-adapter/resources/kernel-wrapper.sh '/var/folders/6s/c4l75z456lvc6f7lcy342nbm0000gn/T/kernel-fhjxAM/kernel.log', '/Applications/Positron.app/Contents/Resources/app/extensions/positron-r/resources/ark/ark', '--connection_file', '/var/folders/6s/c4l75z456lvc6f7lcy342nbm0000gn/T/kernel-fhjxAM/connection.json', '--log', '/var/folders/6s/c4l75z456lvc6f7lcy342nbm0000gn/T/kernel-fhjxAM/kernel.log', '--startup-file', '/Applications/Positron.app/Contents/Resources/app/extensions/positron-r/resources/scripts/startup.R', '--session-mode', 'console', '--', '--interactive', '--no-restore-data'" al iniciarse (código de salida: 134).

## Steps to reproduce the issue:

1.
2.

**Comment by jennybc** [comment]
Assuming this version of R launches successfully in some other context, can you show me the output of `sessionInfo()`?

**Comment by petetronic** [comment]
@alexandergz1983 is it possible you have an architecture mismatch between x86_64 and ARM? See https://github.com/posit-dev/positron/issues/3070

**Comment by jennybc** [comment]
Yeah ☝️ is what I'm probing for via `sessionInfo()`.

**Comment by alexandergz1983** [comment]
The features of my Mac are:
Nombre del modelo:	MacBook Pro
  Identificador del modelo:	MacBookPro11,3
  Nombre del procesador:	Intel Core i7 de cuatro núcleos
  Velocidad del procesador:	2,8 GHz
  Cantidad de procesadores:	1
  Cantidad total de núcleos:	4

This is the error in question:
<img width="1440" alt="Captura de Pantalla 2024-08-04 a la(s) 10 39 57" src="https://github.com/user-attachments/assets/563f6b97-6cc1-49b9-b974-abe8c803f8a0">

R does not let itself be activated
 Rstudio loads R fine
<img width="1440" alt="Captura de Pantalla 2024-08-04 a la(s) 10 44 21" src="https://github.com/user-attachments/assets/1ca42ff0-87b0-4e5a-b24f-19bf30714dfa">

**Comment by DavisVaughan** [comment]
darwin20 is Big Sur, which is the macOS version that added arm64, so this is likely an arm64 machine.

@alexandergz1983 we currently have an issue where an x86_64 version of R won't work on an arm64 Mac.

If possible, you should really try and get the "standard" arm64 version of R for your machine. That should work with Positron and will also run _much_ faster in general.

On this page click
- `Download R for macOS`
- Download `R-4.4.1-arm64.pkg` (i.e. NOT the x86_64 one)

**Comment by DavisVaughan** [comment]
Although

```
Identificador del modelo: MacBookPro11,3
```

would correspond to a 2013 mac (https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i7-2.3-15-dual-graphics-late-2013-retina-display-specs.html) so maybe it isn't an architecture issue like we thought?

**Comment by alexandergz1983** [comment]
> darwin20 es Big Sur, que es la versión de macOS que agregó arm64, por lo que es probable que sea una máquina arm64.
> 
> @alexandergz1983Actualmente tenemos un problema en el que una versión x86_64 de R no funciona en una Mac arm64 ( #3070 ).
> 
> Si es posible, deberías intentar conseguir la versión arm64 "estándar" de R para tu máquina. Debería funcionar con Positron y, en general, también funcionará _mucho más rápido._
> 
> En esta página haga clic
> 
> * `Download R for macOS`
> * Descargar `R-4.4.1-arm64.pkg`(es decir, NO el x86_64)

I can't install R-4.4.1-arm64.pkg, it's not supported

**Comment by jmcphers** [comment]
MacOS Big Sur is no longer supported by Apple. It is likely that there's something we're doing in the R kernel that needs a newer version of macOS.

@alexandergz1983 Are you able to update macOS on your machine to a supported release?

**Comment by danieltomasz** [comment]
Macbooks from 2013/2014 aren't supported by the recent MacOS releases
