### ISSUE TITLE
Polars: panic, found compressed page in the middle of the pages

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#4218]
#### Positron and OS details:

Ubuntu-latest
Main branch around Aug 2nd

#### Interpreter details:

Python 3.10.12

## Describe the issue:
<img width="1142" alt="image" src="https://github.com/user-attachments/assets/82f94d1a-4e03-4aac-b852-b3d37c8921b3">

[exthost.log](https://github.com/user-attachments/files/16471846/exthost.log)

[Python.log](https://github.com/user-attachments/files/16471849/Python.log)

[Console Python 3.10.12 (Global).log](https://github.com/user-attachments/files/16471850/Console.Python.3.10.12.Global.log)

## Steps to reproduce the issue:

1. This happened during a CI run
2. polars.read_parquet on https://github.com/posit-dev/qa-example-content/blob/main/data-files/100x100/100x100.parquet

## Expected or desired behavior:
Parquet read happens without error

## Were there any error messages in the UI, Output panel, or Developer Tools console?
See logs above

**Comment by testlabauto** [comment]
I believe this is an issue with:
polars 1.4.0

**Comment by wesm** [comment]
Appears that polars yanked 1.4.0 because of Parquet regressions https://pypi.org/project/polars/#history so maybe 1.4.1 is ok now

**Comment by kmcentush** [comment]
Can confirm that this issue still persists in 1.4.1

**Comment by wesm** [comment]
Does someone want to file an upstream report in polars? This seems pretty serious

**Comment by kmcentush** [comment]
Will do - I found this issue and blindly assumed it was already in the `polars` repo.

**Comment by jlang-311** [comment]
@testlabauto Polars has closed their ticket and their new release should be available to retest this issue.

**Comment by testlabauto** [comment]
Looks good now.  Unpinned.
