### ISSUE TITLE
Display of Quarto Version not updated

### ISSUE THREAD

**Issue by Steinthal** [posit-dev/positron#4230]
#### Positron and OS details:

Version: Positron Version: 2024.07.0 (Universal) build 125
Code - OSS Version: 1.91.0
Commit: cae4905332a0f41a6233e196b48a6679b832000a
Date: 2024-08-01T00:27:06.019Z
Commit: 29.4.0
Datum: 122.0.6261.156
Electron: 20.9.0
ElectronBuildId: 12.2.281.27-electron.0
Chromium: Darwin arm64 24.1.0
Node.js: undefined
V8: undefined
Betriebssystem: undefined

#### Interpreter details:

- n/a

## Describe the issue:

- Positron displays the "used" Quarto version in the left part of the status bar.
- However, Positron only updates the displayed version at launch time.
- Quarto can be updated independently from Positron.
- The displayed Quarto version is not the correct one if Positron is not restarted after a Quarto update.

## Steps to reproduce the issue:

- n/a

## Expected or desired behavior:

Positron should update the displayed Quarto version when a change is detected, e.g. when rendering a file

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No

**Comment by juliasilge** [comment]
This functionality is provided by the Quarto extension, and they are tracking improvements in https://github.com/quarto-dev/quarto/issues/487. Want to chime in over there, or add a 👍 to express your interest?
