### ISSUE TITLE
Quarto: 'Run [chunks] above' does not work reliably

### ISSUE THREAD

**Issue by madschnun461** [posit-dev/positron#4231]
## Describe the issue:

I’m working in a Quarto file with R chunks. Rendering works fine; all commands run without any errors. However, while working in the Quarto file, the ‘run above’ functionality does not work properly; chunks are not executed from the beginning or in the correct order, leading to errors.

I have no issues with this function for the same Quarto file when working in RStudio.

Quarto version: 1.5.56 (also had the issue with the prior version)

**Comment by DavisVaughan** [comment]
It's helpful to know about this, because it makes me think the problem isn't in the Statement Range provider code. This now smells like an issue in our code execution queue system

**Comment by juliasilge** [comment]
We'll be tracking further in #4068. Thanks!

**Comment by DavisVaughan** [comment]
@lionel- and I have been investigating this and it turns out to be a separate issue from #4068 and we are going to do a Quarto PR to resolve it.

**Comment by madschnun461** [comment]
Many thanks for this! Greatly appreciated!

**Comment by DavisVaughan** [comment]
Quarto PR has been merged, we need a Quarto release now https://github.com/quarto-dev/quarto/pull/510

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 
    OS Version          : OSX

### Test scenario(s) 

Run above from the bottom of the following works as expected:

---
title: "Untitled"
format: html
---


```{r}
library(tidyverse)
library(phyloseq)
library(decontam)
```


```{r}
x <- 1
```

```{r}
y <- x
```

```{r}
z <- y
```

```{r}
a <- z
```


```{r}

```

Link(s) to TestRail test cases run or created:
