### ISSUE TITLE
Support "Save" and "Help" buttons in Bokeh plots

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#4235]
## Steps to reproduce the issue:

1. In a console or notebook, create a Bokeh plot e.g:

    ```py
    from bokeh.plotting import figure, show
    p = figure(title="Simple line example", x_axis_label='x', y_axis_label='y')
    p.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], legend_label="Temp.", line_width=2)
    show(p)
    ```
2. Click the "Save" button. Nothing happens.
    <img width="96" alt="image" src="https://github.com/user-attachments/assets/ef3d0c02-687d-4e79-9f3c-eb5dfec9dd7d">
3. Click the "Help" button. Nothing happens.

## Expected or desired behavior:
If I click the "Save" button, Positron should display a file dialog and save the file.

If I click the "Help" button, a browser should open to the help page (or a confirmation modal?).

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Console logs when clicking "Save":

```
Ignored call to 'prompt()'. The document is sandboxed, and the 'allow-modals' keyword is not set.
doit @ bokeh-3.4.2.min.js:673
(anonymous) @ bokeh-3.4.2.min.js:473
s @ bokeh-3.4.2.min.js:224
emit @ bokeh-3.4.2.min.js:181
_clicked @ bokeh-3.4.2.min.js:474
on_tap @ bokeh-3.4.2.min.js:465
on_tap @ bokeh-3.4.2.min.js:466
_pointer_up @ bokeh-3.4.2.min.js:466
```

Console logs when clicking "Help":

```
bokeh-3.4.2.min.js:475 Blocked opening 'https://docs.bokeh.org/en/latest/docs/user_guide/interaction/tools.html' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.
doit	@	bokeh-3.4.2.min.js:475
(anonymous)	@	bokeh-3.4.2.min.js:473
s	@	bokeh-3.4.2.min.js:224
emit	@	bokeh-3.4.2.min.js:181
_clicked	@	bokeh-3.4.2.min.js:474
on_tap	@	bokeh-3.4.2.min.js:465
on_tap	@	bokeh-3.4.2.min.js:466
_pointer_up	@	bokeh-3.4.2.min.js:466
```

**Comment by nstrayer** [comment]
Probably some overlap with #4087?

**Comment by Pengsqi** [comment]
is the problem sovled？
and how to sovle？
![微信图片_20240819172108](https://github.com/user-attachments/assets/e8a5939a-e24f-4afe-a104-903da3ab31e6)
My vscode doesn't even have a console log when I interact with the save button

**Comment by juliasilge** [comment]
Not yet @Pengsqi but improvements for this are coming in #4377

**Comment by Pengsqi** [comment]
I have been debug for 5 workdays，with my poor skill of coding.
This mail saved my time to do my main job.
THXI've been engaged in debugging for the past five workdays, hampered somewhat by my limited coding proficiency. This email has significantly streamlined my process, allowing me to reallocate time towards my primary job responsibilities. THX.

---- Replied Message ----
| From | Julia ***@***.***> |
| Date | 08/19/2024 22:41 |
| To | posit-dev/positron ***@***.***> |
| Cc | Pengsqi ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [posit-dev/positron] Support "Save" and "Help" buttons in Bokeh plots (Issue #4235) |

Not yet @Pengsqi but improvements for this are coming in #4377

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-65
    OS Version          : OSX

### Test scenario(s) 

Verified fixed in the console/plots pane.

Link(s) to TestRail test cases run or created:
N/A
