### ISSUE TITLE
Python: support "download plot as PNG" for plotly

### ISSUE THREAD

**Issue by isabelizimm** [posit-dev/positron#4239]
## Steps to reproduce the issue:

Run in Console: 

```python
import plotly.express as px
fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
fig
```

<img width="620" alt="Screenshot 2024-08-05 at 10 59 43 AM" src="https://github.com/user-attachments/assets/714a105e-7361-4348-9be4-2ca31df694de">

## Expected or desired behavior:

File saved, perhaps in workspace or pull up the file explorer

## Were there any error messages in the UI, Output panel, or Developer Tools console?

None

**Comment by isabelizimm** [comment]
This seems to be solved in https://github.com/posit-dev/positron/pull/4377! I am able to save plots via icon for plotly on Positron Dev (commit 3fa1a25e0f1505575ac640475cdee5795b11369e) 🥳

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.08.0-63](https://github.com/posit-dev/positron-builds/releases/tag/2024.08.0-63)
OS Version(s) : Windows 11

### Test scenario(s) 



Plots from `plotly` save as expected.

### Link(s) to TestRail test cases run or created:
