### ISSUE TITLE
Missing Features: Packages pane and enhanced help pane for R

### ISSUE THREAD

**Issue by kv9898** [posit-dev/positron#4241]
#### Positron and OS details:

Positron Version: 2024.07.0 (system setup) build 2024.07.0-125
Code - OSS Version: 1.91.0
Commit: cae4905332a0f41a6233e196b48a6679b832000a
Date: 2024-07-31T22:26:02.970Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

#### Interpreter details:

R 4.2.2

## Describe the issue/Expected or desired behavior:

I really appreciate the packages pane where I can see which packages have been loaded and I can easily click on the package names to see which functions are included. This feature is yet missing in Positron.
![image](https://github.com/user-attachments/assets/bc6c2c4d-6380-48b3-9695-9c14a4cd532d)

Also, in RStudio one can search  _across documentations_, but this is not doable in Positron. The search function of the Help panel in Positron only works for the current page. Moreover, there is no "Home" page for the help panel. Moreover, I appreciate the functionality in Positron that when the mouse hovers on a function the information pops up in a window, but the window is too small I hope there is a button that allows the information to be displayed in the help panel on the right.
![image](https://github.com/user-attachments/assets/e72a4530-d420-4180-96f0-933dfcdd0cb6)

## Were there any error messages in the UI, Output panel, or Developer Tools console?
No

**Comment by juliasilge** [comment]
We are tracking UI for installed and loaded packages in #1391 and have discussed the RStudio Packages pane as an entrance for Help in https://github.com/posit-dev/positron/issues/1369#issuecomment-2023387584.

Adding search support for Help is a very early issue for us, in #422!

If you can add any additional thoughts or a 👍 to these issues, that would be very helpful for us in terms of prioritization.

**Comment by kv9898** [comment]
Thank you!
