### ISSUE TITLE
Interactive plots do not fill the plot area until redrawn by switching focus

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#4245]
#### Positron Version: 2024.07.0 (Universal) build 125
Code - OSS Version: 1.91.0
Commit: cae4905332a0f41a6233e196b48a6679b832000a
Date: 2024-08-01T00:27:06.019Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

#### Interpreter details:

Python 3.12.0

## Describe the issue:

Interactive graphics like `plotly` do not resize/redraw to fit the space until a plot other than Session pane is loaded.

## Steps to reproduce the issue:

1. In a Python script run the following code

```python
import plotly.express as px
fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
fig
```

2. Note that the dimensions of the JavaScript/HTML output are essentially fixed, even with resizing of the plot-pane. 
3. Change the overall height and width of the Plot pane, then move focus away from the Session pane to the Viewer pane or Help pane, and then return to the Session > Plot pane.
4. Notice that the interactive plot has redrawn to fit the new dimensions.

https://github.com/user-attachments/assets/9224da76-d7f9-42df-a051-e6cb290658b3

## Expected or desired behavior:

Given interactive graphics can be dynamic to the size, for example in RStudio's plot pane or in a web browser, it should also fit to the Plot pane.

https://github.com/user-attachments/assets/eceb6b5b-ab1a-4157-bd1c-75c64661464e

**Comment by timtmok** [comment]
The plot height seems to be stuck at 450px, which I think is the default for Plotly when no height is specified. The width seems to be set to the view's width when first showing the plot. Plotly won't resize when it has a set size on the container.

It should be triggering the resize event but that doesn't seem to happen. Rendering the plot with the `responsive` option will make the width resize but not the height (still stuck at 450px).

```python
fig.show(
	config={'responsive': True}
)
```
Plotly generates a container where the width is 100% and height is 450px.

```python
fig.show()
```
Plotly generates a container where the width is the plot view's width and height is 450px.

**Comment by midleman** [comment]
@timtmok , despite toggling `Interactive Plots in Viewer` it appears the plot is all rendering in the `viewer` and never in `plots`.
https://github.com/user-attachments/assets/317713f0-23d4-4bd4-a4b7-01fbf76011e1

**Comment by timtmok** [comment]
I'm going to take a closer look. I don't think any of these changes affected it but there seems to be something wrong with reading the preference value. I couldn't reproduce until I toggled the preference on/off. Then I couldn't open in the Plots view no matter what was set with the preference.

**Comment by timtmok** [comment]
I'll create a new issue for this regression. It occurs when showing the figure with `fig` instead of `fig.show()`.

**Comment by midleman** [comment]
### Verified Fixed
Positron Version(s) : 2024.10.0-13
OS Version(s) : MacOS

### Test scenario(s) 

Confirmed expected behavior by using `fig.show()`. Issue will be re-tested when linked regression bug is resolved.

### Link(s) to TestRail test cases run or created: 

n/a
