### ISSUE TITLE
Command Palette or other simple shortcut to get the Positron: About info to clipboard

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#4246]
#### Positron Version: 2024.07.0 (Universal) build 125
Code - OSS Version: 1.91.0
Commit: cae4905332a0f41a6233e196b48a6679b832000a
Date: 2024-08-01T00:27:06.019Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

## Describe the issue:

We open a lot of issues/discussions or Slack chats where having quick access to the Positron info is useful. It would be nice to expose this via the Command Palette for a no-mouse operation, rather than having to click a few times to get to the Positron > About page.

## Steps to reproduce the issue:

1. Go to Positron > About > Click on it > Click on Copy
2. Paste into destination

## Expected or desired behavior:

1. Cmd+Shift+P : Search About and get `Positron: About`
2. Enter to execute and get on to clipboard, kind of like AWS: About

https://github.com/user-attachments/assets/26da51c0-f873-4f1a-9b95-9b6df8b2f423

**Comment by petetronic** [comment]
It would be nice in a single command, though right now the shortest I see is Cmd+Shift+P then search for Help: About, then press enter to select default Copy button. A single command that achieves "Copy About Version Info" should be simple enough, and perhaps a single click method to get that from the UI could be devised too.

**Comment by jthomasmock** [comment]
I'll be using Command Palette > Help: About for now 😄

**Comment by juliasilge** [comment]
We're going to stick with the current options for now, but can re-evaluate/re-open in the future if needed.
