### ISSUE TITLE
Send Bokeh plots to the Plots pane

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#4249]
#### Positron and OS details:

Positron Version: 2024.07.0 (Universal) build 125
Code - OSS Version: 1.91.0
Commit: cae4905332a0f41a6233e196b48a6679b832000a
Date: 2024-08-01T00:27:06.019Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

#### Interpreter details:

Python 3.9.18.

## Steps to reproduce the issue:

1. Create a Bokeh plot via the console:

    ```py
    from bokeh.plotting import figure, show
    p = figure(title="Simple line example", x_axis_label='x', y_axis_label='y')
    p.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], legend_label="Temp.", line_width=2)
    show(p)
    ```
2. It will be created in the Viewer pane.

## Expected or desired behavior:

It should be created in the Plots pane.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Nope.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-41
    OS Version          : OSX

### Test scenario(s) 

Verified using code from original repro steps

Link(s) to TestRail test cases run or created:
Will add an automated test case that loads bokeh plot and manipulates it.
