### ISSUE TITLE
.Rprofile is executed twice at startup on Windows

### ISSUE THREAD

**Issue by DavisVaughan** [posit-dev/positron#4253]
### Discussed in https://github.com/posit-dev/positron/discussions/4252

<div type='discussions-op-text'>

<sup>Originally posted by **CorradoLanera** August  6, 2024</sup>
I have a custom `.Rprofile`. Poistron starts executing it twice, have I missed some configuration or is this an "issue"?

https://github.com/user-attachments/assets/88662c98-dd12-4fdb-bb18-8d2aa79420df

Positron Version: 2024.07.0 (system setup) build 2024.07.0-125
Code - OSS Version: 1.91.0
Commit: cae4905332a0f41a6233e196b48a6679b832000a
Date: 2024-07-31T22:26:02.970Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.26120</div>

Note: to help future open issue search, note that this was also raised by a customer in an issue titled "Console prints renv loading messages twice when .Rproj file exists", which was closed as a duplicate of this issue.

**Comment by DavisVaughan** [comment]
The strange part of what I'm seeing here is:
- It is run one time _without color_ (likely implying it is run by R itself, before our cli color envvars get set up)
- It is run again _with color_ (likely by us, after R fully starts up and we have ark fully set up)

**Comment by DavisVaughan** [comment]
Ok, on Windows we definitely seem to be running `.Rprofile` twice. R is doing it once (bad) and we are doing it once (good).

We use `cmdlineoptions()` here:
https://github.com/posit-dev/ark/blob/9387883055176bb0493b9893cd392f53a1bda0ed/crates/ark/src/sys/windows/interface.rs#L48-L55

Which internally calls `R_common_command_line()` which correctly sets `Rp->LoadInitFile = FALSE`
https://github.com/wch/r-source/blob/49d6f07c828dd73c7fc832478977b142e598cf5e/src/main/CommandLineArgs.c#L94

And that is "finalized" into the `LoadInitFile` global variable in `R_SetParams()` here, also still inside `cmdlineoptions()`
https://github.com/wch/r-source/blob/49d6f07c828dd73c7fc832478977b142e598cf5e/src/gnuwin32/system.c#L1347

So far so good

----

The problem is that we then call `R_DefParamsEx()` to be able to set our own hooks up, and then we call `R_SetParams()` again to finalize our own hooks:
https://github.com/posit-dev/ark/blob/9387883055176bb0493b9893cd392f53a1bda0ed/crates/ark/src/sys/windows/interface.rs#L66-L87

But that `R_DefParamsEx()` function will default to setting `Rp->LoadInitFile = TRUE`, and then calling `R_SetParams()` will overwrite what we did above with `cmdlineoptions()`, causing R on Windows to still actually load the user and site level Rprofiles.

---

I think in the past I had decided that we are using `cmdlineoptions()` out of necessity because it sets up a number of things that are otherwise inaccessible to us. But really we aren't relying on it to set up any of the options contained within `R_DefParamsEx()` - we want to do that ourselves. So I think the right move is to set

```
(*params).LoadInitFile = <value>;
(*params).LoadSiteFile = <value>;
```

to whatever the right value is, passed in through the caller, which has already figured this out for us.

**Comment by juliasilge** [comment]
## QA Notes

This was a problem on Windows only, so needs to be validated there.

- Put something that prints out in your `.Rprofile`. You can pop it open via `usethis::edit_r_profile()`, and you might add something like:

```r
cat(
  sample(
    x = c(
      "Nothing is impossible! 🙌",
      "Generic motivational quote! 👏"
    ),
    size = 1
  )
)
```

- Start or restart R a bunch of times. You should only see _one_ of these print out if you start/restart R, not two.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.11.0-129](https://github.com/posit-dev/positron-builds/releases/tag/2024.11.0-129)
OS Version(s) :  Windows 11

### Test scenario(s) 

.RProile on runs once now!


### Link(s) to TestRail test cases run or created:
