### ISSUE TITLE
Add attribute to `repos`, to increase harmony for renv users

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#4255]
Related to:

- https://github.com/rstudio/renv/issues/1963
- https://github.com/posit-dev/positron/discussions/4214

In Positron, we do in fact set `repos` to `"https://cran.rstudio.com/"` the same as RStudio:

https://github.com/posit-dev/ark/blob/9387883055176bb0493b9893cd392f53a1bda0ed/crates/ark/src/modules/positron/options.R#L30-L45

But RStudio also adds an attribute:

``` r
getOption("repos")
#>                        CRAN 
#> "https://cran.rstudio.com/" 
#> attr(,"RStudio")
#> [1] TRUE
```

<sup>Created on 2024-08-06 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Let's add an attribute of "Positron" so that renv can pick it up in its logic for deciding whether to use PPM.

**Comment by juliasilge** [comment]
Once we bump ark, we can verify that we now see an attribute on this option:

``` r
getOption("repos")
#>                        CRAN 
#> "https://cran.rstudio.com/" 
#> attr(,"IDE")
#> [1] TRUE
```

<sup>Created on 2024-09-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

I will also need to update at https://github.com/rstudio/renv/issues/1963 once this is in a publicly available release build.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-11
    OS Version          : OSX

### Test scenario(s) 

getOption("repos")

CRAN 
"[https://cloud.r-project.org](vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#)"

Link(s) to TestRail test cases run or created: 
N/A
