### ISSUE TITLE
R commands submitted as multi-line selection report back from Console out of order

### ISSUE THREAD

**Issue by tghoward** [posit-dev/positron#4264]
#### Positron and OS details:

Positron Version: 2024.08.0 (system setup) build 5
Code - OSS Version: 1.91.0
Commit: Unknown
Date: 2024-08-06T16:06:18.274Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

#### Interpreter details:

R version 4.4.0 (2024-04-24 ucrt) -- "Puppy Cup"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64

## Describe the issue:

If I select a bunch of lines and submit them at once, the result reported in the console doesn't always follow the same sequence as the lines submitted. This is different than the behavior in RStudio. "Source file" *does* follow the sequence.  Possibly related to https://github.com/posit-dev/positron/issues/4068 ?

## Steps to reproduce the issue:

this script consistently does it for me.  Select all then submit as a single chunk (ctrl-enter if using RStudio shortcuts). 
```
library(sf)
print("start block")
st_layers(system.file("shape", package = "sf"))
print("mid block")
Sys.sleep(0.6)
2+2
nc <- st_read(system.file("shape/nc.shp", package = "sf"))
print("end block")
```

This is what I get:

![image](https://github.com/user-attachments/assets/ae6fa723-fdbe-46b4-84ba-27c3a69f3811)

text version of output:

> library(sf)
+ 
+ print("start block")
+ st_layers(system.file("shape", package = "sf"))
+ print("mid block")
+ Sys.sleep(0.6)
+ 2+2
+ nc <- st_read(system.file("shape/nc.shp", package = "sf"))
+ print("end block")
[1] "start block"
[1] "mid block"
Reading layer `nc' from data source `F:\softwareInstalls\R_packages\sf\shape\nc.shp' using driver `ESRI Shapefile'
Simple feature collection with 100 features and 14 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
Geodetic CRS:  NAD27
[1] "end block"
Driver: ESRI Shapefile 
Available layers:
           layer_name        geometry_type features fields             crs_name
1                  nc              Polygon      100     14                NAD27
2             olinda1              Polygon      470      6 GRS 1980(IUGG, 1980)
3          storms_xyz       3D Line String       71      0                 <NA>
4         storms_xyzm Measured Line String       71      0                 <NA>
5 storms_xyzm_feature Measured Line String       71      1                 <NA>
6  storms_xyz_feature       3D Line String       71      1                 <NA>
[1] 4
>

Which shows the "st_layers" and "2+2" lines reporting back from the Console last. 

## Expected or desired behavior:

I would have expected "st_layers" result to show before the results from the commands that come after it. This is the way it behaves in RStudio and when the file is sourced. 

## Were there any error messages in the UI, Output panel, or Developer Tools console?

no errors that I see, but I didn't look far.

**Comment by jmcphers** [comment]
Related to https://github.com/posit-dev/positron/issues/1762 and https://github.com/posit-dev/positron/issues/1326. I think the right fix here is to submit these as individual statements and wait for each one to run to completion before running the next one. That will remove any possibility of their output getting tangled up.

**Comment by DavisVaughan** [comment]
This works correctly for me now. I think when we switched ark to working 1 line at a time this vastly improved things

![Image](https://github.com/user-attachments/assets/8edb6827-40c3-4715-b8cd-1f710ebd4706)
