### ISSUE TITLE
"No environment providers were found" for new Python project using New Project Wizard

### ISSUE THREAD

**Issue by mayrfb** [posit-dev/positron#4270]
![Screenshot 2024-08-07 170919](https://github.com/user-attachments/assets/a718ec1c-0ce6-4937-b7c2-6f6d935dc1b8)
Type: <b>Bug</b>

When I try to set up a Python environment in Positron, No 'environment providers' are found using VenV . However, when I use Conda there is no problem. Can someone explain to me why this is happening?

VS Code version: Positron 1.91.0 (cae4905332a0f41a6233e196b48a6679b832000a, 2024-07-31T22:26:02.970Z)
OS version: Windows_NT x64 10.0.26120
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz (16 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.81GB (42.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by sharon-wang** [comment]
Hey @mayrfb, thanks for reaching out about this!

From your screenshot, it seems like something went wrong while trying to detect which existing Python installations you have on your machine. The Conda Project Wizard flow doesn't depend on existing python installations on your machine -- an appropriate version of python is downloaded as part of creating a new Conda environment.

Could you please share which versions of Python you have installed on your machine? You can take a screenshot of what shows up via the Command Prompt "Python: Select Interpreter" command.

Here's a short demo on how to do that:
1. <kbd>Ctrl + Shift + P</kbd> to open the Command Prompt
2. Type in `python.setInterpreter` and run the command
3. Screenshot the list of interpreters that appear

https://github.com/user-attachments/assets/72a76c31-1ef3-44d9-8b4b-1f33ab54eed9

**Comment by mayrfb** [comment]
Hi Sharon-Wang,
Thank you for getting back to me so quickly. This is the list of interpreters following your instructions.
![image](https://github.com/user-attachments/assets/071aca7e-a702-4a9d-81e6-fe4e365755ae)

**Comment by sharon-wang** [comment]
Thanks for sharing that! I can confirm that it's a bug in the Project Wizard -- we are not including Microsoft Store global python installs in the dropdown, so we'll need to fix that up.

In the meantime, here's a workaround to create a Venv 👇 

Make sure you've already opened a folder in Positron, then you can do the following steps:

1. <kbd>Ctrl + Shift + P</kbd> to open the Command Prompt
2. Type in `python create environment` and run the command "Python: Create Environment..."
3. Select the `Venv` option
4. Select the version of python to use (in your case, you probably want to use the `Python 3.11.9 64-bit (Microsoft Store)` one!)
5. Click <kbd>Install</kbd> in the `Install Python package "ipykernel"?`dialog 

https://github.com/user-attachments/assets/902ba10b-f062-49df-8f29-56ea82f1f9b8

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.12.0-96](https://github.com/posit-dev/positron-builds/releases/tag/2024.12.0-96)
Workbench Version(s):
OS Version(s) : 

### Test scenario(s) 
 New project finds python everytime

### Link(s) to TestRail test cases run or created:
