### ISSUE TITLE
Add test cases for Data Explorer related to PR 4259

### ISSUE THREAD

**Issue by softwarenerd** [posit-dev/positron#4281]
## Describe the issue:

This is a tracking issue related to https://github.com/posit-dev/positron/pull/4259. We should add tests for two regression-related issues that were experienced in this PR.

1) Ensuring that the following Python code updates the Data Explorer UI as needed:

First create the DataFrame
```
import pandas as pd
import numpy as np

years = list(range(2014, 2025))
datapoints = np.random.normal(3, 0.5, len(years))

df = pd.DataFrame({
    'Year': years,
    'DataPoint': datapoints
})
```

Then in a separate execution, modify the DataFrame, e.g. by appending rows from another DataFrame:
```
new_year = [2025]
new_datapoints = np.random.normal(4, 0.5, 1)
new_df_2025 = pd.DataFrame({
    'Year': new_year,
    'DataPoint': new_datapoints
})


df = pd.concat([df, new_df_2025], ignore_index=True)
```

2) If a reproducible test case can be found, ensuring that Data Explorer does not display a blank grid. (This has happened once or twice but so far hasn't been easily reproduced.)

**Comment by jonvanausdeln** [comment]
Test pass!
