### ISSUE TITLE
Installation on Windows exits with an error 

### ISSUE THREAD

**Issue by b-trochimowicz** [posit-dev/positron#4282]
## System details:

Intel i5 13th Gen
Windows 11 Pro, Version: 22H2, Build: 22621.3880

#### Positron and OS details:

Positron build 2024.08.0-5

#### Interpreter details:

N/A

## Describe the issue:

Installation from Positron-2024.08.0-5-Setup.exe and Positron-2024.08.0-5-UserSetup.exe exists with error.

![image](https://github.com/user-attachments/assets/50fb5631-61dc-4892-a4f1-ea2df3a1bf48)

Previous build (2024.07.0-125) installs without issues on the same system.

## Steps to reproduce the issue:

1. Run Positron-2024.08.0-5-Setup.exe or Positron-2024.08.0-5-UserSetup.exe from local drive

## Expected or desired behavior:

N/A

## Were there any error messages in the UI, Output panel, or Developer Tools console?

N/A

**Comment by jmcphers** [comment]
It's possible that you need to adjust the permissions on your temporary folder. You can also create a new temp folder to see if that works. 

https://www.partitionwizard.com/clone-disk/unable-to-execute-file-in-temporary-directory.html

Do solutions 2 or 3 mentioned there resolve this issue for you?

**Comment by seeM** [comment]
Sounds like this is resolved, so I'll close the issue. Please feel free to comment or create a new issue if you encounter any challenges!
