### ISSUE TITLE
Data Explorer: R update variable by only changing the number of rows will keep broken state

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#4286]
#### Positron and OS details:

Positron Version: 2024.08.0 (Universal) build 5
Code - OSS Version: 1.91.0
Commit: Unknown
Date: 2024-08-06T17:08:14.498Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

## Describe the issue:

See video below:

- Create a table and open it with data explorer
- Modify the variable to be a subset of the rows (eg using `tail`)
- Go back to data explorer

https://github.com/user-attachments/assets/2fee159a-7786-4235-974c-e242ee330150

This only affects R, so probably an error from the R backend.

## Expected or desired behavior:

Data should be updated accordingly.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-77
    OS Version          : OSX

### Test scenario(s) 

Verified with original filing instructions.

Link(s) to TestRail test cases run or created:
N/A
