### ISSUE TITLE
Painting bugs with the Data Explorer column null percentage graph

### ISSUE THREAD

**Issue by softwarenerd** [posit-dev/positron#4291]
## System details:

<img width="392" alt="image" src="https://github.com/user-attachments/assets/e92b08c1-f0af-474b-a35f-91f3fd8d8021">

#### Positron and OS details:

Positron Dev Version: 2024.08.0 build 0
Code - OSS Version: 1.91.0
Commit: Unknown
Date: Unknown
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

#### Interpreter details:

Python 3.11.9

## Describe the issue:

There are a couple of painting bugs with the Data Explorer column null percentage graph.

First, when 100% of the values in the column are null, the graph is painting as though some small percentage of the values are non-null:

<img width="616" alt="100-percent-bug" src="https://github.com/user-attachments/assets/e26512ad-7efb-4935-8ea5-9d391bdbda35">

The graph above should be 100% red with a grey border.

Second, the graph is bleeding outside of the rounded corners of the indicator:

<img width="616" alt="image" src="https://github.com/user-attachments/assets/1194a6b9-69b0-458f-81ed-3690ab22e84e">

The graph above should have a clean grey border.

## Steps to reproduce the issue:

1. For the first issue, open a Data Explorer and add a row filter to it that causes the column null percentage graph to be 100%.
2. For the second issue, open a Data Explorer and add a row filter to it that causes the column null percentage graph to be a small percentage - say 2%.

## Expected or desired behavior:

The column null percentage graph should be drawn without these issues.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No.

**Comment by jmcphers** [comment]
Also covered (partly?) by https://github.com/posit-dev/positron/issues/2861

**Comment by softwarenerd** [comment]
Addressed in https://github.com/posit-dev/positron/pull/4295.

**Comment by softwarenerd** [comment]
> Also covered (partly?) by #2861

Thanks, @jmcphers. I've assigned https://github.com/posit-dev/positron/issues/2861 to myself and moved it into the PR Ready state.

**Comment by softwarenerd** [comment]
https://github.com/posit-dev/positron/issues/2861 has been closed as a duplicate.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-24
    OS Version          : OSX

### Test scenario(s) 

Used polars data frame from qa-example-content with column b equal to null.  Looks good.

Link(s) to TestRail test cases run or created:
N/A
