### ISSUE TITLE
Build commit is Unknown in Positron

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#4292]
## System details:

```
Positron Version: 2024.08.0 (Universal) build 16
Code - OSS Version: 1.91.0
Commit: Unknown
Date: 2024-08-08T04:26:32.029Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

## Describe the issue:

Builds using the new submodule-based build infrastructure don't have any commit information.

<img width="272" alt="image" src="https://github.com/user-attachments/assets/7b4de1dd-8ab2-4c47-a2e5-7c5d72bdab11">

This information is important for identifying the exact code revision from which Positron was built, and it's also used as a unique identifier for a binary to e.g. identify remote host compatibility with Remote SSH.

## Steps to reproduce the issue:

Positron -> About Positron

## Expected or desired behavior:

We should know the commit from which Positron was built.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No.

**Comment by petetronic** [comment]
Next builds should include the commit sha again.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) :[2024.08.0-31
    OS Version          : OSX

### Test scenario(s) 

Build commit is now present in dialog.

Link(s) to TestRail test cases run or created:
N/A
