### ISSUE TITLE
Add Quarto Smoke Tests

### ISSUE THREAD

**Issue by jonvanausdeln** [posit-dev/positron#4293]
Now that we bundle both the Quarto CLI and the extension, we should have some tests around it.

Possible things to include:

* Different types of quarto document creation
* Visual Editor
* Rendering different types of documents

We might also want to talk to quarto team on any integration testing they may (or may not) have already in place for VSCode.

**Comment by jonvanausdeln** [comment]
Note.. I added to the November release because there are some visual editor work being done as part of the next IDE release (targeted for November).

**Comment by jlang-311** [comment]
@jlang-311 reminder to look at this

**Comment by jlang-311** [comment]
We can work around this [issue](https://github.com/quarto-dev/quarto/issues/517) but will move forward knowing that we will need to rework these tests once the fix is made.

**Comment by jonvanausdeln** [comment]
We should check if we can re-enable the [rmarkdown preview test](https://github.com/posit-dev/positron/blob/4268ffd0ae51c8f67d7dd80289df1fda538d6af0/test/smoke/src/areas/positron/rmarkdown/rmarkdown.test.ts#L45) as well.
