### ISSUE TITLE
Ark: `browseURL()` on an HTML file is opening that file in the editor

### ISSUE THREAD

**Issue by DavisVaughan** [posit-dev/positron#4297]
`pkgdown::preview_site()` will attempt to call `browseURL()` on an `index.html` file, expecting that it opens in the browser

That is no longer happening, although it used to work. Currently calling `pkgdown::preview_site()` will open the HTML file directly in the editor, which is not great.

**Comment by DavisVaughan** [comment]
Probably related to https://github.com/posit-dev/positron/pull/4151 if I had to guess

**Comment by DavisVaughan** [comment]
Ok @lionel- and I have confirmed that #4151 was indeed what caused this regression

The problematic diff seem to be:
https://github.com/posit-dev/positron/pull/4151/files#diff-b42b14eff9e1b23c8e4bbe70783a6a4065dd0ecc89d250f1012e006367079366R131-R132

Here is a link to this in the current codebase

https://github.com/posit-dev/positron/blob/3b95c3e3bfd3d4aa9aa5e23a673a0eff78f83c0b/src/vs/workbench/services/languageRuntime/common/languageRuntimeUiClient.ts#L123-L131

The problem seems to be that `this._openerService.resolveExternalUri()` alters the `uri` in a way that causes this later call to `this._openerService.open()` to open it _within positron_ rather than opening it in an external browser:

https://github.com/posit-dev/positron/blob/3b95c3e3bfd3d4aa9aa5e23a673a0eff78f83c0b/src/vs/workbench/contrib/positronPreview/browser/positronPreviewServiceImpl.ts#L456-L458

---

Calling `this._openerService.resolveExternalUri()` results in this change from `uri` to `resolved`:
- Note the `'workspace'` path
- Note the `'positron'` scheme

<img width="1368" alt="Screenshot 2024-08-23 at 9 30 29 AM" src="https://github.com/user-attachments/assets/0b480d43-04b6-496b-87c1-402b96903bd6">

Either the `'workspace'` path or `'positron'` scheme seem to be the issue. It seems to cause `open()` to open the uri in Positron even though we set `openExternal: true` as an `open()` option. I think the idea is that this uri is _already resolved_ so the `openExternal` option is basically ignored, because it doesn't need to try and re-resolve the uri.

I feel like we need to try and conditionally pass `openExternal: true` to `resolveExternalUri()` so that it resolves it early in a way that is consistent with our `open()` call. That's complicated by two things:
- I don't exactly know what the condition to set this to `true` would be. We can use something like `this.canOpenInViewer()`, but is that enough?
- For some reason `resolveExternalUri()` takes `ResolveExternalUriOptions` which _doesn't_ allow `openExternal`, even though that option type is immediately cast to an `OpenOptions` type that does take `openExternal` when passed to `resolver.resolveExternalUri()`.

https://github.com/posit-dev/positron/blob/3b95c3e3bfd3d4aa9aa5e23a673a0eff78f83c0b/src/vs/platform/opener/common/opener.ts#L41-L50

https://github.com/posit-dev/positron/blob/3b95c3e3bfd3d4aa9aa5e23a673a0eff78f83c0b/src/vs/editor/browser/services/openerService.ts#L193-L196

We even confirmed that if you forcibly shove `openExternal: true` through as an option, it will "resolve" the uri in a way that is consistent with `open()` and it does open in the browser if you do that, but its ugly since we are forcing through an option that `ResolveExternalUriOptions` doesn't allow:

<img width="1538" alt="Screenshot 2024-08-23 at 9 45 57 AM" src="https://github.com/user-attachments/assets/eb334604-181f-4103-ab4f-9d4e1e78e4cf">

Setting `openExternal: true` here eventually makes its way to here, skipping this rewrite if the `fileService` thinks it can handle the file, which is a good thing and seems to be the key to making this work as expected.

https://github.com/posit-dev/positron/blob/3b95c3e3bfd3d4aa9aa5e23a673a0eff78f83c0b/src/vs/workbench/electron-sandbox/window.ts#L875-L885

**Comment by DavisVaughan** [comment]
This also affects `profvis::profvis()`, which used to at least open in the browser, but currently opens an HTML file in the editor

**Comment by jmcphers** [comment]
Notes for QA:

- I have fixed the two test cases in this bug (`profvis` and `preview_site` with no parameters). Both should work now; the desired behavior is opening the content in a browser.
- There are still situations wherein the HTML doesn't open correctly, specifically when you call `preview_site` on a _specific file_ (see notes in #4472). We are tracking that work separately as noted.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.08.0-77](https://github.com/posit-dev/positron-builds/releases/tag/2024.08.0-77)
OS Version(s) : Windows 11

### Test scenario(s) 



Test Several different code snippets as suggested. All work as expected showing results in viewer pane.

Also see #4514 for follow up automated tests.

### Link(s) to TestRail test cases run or created:
