### ISSUE TITLE
long column names are pushing the `ColumnNullPercent` component out of view to the right

### ISSUE THREAD

**Issue by softwarenerd** [posit-dev/positron#4301]
## System details:

<img width="280" alt="image" src="https://github.com/user-attachments/assets/952b3946-b4dd-45a3-a3fb-cedbb37bdb41">

#### Positron and OS details:

Positron Dev Version: 2024.08.0 build 0
Code - OSS Version: 1.91.0
Commit: Unknown
Date: Unknown
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

#### Interpreter details:

Python 3.11.9.

## Describe the issue:

In Data Explorer, in the table summary panel, long column names are pushing the `ColumnNullPercent` component out of view to the right.

## Steps to reproduce the issue:

1. Make sure you have the `qa-example-content` repo cloned locally.
2. Run `import pandas as pd`
3. Run `pandas100x100 = pd.read_parquet('your-repo-path/qa-example-content/data-files/100x100/100x100.parquet')`
5. Notice that the table summary panel is painting thusly:

<img width="1816" alt="image" src="https://github.com/user-attachments/assets/1f9d5c6f-ce69-4ce8-ac7a-acc0d4073a8a">

## Expected or desired behavior:

I expected the column names to be truncated with an ellipse and that the `ColumnNullPercent` component would not get pushed out of view to the right.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-41
    OS Version          : OSX

### Test scenario(s) 

Verified according to original filing instructions.

Link(s) to TestRail test cases run or created:
N/A
