### ISSUE TITLE
Data explorer throws error on summary calculation for columns with 100% missing data

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#4307]
#### Positron and OS details:

Positron Version: 2024.08.0 (Universal) build 24
Code - OSS Version: 1.91.0
Commit: d1012cc6f36088bac24a16dcfd1b55d026b239c1
Date: 2024-08-09T04:20:57.440Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

## Describe the issue:

I am seeing this with 100% NA columns + Pandas, not with Polars or R.

It will view and display fine, but when opening the Summary Panel for that column:

```python
/Users/thomasmock/arrow-eda/.venv/lib/python3.10/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
```

## Steps to reproduce the issue:

In a Python script:

1. Create a dataframe with a column that contains 100% missing data.

```python
import pandas as pd
import numpy as np

pd_na = pd.DataFrame({"missing": [np.nan,np.nan,np.nan,np.nan, np.nan]})
```

It will view just fine in the grid, but opening summary stats will throw a warning:

```python
/Users/thomasmock/arrow-eda/.venv/lib/python3.10/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
```

I can repro that independent of Data Explorer:

```python
np.nanmean(pd_na['missing'])
<positron-console-cell-13>:1: RuntimeWarning: Mean of empty slice
```

## Expected or desired behavior:

Ignore NAs for summary calculations such as mean, sd, median, etc.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-41
    OS Version          : OSX

### Test scenario(s) 

Verified using original filing instructions.

Link(s) to TestRail test cases run or created:
Will add a fully "missing data" row to data frame when writing summary stats automated test.
