### ISSUE TITLE
Data Explorer: Python %view doesn't respect label

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#4310]
#### Positron and OS details:

Positron Version: 2024.08.0 (Universal) build 24
Code - OSS Version: 1.91.0
Commit: d1012cc6f36088bac24a16dcfd1b55d026b239c1
Date: 2024-08-09T04:20:57.440Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

## Describe the issue:

Using `%view df "some label"` doesn't apply the custom label, just applies the name of the dataframe object.

## Steps to reproduce the issue:

Py Script:

```python
import pandas as pd
import polars as pl

xpd = pd.DataFrame({"vals": [100, 10, 1, 0.1, 0.01]})
xpd

%view xpd "my Pandas df"

xpl = pl.DataFrame({"vals": [100, 10, 1, 0.1, 0.01]})
xpl

%view xpl "my Polars df"

```

## Expected or desired behavior:

Custom labels should be applied. Reusing a label should also overwrite an existing data explorer instance.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Thanks to some digging by @petetronic 

> An issue may be that we're now setting a variable_path here:
> https://github.com/posit-dev/positron/blob/main/extensions/positron-python/python_files/positron/positron_ipykernel/positron_ipkernel.py#L165 
> 
> Does that cause us to ignore the title? https://github.com/posit-dev/positron/blob/main/extensions/positron-python/python_files/positron/positron_ipykernel/data_explorer.py#L2556-L2559

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.08.0-48](https://github.com/posit-dev/positron-builds/releases/tag/2024.08.0-48)
OS Version(s) : Windows 11, MacOS 14

### Test scenario(s) 



Dataframe tab is renamed with new title

### Link(s) to TestRail test cases run or created:
