### ISSUE TITLE
Support for Positron as default external editor in Github Desktop

### ISSUE THREAD

**Issue by kv9898** [posit-dev/positron#4314]
#### Positron and OS details:

Positron Version: 2024.08.0 (system setup) build 24
Code - OSS Version: 1.91.0
Commit: d1012cc6f36088bac24a16dcfd1b55d026b239c1
Date: 2024-08-09T03:33:00.069Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

#### Interpreter details:

R 4.4.1

## Describe the issue:

Positron is currently not supported as a default external editor in Github Desktop (while VS Code, VS Codium and RStudio are).  [This link](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md) describes how to start a pull request to add a new editor and therefore I created a [new issue](https://github.com/desktop/desktop/issues/19087) and started a [pull request](https://github.com/desktop/desktop/pull/19088/commits/8498af99d48ee215fdb6ed6be1cb61d053b5d92c) in the Desktop project to add information about Positron identifiers for 64-bit version of Positron (system installation) on Windows. However, for support of other versions (e.g. user installations rather than system installation) or other OS (Mac or Linux), additional identifiers are needed and I currently don't have this information from my part.

## Expected or desired behavior:

Positron should be added to the list of default external editor in Github Desktop.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No

**Comment by seeM** [comment]
Thanks for the report and for helping out on the GitHub Desktop repo! We'll look into what's needed to get this working on the remaining OSs.

**Comment by kv9898** [comment]
the Desktop team replied that they will let users choose their preferred executables in the next version so I guess this is no longer the issue
