### ISSUE TITLE
?? or help.search() doesn't work for R

### ISSUE THREAD

**Issue by kv9898** [posit-dev/positron#4320]
## System details:

Windows 11

#### Positron and OS details:
Positron Version: 2024.08.0 (system setup) build 24
Code - OSS Version: 1.91.0
Commit: d1012cc6f36088bac24a16dcfd1b55d026b239c1
Date: 2024-08-09T03:33:00.069Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

#### Interpreter details:

R 4.4.1

## Describe the issue:
The ?? or help.search() command returns _all_ vignettes rather than only those that match the pattern.

## Steps to reproduce the issue:

1. Switch to the R console
2. Try `??plot`
3. All command vignettes A-Z are shown, rather than only plot-related vignettes.
![image](https://github.com/user-attachments/assets/49073248-854a-47f2-b969-7bfe7479b55c)

## Expected or desired behavior:

1. The ?? and help.search() commands work properly, as in RStudio.
2. Even better, add an input to the help pane as suggested in #422.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No

**Comment by kv9898** [comment]
![image](https://github.com/user-attachments/assets/4b9455bd-7ca8-48e4-a898-9ce9bcd3db9a)
I think I identified the bug. While the port is 27692, the help pane wrongly access 44051 after 127.0.0.1. I manually accessed http://127.0.0.1:27692/doc/html/Search?objects=1&port=27692 and it worked fine.

**Comment by seeM** [comment]
Thank you for the report @kv9898! I am able to repro this on macOS with Positron 

Here is the top of the result of `??plot` in RStudio for comparison:

<img width="759" alt="image" src="https://github.com/user-attachments/assets/405524a3-ba15-4eed-8029-60e9e3f757e1">

This does seem to affect the results: `help.search("", package = "stats")`. I noticed another issue where any additional `help.search` calls after the first one don't seem to have any effect.

Related to https://github.com/posit-dev/positron/issues/429.

**Comment by kv9898** [comment]
Is there any temporary fix? Currently I rely on accessing the non-proxy help page on my external browser.

**Comment by juliasilge** [comment]
@kv9898 unfortunately we don't have a workaround right now, no. 😕 This issue is in triage right now so we'll soon decide when we can work on it; we may be able to address it together with #3753.

**Comment by kv9898** [comment]
Thank you!

**Comment by juliasilge** [comment]
I spent a little bit of time on this today and wanted to pull out something that was mentioned earlier. The URLs for these results are like: <http://127.0.0.1:30580/doc/html/Search?objects=1&port=30580>. It always uses `objects=1` no matter what you search AFAICT.

Here is where I maybe embarrass myself but admit that I have no idea what a port in a query string means. FWIW our URL munging in `handle_show_help_url()` currently replaces the first (real?) port with the proxy port but it does not do anything to the `port` query parameter. I did a quick test of whether replacing _both_ would fix this but it does not.

**Comment by kv9898** [comment]
Thank you so much for looking into this! From my experience, replace the first (proxy) port with the original port in the end would uncover the original link, which could be opened in an external browser (although this misses the whole point of the proxy server). Nevertheless, this seems to mean that the `objects=1` is fine as this is what the original link always use.


> I spent a little bit of time on this today and wanted to pull out something that was mentioned earlier. The URLs for these results are like: <http://127.0.0.1:30580/doc/html/Search?objects=1&port=30580>. It always uses `objects=1` no matter what you search AFAICT.
> 
> Here is where I maybe embarrass myself but admit that I have no idea what a port in a query string means. FWIW our URL munging in `handle_show_help_url()` currently replaces the first (real?) port with the proxy port but it does not do anything to the `port` query parameter. I did a quick test of whether replacing _both_ would fix this but it does not.

**Comment by juliasilge** [comment]
Here is some info on what RStudio does: 

https://github.com/rstudio/rstudio/blob/e30b33bca603feeb6552ba96d5f720d6a25497c1/src/cpp/session/modules/SessionHelp.cpp#L102-L103

**Comment by kv9898** [comment]
Fantastic! If this is complicated to implement in Positron, here's a temporary fix that could serve in the short term. This could also serve as a temporary fix to #3738. I noted that `doc/html/SearchOn.html` is a built-in search engine for R. We can set this as the temporary home page for the help panel for R before a proper page is created. Here is a reproducible demo:

1. In the R console of positron, run `??plot`, note the help page is not displayed properly.
2. In developer tools, find the PositronHelpService log and note the original port:
![image](https://github.com/user-attachments/assets/412bc65b-fee4-4666-af71-b5fbed541628)
In my case, the original port is 31490
3. In the R console, type `http://127.0.0.1:[OriginalPort]/doc/html/SearchOn.html` and hit enter.
4. Select "Open in Viewer Pane"
5. A functioning search portal appears in the viewer.
![image](https://github.com/user-attachments/assets/457309a0-2f48-4aae-904a-6349cb3e671e)
6. Search for plot and the results are displayed properly:
![image](https://github.com/user-attachments/assets/a51b1c7c-f8ef-465f-83cf-b9f9a7f3c63c)

**Comment by juliasilge** [comment]
Looks like what we need to do is munge the _content_ of the result, like RStudio does here:

https://github.com/rstudio/rstudio/blob/e30b33bca603feeb6552ba96d5f720d6a25497c1/src/cpp/session/modules/SessionHelp.cpp#L147

**Comment by kv9898** [comment]
Thank you!

**Comment by juliasilge** [comment]
I opened up https://github.com/posit-dev/positron/issues/4484 to track the remaining issue with refreshing the page.

## QA Notes

After https://github.com/posit-dev/ark/pull/484 and then we bump ark, we should observe:

- All requests for help that do _not_ use query strings, like `?lm`, should still work well
- Requests for help that _do_ use query strings, like `??cat`, should now also work well

**Comment by kv9898** [comment]
Thank you so much!

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-77
    OS Version          : OSX

### Test scenario(s) 

Verified with initial filing instructions.

Link(s) to TestRail test cases run or created:
N/A
