### ISSUE TITLE
Mixing R and Python code cells in a Quarto document

### ISSUE THREAD

**Issue by Matteo-Valerio** [posit-dev/positron#4321]
## System details:

Win 11

#### Positron and OS details:
Positron Version: 2024.08.0 (system setup) build 31
Code - OSS Version: 1.91.0
Commit: 7ee0596b81d578059e63c9af7c535c6b6040b947
Date: 2024-08-10T13:58:22.910Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621

#### Interpreter details:
R 4.4.0 and  Python 3.10.9

## Describe the issue:

In a Quarto document, when mixing R and Python code cells, the results are not reported in the relative consoles. 

![image](https://github.com/user-attachments/assets/d8645d99-ab0f-4f7e-b6ef-6b6f6c9fa44a)

For R cells the results is reported in the relative console as expected.

![image](https://github.com/user-attachments/assets/d2e5b257-103c-4fc2-b203-21bd13d98c01)

For Python cells the result is reported in two different ways:

1. Clicking on the “Run Cell” the code is executed via “reticulate”, the statements are reported in the R console, but not executed, indeed the results are reported neither in the R console not in the Python console and the variables are not set.

![image](https://github.com/user-attachments/assets/dee29a69-97f6-4881-ba85-a1aedce35f1d)

2. Selecting the lines of code and executing manually (Ctrl + Enter) the statements are reported in the Python console and are executed correctly.

![image](https://github.com/user-attachments/assets/48a99a45-4873-496a-a457-ee3be87d255c)

## Expected or desired behavior:

Get the same result by running the Python code with the previous two ways.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No

**Comment by seeM** [comment]
Thanks for the writeup @Matteo-Valerio! We are aware of the issues with mixed R/Python Quarto documents and are already tracking that work e.g. see https://github.com/posit-dev/positron/issues/1646#issuecomment-2135993785.
