### ISSUE TITLE
Positron notebooks do not support .Rprofile

### ISSUE THREAD

**Issue by muhsinciftci** [posit-dev/positron#4340]
Hi,
   I just started using Positron IDE for R and Python and it looks awesome so far. However, when I open my existing R project in Positron IDE, my pre-defined functions and paths in .Rprofile  are not recognized in Notebooks (.ipynb) but they are perfectly functioning in regular R files. The kernel of notebook is also R 4.4.2. Is there any way to handle this issue? Thanks

**Comment by jmcphers** [comment]
Is your `.Rprofile` in the same directory as your notebook?

(Positron starts R in your notebook's directory, so if your .RProfile isn't there, it won't be run.)

**Comment by juliasilge** [comment]
Let us know if you have further questions!
