### ISSUE TITLE
Error opening the viewer for pandas dataframe in Quarto document

### ISSUE THREAD

**Issue by Matteo-Valerio** [posit-dev/positron#4347]
#### Positron and OS details:

Positron Version: 2024.08.0 (system setup) build 31
Code - OSS Version: 1.91.0
Commit: 7ee0596b81d578059e63c9af7c535c6b6040b947
Date: 2024-08-10T13:58:22.910Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22621

#### Interpreter details:

Python 3.10.9

## Describe the issue:

In a Quarto document, running the Python code reported below to create a pandas dataframe, it’s not possible to visualize the data in the viewer. 

![image](https://github.com/user-attachments/assets/ff13c822-abb0-43a4-b823-0a0623a21942)

The code is executed correctly, and in the console the results are presented as expected.

![image](https://github.com/user-attachments/assets/d3472886-a018-4dfb-a734-fb60f6a2d5f2)

When clicking on the grid icon to visualize the data, an error message is displayed. 

![image](https://github.com/user-attachments/assets/d6d33c4f-633e-43b0-956b-df11b1771c3c)

![image](https://github.com/user-attachments/assets/058f0771-2652-4df7-a1af-aa30c163d21a)

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Yes

**Comment by Matteo-Valerio** [comment]
I'm using Win 11, and even if I restart the session the data explorer doesn't work.
Thank you

**Comment by seeM** [comment]
Hmm, I'm unable to repro on Win 11 as well. Could you please share the Python kernel logs? That could give us a clue about what's going wrong.

You'll need to do the following:

1. Set the kernel log level setting to `debug`. You can search the settings for `python.languageServerLogLevel` to find it.
2. Completely close and reopen Positron to let it take affect.
3. Reproduce the error.
4. Share the kernel log file here, which you can find by running the "Interpreter: Show interpreter output" command. It's worth making sure there is no confidential info in the logs before sharing.

**Comment by seeM** [comment]
Ah! This looks like a bug, where we're not handling an unexpected (possibly older?) version of sqlalchemy.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-77
    OS Version          : OSX 

### Test scenario(s) 

Verified with original filing instructions

Link(s) to TestRail test cases run or created:
N/A
