### ISSUE TITLE
Data explorer: Warnings displayed in the console when no-non NA values

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#4353]
## System details:

MacOS Sonoma 14.5

#### Positron and OS details:

Positron Dev Version: 2024.08.0 build 0
Code - OSS Version: 1.91.0
Commit: Unknown
Date: Unknown
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

#### Interpreter details:

R

## Describe the issue:

```
There were 50 or more warnings (use warnings() to see the first 50)
Warning messages:
1: In min(col, na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
2: In max(col, na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
```

Also seeing some: 

```
Warning messages:
1: In as.POSIXlt.POSIXct(x) : unknown timezone '+00:00'
2: In as.POSIXlt.POSIXct(x) : unknown timezone '+00:00'
3: In as.POSIXlt.POSIXct(x) : unknown timezone '+00:00'
4: In as.POSIXlt.POSIXct(x) : unknown timezone '+00:00'
5: In as.POSIXlt.POSIXct(x) : unknown timezone '+00:00'
```

## Steps to reproduce the issue:

1. `View(mtcars)`
2. Add a filter that removes all rows, eg `mpg < 10`
3. Warnings appear in the console

## Expected or desired behavior:

No warning should appear in the console

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) :2024.08.0-48
    OS Version          : OSX

### Test scenario(s) 

View(mtcars)
Add a filter that removes all rows, eg mpg < 10
Verify no warnings appear in the console

Link(s) to TestRail test cases run or created:
N/A
