### ISSUE TITLE
Data Explorer: Date/Datetimes summary stats should be optional

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#4356]
## Describe the issue:

Some stats such as `min`, `max`, `mean` and `median` should be optional for date and datetime variables, like they are for numeric columns, so we can ommit them in case they can't be computed (for example, when the data frame is empty, or the column is just NA's).

Related to https://github.com/posit-dev/positron/issues/4352

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.10.0-13](https://github.com/posit-dev/positron-builds/releases/tag/2024.10.0-13)
OS Version(s) : windows 11, Ubuntu 22

### Test scenario(s) 



Values now show as N/A

### Link(s) to TestRail test cases run or created:
