### ISSUE TITLE
Implement copy plot to clipboard from plot editor

### ISSUE THREAD

**Issue by timtmok** [posit-dev/positron#4362]
Follow-up to #2270

Add a button to the editor action bar to copy the plot to the clipboard.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-27
    OS Version          : OSX

### Test scenario(s) 

Copied R & Python plots

Link(s) to TestRail test cases run or created: 
N/A

**Comment by FinYang** [comment]
I couldn't find a button on the bar if I opened the plot in an editor tab. That is what this issue is referring to, right? I can only find the original copy button in the plot pane. 

![image](https://github.com/user-attachments/assets/e696d4c8-b132-43a7-985d-f07d88fdfa63)

**Comment by jmcphers** [comment]
@FinYang Yes, this is an experimental feature. We plan to add an action bar to the editor with (largely) the same features you get in the Plots pane, e.g. https://github.com/posit-dev/positron/issues/4361

**Comment by FinYang** [comment]
Is this currently implemented? I saw all the other open issues related to the plot editor action bar, and only this one has been tested and closed, so I assumed it was available in the last pre-release.

**Comment by timtmok** [comment]
I'll reopen. I accidentally moved this into verification when mixing up the copy plot fix for web.

@FinYang Sorry for the confusion! I do have something in progress for this that will be enabled with the same experimental option.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-95
    OS Version          : OSX

### Test scenario(s) 

Copied R and python plots to clipboard successfully

Link(s) to TestRail test cases run or created:
