### ISSUE TITLE
hvplots doesn't work with plotly extension

### ISSUE THREAD

**Issue by nstrayer** [posit-dev/positron#4365]
As of #4335, basic hvplot plots work, but if you switch to plotly as the rendering extension things still don't work. 

```python
import hvplot.pandas
from bokeh.sampledata.penguins import data as df

hvplot.extension('plotly')

df.hvplot.scatter(x='bill_length_mm', y='bill_depth_mm', by='species')
```

**Comment by nstrayer** [comment]
This turned out to be way more interesting than expected. I believe it has to do with how we execute multiple lines of code at once. Both `import hvplot.pandas` and `hvplot.extension('plotly')` emit a few output messages that set up the webview for the main plot call. Problem is, in order for things to work, the messages from `hvplot.extension('plotly')` need to come out after the ones from `import hvplot.pandas`, but when run in one big chunk, they come out before, and thus `bokeh` is the loaded plotting library, but the plot message expects plotly. As seen in these error messages: 

![Image](https://github.com/user-attachments/assets/3d70ba5a-6593-4bfd-95ec-c02d3eb57d8d)

(_note that the use of 'bokeh' in the error message is because hvplot doesn't change the name when in plotly mode._)


![Image](https://github.com/user-attachments/assets/be8a502d-d81b-4348-9b15-9a89390f97c5)


I think this means that without serious hacky work this won't be fixable for all scenarios until #1762 is addressed.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-88
    OS Version          : OSX

### Test scenario(s) 

Verified according to original filing steps.

Link(s) to TestRail test cases run or created:
Smoke test added with PR
