### ISSUE TITLE
The Alt+- shortcut for <- does not in visual mode of Quarto

### ISSUE THREAD

**Issue by kv9898** [posit-dev/positron#4368]
## System details:

Windows 11

#### Positron and OS details:

Positron Version: 2024.08.0 (system setup) build 31
Code - OSS Version: 1.91.0
Commit: 7ee0596b81d578059e63c9af7c535c6b6040b947
Date: 2024-08-10T13:58:22.910Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
#### Interpreter details:

R 4.4.1

## Describe the issue:

While the Alt+- shortcut correctly produces `<-` for .R files and Quarto documents in source mode in Positron, it does not work for Quarto documents in visual mode.

## Steps to reproduce the issue:

1. Start a Quarto document
2. Switch to visual mode
3. Create an R chunk
4. Press Alt and - keys (nothing happens)
5. Switch to source mode
6. Press Alt and - keys (`<-`  is created)

## Expected or desired behavior:

The Alt+- shortcut produces `<-`  for Quarto documents in visual mode, as in RStudio.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No

**Comment by jmcphers** [comment]
This is tracked in https://github.com/posit-dev/positron/issues/1955.

**Comment by kv9898** [comment]
> This is tracked in #1955.

Thank you!

**Comment by seeM** [comment]
Thanks for the report! I'll close this as a duplicate.
