### ISSUE TITLE
Change bloqmayus to use Escape neovim in positron

### ISSUE THREAD

**Issue by joscani** [posit-dev/positron#4384]
Hi. I'm using linux mint,  and positron 
Versión: Positron Version: 2024.08.0 build 31,
together with vscode [neovim extension](https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim) 
I'm using a spanish keyboard layout and in linux I usually change the keymaps using `sudo /usr/bin/setxkbmap -option "caps:swapescape"`. 

Then, in terminal and in all programs (for instance neovim) when I push BlqMayus, I get Escape, but not in positron. 
Any idea? 
Thanks

**Comment by juliasilge** [comment]
Thanks for this report! Does this method of changing your keymap work in: 

- vanilla VS Code? (no extensions)
- VS Code with the neovim extension?

**Comment by joscani** [comment]
Ups. It doesn't work in VSCode. Then the problem is how vscode map the keys. Thanks in advance @juliasilge
