### ISSUE TITLE
Support for interactive jupyter notebook via @interact

### ISSUE THREAD

**Issue by vinaychuri** [posit-dev/positron#4390]
System:
- Positron Version: 2024.08.0 (Universal) build 31
- MacOS : Ventura 13.6.8
- Python : 3.12.4

The following code allows user to make Jupyter cell interactive with selectors/input options. This works in Vscode->Jupyter notebook as expected.

In Positron the initial chart is displayed first and then the UI controls(this is incorrect , UI should be shown first). Any changes to the UI does not refresh the chart

```
%matplotlib widget
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact, widgets
 
def circle(radius, linewidth, color):
    angles = np.linspace(0,2*np.pi,100)
    fig, ax = plt.subplots()
    ax.set_aspect(1)
    ax.set_xlim(-10,10)
    ax.set_ylim(-10,10)
    ax.plot(radius*np.cos(angles), radius*np.sin(angles), linewidth = linewidth, c = color)
    plt.title('Circle of radius {} units'.format(radius))
    plt.show()
 
interact(
    circle,
    radius = widgets.FloatSlider(min = 0, max = 10, value = 1),
    linewidth = widgets.IntSlider(min = 0, max = 5, value = 1),
    color = widgets.ColorPicker()
)
```

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-11
    OS Version          : OSX

### Test scenario(s) 

Verified with notebook and sample from original filing

Link(s) to TestRail test cases run or created: 
Adding code sample to qa-example-content
