### ISSUE TITLE
Support comment-derived sections in the R code outline

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/positron#4393]
RStudio support comment sections, e.g. 

```r
# Setup -----------------------------------------------------------------------

# UI ----

#### Server ####
```

I think the specific rules are: 

1. A comment ending in 4+ dashes (`----`)
2. A comment surrounded by 4+ hashes on both sides `#### Title ####`

In RStudio, these structural comments are then exposed in the document outline and are foldable. 

RStudio doesn't differentiate between these headings as having any kind of hierarchy, but it'd be a helpful and welcome addition if they could. I'd personally advocate for the above examples being level-1, level-3 and level-2 headings (respectively), but I'd be open to any kind of rule. Another option would be to assume similar heading styles are at the same level and any change in heading style indicates a sub-section.

This issue was also mentioned in #1427:

> The VSCode outline does not support sections, sub sections etc in a way that makes it easy to navigate a long script like the Rstudio IDE does. Would really love having those sections/subsections including indentations like it's in the Rstudio
>
> _Originally posted by @IyarLin in https://github.com/posit-dev/positron/issues/1427#issuecomment-2202150173_

**Comment by juliasilge** [comment]
I believe this is the same as #3822. Feel free to add additional detail there!

**Comment by gadenbuie** [comment]
Will do thanks!
