### ISSUE TITLE
Plot pane not showing any plots

### ISSUE THREAD

**Issue by prasundutta87** [posit-dev/positron#4400]
#### Positron and OS details:

Positron Version: 2024.08.0 (system setup) build 31
Code - OSS Version: 1.91.0
Commit: 7ee0596b81d578059e63c9af7c535c6b6040b947
Date: 2024-08-10T13:58:22.910Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

#### Interpreter details:

 R 4.4.1

## Describe the issue:
Plots are not being showed in the Plot pane. They could be saved as a file though.

## Steps to reproduce the issue:

1. Running this code-
```
ggplot(dt, aes(AF)) + 
  geom_density(fill = "dodgerblue1", colour = "black", alpha = 0.3)+ 
  theme_pubclean()+
  labs(x="SVs Allele Frequency")+
  scale_x_continuous(breaks = seq(0,1,0.05))+
  theme(axis.text.x=element_text(angle = 45, vjust = 0.5))
```

## Expected or desired behavior:
Plot should be visible on the plot pane

**Comment by jonvanausdeln** [comment]
@prasundutta87 thank you for the report.  Could you share more of your code so I can try to reproduce your example?  Other simple ggplot examples are working for me.

**Comment by prasundutta87** [comment]
Hi @jonvanausdeln ..thanks for your reply. I was unable to reproduce the issue. I think its related to the source(), which somehow got run without my knowledge (it was not in my script, nor I wrote it in the console), which led to the plotting issues.

**Comment by jonvanausdeln** [comment]
Glad it's working for you now! I'm going to close this issue, but please re-open if you experience it again!
