### ISSUE TITLE
Commenting/uncommenting lines does not work

### ISSUE THREAD

**Issue by cgeger** [posit-dev/positron#4405]
Type: <b>Bug</b>

sometimes it is handy to be able to comment/uncomment a block of text quickly. The expected behavior is:

Highlight text and press Ctrl+Shift+C on windows:

```{r}
# code line one
# ...
# code line fifty
```

What actually happens:
a random terminal window opens up

choosing comment block from the drop-down selection works, and it even indicates that Ctrl+Shift+C is the correct shortcut

I have only used positron a few days, so there may be a setting I have not discovered to turn on the shortcuts, but in my opinion this should happen by default. 
Other shortcuts do work: 
Ctrl+Enter executes code line by line into the consol

VS Code version: Positron 1.91.0 (7ee0596b81d578059e63c9af7c535c6b6040b947, 2024-08-10T13:58:22.910Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
pyright|ms-|1.1.372
debugpy|ms-|2024.8.0
jupyter|ms-|2024.6.0
jupyter-renderers|ms-|1.0.18
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
js-debug|ms-|1.92.0
shiny|Pos|1.0.0
shinyuieditor|pos|0.5.0

</details>

**Comment by DavisVaughan** [comment]
If you enable the RStudio Keymap then that will work for you
https://github.com/posit-dev/positron/wiki/Keyboard-Shortcuts#rstudio-keymap

Otherwise, the way to comment/uncomment is `Ctrl + /` on Windows. Being an entirely different IDE from RStudio means that we also have different keyboard shortcuts for certain things, the RStudio Keymap is a way to bridge the gap a little.
