### ISSUE TITLE
Data viewer column divider is dragable behind scroll bar

### ISSUE THREAD

**Issue by ryjohnson09** [posit-dev/positron#4408]
#### Positron and OS details:

Positron Version: 2024.08.0 (Universal) build 31
Code - OSS Version: 1.91.0
Commit: 7ee0596b81d578059e63c9af7c535c6b6040b947
Date: 2024-08-10T14:49:10.180Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

#### Interpreter details:

R 4.4.0

## Describe the issue:

When viewing data in the data viewer, the column dividers can be clicked on despite being behind the vertical scroll bar:

https://github.com/user-attachments/assets/d23aa757-77d6-44ab-95ea-9c28c35ca6ab

## Expected or desired behavior:

The scroll bar should negate the column dividers.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-27
    OS Version          : OSX

### Test scenario(s) 

Dividers can no longer be used behind scroll bar

Link(s) to TestRail test cases run or created: 
N/A
