### ISSUE TITLE
Positron does not find R interpreter in PATH on Linux

### ISSUE THREAD

**Issue by csnydermph** [posit-dev/positron#4412]
#### Positron and OS details:

Positron Version: 2024.08.0 build 48
Code - OSS Version: 1.91.0
Commit: ed616b36655fb24d116108bdd833f1321704315b
Date: 2024-08-19T03:18:03.038Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 5.15.0-118-generic

System:
  Kernel: 5.15.0-118-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 5.4.12
    tk: GTK 3.24.33 wm: Mutter dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy

#### Interpreter details:

R 4.1.2

## Describe the issue:

Positron .deb is installed on Linux Mint 21. `r-base` package is installed via apt repository. Positron is unable to find R in PATH or at `/bin/R`. Despite R being installed, there is no option to start the R interpreter from Positron. The generic Python library was discovered successfully.

## Steps to reproduce the issue:

1. Install Linux Mint 21
2. Install R via apt via: `sudo apt install r-base`
3. Install Positron via `.deb` in GitHub repo
4. Launch Positron and navigate to `Start Interpreter`
5. Interpreter will discover the global python 3.10.12 at `/bin/python3`, will not discover the R install at `/bin/R`

![image](https://github.com/user-attachments/assets/9f8d903b-00b9-4a66-80cd-5d1d4b112547)

![image](https://github.com/user-attachments/assets/f0712b97-9384-4f6a-a457-23fd43b4245f)

## Expected or desired behavior:

Positron would discover the R install in PATH at `/bin/R` on Linux

**Comment by jmcphers** [comment]
> R 4.1.2

That's the problem; Positron requires R 4.2. More info here: https://github.com/posit-dev/positron/wiki#r-prerequisites

**Comment by csnydermph** [comment]
Thank you for confirmation.
Will compile newer R and confirm it is working as intended.

**Comment by csnydermph** [comment]
Confirming that R 4.4.1 is identified in the PATH by Positron.
Mint repositories are not kept current. Added additional deb repository per: https://cran.r-project.org/bin/linux/ubuntu/fullREADME.html
Positron now runs Global Python and R.
