### ISSUE TITLE
Hyperlinks in console interpret the closing angled bracket `>` as part of the URL

### ISSUE THREAD

**Issue by yjunechoe** [posit-dev/positron#4413]
#### Positron and OS details:

Positron Version: 2024.08.0 (system setup) build 31
Code - OSS Version: 1.91.0
Commit: 7ee0596b81d578059e63c9af7c535c6b6040b947
Date: 2024-08-10T13:58:22.910Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

#### Interpreter details:

R 4.4.1

## Steps to reproduce the issue:

Reprex in the R console:

```r
# Works as expected
message("https://tidyverse.r-lib.org")

# Includes the closing ">" in the hyperlink
message("<https://tidyverse.r-lib.org>")
```

In the wild, there are a couple places in the tidyverse that prints `<url>` and hyperlinks incorrectly, like the tidyselect lifecycle warning:

```r
rlang::with_options({
  x <- 1; invisible(dplyr::select(mtcars, x))
}, lifecycle_verbosity = "warning")
```

## Expected or desired behavior:

Closing angled bracket should not be interpreted as part of the url.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-83
    OS Version          : OSX

### Test scenario(s) 

Verified according to original filing with modified URL that leads to a working page.

Link(s) to TestRail test cases run or created: 
N/A
