### ISSUE TITLE
WIndown SSH can't work

### ISSUE THREAD

**Issue by chmzs** [posit-dev/positron#4418]
## Steps to reproduce the issue:

1.
2.

**Comment by chmzs** [comment]
[Info  - 09:32:01.1] Resolving ssh remote authority 'ssh-remote+chmozs-server' (attemp #1)
[Error  - 09:32:01.49] Couldn't get identities from OpenSSH agent
Error: Failed to connect to agent
	at Socket.r (d:\Program Files\Positron\resources\app\extensions\open-remote-ssh\dist\extension.js:1:132148)
	at Socket.emit (node:events:514:28)
	at Socket.emit (node:domain:488:12)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[Trace  - 09:32:01.49] Identity keys:
C:\Users\chmzs/.ssh/id_rsa ssh-rsa SHA256:+Zv5ImK8j8TnlDYYfLc879INtIJDbbgz+2cIOeofV0c=
[Error  - 09:32:03.656] Error resolving authority
AggregateError: 
	at internalConnectMultiple (node:net:1114:18)
	at afterConnectMultiple (node:net:1667:5)

**Comment by jonvanausdeln** [comment]
Thanks for the report! Could you please share a little more information about your system?  Which Positron version are you using? What Windows Version? And the steps you followed to get to that error,

**Comment by chmzs** [comment]
**laptop**：Windows 11  23H2 22631.4037
**remote server**：Windows 11 Professional Workstation Edition  22H2  22621.4037
**Positron**
Positron Version: 2024.08.0 (system setup) build 48
Code - OSS Version: 1.91.0
Commit: ed616b36655fb24d116108bdd833f1321704315b
Date: 2024-08-19T03:30:12.447Z
提交: 29.4.0
日期: 122.0.6261.156
Electron: 20.9.0
ElectronBuildId: 12.2.281.27-electron.0
Chromium: Windows_NT x64 10.0.22631
Node.js: undefined
V8: undefined
OS: undefined

**Comment by jonvanausdeln** [comment]
Closing this for now. If there is additional information, please feel free to re-open or open a new issue.
