### ISSUE TITLE
Error when installing latest version on Windows (User install version)

### ISSUE THREAD

**Issue by Robinlovelace** [posit-dev/positron#4420]
With apologies for lack of detail (can provide later if needs be), just hit this error and thought it may be of use/interest to others.

## System details:

Windows 111

#### Positron and OS details:

```
Positron Version: 2024.08.0 (user setup) build 48
Code - OSS Version: 1.91.0
Commit: ed616b36655fb24d116108bdd833f1321704315b
Date: 2024-08-19T03:31:54.240Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
```

#### Interpreter details:

NA

## Describe the issue:

This message popped-up during the installation:

![image](https://github.com/user-attachments/assets/98bb1a80-cccf-4e82-a581-5305baf0e17d)

## Steps to reproduce the issue:

Install the .exe on Windows

## Expected or desired behavior:

No error messages during install

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Yes, see above.

**Comment by jonvanausdeln** [comment]
@Robinlovelace , thank you for the report!. This appears to be the same issue as #4387

**Comment by Robinlovelace** [comment]
Thanks @jonvanausdeln closing in favour of that #deduplication https://github.com/posit-dev/positron/issues/4387
