### ISSUE TITLE
Copy plot to clipboard errors in Positron Web

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#4433]
#### Positron and OS details:

Positron Version: 2024.03.0 build undefined
Code - OSS Version: 1.91.0-dev
Commit: Unknown
Date: Unknown
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

Ran in Arc Browser (Version 1.56.0 (52658); Chromium Engine Version 127.0.6533.120) on Mac, but any browser should do.

#### Interpreter details:

Any, but I was using R 4.3.1.

## Describe the issue:

The "copy plot to clipboard" action errors in the plots pane in Positron Web.

## Steps to reproduce the issue:

https://github.com/user-attachments/assets/669add95-dee4-478e-bc7d-938e2a9fb5e3

In Positron Web:
1. Start an R interpreter
2. Run `plot(iris)` in the console
3. Click the "copy plot to clipboard" button in the plots pane
4. The image doesn't get copied to the clipboard and there is an error in the console

## Expected or desired behavior:

The plot image should be copied to the clipboard, like on Positron Desktop.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Developer Tools console output:

```
  ERR Failed to execute 'write' on 'Clipboard': Failed to read or decode Blob for clipboard item type image/png.: Error: Failed to execute 'write' on 'Clipboard': Failed to read or decode Blob for clipboard item type image/png.
```

Relevant code

https://github.com/posit-dev/positron/blob/4d79266f9978279661ac0d3bae834cadae67c707/src/vs/platform/clipboard/browser/clipboardService.ts#L192-L201

**Comment by sharon-wang** [comment]
Right-click to copy the plot would be a great alternative to the copy button! Right-clicking currently doesn't seem to work on the plot, but a corresponding context menu like the one for the Console or an Editor would be great.

Here's a video where I `plot(iris`, then right-click in a few areas of the IDE:

https://github.com/user-attachments/assets/bb11a833-3f02-49a5-a1bf-ae941f4c141e

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-33
    OS Version          : OSX

### Test scenario(s) 

plot(iris)
sucessful copy to clipboard

Link(s) to TestRail test cases run or created: 
N/A
