### ISSUE TITLE
R: Console doesn't scroll down when input across lines

### ISSUE THREAD

**Issue by FinYang** [posit-dev/positron#4446]
In Positron, if I directly type multiline commands in the console, it doesn't scroll down to the input line automatically, but only scrolls down when I type on the new line. Notice the scrollbar on the right:

![Kapture 2024-08-23 at 02 18 10](https://github.com/user-attachments/assets/2937817c-a02d-4cbd-860d-85c2bca37723)

This is how it behaves in RStudio:

![Kapture 2024-08-23 at 02 21 22](https://github.com/user-attachments/assets/04f2f712-f565-4a58-a1a1-6c802834a9ae)

**Comment by juliasilge** [comment]
To me, this looks the same as #2755.

In general we still have a fair number of problems with the scroll lock; here are [all the issues about scrolling in the console](https://github.com/posit-dev/positron/issues?q=is:issue+is:open+label:%22area:+console%22+scroll) in case we can address some of them together.

**Comment by juliasilge** [comment]
We'll track this in #2755. Thanks!
