### ISSUE TITLE
Issue with in keras visualizations.

### ISSUE THREAD

**Issue by davidrsch** [posit-dev/positron#4457]
While trying to plot a keras model I get the following errors in Positron:

```
File "C:\Path\to\PYTHON~3\Lib\subprocess.py", line 992, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
                                  ^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Path\to\PYTHON~3\Lib\subprocess.py", line 1348, in _get_handles
    p2cread = _winapi.GetStdHandle(_winapi.STD_INPUT_HANDLE)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
```
while in RStudio it generates the desired plot. And when fitting the model no matter which verbose option I pass to `fit` function it doesn't generate any kind of output while in RStudio works. I am using `keras3` package, I don't know if this issues appears with previous version of keras or in other OS.

I tried to generate a reprex example using `reprex` package and it worked as expected:

```{r}
library(keras3)
library(reprex)
# Just for demonstration purposes.
inputs <- keras_input(shape = c(784))
dense <- layer_dense(units = 64, activation="relu")
x <- dense(inputs)
outputs <- x |>
  layer_dense(units = 64, activation = "relu") |>
  layer_dense(units = 10)
model <- keras_model(
  inputs = inputs, 
  outputs = outputs, 
  name = "mnist_model")
summary(model)
#> Model: "mnist_model"
#> ┌───────────────────────────────────┬──────────────────────────┬───────────────
#> │ Layer (type)                      │ Output Shape             │       Param # 
#> ├───────────────────────────────────┼──────────────────────────┼───────────────
#> │ input_layer (InputLayer)          │ (None, 784)              │             0 
#> ├───────────────────────────────────┼──────────────────────────┼───────────────
#> │ dense (Dense)                     │ (None, 64)               │        50,240 
#> ├───────────────────────────────────┼──────────────────────────┼───────────────
#> │ dense_1 (Dense)                   │ (None, 64)               │         4,160 
#> ├───────────────────────────────────┼──────────────────────────┼───────────────
#> │ dense_2 (Dense)                   │ (None, 10)               │           650 
#> └───────────────────────────────────┴──────────────────────────┴───────────────
#>  Total params: 55,050 (215.04 KB)
#>  Trainable params: 55,050 (215.04 KB)
#>  Non-trainable params: 0 (0.00 B)
plot(model)
```
![image](https://github.com/user-attachments/assets/4dc67be6-ad11-4dc6-ab82-5a4c4de8150e)

So I am clueless about what is going on here. How does it work when using reprex environment but not in global?

**Comment by juliasilge** [comment]
I am able to run this example in Positron and see the plot as expected:

![keras-plot](https://github.com/user-attachments/assets/4d12b1b8-8404-461f-8af6-b9ec64820232)

Can you share the info on versions of Positron, R, Python, etc that is requested in the issue template so we can check that out?

**Comment by davidrsch** [comment]
OS: Microsoft Windows Version 22H2 (OS Build 19045.4780)
Positron: 2024.08.0-48
R: 4.4.1
[renv.txt](https://github.com/user-attachments/files/16751936/renv.txt)

Python: 3.11.9
[requirements.txt](https://github.com/user-attachments/files/16751928/requirements.txt)

![image](https://github.com/user-attachments/assets/fb5765ca-1260-4b9f-bb22-96ee9ce948ae)

**Comment by jonvanausdeln** [comment]
I just tried on my windows box.. and I get a slightly different error on the plot step
```
> plot(model)
See ?keras3::plot.keras.src.models.model.Model for instructions on how to install graphviz and pydot.
Error in `py_call_impl()`:
! OSError: [WinError 6] The handle is invalid
Run `reticulate::py_last_error()` for details.

> reticulate::py_last_error()

── Python Exception Message ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "C:\Users\JONVAN~1\DOCUME~1\VIRTUA~1\r-keras\Lib\site-packages\pydot\core.py", line 1708, in write
    s = self.create(prog, format, encoding=encoding)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JONVAN~1\DOCUME~1\VIRTUA~1\r-keras\Lib\site-packages\pydot\core.py", line 1799, in create
    stdout_data, stderr_data, process = call_graphviz(
                                        ^^^^^^^^^^^^^^
  File "C:\Users\JONVAN~1\DOCUME~1\VIRTUA~1\r-keras\Lib\site-packages\pydot\core.py", line 222, in call_graphviz
    process = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\JONVAN~1\PYENV~1\PYENV-~1\versions\311~1.9\Lib\subprocess.py", line 992, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JONVAN~1\PYENV~1\PYENV-~1\versions\311~1.9\Lib\subprocess.py", line 1348, in _get_handles
    p2cread = _winapi.GetStdHandle(_winapi.STD_INPUT_HANDLE)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
```

**Comment by juliasilge** [comment]
cc @t-kalinowski thank you for taking a look at this!

**Comment by davidrsch** [comment]
Hello updated `reticulate` and tested it and it works fin, thanks @t-kalinowski and @juliasilge.
I have also noticed that not matter which verbosity I choose when fitting the model nothing gets printed or no plot appears in the viewer panel of positron. I almost certain that this is not related with neither positron or reticulate I think it's related with the api that `keras3` uses.

**Comment by t-kalinowski** [comment]
Thanks for reporting @davidrsch! The live metrics viewer is not expected to work yet (on any platform), but the lack of console output on Windows is a surprise. I opened #4580 to track it.
