### ISSUE TITLE
cntrl+shift+n File -> New Window opens a script

### ISSUE THREAD

**Issue by asadow** [posit-dev/positron#4460]
#### Positron and OS details:

Positron Version: 2024.08.0 (system setup) build 48
Code - OSS Version: 1.91.0
Commit: ed616b36655fb24d116108bdd833f1321704315b
Date: 2024-08-19T03:30:12.447Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

#### Interpreter details:

R 4.4.1 

## Describe the issue:
cntrl+shift+n File -> New Window opens a script

## Expected or desired behavior:

New Positron window

**Comment by juliasilge** [comment]
Thanks for this report! I can confirm that as of build 48, _both_ <kbd>Cmd</kbd>+<kbd>N</kbd> and <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd> open a new file and I cannot open a new window via keyboard shortcut at all. This is what the menu says (choosing the option in the menu still works):

![Screenshot 2024-08-23 at 8 35 52 AM](https://github.com/user-attachments/assets/d7738f2a-b5cb-4c08-8828-a4af2b181177)

This must be a recent regression because I was able to open a new window via keyboard shortcut fairly recently.

**Comment by DavisVaughan** [comment]
With build 48, `CMD + Shift + N` works as expected for me and opens a new window

**Comment by juliasilge** [comment]
It's the RStudio Keymap. When it is turned on, <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd> opens a new file instead of a new window:

https://github.com/posit-dev/positron/blob/fa78131f2a5a8a43eb6ebc60f78bf39f40dce4f4/extensions/positron-rstudio-keymap/package.json#L58

**Comment by DavisVaughan** [comment]
So, not a bug?

**Comment by juliasilge** [comment]
This is sort of related to https://github.com/posit-dev/positron/issues/2423 where we have a keyboard shortcut shown in the UI which does not actually work in some situations.

**Comment by juliasilge** [comment]
> So, not a bug?

I think it's reasonable to call this a bug; we have called #3847 and related issues bugs.

@asadow as a workaround, if you want to opt in to the RStudio Keymap but _not_ to this particular shortcut, you can create a [personal user keybinding](https://code.visualstudio.com/docs/getstarted/keybindings) to override it; it will take precedence. From the command palette you would choose "Open Keyboard Shortcuts (JSON") and add this to create the keybinding for you:

```json
    {
        "key": "ctrl+shift+n",
        "command": "workbench.action.newWindow",
    }
```

**Comment by DavisVaughan** [comment]
The bug is just that it shows the keycode for `CMD + Shift + N` beside the `File -> New Window` UI element, even though that combination has been overridden by the RStudio keymap, right?

**Comment by jennybc** [comment]
I think this problem about menus displaying keybindings that are not accurate, in light of extensions and user configuration is a general VS Code problem. That doesn't mean we can't or shouldn't solve it. But I don't think it's a problem of Positron's (sole) making.

**Comment by juliasilge** [comment]
Related to https://github.com/posit-dev/positron/issues/4254

**Comment by juliasilge** [comment]
This is actually exactly the same as #3400 so let's track this problem there. 👍
