### ISSUE TITLE
Editor font not being displayed properly

### ISSUE THREAD

**Issue by tomcardoso** [posit-dev/positron#4465]
I use "Operator Mono" as my editor font, same as when I was on VS Code. When I copied my settings over from VS, however, I found that my editor was always bolded:

![Screenshot 2024-08-23 at 12 19 16 PM](https://github.com/user-attachments/assets/40fafaf9-3125-45e8-ab4b-9d3eab76ad24)

Here's VS Code, for comparison:

<img width="779" alt="Screenshot 2024-08-23 at 12 20 32 PM" src="https://github.com/user-attachments/assets/4eb5a1e6-1dc8-4ebf-9d6a-b8f6c492852e">

I can get around this by explicitly using the PostScript name for the font ("OperatorMono-Book") in the `fontFamily` setting, but that doesn't solve my other issue: The theme I'm using declares comments as italics, but that reverts everything back to a faux bold italic, which I can't override, even with a `"editor.tokenColorCustomizations"` setting overwriting the fontStyle and/or fontFamily:

![Screenshot 2024-08-23 at 12 21 58 PM](https://github.com/user-attachments/assets/342c6da8-8aa8-4acc-92e5-cdeb0ccebd37)

I wonder if this is related to [this recently fixed bug in VS Code](https://github.com/microsoft/vscode/issues/214390), which perhaps hasn't been merged down to Positron yet? 

My Positron version info:
```
Positron Version: 2024.06.1 (Universal) build 54
Code - OSS Version: 1.90.0
Commit: 5115c73e0670f39139e55eeedf0717b468a0658d
Date: 2024-07-03T03:51:33.756Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin x64 23.1.0
```

**Comment by DavisVaughan** [comment]
Yea this is almost certainly that upstream bug which hasn't made it in yet

**Comment by jmcphers** [comment]
Your Positron version is also several months out of date -- a more recent version should have the bugfix.

**Comment by tomcardoso** [comment]
Welp, that's embarrassing for me! I assumed Positron was auto-updating this whole time, but I just updated manually and this is fixed. Closing.

**Comment by jmcphers** [comment]
That's a feature we hope to add! See https://github.com/posit-dev/positron/issues/1837.
