### ISSUE TITLE
Quarto YAML autocompletion doesn't work

### ISSUE THREAD

**Issue by FinYang** [posit-dev/positron#4476]
YAML autocompletion has no suggestions:
 
![Kapture 2024-08-26 at 22 46 47](https://github.com/user-attachments/assets/bb4abd90-7153-40c1-944f-b84944da0dbe)

while it works in VSCode, so I am guessing this is a Positron issue, not a quarto issue

![Kapture 2024-08-26 at 22 50 30](https://github.com/user-attachments/assets/07ba7cbf-aeaa-4aa0-9b2b-1c46023dc627)

Or it could be a me issue. I vaguely remember reading about YAML suggestions somewhere but couldn't find any documentation or issue.

I am using Quarto 1.5.56.

<details>
  <summary>Positron version info</summary>

Positron Version: 2024.08.0 (Universal) build 31
Code - OSS Version: 1.91.0
Commit: 7ee0596b81d578059e63c9af7c535c6b6040b947
Date: 2024-08-10T14:49:10.180Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.6.0
</details>

**Comment by FinYang** [comment]
My bad. Didn't realise it was controlled by `Suggest: Show Fields`. I had it off in my setting. All good now. This issue can be closed.

**Comment by isabelizimm** [comment]
Thank you so much for the report, I'm glad you were able to find that setting! Closing this out 👍
