### ISSUE TITLE
params not found .qmd

### ISSUE THREAD

**Issue by aito123** [posit-dev/positron#4492]
Hello I'm trying Positron coming from the RStudio IDE.
When I run the cells of a Quarto Markdown document that has parameters, the params object is automatically generated in RStudio, but that is not the case in Positron. That's why my console is throwing this error:

```
Caused by error:
! object 'params' not found 
```

If you run this reprex in Positron you can see that you cannot use the parameter values inside your Quarto document because the object is not automatically generated.

reprex:

````{qmd}
---
title: "reprex for positron"
format: html
params:
  mycolor: "red"
---


```{r}
library(tidyverse)
mtcars %>% 
    ggplot(aes(x = mpg, y = cyl)) +
    geom_point(color = params$mycolor)

```


````

#### Positron and OS details:

Positron Version: 2024.08.0 (Universal) build 31
Code - OSS Version: 1.91.0
Commit: 7ee0596b81d578059e63c9af7c535c6b6040b947
Date: 2024-08-10T14:49:10.180Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.6.0

#### Interpreter details:

R 4.4.0

**Comment by jmcphers** [comment]
Thanks for reporting! We're tracking this in https://github.com/posit-dev/positron/issues/4338 (please let us know if that doesn't look like your issue.)

**Comment by aito123** [comment]
Hi @jmcphers, thanks for pointing that out. Indeed looks like this issue has already been brought up in issue #4338. Thanks, keep up the hard work Positron could become the best of both worlds (vscode + Rstudio IDE 💙 ).
