### ISSUE TITLE
Quarto visual and source highlights are different (non-default themes)

### ISSUE THREAD

**Issue by melimelo24** [posit-dev/positron#4494]
#### Positron and OS details:

Positron Version: 2024.08.0 (Universal) build 48
Code - OSS Version: 1.91.0
Commit: ed616b36655fb24d116108bdd833f1321704315b
Date: 2024-08-19T04:26:51.868Z (1 wk ago)
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin x64 22.6.0

#### Interpreter details:

R 4.4.1

## Describe the issue:

In quarto visual editor mode, the highlights change back to default theme instead of the currently active theme. This is independent of whatever theme was selected in YAML.

Example below: same document opened in visual mode (default highlights), source mode (rosé pine dawn no italics highlights) and the HTML file rendered in the viewer (ayu highlights).
![Screenshot 2024-08-27 at 12 30 10](https://github.com/user-attachments/assets/4f9795c7-46d8-48bd-9391-67f4e56d01c7)

## Steps to reproduce the issue:

Using a non-default theme, create a qmd document, write anything and switch to visual mode.
`1 + 1 = "bob"`

## Expected or desired behavior:

Highlights should stay the same between visual and source mode. Some people might be interested in using the YAML defined highlight? (I am not :) )

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No, this is purely aesthetics issue.

**Comment by juliasilge** [comment]
The visual editor is provided by the Quarto VS Code extension (not Positron itself). Looks to me like this also happens when using the visual editor in VS Code so I don't think it's anything that Positron specifically is doing. Can you open an issue [on the Quarto extension repo](https://github.com/quarto-dev/quarto/issues) with these details? Thanks! 🙌
