### ISSUE TITLE
Switch from `r_parse_eval0` to `parse_eval_global()` or `parse_eval_base()`

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#4497]
In many of the data explorer tests we are using `r_parse_eval0` and manually specifying the environments.
Once https://github.com/posit-dev/ark/pull/480 is merged, we can then  use `parse_eval_global`, which should make the code simpler.

See also https://github.com/posit-dev/ark/pull/458#discussion_r1724902370

**Comment by lionel-** [comment]
Done in #480.
