### ISSUE TITLE
ARK: Build mac artifacts using a GitHub arm64 runner

### ISSUE THREAD

**Issue by petetronic** [posit-dev/positron#4499]
Task to track to the work to migrate [ARK](https://github.com/posit-dev/ark) [mac builds](https://github.com/posit-dev/ark/blob/076610c59a0695a5d65e3d6273fd3cf4dc429d5b/.github/workflows/release.yml#L61) to use an arm64 based GitHub github runner.

**Comment by petetronic** [comment]
Can we please address this before the end of September 2024?

**Comment by lionel-** [comment]
We now build ark releases on the default macOS runner. I've tested the arm64 arm of the universal build locally, and @DavisVaughan tested the x86_64 arm on his Intel mac (thanks!).

Is this good to close @petetronic or does this need more QA?

**Comment by petetronic** [comment]
Thanks @lionel- for doing this so quickly. We can close this and we'll let you know if we run into any issues.
