### ISSUE TITLE
Build ark for supported x86_64 linux platforms

### ISSUE THREAD

**Issue by lionel-** [posit-dev/positron#4506]
Needed for https://github.com/posit-dev/positron/issues/1617

Related discussions in https://github.com/posit-dev/positron/issues/1619 and https://github.com/posit-dev/positron/issues/3854

See supported x86_64 platforms on https://dailies.rstudio.com

- Ubuntu 20
- Ubuntu 22 
- Ubuntu 24 
- RedHat 8
- RedHat 9
- SUSE 15+

We can take two approaches:

- Build ark on every platforms. With our current infrastructure (github actions) that would require many custom runners, not all of which might be possible.

- Build ark on a single platform and make sure it can load everywhere. The main hurdles here are incompatibilities with target glibc versions (https://github.com/posit-dev/positron/issues/3854) and target openssl versions (https://github.com/posit-dev/positron/issues/3854#issuecomment-2226860016).

**Comment by lionel-** [comment]
QA: I've already verified that ark now runs on these platforms by using it with jupyter-console:

```sh
fuzzbucket-client create ubuntu20-ide-prereqs-ci
fuzzbucket-client create ubuntu22-ide-prereqs
fuzzbucket-client create ubuntu24-ide-prereqs-ci
fuzzbucket-client create rhel8-ide-prereqs
fuzzbucket-client create rhel9-ide-prereqs
fuzzbucket-client create opensuse15.2
fuzzbucket-client create opensuse15.5-ide-prereqs-ci
```

See @dskard's notes for testing within Positron using a VNC connection: https://github.com/posit-dev/positron/issues/1619#issuecomment-1964637961

**Comment by juliasilge** [comment]
## QA Notes

Once we have verified this issue, can we work on evaluating if there is still any work to do for #3715? i.e. can we make the RPM build available again?

**Comment by jonvanausdeln** [comment]
We were able to verify that Ark seems to work with what we have available for Linux to test.

@juliasilge , I am hesitant to start pushing RPM build right now, as we haven't tested it very much yet.
