### ISSUE TITLE
Build ark for supported arm64 linux platforms

### ISSUE THREAD

**Issue by lionel-** [posit-dev/positron#4507]
Needed for https://github.com/posit-dev/positron/issues/1617

Sibling issue for x86_64: https://github.com/posit-dev/positron/issues/4506

See supported arm64 platforms on https://dailies.rstudio.com/

 - Ubuntu 22
 - Ubuntu 24
 - RedHat 9

Potential approaches:

- Build on an arm64 GHA runner. This is not part of the default supported platforms so we'd need a custom runner.

- Cross compile with https://github.com/cross-rs/cross. This cross-compiles in a docker or podman container. I tried this and unfortunately the toolchain of the default image seems too old for 0mq. This can probably be solved as it's possible to define custom toolchains: https://github.com/cross-rs/cross-toolchains. I'm not sure podman is supported in this case as they only mention docker. Would require a docker license in this case.

  One advantage of this approach is that we can also run ark in the container to test it.

- Cross compile with https://github.com/rust-cross/cargo-zigbuild. This might be tricky with  system libs like openssl. We might have better luck by compiling openssl as part of the build, and the openssl-sys crate has support for this ("vendored" feature), but I had trouble getting this to work.

**Comment by kevinushey** [comment]
I tried this with the debug build of ark and jupyter-console just hangs:

```
kevin@kbox:~/Downloads
$ ./ark --install
Successfully installed Ark Jupyter kernelspec.

    R (4.3.3): /usr/lib/R
    Kernel: /home/kevin/.local/share/jupyter/kernels/ark/kernel.json
    
kevin@kbox:~/Downloads
$ RUST_LOG=warn jupyter-console --kernel=ark
```

The release build seems to work, but we do get some warnings on startup:

```
$ RUST_LOG=warn jupyter-console --kernel=ark
/home/kevin/Downloads/venv/lib/python3.12/site-packages/jupyter_console/ptshell.py:136: UserWarning: No lexer found for language ''. Treating as plain text.
  warn("No lexer found for language %r. Treating as plain text." % name)
Jupyter console 6.6.3
```

I also get some unexpected output on the first code execution:

```
In [1]: 1 + 1  2024-09-11T19:34:40.519221Z  WARN  Could not read message from shell socket: Unknown message type 'history_request'
    at crates/amalthea/src/socket/shell.rs:122

Using libraries at paths:
- /home/kevin/R/aarch64-unknown-linux-gnu-library/4.3
- /usr/local/lib/R/site-library
- /usr/lib/R/site-library
- /usr/lib/R/library
In [1]: 1 + 1
Out[1]: [1] 2
```

The library path stuff comes from my .Rprofile, where I use `message()` to write some outputs to the console on startup.

**Comment by jonvanausdeln** [comment]
Seems that it works well enough for the context of this issue, so closing it.
