### ISSUE TITLE
Bundled Quarto not found if not on PATH and using Pyenv

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#4511]
Need to handle https://github.com/quarto-dev/quarto/issues/517 on the Positron side.

#### Positron and OS details:

[2024.08.0-77](https://github.com/posit-dev/positron-builds/releases/tag/2024.08.0-77)
OSX

#### Interpreter details:

Any

## Describe the issue:

See https://github.com/quarto-dev/quarto/issues/517

## Steps to reproduce the issue:

See https://github.com/quarto-dev/quarto/issues/517

## Expected or desired behavior:
Bundled Quarto can be used without a seperate Quarto install

## Were there any error messages in the UI, Output panel, or Developer Tools console?

See https://github.com/quarto-dev/quarto/issues/517

## Once we have fixed 
We will need to make changes to our Quarto tests.  @testlabauto [created a work around](https://github.com/posit-dev/positron/pull/4754/files) for this issue.  Once we make this fixed we will need to change our Quarto tests to ensure they are working as expected.

**Comment by juliasilge** [comment]
From @jmcphers:

> pre-bundling Quarto (as was done in #3705) doesn't fix the problem of Positron working without an existing Quarto installation if you're using Pyenv, due to a bad interaction between Pyenv and the Quarto extension. 
>
> The actual change will probably need to happen in the Quarto extension and is tracked by https://github.com/quarto-dev/quarto/issues/517.

**Comment by jlang-311** [comment]
@testlabauto [created a work around](https://github.com/posit-dev/positron/pull/4754/files) for this issue.  Once we make this fixed we will need to change our Quarto tests to ensure they are working as expected.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-41
    OS Version          : OSX

### Test scenario(s) 

Verified by removing local quarto cli install.  Note that the "workaround" mentioned in the comments needs to stay where it is because dev build do not have the bundled CLI.

Link(s) to TestRail test cases run or created:
