### ISSUE TITLE
Variables pane crashes when called with ALTREP strings objects

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#4512]
Here's a reprex:

```
x <- c(1:64) # We need at least length=64 to cause a crash
names(x) <- x
z <- names(x)
```
In this example AFAICT `names()` returns a defered string (as in [here](https://github.com/wch/r-source/blob/10244dca178302e4caf760b2f81c73000996e47d/src/main/altclasses.c#L597))

And the error seems to be caused by the call the `object.size()` when creating the variable for the Variables pane.
The issue is caused by the defered string to have a malformed string object returned by `R_altrep_data2(x)`,
which is actually a STRSXP, with the same length as `x` but with non initialized elements. But `object.size()` expects all elements to be CHARSXP. See [here](https://github.com/wch/r-source/blob/10244dca178302e4caf760b2f81c73000996e47d/src/main/altclasses.c#L691-L694)

The crash backtrace:

<details>

```
[R]   2024-08-28T17:38:16.407739Z ERROR  
[R] >>> Backtrace for signal 11
[R] >>> In thread main
[R]    0: std::backtrace::Backtrace::create
[R]    1: ark::traps::backtrace_handler
[R]    2: __simple_esappend
[R]    3: _objectsize
[R]    4: _objectsize
[R]    5: _objectSize
[R]    6: R_doDotCall
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/dotcode.c:868:17
[R]    7: bcEval
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:8002:21
[R]    8: Rf_eval
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:1013:8
[R]    9: forcePromise
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:833:8
[R]   10: FORCE_PROMISE
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:5467:15
[R]   11: getvar
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:5508:14
[R]   12: bcEval
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:7198:20
[R]   13: Rf_eval
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:1013:8
[R]   14: R_execClosure
[R]   15: Rf_applyClosure
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:2113:16
[R]   16: bcEval
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:7414:12
[R]   17: Rf_eval
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:1013:8
[R]   18: R_execClosure
[R]   19: Rf_applyClosure
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:2113:16
[R]   20: Rf_eval
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:1140:12
[R]   21: harp::exec::try_catch::callback
[R]   22: R_withCallingErrorHandler
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/errors.c:2613:16
[R]   23: harp::exec::top_level_exec::callback
[R]   24: R_ToplevelExec
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/context.c:799:2
[R]   25: harp::exec::try_eval
[R]   26: harp::exec::RFunction::call
[R]   27: harp::object::r_size
[R]   28: ark::variables::variable::PositronVariable::from
[R]   29: ark::variables::variable::PositronVariable::new
[R]   30: ark::variables::r_variables::RVariables::update::{{closure}}
[R]   31: core::ops::function::FnOnce::call_once{{vtable.shim}}
[R]   32: harp::exec::try_catch::callback
[R]   33: R_withCallingErrorHandler
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/errors.c:2613:16
[R]   34: harp::exec::top_level_exec::callback
[R]   35: R_ToplevelExec
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/context.c:799:2
[R]   36: harp::exec::r_sandbox
[R]   37: tracing::span::Span::in_scope
[R]   38: ark::interface::RMain::handle_task
[R]   39: ark::interface::RMain::handle_task_interrupt
[R]   40: ark::interface::RMain::read_console
[R]   41: harp::exec::try_catch::callback
[R]   42: R_withCallingErrorHandler
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/errors.c:2613:16
[R]   43: harp::exec::top_level_exec::callback
[R]   44: R_ToplevelExec
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/context.c:799:2
[R]   45: harp::exec::r_sandbox
[R]   46: _r_read_console
[R]   47: Rf_ReplIteration
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/main.c:210:10
[R]   48: R_ReplConsole
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/main.c:314:11
[R]   49: run_Rmainloop
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/main.c:1200:5
[R]   50: ark::interface::start_r
[R]   51: ark::main
[R]   52: std::sys_common::backtrace::__rust_begin_short_backtrace
[R]   53: std::rt::lang_start::{{closure}}
[R]   54: std::rt::lang_start_internal
[R]   55: _main
[R] 
[R]     at crates/ark/src/traps.rs:41
[R]     in R task with thread: "ark-variables", interrupt: true
[R]     in update
```

</details>

Another example is the following:

```
f <- function() {
  x <- 1:1e10
  names(x) <- x
  list(x = names(x))
}

x <- f()
```

In this case, we see that the `object.size()` call is somehow triggering the ALTREP object to be materialized, which will then crash the session because it tries to allocate the large vector.

Backtrace:

<details>
R]   2024-08-28T17:57:26.973098Z ERROR  Panic! In file 'crates/ark/src/r_task.rs' at line 220: While running task: vector memory exhausted (limit reached?)
[R] 
[R] R backtrace:
[R] 0. try_catch_handler(structure(list(message = "vector memory exhausted (limit reached?)", 
[R]        call = NULL), class = c("simpleError", "error", "condition"
[R]    )))
[R] 1. h(simpleError(msg, call))
[R] 2. .handleSimpleError(function (cond) 
[R]    .Internal(C_tryCatchHelper(addr, 1L, cond)), "vector memory exhausted (limit reached?)", 
[R]        base::quote(NULL))
[R] 
[R] 
[R] R thread backtrace:
[R]    0: std::backtrace::Backtrace::create
[R]    1: harp::exec::try_catch::handler
[R]    2: do_internal
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/names.c:1404:11
[R]    3: Rf_eval
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:1092:12
[R]    4: R_execClosure
[R]    5: Rf_applyClosure
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:2113:16
[R]    6: bcEval
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:7414:12
[R]    7: Rf_eval
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:1013:8
[R]    8: R_execClosure
[R]    9: Rf_applyClosure
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:2113:16
[R]   10: Rf_eval
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/eval.c:1140:12
[R]   11: vsignalError
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/errors.c:1903:3
[R]   12: Rf_errorcall
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/errors.c:912:5
[R]   13: mem_err_heap
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/memory.c:2143:5
[R]   14: R_gc_internal
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/memory.c:3130:8
[R]   15: Rf_allocVector3
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/memory.c:2808:2
[R]   16: Rf_allocVector
[R]              at /Volumes/Builds/R4/R-4.3.1/src/include/Rinlinedfuns.h:595:12
[R]   17: ExpandDeferredStringElt
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/altclasses.c:692:8
[R]   18: deferred_string_Elt
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/altclasses.c:779:13
[R]   19: ALTSTRING_ELT
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/altrep.c:529:11
[R]   20: harp::vector::Vector::format_elt_unchecked
[R]   21: <harp::vector::formatted_vector::FormattedVectorIter as core::iter::traits::iterator::Iterator>::next
[R]   22: ark::variables::variable::WorkspaceVariableDisplayValue::from
[R]   23: ark::variables::variable::WorkspaceVariableDisplayValue::from
[R]   24: ark::variables::variable::PositronVariable::from
[R]   25: ark::variables::variable::PositronVariable::new
[R]   26: ark::variables::r_variables::RVariables::update::{{closure}}
[R]   27: core::ops::function::FnOnce::call_once{{vtable.shim}}
[R]   28: harp::exec::try_catch::callback
[R]   29: R_withCallingErrorHandler
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/errors.c:2613:16
[R]   30: harp::exec::top_level_exec::callback
[R]   31: R_ToplevelExec
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/context.c:799:2
[R]   32: harp::exec::r_sandbox
[R]   33: tracing::span::Span::in_scope
[R]   34: ark::interface::RMain::handle_task
[R]   35: ark::interface::RMain::handle_task_interrupt
[R]   36: ark::interface::RMain::read_console
[R]   37: harp::exec::try_catch::callback
[R]   38: R_withCallingErrorHandler
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/errors.c:2613:16
[R]   39: harp::exec::top_level_exec::callback
[R]   40: R_ToplevelExec
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/context.c:799:2
[R]   41: harp::exec::r_sandbox
[R]   42: _r_read_console
[R]   43: Rf_ReplIteration
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/main.c:210:10
[R]   44: R_ReplConsole
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/main.c:314:11
[R]   45: run_Rmainloop
[R]              at /Volumes/Builds/R4/R-4.3.1/src/main/main.c:1200:5
[R]   46: ark::interface::start_r
[R]   47: ark::main
[R]   48: std::sys_common::backtrace::__rust_begin_short_backtrace
[R]   49: std::rt::lang_start::{{closure}}
[R]   50: std::rt::lang_start_internal
[R]   51: _main
[R] 
[R] 
[R] Backtrace of calling thread:
[R] 
[R]    0: std::backtrace::Backtrace::create
[R]    1: ark::r_task::r_task
[R]    2: ark::variables::r_variables::RVariables::update
[R]    3: ark::variables::r_variables::RVariables::execution_thread
[R]    4: std::sys_common::backtrace::__rust_begin_short_backtrace
[R]    5: core::ops::function::FnOnce::call_once{{vtable.shim}}
[R]    6: std::sys::pal::unix::thread::Thread::new::thread_start
[R]    7: __pthread_joiner_wake
[R] 
[R] 
[R] Backtrace:
[R]    0: std::backtrace::Backtrace::create
[R]    1: ark::main::{{closure}}::{{closure}}
[R]    2: ark::main::{{closure}}
[R]    3: std::panicking::rust_panic_with_hook
[R]    4: std::panicking::begin_panic_handler::{{closure}}
[R]    5: std::sys_common::backtrace::__rust_end_short_backtrace
[R]    6: _rust_begin_unwind
[R]    7: core::panicking::panic_fmt
[R]    8: ark::r_task::r_task
[R]    9: ark::variables::r_variables::RVariables::update
[R]   10: ark::variables::r_variables::RVariables::execution_thread
[R]   11: std::sys_common::backtrace::__rust_begin_short_backtrace
[R]   12: core::ops::function::FnOnce::call_once{{vtable.shim}}
[R]   13: std::sys::pal::unix::thread::Thread::new::thread_start
[R]   14: __pthread_joiner_wake
[R] 
[R]     at crates/ark/src/main.rs:489
[R]     in update
[R] 
[R]   2024-08-28T17:57:27.228675Z TRACE  Sending 'stream' message via IOPub socket
[R]     at crates/amalthea/src/wire/wire_message.rs:204
[R] 
[R] 
</details>

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.08.0-88
    OS Version          : OSX

### Test scenario(s) 

First example now works.

Second example exposed a new issue: https://github.com/posit-dev/positron/issues/4537

Link(s) to TestRail test cases run or created:
N/A
