### ISSUE TITLE
Repeated output with pauses + newlines loses text

### ISSUE THREAD

**Issue by hadley** [posit-dev/positron#4519]
#### Positron and OS details:

Positron Version: 2024.07.0 (Universal) build 125
Code - OSS Version: 1.91.0
Commit: cae4905332a0f41a6233e196b48a6679b832000a
Date: 2024-08-01T00:27:06.019Z (3 wks ago)
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

#### Interpreter details:

R 4.4.0

## Describe the issue:

Sometimes printed output is silently lost from the console.

## Steps to reproduce the issue:

```R
tokens <- c("", "Why", " do", " programmers", " prefer", " dark", " mode", 
"?\n\n", "Because", " light", " attracts", " bugs", "!")

# Always ok
for(token in tokens) {cat(token)}

# Sometimes misses on one or words in the second paragraph
for(token in tokens) {cat(token); Sys.sleep(0.01)}
```

## Expected or desired behavior:

Output shouldn't go missing 😄

**Comment by hadley** [comment]
Just updated positron and I still see the problem:

Positron Version: 2024.08.0 (Universal) build 48
Code - OSS Version: 1.91.0
Commit: ed616b36655fb24d116108bdd833f1321704315b
Date: 2024-08-19T04:26:51.868Z (1 wk ago)
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

**Comment by juliasilge** [comment]
Do we think this may be another example of problems arising from our current approach to #1762? It is a `for()` loop where things are getting dropped, however, and not literal lines of code.

**Comment by DavisVaughan** [comment]
This is likely a unique bug we haven't seen before

**Comment by hadley** [comment]
I was reminded of this issue again today as I was working on [elmer](https://github.com/hadley/elmer). It makes it really difficult to use streaming output (which you really want to do for a good user experience).

**Comment by DavisVaughan** [comment]
Bumping priority so 2024.11

**Comment by DavisVaughan** [comment]
Enabling trace mode shows that I don't think this is an ark issue, I think it is a Console issue. Ark is indeed forwarding all relevant output to the frontend. In this case that 2nd stream message is getting dropped somehow

<img width="817" alt="Screenshot 2024-09-27 at 3 23 26 PM" src="https://github.com/user-attachments/assets/46a80110-73a7-4172-9875-50b2a7efb475">

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-107
    OS Version          : OSX

### Test scenario(s) 

No output is dropped now.

Link(s) to TestRail test cases run or created:
