### ISSUE TITLE
ark: support 'dotty' destructuring assignments

### ISSUE THREAD

**Issue by kevinushey** [posit-dev/positron#4544]
The [dotty](https://cran.r-project.org/web/packages/dotty/index.html) package allows users to write code like:

```
.[nr, nc] <- dim(cars)
```

Could `ark`'s diagnostic system support such assignments, so that the following diagnostic is no longer produced?

<img width="388" alt="Screenshot 2024-08-31 at 5 21 57 PM" src="https://github.com/user-attachments/assets/c6dc0165-1c5f-4b9b-a9df-75eaebcbf288">

Note that transformations are also allowed, e.g. this is also valid:

```
.[mpg2 = mpg * 2] <- mtcars
```

**Comment by lionel-** [comment]
There is also https://github.com/r-lib/zeallot

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-95
    OS Version          : OSX

### Test scenario(s) 

Verified with filing examples

Link(s) to TestRail test cases run or created:
