### ISSUE TITLE
Starting a Python venv in one workspaces sometimes causes it to also start in another workspace

### ISSUE THREAD

**Issue by georgestagg** [posit-dev/positron#4552]
#### Positron and OS details:

Currently below, but have mostly seen in in older builds.

Positron Version: 2024.08.0 (Universal) build 48
Code - OSS Version: 1.91.0
Commit: ed616b36655fb24d116108bdd833f1321704315b
Date: 2024-08-19T04:26:51.868Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

#### Interpreter details:

R 4.4.0, Python 3.10.11 (with a venv)

## Describe the issue:
When multiple workspaces are open, starting a Python venv in one workspaces sometimes causes it to start in another unrelated workspace.

I was able to catch this movie in an older version of Positron:

https://github.com/user-attachments/assets/407b1052-b1c2-4c0f-810b-968ac66d1e43

## Steps to reproduce the issue:

I am unable to reliably reproduce the problem, most of the time it works OK.

## Expected or desired behavior:

Starting a venv in one workspace should not affect any other workspaces, especially not ones with just an R interpreter running as Python seems to be "greedy" and takes over the console.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Last time I had the issue I saved this log. I am unsure if it is useful. I'll update with more if I can catch it happening again.

[greedy_python.log](https://github.com/user-attachments/files/16846357/greedy_python.log)

**Comment by jthomasmock** [comment]
We should do a bug bash on multi-window Positron and making sure there isn't bleed over between sessions.

**Comment by cwickham** [comment]
I've also experienced this, and in particular, it seems related to the "user" `Python: Default Interpreter Path` being set. 

This video is with Positron Version: 2024.09.0 (Universal) build 45, two new empty workspaces:
1. Select a Python interpreter in one workspace.
2.  `Python: Default Interpreter Path` gets set, and other project starts the same Python interpreter in the Console.

https://github.com/user-attachments/assets/ab02a17f-b246-4b15-90f8-747755944bcf

**Comment by juliasilge** [comment]
I did a bit of exploration of this today, and it looks like:

- When you start a Python runtime, that updates/sets the user level config `defaultInterpreterPath`. You end up here:

https://github.com/posit-dev/positron/blob/67cf79b66db6af9840b649746e845c30458c600b/extensions/positron-python/src/client/common/configSettings.ts#L75

- When you set/update the user level config `defaultInterpreterPath`, that triggers the Python extension to start that runtime in a workspace. I see `'Extension-requested runtime restart via Positron API'`.

I may not be entirely understanding the situation, but both of these seem wrong to me.

**Comment by juliasilge** [comment]
I think the second bullet is more complex and not due (or entirely due) to something we have done or added. We can solve the present user-facing problem just by addressing how we are updating the setting globally.

Some notes about the config `python.defaultInterpreterPath`:

- If you are in a workspace with no Python running and then set `python.defaultInterpreterPath` manually in the settings UI, Python will start in that workspace but it is _not necessarily the Python you just set as a default_. 😱 
- Like I mentioned before, the message on the Positron side is `'Extension-requested runtime selection via Positron API'`.
- The `onDidChangeConfiguration` handlers in the Python extension are pretty complex, but probably the place to start to untangle what's going on here.
- One of the suspicious places I explored was here (if configuration changes, trigger environment selection) but I did not entirely get clarity and I don't believe there is much around here we have changed:

https://github.com/posit-dev/positron/blob/f786b010922f6b80b3ed7ae14ad7829d4a73300d/extensions/positron-python/src/client/application/diagnostics/checks/pythonInterpreter.ts#L136-L140

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-76
    OS Version          : OSX

### Test scenario(s) 

Unable to repro with specified version after multiple changes to interpreter in both instances of app.

Link(s) to TestRail test cases run or created:
