### ISSUE TITLE
Add a `serverReadyAction.action` to open the URI in the Viewer pane

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#4553]
There is existing support to configure debugging to run some action when a server starts, determined by scraping the contents of the terminal ([docs](https://code.visualstudio.com/docs/editor/debugging#_automatically-open-a-uri-when-debugging-a-server-program)). This is implemented in the `debug-server-ready` extension.

There are actions to open the URI externally, or debug in Chrome/Edge. We should add an action to open the URI in the Viewer pane.

Here's how you might use it with Streamlit.

1. Create an `app.py` file with:
    ```python
    import pandas as pd
    df = pd.DataFrame({
      'first column': [1, 2, 3, 4],
      'second column': [10, 20, 30, 40]
    })
    df
    ```
2. Create a `launch.json` with:
    ```json
    {
      "configurations": [
        {
          "name": "Streamlit",
          "type": "debugpy",
          "request": "launch",
          "module": "streamlit",
          "args": [
            "run",
            "${file}",
            "--server.headless",
            "true",
          ],
          "console": "integratedTerminal",
          "serverReadyAction": {
            "action": "openInViewer",
            "killOnServerStop": false,
            "pattern": "Local URL: http://localhost:([0-9]+)",
            "uriFormat": "http://localhost:%s",
          }
        }
      ]
    }
    ```
3. Start the `Streamlit` debugger configuration.
4. It should debug the app (stopping at any breakpoints) and display the app in the Viewer pane.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-11
    OS Version          : OSX

### Test scenario(s) 

debugging with the specified launch.json works with the streamlit-py-example from [qa-example-content](https://github.com/posit-dev/qa-example-content/tree/main)

Link(s) to TestRail test cases run or created: 
N/A
