### ISSUE TITLE
Automatically open external application URIs (e.g. streamlit, gradio) in the Viewer pane

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#4555]
When a user runs a command like "Run Streamlit App",  we should automatically open the app's URI in the Viewer pane. It should be built in a way that makes it easy to add new application development frameworks down the line.

The tricky part is determining the URI. There are at least three ways we can do that:

1. **Determine an open port and run command ourselves.** The `vscode-shiny` extension does this.
2. **Scrape the terminal.** The `debug-server-ready` built-in extension adds the `serverReadyAction` property of `launch.json` debugger configurations, which runs an action when a given pattern is matched in the terminal output, but only for debugging ([docs](https://code.visualstudio.com/docs/editor/debugging#_automatically-open-a-uri-when-debugging-a-server-program)).
3. **Poll for opened ports.** Workbench does this.

---

This functionality will be needed by:

* https://github.com/posit-dev/positron/issues/3023
* https://github.com/posit-dev/positron/issues/3027
* https://github.com/posit-dev/positron/issues/3026
* https://github.com/posit-dev/positron/issues/3025
* https://github.com/posit-dev/positron/issues/3024

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-95
    OS Version          : OSX

### Test scenario(s) 

Verified with various app types

Link(s) to TestRail test cases run or created:
