### ISSUE TITLE
python: implement generic "Run app" button

### ISSUE THREAD

**Issue by isabelizimm** [posit-dev/positron#4557]
Once the Positron Python extension has determined a user is in an app, there should be a "Run App" option (perhaps with a "Debug App" option as well) in the play button. Clicking this button should call the appropriate command for the app framework in a new terminal instance.

Related to #4555 #3023 #3025 #3024 #3027

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-95
    OS Version          : OSX

### Test scenario(s) 

Verified with FastAPI.  Will cross check with other apps.

Link(s) to TestRail test cases run or created:
