### ISSUE TITLE
Data-App Support Epic

### ISSUE THREAD

**Issue by nstrayer** [posit-dev/positron#4558]
Epic for improved support of "data apps:" e.g. Gradio, Streamlit, Dash, etc.. 

Ultimately we want Positron to feel natural and intuitive to use for writing and running these applications. 

### General Topics

- How to detect what files represent a data app
- Handling running a server in a terminal and displaying the output to the user via the viewer pane
- Making all of this easy to use for third parties with extension endpoints. 

### Sub-Issues
- #4557
- #4555
- #4553
- #4560

**Comment by seeM** [comment]
Notes on different app frameworks:

* **Streamlit:**
    * _Run:_ `python -m streamlit run <file>`.
    * _Port:_ configured via `--server.port` argument or via `config.toml` file (accessible via CLI `streamlit config show`).
    * _URL output:_ `  Local URL: http://localhost:<port>`.
    * May also want to set `--server.headless true` to stop an external browser from opening.
* **Dash:**
    * _Run:_ `python <file>`, assuming the file calls `dash.Dash.run()` (or the deprecated `.run_server`).
    * _Port:_ configured via `run(port=...)` or the `PORT` environment variable.
    * _URL output:_ `Dash is running on http://127.0.0.1:<port>/`.
    * _Workbench:_
        * Parses the server port from `run(...)` args.
        * Warns if `requests_pathname_prefix` appears in the file, since it needs to control it via the `DASH_REQUESTS_PATHNAME_PREFIX` environment variable.
* **Gradio:**
    * _Run:_ `python <file>`, assuming the file calls `gradio.Interface.launch`.
    * _Port:_ Configured via `launch(server_port=...)` or `GRADIO_SERVER_PORT` environment variable.
    * _URL output:_ `Running on local URL:  http://127.0.0.1:<port>`.
* **FastAPI:** (should be the same for any ASGI server framework).
    * _Run:_ `python -m uvicorn <file>:<appObject>` or `python <file>` assuming the file calls `uvicorn.run`.
        * `file` must be in Python module format (e.g. `myapp.subfolder.app`), not ordinary path format (e.g. `myapp/subfolder/app.py`).
        * `appObject` is the name of a `fastapi.FastAPI` object defined in `file`.
    * _Port:_ If run like `python -m uvicorn`, configured via `--port` argument or `UVICORN_PORT` environment variable. Otherwise must be set via `uvicorn.run(port=...)`.
    * _URL output_: `INFO:     Uvicorn running on http://127.0.0.1:<port> (Press CTRL+C to quit)`
    * _Workbench:_
        * Needs to control `--root-path` or `uvicorn.run(root_path=...)`.
* **Flask**:
    * _Run:_ `python -m flask --app <file>:<appObject> run` (see the notes on `file` and `appObject` in FastAPI section), or `python <file>` assuming the file calls `flask.Flask.run`. Note that this is a dev server. Development servers are treated differently.
    * _Port:_ Configured via `--port` argument, `FLASK_RUN_PORT` environment variable, or `Flask.run(port=...)`.
    * _URL output:_ ` * Running on http://127.0.0.1:5000`.
    * _Workbench:_
        * Needs to include `ProxyFix` middleware ([docs](https://flask.palletsprojects.com/en/2.3.x/deploying/proxy_fix/)).

**Comment by jonvanausdeln** [comment]
we've verified all the associated issues and added some automated tests for different apps.
