### ISSUE TITLE
python: detect if `.py` file is an application

### ISSUE THREAD

**Issue by isabelizimm** [posit-dev/positron#4560]
To support running web applications in the viewer via a "Run App" button, there should be some way to determine if a `.py` script is an app.

Potential ideas:
- imports (eg, `import streamlit as st` is a good signal of a streamlit app) 
- file name (eg, `app.py`)

Related #3024 #3025 #3026 #3027

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-95
    OS Version          : OSX

### Test scenario(s) 

Verified with FastAPI

Link(s) to TestRail test cases run or created:
