### ISSUE TITLE
Bundled Quarto not found if not on PATH and using Pyenv

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#4561]
This is a placeholder issue tracking the fact that pre-bundling Quarto (as was done in #3705) doesn't fix the problem of Positron working without an existing Quarto installation if you're using Pyenv, due to a bad interaction between Pyenv and the Quarto extension. 

The actual change will probably need to happen in the Quarto extension and is tracked by https://github.com/quarto-dev/quarto/issues/517.

**Comment by juliasilge** [comment]
Duplicate of #4511
