### ISSUE TITLE
Progress bar on plot in editor should show at the top

### ISSUE THREAD

**Issue by timtmok** [posit-dev/positron#4562]
![image](https://github.com/user-attachments/assets/88ac009a-ce40-4a78-bc88-3fb6e22900cc)

The plot in an editor feature renders progress bars centered in the editor. It should be aligned at the top of the editor like in the Plots view.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-95
    OS Version          : OSX

### Test scenario(s) 

Verified with R plot

library('corrr')

x <- correlate(mtcars)
rplot(x)

# Common use is following rearrange and shave
x <- rearrange(x, absolute = FALSE)
x <- shave(x)
rplot(x)
rplot(x, print_cor = TRUE)
rplot(x, shape = 20, colors = c("red", "green"), legend = TRUE)

Link(s) to TestRail test cases run or created:
