### ISSUE TITLE
UI is very slow after creating a large character variable

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#4573]
Positron Version:

Positron Dev Version: 2024.09.0 build 0
Code - OSS Version: 1.92.0
Commit: Unknown
Date: Unknown
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0

If you read a large text file into a single string with eg (`readr::read_file`) the UI becomes almost unusable. A reprex:

```
x <- paste(1:5e6, collapse = "-")
```

https://github.com/user-attachments/assets/d0625079-c81a-43ee-b4df-87c6a428dcf7

This doesn't happen with Python, eg. if you do `x = "-".join(["---------"]*1_000_000)`.

We should probably limit the size of the string we send to the front-end, or like RStudio, show something like:

![image](https://github.com/user-attachments/assets/aeb87326-fa25-44b3-a7d8-3ff7ec7f68c9)

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-66
    OS Version          : OSX

### Test scenario(s) 

UI no longer becomes sluggish after executing reprex

Link(s) to TestRail test cases run or created:
