### ISSUE TITLE
Multiplots with par and mfrow does not work

### ISSUE THREAD

**Issue by arnaldmarcer** [posit-dev/positron#4582]
#### Positron and OS details:

Positron Version: 2024.09.0 (Universal) build 1
Code - OSS Version: 1.92.0
Commit: f37f4f5044a2a619e73d5db61a31e37fbd3faf18
Date: 2024-09-03T02:37:20.474Z (2 days ago)
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

#### Interpreter details:

R 4.4.3

## Describe the issue:
This does not work:

par(mfrow=c(1,2))
plot(rnorm(100))
plot(rnorm(1000))

Second plot is not shown in the plots area, although if using pdf device with pdf("plots.pdf"), the plot in the pdf is correct.

## Steps to reproduce the issue:

Just copy paste the above lines of code

## Expected or desired behavior:

A plot with two subplots in two columns

## Were there any error messages in the UI, Output panel, or Developer Tools console?
No

**Comment by testlabauto** [comment]
Hi @arnaldmarcer, thank you for using Positron!  

I am able to reproduce your problem.  Also, I have noticed that if I re-run just:
```
plot(rnorm(1000))
```
after running all three lines, then when the second plot opens and I toggle back to the first plot, it is surprisingly updated to look like I think you were expecting:

![Image](https://github.com/user-attachments/assets/740f81b7-b195-4e80-9721-a7ebef52869a)

**Comment by jmcphers** [comment]
This is tracked in https://github.com/posit-dev/positron/issues/3562.
