### ISSUE TITLE
F1 shortcut to open the help window does not work

### ISSUE THREAD

**Issue by abduazizR** [posit-dev/positron#4584]
Hi 

I recently updated positron the most recent version and the F1 shortcut to open a help file for a function does not work anymore.

Here is my specs

Positron Version: 2024.09.0 (Universal) build 1
Code - OSS Version: 1.92.0
Commit: f37f4f5044a2a619e73d5db61a31e37fbd3faf18
Date: 2024-09-03T02:37:20.474Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

**Comment by testlabauto** [comment]
Hi @abduazizR, thank you for using Positron!

Could you please attach a code sample showing an example of a case where F1 is not working for you?

I am using Positron Version: 2024.09.0 (Universal) build 8 and I am able to get help to open for both R and Python samples.

Thanks,
Chris

**Comment by abduazizR** [comment]
I restarted Positron, and it's working now.
Not sure what was causing the issue for me

**Comment by juliasilge** [comment]
This is tracked in https://github.com/posit-dev/positron/issues/4097. Let us know if you have further questions!
