### ISSUE TITLE
Text encoding issue with quotes in license agreement on Windows

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#4595]
#### Positron and OS details:

Positron Version: 2024.09.0 (user setup) build 11
Code - OSS Version: 1.92.0
Commit: 7a5505d8878f50c2e317aed07942430396fd35f7
Date: 2024-09-06T02:40:12.188Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

#### Interpreter details:

N/A

## Describe the issue:

Encoding issue with the quotes used around the word `SOFTWARE` in the license text causing the quotes to display oddly.

## Steps to reproduce the issue:

1. Run `Positron-2024.09.0-11-UserSetup.exe`
2. See the issue in the license agreement step immediately

![windows_license_agreement_usersetupexe](https://github.com/user-attachments/assets/10721f66-278b-42f4-ab86-c0abaf07f489)

## Expected or desired behavior:

The quotes should display without encoding issues, like where `"LICENSOR"` is mentioned in the license blurb.

We can fix this issue by using the basic double quote `"` instead of the Unicode Left and Right double quotation marks.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

N/A

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.09.0-17](https://github.com/posit-dev/positron-builds/releases/tag/2024.09.0-17)
OS Version(s) : Windows 11

### Test scenario(s) 



License looks correct now during install

### Link(s) to TestRail test cases run or created:
