### ISSUE TITLE
Hide GlyphRenderer(...) message from plots pane for bokeh

### ISSUE THREAD

**Issue by nstrayer** [posit-dev/positron#4597]
When drawing bokeh plots in the console, you often will get a semi-useless `GlyphRenderer(...)` output that goes to the console.

It doesn't really do anything and is pretty confusing to the user.

It's because sometimes in the console mode, you will run a line that ends in something like `p.line(...)` while building a bokeh plot. This causes jupyter to print the returned value which is a `GlyphRenderer` class that has a `_repr_html_` method on it that it inherits from the `Model()` class defined in bokeh. 

To reproduce run the following in the console
```python
from bokeh.plotting import figure
p = figure(title="Simple line example", x_axis_label='x', y_axis_label='y')
p.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], legend_label="Temp.", line_width=2)
```

You will see the following show up in the plots pane:
<img width="628" alt="image" src="https://github.com/user-attachments/assets/dc8af729-0fe5-4622-91c6-504a954a12d0">

Which feels like a pretty poor experience.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.09.0-38](https://github.com/posit-dev/positron-builds/releases/tag/2024.09.0-38)
OS Version(s) : Windows 11

### Test scenario(s) 



Teh GlyphRenderer() message no longer shows.

### Link(s) to TestRail test cases run or created:
