### ISSUE TITLE
Mocha `.only` pre-commit hook sometimes errors on Windows

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#4599]
#### Positron and OS details:

Dev setup on Windows.

#### Interpreter details:

N/A

## Describe the issue:
@jonvanausdeln was seeing issues with the mocha only pre-commit hook on his Windows machine.

The behaviour was odd in that it seemed to work once, but then failed subsequently with errors such as:

```
No files matching the pattern "error'" were found.
Please check for typing mistakes in the pattern.

[35mIt looks like you've included `.only` in your test(s):
[39m
If you end up committing with `.only`: please remove `.only` from your tests before merging to `main` :)
```

Changing the command in `build/eslint-mocha-only.js` to `npx eslint --no-eslintrc --parser '@typescript-eslint/parser' --plugin 'mocha' --rule 'mocha/no-exclusive-tests:error' ${files}` (removing the space before `error`) didn't resolve the issue:

```
Invalid value for option 'rule' - expected type Object, received value: 'mocha/no-exclusive-tests:error'.
[35mIt looks like you've included `.only` in your test(s):
[39m
If you end up committing with `.only`: please remove `.only` from your tests before merging to `main` :)
```

## Steps to reproduce the issue:

On a Windows machine,
1. Change some code in a smoke test
2. Commit that code
3. See an error like mentioned above

## Expected or desired behavior:

The mocha `.only` pre-commit hook should work without issue on Windows -- it should not error on the command itself.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

N/A

**Comment by jonvanausdeln** [comment]
Works for me!
