### ISSUE TITLE
Update `builtin` extensions

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#4624]
It has been a while since we updated the `builtInExtensions` we include here:

https://github.com/posit-dev/positron/blob/1a392b3752cd81565bbcdc3eddb0f4921212c5b5/product.json#L39

When these get old, it can result in an annoying user experience where you click on the Extensions tab, they all autoupdate, and then you are asked to restart the Extension Host.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.09.0-33](https://github.com/posit-dev/positron-builds/releases/tag/2024.09.0-33)
OS Version(s) : Windows 11, MacOS 14

### Test scenario(s) 



Extensions are updated!

### Link(s) to TestRail test cases run or created:
