### ISSUE TITLE
Data explorer get_column_profiles requests can time out on large datasets

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#4629]
#### Positron and OS details:

main as of 9/10/24

#### Interpreter details:

Python 3.11

## Describe the issue:

On a 17M row dataset, actions in the data explorer can cause `get_column_profiles` requests to exceed a 10 second timeout

https://github.com/user-attachments/assets/5a3c9f6a-1e85-4817-944c-a2bec27aa522

I made this dataset by concatenating 50 copies of our testing `flights.parquet` dataset

```
flights = pd.read_parquet('/home/wesm/code/testingstuff/flights.parquet')
flights_big = pd.concat([flights] * 50, ignore_index=True)
```

![image](https://github.com/user-attachments/assets/d965c7bf-50e9-4e13-8823-d03e6b553ed4)

## Possible solutions

I think for very large datasets, it will make sense to send the profile requests in smaller batches, or even one column at a time, and also to increase the timeout.

**Comment by wesm** [comment]
This issue is rather noxious so I'm going to see if there is an easy fix (beyond just increasing the timeout) to be able to resolve this and #2851

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-111
    OS Version          : OSX

### Test scenario(s) 

Tested with 33 million row data set.
Added filters like in the filing video.  Didn't see any timeouts.  Updates seem to be with 5 seconds based on rough timing.

Link(s) to TestRail test cases run or created:
