### ISSUE TITLE
reh-web package.json file line ending changing on Windows

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#4646]
#### Positron and OS details:

An up-to-date checkout of the `main` branch on Windows

#### Interpreter details:

N/A

## Describe the issue:
Git is showing _invisible_ 👻 changes to `remote/reh-web/package.json` file after running `yarn` on Windows.

This was seen by Brian and Jon. I was able to reproduce on my Windows machine as well.

## Steps to reproduce the issue:

1. Checkout the latest changes on `main` on Windows
2. Run `yarn`
3. See `remote/reh-web/package.json` as having changes via `git status`
4. Running `git diff -w` will output `warning: in the working copy of 'remote/reh-web/package.json', LF will be replaced by CRLF the next time Git touches it`

## Expected or desired behavior:

If there are no actual changes to the package.json, it shouldn't be showing as changed!

The theory is that git is applying line ending changes to the file since it is being generated on Windows. It was originally created on Linux which would have used LF, so on Windows it may be getting switched to CRLF.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

N/A

**Comment by jonvanausdeln** [comment]
Just verified on `main`. I had to stage it after the yarn, but now it appears good!
