### ISSUE TITLE
Error when executing task "R: Install R Package and Restart R"

### ISSUE THREAD

**Issue by sjmgarnier** [posit-dev/positron#4649]
#### Positron and OS details:

Positron Version: 2024.09.0 (Universal) build 27
Code - OSS Version: 1.92.0
Commit: d996153f3be6bcc9af460300e61103425323b973
Date: 2024-09-11T02:38:46.408Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

#### Interpreter details:

R 4.4.1

## Describe the issue:

With this update, the task "R: Install R Package and Restart R" fail with the following error message 

```
 *  Executing task: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/bin/R '--quiet --no-restore --no-save -e' 'pak::local_install(upgrade = FALSE)' 

ARGUMENT '=' __ignored__

ARGUMENT 'FALSE)' __ignored__

> pak::local_install(upgrade
+ 
+ Error: unexpected end of input
Execution halted

 *  The terminal process "/opt/homebrew/bin/zsh '-l', '-c', '/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/bin/R '--quiet --no-restore --no-save -e' 'pak::local_install(upgrade = FALSE)''" failed to launch (exit code: 1). 
 *  Terminal will be reused by tasks, press any key to close it. 
```

## Steps to reproduce the issue:

1. Open an R package folder
2. Run the task "R: Install R Package and Restart R"

## Expected or desired behavior:

The pak command should be executed and R be restarted. 

## Were there any error messages in the UI, Output panel, or Developer Tools console?

See above.

**Comment by juliasilge** [comment]
Thank you for this bug report!

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.09.0-38](https://github.com/posit-dev/positron-builds/releases/tag/2024.09.0-38)
OS Version(s) : Windows 11, MacOS 14

### Test scenario(s) 



All the package commands work as expected.

### Link(s) to TestRail test cases run or created: 
https://posit.testrail.io/index.php?/cases/view/809821
