### ISSUE TITLE
r: development documentation opens in external browser

### ISSUE THREAD

**Issue by JosiahParry** [posit-dev/positron#4653]
#### Positron and OS details:

Positron Version: 2024.09.0 (Universal) build 27
Code - OSS Version: 1.92.0
Commit: d996153f3be6bcc9af460300e61103425323b973
Date: 2024-09-11T02:38:46.408Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.4.0

#### Interpreter details:

R 4.4.1 

## Describe the issue:

Related https://github.com/posit-dev/positron/issues/1025

Development documentation opens in external browser.

![Screen Recording 2024-09-11 at 16 39 40](https://github.com/user-attachments/assets/64e038a3-83a7-464c-8bd9-b541a71dbd34)

## Steps to reproduce the issue:

- `devtools::load_all()`
- `?fn_name`

## Expected or desired behavior:

Development documentation is opened in the documentation viewer

**Comment by jennybc** [comment]
I am not able to reproduce this:

Positron Version: 2024.09.0 (Universal) build 27
Code - OSS Version: 1.92.0
Commit: d996153f3be6bcc9af460300e61103425323b973
Date: 2024-09-11T02:38:46.408Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0


https://github.com/user-attachments/assets/cc932cbe-3451-4fd2-be78-031b7bdd151a

Are you running up-to-date versions of the R packages listed here in R prerequisites?

https://github.com/posit-dev/positron/wiki#r-prerequisites

**Comment by jennybc** [comment]
Specifically, it is definitely important to have the up-to-date pkgload in order to have the best experience with dev help in Positron.

**Comment by JosiahParry** [comment]
``` r
positron_deps <- c("usethis", "cli", "crayon", "rlang", "roxygen2", "pkgload")
lapply(setNames(positron_deps, positron_deps), packageVersion)
#> $usethis
#> [1] '2.2.3'
#> 
#> $cli
#> [1] '3.6.3.9000'
#> 
#> $crayon
#> [1] '1.5.2'
#> 
#> $rlang
#> [1] '1.1.4'
#> 
#> $roxygen2
#> [1] '7.3.1'
#> 
#> $pkgload
#> [1] '1.3.4'
```

<sup>Created on 2024-09-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Here are my current versions. I will update each of them and report back

**Comment by JosiahParry** [comment]
Updating `pkgload` to `1.4.0.9000` fixed this. Could Positron detect that pkgload <= 1.4.0 and provide a warning in that case? I have noticed that something similar happened with roxygen2 in the past

**Comment by jennybc** [comment]
Maybe? We've talked about that. But I don't really expect this tightly coupled relationship between Positron and certain R packages to be a persistent situation long-term. It's fairly unique to being a very beta product. I feel like we have an issue that discusses whether we might want to actually build UI around this ... I'm going to search for it.

**Comment by jennybc** [comment]
Also in this case, the thing you are trying to do _works_ (view dev help), but the experience is just nicer with a newer version of pkgload. If we start to message about "nice-to-haves", then some folks will have their reasons for using less current versions, and then they'd want a way to turn this UI off, etc. It's not a no brainer, in any case.

**Comment by jennybc** [comment]
I refreshed my memory on this: we do have and use internal facilities for guarding a hard package or package version dependency. But that's not the case here. So I feel comfortable saying that this is a just a good illustration that having the recommend pre-requisites leads to the best experience in Positron, which is still in beta.
