### ISSUE TITLE
Mismatch between the SHA Positron reports vs SHA associated with the release on GitHub

### ISSUE THREAD

**Issue by jennybc** [posit-dev/positron#4656]
This may be a consequence of moving the release building process to another repository? But I'm finding that these two SHAs don't match, which surprises me:

Where one downloads a GitHub release:

Tag is [2024.09.0-27](https://github.com/posit-dev/positron/releases/tag/2024.09.0-27)
SHA is https://github.com/posit-dev/positron/commit/f5cd27fdf143d8dde3edcc19dc9ad3b71ad1440c

<img width="601" alt="Screenshot 2024-09-11 at 6 49 20 PM" src="https://github.com/user-attachments/assets/0a3fc562-ad17-4a75-9cf0-327576deec5d">

But when I download and launch that, *Positron > About Positron* reports:

Positron Version: 2024.09.0 (Universal) build 27
Code - OSS Version: 1.92.0
Commit: d996153f3be6bcc9af460300e61103425323b973
Date: 2024-09-11T02:38:46.408Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0

This SHA *does* refer to a commit here in Positron: https://github.com/posit-dev/positron/commit/d996153f3be6bcc9af460300e61103425323b973

Shouldn't they be the same? 🤔

**Comment by jmcphers** [comment]
As I understand it, the commit you see in _About Positron_ is correct. I think this is a bug caused by the fact that when we promote a release we do not specify which commit to use for the tag, so it creates a tag with whatever `main` was pointing at when the release was promoted.

The solution is probably to specify `target_committish` when promoting the release:

https://github.com/softprops/action-gh-release?tab=readme-ov-file#inputs

**Comment by jennybc** [comment]
Yes! I think this is important. The way I discovered this is trying to replicate someone's issue and trying to make sure I had the same version and that we were both up-to-date. It's pretty confusing if we're tagging a different commit than the actual contents of the release.

**Comment by petetronic** [comment]
Yes, it's not intended, I'll fix this.

**Comment by petetronic** [comment]
@jonvanausdeln when we push the next pre-release to the positron repo, let's sync up to confirm the sha is pointing to the correct commit.
