### ISSUE TITLE
BUG: Source Control / Git SCM Buggy since v.2024.08.0-83

### ISSUE THREAD

**Issue by bschulth** [posit-dev/positron#4669]
#### Positron and OS details:

Positron Version: 2024.09.0 (Universal) build 27
Code - OSS Version: 1.92.0
Commit: d996153f3be6bcc9af460300e61103425323b973
Date: 2024-09-11T02:38:46.408Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0

#### Interpreter details:

Python 3.11.9 

## Describe the issue:
- Ever since release v.2024.08.0-83 the SCM panel has been buggy in what the panel shows as current.
- Notably, that release: Merged upstream VS Code 1.92 (https://github.com/posit-dev/positron/pull/4283)
- <img width="874" alt="image" src="https://github.com/user-attachments/assets/cee44599-d060-4f69-8c45-390d4d6a1239">

## Steps to reproduce the issue:
- switch to Explorer view
- Edit  a file
- Open source control view..see if change shows up...like icon in side bar shows a 1 for changes
- switch to Explorer view
- Reverse your edit
- Open source control view....the Icon on left indicating change is probably gone, but panel still shows changed file
- Go to command line, run a git status to  verify no pending changes.
- You may have to try  a couple of times...but if you keep playing with it more than once, it should show up.
- sometimes it is a jumbled mess of overlayed text:
- <img width="745" alt="image" src="https://github.com/user-attachments/assets/7cc755aa-90f5-436d-bac0-545de15524ca">

## Expected or desired behavior:
- The Source tab view should mirror reality and not get stuck showing some past state

## Were there any error messages in the UI, Output panel, or Developer Tools console?

- Git Output Panel is clean looking 
   - <img width="1651" alt="image" src="https://github.com/user-attachments/assets/c4c98f46-625b-48fd-a0be-403525ac9937">

- Developer Tools  shows a number of errors similar to:
   - <img width="1292" alt="image" src="https://github.com/user-attachments/assets/a7ef9f22-72fa-4966-a201-31ffe1899a81">

**Comment by jennybc** [comment]
I have not able to replicate this and I haven't seen any other reports.
Positron does not, to my knowledge, make any changes to the Git functionality of VS Code.

So I'm afraid we don't have much to go on.

Is there anything "interesting" about your setup? Does this happen across all workspaces/repos for you? Is there any angle such as the repo lives on DropBox or OneDrive or some such? Does this reproduce if you disable all extensions? Etc etc.

**Comment by DavisVaughan** [comment]
The only thing I have to offer is that the new `Incoming/Outgoing` panel that VS Code added definitely has some performance issues with projects that have a pretty big git history.

It slowed me down enough in tree-sitter-r that I turned it off:
https://github.com/r-lib/tree-sitter-r/commit/70d9b7227af69368596d5da7f8b51267eb45e7cc

You could try setting `"scm.showHistoryGraph": false` in your `settings.json` to see if that magically fixes things

The next VS Code update will also drastically change this panel again, so we can see if things just "get better" once we sync with the August 2024 update

**Comment by bschulth** [comment]
@jennybc, I'll try to remove any plugins (I think I only have added Theme based plugins for darkmode) and get back to you.
@DavisVaughan  I tried the setting to hide the history graph and the history graph clearly went away, but the source  control view is not showing my current changes (even though the sidebar icon knows I have 2 changes):
<img width="343" alt="image" src="https://github.com/user-attachments/assets/0a534404-f1d3-4e66-a16d-3ba406ef12e9">

I will update this thread if I can find any extra details.
Thanks both.

**Comment by bschulth** [comment]
- So, as I mentioned in the original post...this error repeats alot:
 - <img width="1292" alt="image" src="https://github.com/user-attachments/assets/ddb97631-8016-4aff-a0e2-55448b87564a">

- So I found that File on my Mac:
   - /Applications/Positron.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js
   - Went to line 294639 as indicated in the error
   - Proceded to minorly hack the code with a try/catch and printout of the state of the object.
   - It seems to be the SCM graph that @DavisVaughan  mentioned
   - Here is my hack:
   ```js
        //BJS: debugger;
        let circleColor = "#FFFFFF";
        try{
            circleColor = circleIndex < outputSwimlanes.length ? outputSwimlanes[circleIndex].color : inputSwimlanes[circleIndex].color;
        } catch(err) {
            console.log("circleIndex: " + circleIndex);
            console.log(outputSwimlanes);
            console.log(err)
        }
```
After doing this, I can see the `outputSwimlanes` array is empty, but `circleIndex` is 0, so clearly cannot pull a `color` property from an undefined as the error indicates:

<img width="676" alt="image" src="https://github.com/user-attachments/assets/4bfa98ef-c8e9-408f-ac9b-c896a0c81ee3">

- also, since I put a default value in (probably wrong value), I then get a rendered source SCM panel:

- <img width="620" alt="image" src="https://github.com/user-attachments/assets/e86e7013-4c44-4962-9d82-764cb61e9c76">



So the bug seems to be related to swimlanes.

**Comment by bschulth** [comment]
As another aside....I had originally set  "scm.showHistoryGraph": false on my folder-level settings.json that had a git repo associated with it...this was apparently too granular.

if I set "scm.showHistoryGraph": false at the "user" or "workspace" levels, I can remove the hacked code and still get a properly rendered change list, just without the history graph.

So this seems to be the work-around if the code needs to be fixed in upstream VsCode repo.

**Comment by jennybc** [comment]
These lines of code don't appear to be anything Positron devs have touched (rather, the `.ts` files that eventually produce the `.js` you're tweaking). So I suspect that this is a problem in VS Code that Positron inherits. And perhaps your specific history is unique enough to be presenting an unhandled edge case.

Can you reproduce your problems with the SCM functionality in plain old VS Code?

**Comment by bschulth** [comment]
- @jennybc, it renders fine in VsCode v 1.93.0 ( +1 from Positron), and no errors in the developer tools console.
   - <img width="484" alt="image" src="https://github.com/user-attachments/assets/8aaedb79-efe7-44c1-ae43-a953ba8329d2">

- I think we should wait for Positron t move to 1.93.0 and see what happens.
- I am good if you want to close this ticket.
- Thanks....and great work on all the new tooling (which I forgot to mention :( )

**Comment by DavisVaughan** [comment]
Yea let's close and reopen if it comes back up after getting 1.93.0 in, thanks for the research!

**Comment by bschulth** [comment]
@DavisVaughan, @jennybc 

Just a follow-up, just wanted to confirm that is looks like the latest vscode release (1.93) in Positron 2024.09.0-77 fixed this issue.  The source tab behaves normally, and the graph tree renders, and no errors in the developer console.

<img width="787" alt="image" src="https://github.com/user-attachments/assets/2a28ec81-afd0-4d23-aa3c-6bd608dc3108">
