### ISSUE TITLE
Data Explorer "Summary Hidden" feature is no longer needed.

### ISSUE THREAD

**Issue by softwarenerd** [posit-dev/positron#4672]
## System details:

N/A

#### Positron and OS details:

Positron Dev Version: 2024.09.0 build 0
Code - OSS Version: 1.92.0
Commit: Unknown
Date: Unknown
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

#### Interpreter details:

Python or R, not specific to any version.

## Describe the issue:

Now that the Data Explorer column summary panel can be expanded and collapsed:

https://github.com/user-attachments/assets/90cdc61f-701b-4891-9105-92857bc334c2

The **Summary Hidden** Layout option is no longer needed (and is confusing):

![image](https://github.com/user-attachments/assets/ec4097ee-e4f3-4be2-9869-3bed6ec965e5)

Remove the feature.

**Comment by softwarenerd** [comment]
This is addressed in https://github.com/posit-dev/positron/pull/4673.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-55
    OS Version          : OSX

### Test scenario(s) 

Summary Hidden feature is no longer present

Link(s) to TestRail test cases run or created:
