### ISSUE TITLE
python: reconcile Run App options in Play button

### ISSUE THREAD

**Issue by isabelizimm** [posit-dev/positron#4675]
to follow #4625 and #4662 merge

as a result of adding more options in the Play dropdown, it is getting a little cluttered (particularly if the Shiny extension is also involved). 

![Screenshot 2024-09-13 at 9 44 07 AM](https://github.com/user-attachments/assets/d2222bbe-0c90-4262-a0f1-8e80aadd2881)

Additionally, some of these options do not make sense for an application, such as "Run file in Console." We will want to clean these options up conditionally for an app file.

**Comment by petetronic** [comment]
Could we also consider changing the default to not be run selection, as this button now tends to imply operations that are "the whole file" or "app"? We have great shortcuts for running selections, and I find this icon to imply running the whole file by default.
