### ISSUE TITLE
shinylive rendering issue

### ISSUE THREAD

**Issue by davidrsch** [posit-dev/positron#4676]
#### Positron and OS details:

Positron Version: 2024.09.0 (system setup) build 27
Code - OSS Version: 1.92.0
Commit: d996153f3be6bcc9af460300e61103425323b973
Date: 2024-09-11T02:38:49.688Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

#### Interpreter details:

R 4.4.1

## Describe the issue:

When trying to render a quarto document with shinylive returns the following error:

```{r}
(E) Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?
```

Which seems to indicate that Positron can't find a `shinylive` R package installation, which is odd because `shinylive` is indeed installed, in fact I am able to render in the quarto document in RStudio without any issue. I tried both in project with or without renv and in RStudio works but it doesn't in Positron.  

## Steps to reproduce the issue:

I just try to replicate the example in [shinylive.io](https://shinylive.io/r/examples/):

``````{qmd}
---
title: "Results"
format: 
  html:
    resources: 
      - shinylive-sw.js
filters: 
  - shinylive
---

:::{.column-screen}

```{shinylive-r}
#| standalone: TRUE
#| viewerHeight: 420

library(shiny)
library(bslib)


# Define UI for app that draws a histogram ----
ui <- page_sidebar(

  # App title ----
  title = "Hello Shiny!",

  # Sidebar panel for inputs ----
  sidebar = sidebar(

    # Input: Slider for the number of bins ----
    sliderInput(
      inputId = "bins",
      label = "Number of bins:",
      min = 1,
      max = 50,
      value = 30
    )
  ),

  # Output: Histogram ----
  plotOutput(outputId = "distPlot")
)

# Define server logic required to draw a histogram ----
server <- function(input, output) {

  # Histogram of the Old Faithful Geyser Data ----
  # with requested number of bins
  # This expression that generates a histogram is wrapped in a call
  # to renderPlot to indicate that:
  #
  # 1. It is "reactive" and therefore should be automatically
  #    re-executed when inputs (input$bins) change
  # 2. Its output type is a plot
  output$distPlot <- renderPlot({
    x <- faithful$waiting
    bins <- seq(min(x), max(x), length.out = input$bins + 1)

    hist(
      x,
      breaks = bins,
      col = "#75AADB",
      border = "white",
      xlab = "Waiting time to next eruption (in mins)",
      main = "Histogram of waiting times"
    )
  })
}

# Create Shiny app ----
shinyApp(ui = ui, server = server)
```
:::

`````` 

## Expected or desired behavior:

**Note:** Output obtained in browser when using RStudio

![image](https://github.com/user-attachments/assets/b45652ce-96e1-4d9c-83c1-b1125b58d06e)

**Comment by jennybc** [comment]
Apologies in advance because I am certainly less knowledgeable about shinylive than you are!

But when I render this in Positron with the "Preview" button, I seem to succeed:

<img width="1593" alt="Screenshot 2024-09-13 at 12 20 43 PM" src="https://github.com/user-attachments/assets/26221ed9-3c98-4b64-963c-9aeb62d2354a">


Going back to my lack of experience, this also means that I have just freshly installed the shinylive R package, as well as the shinylive extension (via `quarto add quarto-ext/shinylive`). Are you sure those are both installed and current?

This issue (now closed) seems perhaps related? https://github.com/quarto-ext/shinylive/issues/35

**Comment by davidrsch** [comment]
Yes I have both the R package and the quarto extension that is way I am able to render it in RStudio, could be an only windows problem?

**Comment by jennybc** [comment]
> Could it be an issue only on windows?

Yes that's always a rich source of sadness 😢 

I will try to reproduce it on Windows shortly.

**Comment by jennybc** [comment]
OK yes I see the same as you on Windows, but I'm going to add the full error:

```
PS C:\Users\jenny\windows-tirekicking> quarto preview c:/Users/jenny/windows-tirekicking/iss4676.qmd --no-browser --no-watch-inputs
pandoc 
  to: html
  output-file: iss4676.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Results
  resources:
    - shinylive-sw.js
  
(E) Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?
 Error:
 PandocError {}
Error running filter C:/Program Files/Quarto/share/filters/main.lua:
...rekicking\_extensions\quarto-ext\shinylive\shinylive.lua:40: Error running 'Rscript' command. Perhaps you need to install / update the 'shinylive' R package?

stack traceback:
        ...rekicking\_extensions\quarto-ext\shinylive\shinylive.lua:40: in global 'throw_quarto_error'
        ...rekicking\_extensions\quarto-ext\shinylive\shinylive.lua:86: in global 'callRShinylive'
        ...rekicking\_extensions\quarto-ext\shinylive\shinylive.lua:113: in global 'callShinylive'
        ...rekicking\_extensions\quarto-ext\shinylive\shinylive.lua:286: in global 'ensureBaseSetup'
        ...rekicking\_extensions\quarto-ext\shinylive\shinylive.lua:315: in global 'ensureLanguageSetup'
        ...rekicking\_extensions\quarto-ext\shinylive\shinylive.lua:424: in function <...rekicking\_extensions\quarto-ext\shinylive\shinylive.lua:408>
        [C]: in ?
        [C]: in method 'walk'
        C:/Program Files/Quarto/share/filters/main.lua:557: in local 'checked_walk'
        C:/Program Files/Quarto/share/filters/main.lua:609: in function 'run_emulated_filter'
        C:/Program Files/Quarto/share/filters/main.lua:1334: in local 'callback'
        [string "..."]:1888: in field 'withScriptFile'
        C:/Program Files/Quarto/share/filters/main.lua:1350: in upvalue 'run_emulated_filter_chain'
        C:/Program Files/Quarto/share/filters/main.lua:1388: in function <C:/Program Files/Quarto/share/filters/main.lua:1385>
stack traceback:
        C:/Program Files/Quarto/share/filters/main.lua:557: in local 'checked_walk'
        C:/Program Files/Quarto/share/filters/main.lua:609: in function 'run_emulated_filter'
        C:/Program Files/Quarto/share/filters/main.lua:1334: in local 'callback'
        [string "..."]:1888: in field 'withScriptFile'
        C:/Program Files/Quarto/share/filters/main.lua:1350: in upvalue 'run_emulated_filter_chain'
        C:/Program Files/Quarto/share/filters/main.lua:1388: in function <C:/Program Files/Quarto/share/filters/main.lua:1385>
```

**Comment by jennybc** [comment]
I don't believe this is a Positron issue, so I plan to return with advise on where to take this next.

**Comment by jennybc** [comment]
I see the error above in all contexts on my Windows machine: in Positron, in RStudio, in VS Code, and in a Git Bash terminal. So I suggest that you report this problem on the repo of the quarto cli:

https://github.com/quarto-dev/quarto-cli

*I can't transfer it for you, because these projects belong to different orgs. But I recommend that you include a link to this thread.*

**Comment by timtmok** [comment]
Another use opened it in Quarto: https://github.com/quarto-dev/quarto/issues/557
