### ISSUE TITLE
no symbol named in scope for dot in formula

### ISSUE THREAD

**Issue by EmilHvitfeldt** [posit-dev/positron#4679]
#### Positron and OS details:

Positron Version: 2024.09.0 (Universal) build 1
Code - OSS Version: 1.92.0
Commit: f37f4f5044a2a619e73d5db61a31e37fbd3faf18
Date: 2024-09-03T02:37:20.474Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0

#### Interpreter details:

R 4.4.0

## Describe the issue:

I get a `no symbol named '.' in scope` for a formula on the form `~ .`. It disappear if there is a left hand side, but persists if you `+` more terms to the formula. It doesn't complain if it is used in a function.

<img width="348" alt="Screenshot 2024-09-13 at 1 50 16 PM" src="https://github.com/user-attachments/assets/41cbede7-daa7-4ec1-ae29-8b203aa9ba5a">

## Steps to reproduce the issue:

1. Open R script. 
2. Type in `~ .`

## Expected or desired behavior:

to not see the message

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-55
    OS Version          : OSX

### Test scenario(s) 

reprex no longer produces message

Link(s) to TestRail test cases run or created:
