### ISSUE TITLE
TIFF format support in plot export

### ISSUE THREAD

**Issue by petetronic** [posit-dev/positron#4690]
### Discussed in https://github.com/posit-dev/positron/discussions/4689

<div type='discussions-op-text'>

<sup>Originally posted by **quantumfrost00** September 16, 2024</sup>
I recently switched from RStudio to Positron and so far loving the experience. One thing I miss is the ability to export plot to .TIFF format. I usually make graphs for my academic papers and most medicine journals require me to upload images in TIFF format. Please bring the ability to export plots/graphs/images in .tiff format.</div>

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : Main on 10/22/24 at noon MST
    OS Version          : OSX

### Test scenario(s) 

Tested TIFF export with:

```
import pandas as pd
import matplotlib.pyplot as plt
data_dict = {'name': ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'],
				'age': [20, 20, 21, 20, 21, 20],
				'math_marks': [100, 90, 91, 98, 92, 95],
				'physics_marks': [90, 100, 91, 92, 98, 95],
				'chem_marks': [93, 89, 99, 92, 94, 92]
				}

df = pd.DataFrame(data_dict)

df.plot(kind='scatter',
		x='math_marks',
		y='physics_marks',
		color='red')

plt.title('ScatterPlot')
plt.show()
```

Link(s) to TestRail test cases run or created:

**Comment by testlabauto** [comment]
Oh yeah, thanks for the heads up:

![Image](https://github.com/user-attachments/assets/10fa5ac2-6a9e-48dd-a7f9-e083f77cf03c)

with
```
cars <- c(1, 3, 6, 4, 9)
plot(cars, type="o", col="blue")
title(main="Autos", col.main="red", font.main=4)
```

I thought the plot was no longer connected to the language that generated it once it was created.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-90
    OS Version          : OSX

### Test scenario(s) 

R save as TIFF looks good now.

Link(s) to TestRail test cases run or created:
