### ISSUE TITLE
Provide options to specify working directory for Quarto, `.Rmd`, notebooks

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#4692]
Folks coming from RStudio are used to having options for what their `.Rmd` and `.qmd` files use as the working directory:

### Discussed in https://github.com/posit-dev/positron/discussions/4688

<sup>Originally posted by **AndrewSkelton** September 15, 2024</sup>

> Hi, 
> 
> Typical behavior in RStudio was that when an Rmd file was open, paths in the notebook were relative to where the file was located, this doesn't seem to be the same in Positron. Is there a setting to enable that?
> 
> Thanks, 
> 
> Andrew

In #2648 we changed the working directory for `.ipynb` files to default to the location of the notebook file, and this is like an analogous request for our other notebook-ish files.

RStudio offers this as an option:
 
![Screenshot 2024-09-16 at 11 25 29 AM](https://github.com/user-attachments/assets/3150677e-dc0d-411a-a89d-f2086c7f9579)

I will say that personally I find this behavior for notebooks and notebook-adjacent things pretty confusing (it has surprised me more times than I would like to admit!) and I like that RStudio lets me opt out from this automatic mucking about with my working directory.

**Comment by jmcphers** [comment]
There's also an issue requesting that we do this for Python scripts. https://github.com/posit-dev/positron/issues/3156

**Comment by juliasilge** [comment]
I was just experimenting in RStudio and is it right that the working directory only changes if you render the whole document? Not when executing code interactively? Because that would be much easier to offer as an option, especially only for `.Rmd` and not for Quarto.

**Comment by juliasilge** [comment]
OK, I am going to sum up the current situation:

- The defaults right now are similar to RStudio's behavior; we use the file's directory as the working directory when rendering, and there are no changes to the console's working directory for code coming from `.Rmd` or `.qmd`. All of this can be set/changed by the user, using `here::here()` or the `knit_root_dir` argument to `rmarkdown::render()` or by explicitly changing the working directory.
- Positron does _not have_ inline output, which is I bet what the original discussion was getting at. Setting the working directory in inline output makes sense, but it doesn't really for send-to-console execution.
- We could address this use case in the future with a treatment similar to what we land on for #3156, for example providing a way to spawn a new, quasi-notebook-like console session for `.Rmd` and `.qmd` files.
