### ISSUE TITLE
Ark: Variable pane can't compute the size in presence of immediate bindings

### ISSUE THREAD

**Issue by lionel-** [posit-dev/positron#4700]
## Describe the issue:

The variable pane computes the size of objects in the global environments. If those objects contain environments with "immediate bindings", the size computation fails with a warning in the Ark logs.

See the parent issue https://github.com/posit-dev/positron/issues/4686 and the investigation notes in https://github.com/posit-dev/positron/issues/4686#issuecomment-2352427239. See also the issue in lobstr, from which we pulled our size computation routine: https://github.com/r-lib/lobstr/issues/48

## Steps to reproduce the issue:

Run this in the R console:

```r
library(brms)
m <- brm(bf(mpg ~ hp + (1 | cyl), sigma ~ cyl), data = mtcars, seed = 123)
```

## Expected or desired behavior:

No warning in the logs:

```log
[R]   2024-09-17T09:34:59.797038Z  WARN  Can't compute size of object: bad binding access
```

And the model `m` should have a non-zero size when the variable pane is sorted by size:

<img width="526" alt="Screenshot 2024-09-17 at 11 32 44" src="https://github.com/user-attachments/assets/007913b1-7d94-4f6d-9795-80b8063a6b86">

**Comment by petetronic** [comment]
I was able to reproduce this issue, sending to Triage.

**Comment by petetronic** [comment]
Hopefully addressed by this PR to ARK https://github.com/posit-dev/ark/pull/538

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-95
    OS Version          : OSX

### Test scenario(s) 

Error no longer present and m has nonzero size.

Link(s) to TestRail test cases run or created:
