### ISSUE TITLE
`rstudioapi::getVersion()` isn't returning the date and/or correct Positron version string

### ISSUE THREAD

**Issue by coatless** [posit-dev/positron#4706]
#### Positron and OS details:

Positron Version: 2024.09.0 (Universal) build 45
Code - OSS Version: 1.92.0
Commit: b0ec249b20455499f9e79ffe0bec35a5ff602ea4
Date: 2024-09-16T02:45:13.900Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

#### Interpreter details:

R 4.4.1

## Describe the issue:

While trying to retrieve the version of Positron using the `rstudioapi` R package, I'm getting an odd string:

```r
rstudioapi::getVersion()
[1] ‘2023.3’
```

From https://github.com/posit-dev/positron/issues/1312#issuecomment-1759791238, I think this should be calendard-based versioning? But, the string is dated to 2023. 

## Steps to reproduce the issue:

1. Open Positron and set Interpreter to R
2. Install rstudioapi
3. Run `rstudioapi::getVersion()`
4. Compare with `Positron > About` menu version information

<img width="1418" alt="A screenshot showing the results of running under the R 4.4.1 interpreter `rstudioapi::getVersion()` compared to using the `Positron > About` menu approach" src="https://github.com/user-attachments/assets/6bce58ea-d9c2-4578-863c-77ba75e703ec">

## Expected or desired behavior:
Version or at least the build information from `Positron > About` menu.

**Comment by jennybc** [comment]
This a known (internally, at least) artificial placeholder at the moment:

https://github.com/posit-dev/ark/blob/8f5040d62f25e4bcdcdfe0f0a85f455079528183/crates/ark/src/modules/rstudio/rstudioapi.R#L2-L21

This may be neither here nor there, but `rstudioapi::getVersion()` is documented to return the current version of the **RStudio API** and I'm not sure if that is necessarily the version of, say, RStudio. In any case, I would not have any immediate hopes that `rstudioapi::getVersion()` is going to give you the information you see in *Positron > About*.

A better partial alternative is the `POSITRON_VERSION` env var:

``` r
Sys.getenv("POSITRON_VERSION")
#> [1] "2024.09.0"
```

**Comment by juliasilge** [comment]
Related to #4081

**Comment by coatless** [comment]
> This a known (internally, at least) artificial placeholder at the moment:
> 
> https://github.com/posit-dev/ark/blob/8f5040d62f25e4bcdcdfe0f0a85f455079528183/crates/ark/src/modules/rstudio/rstudioapi.R#L2-L21

Thanks! From the diff, there are only two environment variables at the moment: `POSITRON` and `POSITRON_VERSION`? 

> This may be neither here nor there, but `rstudioapi::getVersion()` is documented to return the current version of the **RStudio API** and I'm not sure if that is necessarily the version of, say, RStudio. In any case, I would not have any immediate hopes that `rstudioapi::getVersion()` is going to give you the information you see in _Positron > About_.

I think this is a case of a documentation hiccup in the man pages 😢 

If I run `RStudio.Version()`, then I get: 

```r
RStudio.Version()
# $citation (truncated)
# $mode
# [1] "desktop"
# 
# $version
# [1] ‘2024.4.2.764’
# 
# $long_version
# [1] "2024.04.2+764"
#
# $release_name
# [1] "Chocolate Cosmos"
```

Meanwhile, from the API: 

```r
rstudioapi::getVersion()
# [1] ‘2024.4.2.764’
```

So, I think it's picking up the installed actual RStudio version instead of the `rstudioapi` package version information.

**Comment by juliasilge** [comment]
After my work in https://github.com/posit-dev/ark/pull/531 and https://github.com/posit-dev/positron/pull/4703, we now see:

``` r
rstudioapi::getVersion()
#> [1] '2024.9.0'
```

This is consistent with the RStudio behavior but [the rstudioapi documentation](https://rstudio.github.io/rstudioapi/reference/getVersion.html) is somewhat confusing. Does "RStudio API" mean... RStudio? Or the version of the rstudioapi package? What it is [actually doing is getting version info from RStudio](https://github.com/rstudio/rstudioapi/blob/d5d5a2220313c274b3e316ca51838b9e3c30bfe0/R/code.R#L68), not looking at the R package, so I think we can resolve this issue with my two PRs.

**Comment by coatless** [comment]
@juliasilge sent a clarifying PR over to `{rstudioapi}`:

https://github.com/rstudio/rstudioapi/pull/304

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-69
    OS Version          : OSX

### Test scenario(s) 

rstudioapi::getVersion()

Link(s) to TestRail test cases run or created:
