### ISSUE TITLE
Console prints `renv` loading messages twice when `.Rproj` file exists

### ISSUE THREAD

**Issue by psychelzh** [posit-dev/positron#4714]
See the following screen shot as example:

![image](https://github.com/user-attachments/assets/9d30ab32-e6a8-4cfd-a6c6-1ab0d3d83dd4)

**Comment by petetronic** [comment]
Hi @psychelzh, thanks for helping test Positron! I wasn't able to immediately reproduce this locally. Is it possible you might have multiple `source()` calls in your `.Rprofile`?

**Comment by psychelzh** [comment]
The `.Rprofile` is okay.

![image](https://github.com/user-attachments/assets/a5c0ab18-e41c-4b83-8ad2-751b77a20300)

**Comment by psychelzh** [comment]
Interestingly, if I create a new project and use `renv`, it will be okay. But my existing renv projects are not so.

**Comment by psychelzh** [comment]
Found reproducible steps:

1. Create R project using RStudio with renv enabled.
2. Open that folder using Positron.

Then you will found the project loading messages are printed twice.

**Comment by petetronic** [comment]
Thank you for the additional info, I can reproduce the issue on Windows, but not MacOS. I'll send this to Triage.

**Comment by DavisVaughan** [comment]
This is https://github.com/posit-dev/positron/issues/4253 so we will track over there

**Comment by psychelzh** [comment]
@DavisVaughan Interestingly, we should note that I found if there is no `.Rproj` file, the messages do not print twice. Is there something related to `.Rproj` file?

**Comment by DavisVaughan** [comment]
Positron does not use that file in any way, so I'm not sure, but I'll keep it in mind when we work on #4253 as a test case

**Comment by psychelzh** [comment]
You are correct that it has nothing to do with the `.Rproj` file. I have tested it then.
