### ISSUE TITLE
Variables pane vertical splitter is hard to drag

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#4720]
#### Positron and OS details:

Positron Version: 2024.09.0 (Universal) build 45
Code - OSS Version: 1.92.0
Commit: b0ec249b20455499f9e79ffe0bec35a5ff602ea4
Date: 2024-09-16T02:45:13.900Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0

#### Interpreter details:

R 4.3.1 - probably doesn't matter

## Describe the issue:

The variables pane vertical splitter that separates the variables name from its display values is hard to drag. When you click to drag it, you can only drag it a few pixels. See screencast below:

https://github.com/user-attachments/assets/948c798a-6d37-4225-94eb-7d4baab43a71

## Steps to reproduce the issue:

Create a variable like: 

```
very_long_name <- list(
  a_very_very_very_long_name = list(1,2,3)
)
```

## Expected or desired behavior:

Should be easy to drag that splitter so you can quickly see the full name.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

N/A

**Comment by petetronic** [comment]
I'm able to reproduce this

**Comment by juliasilge** [comment]
Reported in discussions here: https://github.com/posit-dev/positron/discussions/4805

**Comment by anbrav0** [comment]
Hello!

<details><summary>Positron Info and specs</summary><p>

```
Positron Version: 2024.09.0 (Universal) build 77
Code - OSS Version: 1.93.0
Commit: 9b6f7c066546a4c7f104368fc769fb3768b08bfd
Date: 2024-09-23T02:43:50.589Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

.rs.api.versionInfo()
$citation
To cite Positron in publications use:

  Posit team (2024). Positron: A next generation data science IDE. Posit Software,
  PBC, Boston, MA. URL [https://www.posit.co/.](vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#)

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {Positron: A next generation data science IDE},
    author = {{Posit team}},
    organization = {Posit Software, PBC},
    address = {Boston, MA},
    year = {2024},
    url = {[https://www.posit.co/](vscode-file://vscode-app/Applications/Positron.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html#)},
  }

$mode
[1] "desktop"

$version
[1] ‘2024.9.0’

$long_version
[1] "2024.09.0+77"

$ark_version
                                                                                     branch 
                                                                                     "main" 
                                                                                     commit 
                                                                                  "5a9ceda" 
                                                                                       date 
                                                                  "2024-09-19 11:41:07 EDT" 
                                                                                     flavor 
                                                                                  "release" 
                                                                                       path 
"/Applications/Positron.app/Contents/Resources/app/extensions/positron-r/resources/ark/ark" 
                                                                                    version 
                                                                                  "0.1.138"
```

</p></details>





I recently posted a discussion here at #4805 regarding this behavior in Positron. and i seemed to have missed that there is an open issue regarding this behavior! I apologize for that! I also wanted to add that once you're able to pull the splitter, the variable panel vertical splitter stops at about here (see below) and at that point you are not able to pull or drag past that stopping point 
<img width="1722" alt="image" src="https://github.com/user-attachments/assets/ba1b6e99-ca4f-442d-b7e5-8d701fa27188">


where as in R studio, it stops at about here:
<img width="1727" alt="image" src="https://github.com/user-attachments/assets/8c7b8106-bde4-4707-8fbd-2644aca603f9">

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-66
    OS Version          : OSX

### Test scenario(s) 

Dragging after executing reprex is smooth

Link(s) to TestRail test cases run or created:
