### ISSUE TITLE
Unreliable readline prompt detection with active browser sessions

### ISSUE THREAD

**Issue by lionel-** [posit-dev/positron#4742]
When R requests inputs, we don't know for sure what is the intent:

- The next top-level command to execute
- The next command to execute in a debugging session
- The last command was incomplete and R requests more input to complete it
- Some running R code requests input via `readline()` or `menu()`

We currently use heuristics to determine these cases (see [prompt_info](https://github.com/posit-dev/ark/blob/a0c4890e2e52a670f629ba12c17a638c258c3a52/crates/ark/src/interface.rs#L753)).

Since https://github.com/posit-dev/ark/pull/346, we have made the detection of _debug prompts_ more reliable at the expense of the detection of _readline prompts_. Here is a reprex:

```r
foo <- function() {
  bar()
  NULL
}

bar <- function() {
  readline("foo ")
}

debug(foo)
foo()
```

Once in `foo()`, step _over_ `bar()`. Ark drops in the debugger again, inside `readline()`.

<img width="805" alt="Screenshot 2024-09-19 at 12 40 10" src="https://github.com/user-attachments/assets/b584c6c2-a665-4d6b-b4fe-7d331be43318">

Possible fixes:

- Eventually we would like to contribute an extended `ReadConsoleExt()` hook to R where contextual information would be passed via a struct. Then we would know for sure what kind of prompts we're dealing with.

- In the meantime we could detect `readline()` or `menu()` on the stack and never drop in the debugger in that case, and instead treat the prompt like a readline request. However that would get us in a weird state with `debug(readline)` (or a user stepping in it by accident with F11).

- We could match `Browse[%d]> ` in the prompt string. If it matches, it's a browser prompt, otherwise, it's a readline prompt running within a debug session. We could still be tricked by `readline("Browse[0]> ")` but I think that's ok.

**Comment by DavisVaughan** [comment]
This particular example looks nice to me now. Compared to above, we temporarily exit the debug state to allow the user to type in their input-reply, and then we drop back in to the debugger on the next line.

https://github.com/user-attachments/assets/59e4ebe4-ab18-4754-a5f9-d16d981c4e53
