### ISSUE TITLE
Default session

### ISSUE THREAD

**Issue by matthewgson** [posit-dev/positron#4749]
Hi, 

Whenever I start Positron, the session opens with R and automatically switches to Python in a few seconds. 
Is there a way to prevent it and set a default session (to a specific version of R) when launched?  

https://github.com/user-attachments/assets/1f177432-1db0-4dfc-8be4-02052b096c1d

**Comment by petetronic** [comment]
Thank you @matthewgson for reporting this, I often experience this too. We plan to fix this as we address the epic #3541 "Epic: Runtime Startup Refinement". I believe this particular issue is covered by #3432 (and somewhat related, #1044, #1143).

**Comment by petetronic** [comment]
Closing this one and will track work via the above mentioned issues.
