### ISSUE TITLE
R - `ctrl+enter` copy the script at console and don't run

### ISSUE THREAD

**Issue by rtheodoro** [posit-dev/positron#4751]
#### Positron and OS details:

Positron Version: 2024.09.0 build 45
Code - OSS Version: 1.92.0
Commit: b0ec249b20455499f9e79ffe0bec35a5ff602ea4
Date: 2024-09-16T02:39:36.374Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.9.3-76060903-generic

#### Interpreter details:

 R 4.4.1

## Describe the issue:

Positron don't run the code, just copy and paste at console.

## Steps to reproduce the issue:

R Script

1. Put a |> or (  inside a function  - and don't close or add nothing after
2. Click at the line
3. Press `ctrl+enter`
4.  The line (or select code) don't run and don't show errors. All the script is paste at the console
5.  Anything I tried to run after this was just pasted at the console

To fix this I need to run something direct on the console. Ex: 5-5.
Than find where was the error and fix.

## Expected or desired behavior:
Run the code and show the error inside the function.

## Were there any error messages in the UI, Output panel, or Developer Tools console?
No errors, warnings, nothing.

**Comment by MGousseff** [comment]
I reproduce the bug. It seems it happens when you selection doesn't end by an end of line. Clicking in the console and pressing enter runs the copied selection, but it is not the most desired way of doing it.

**Comment by petetronic** [comment]
Hi @rtheodoro, I think this might be related to "incomplete" code being sent for evaluation. Does issue https://github.com/posit-dev/positron/issues/4594 match your scenario?

**Comment by rtheodoro** [comment]
> Hi @rtheodoro, I think this might be related to "incomplete" code being sent for evaluation. Does issue #4594 match your scenario?

yes, I think so! sorry, I did not found.

> I reproduce the bug. It seems it happens when you selection doesn't end by an end of line. Clicking in the console and pressing enter runs the copied selection, but it is not the most desired way of doing it.

I don't know what I did before, now its working as you said.

**Comment by petetronic** [comment]
Thank you still for reporting this, I'll close this issue and track the request via the above mentioned issue.
