### ISSUE TITLE
Toggle Line Comment is really `CTRL+/` when the drop down menu says it is `CTRL+SHIFT+C` (as is the default in Rstudio, I think)

### ISSUE THREAD

**Issue by MGousseff** [posit-dev/positron#4753]
## Describe the issue:
Toggle Line Comment is really `CTRL+/` when the drop down menu says it is `CTRL+SHIFT+C` (as is the default in Rstudio, I think)

## Expected or desired behavior:
I don't care which shortcut should be the default, but the drop down menu message and the shortcut should be consistent. 
I hope it's not a duplicate, didn't find it in opened issues.

**Comment by petetronic** [comment]
Hi @MGousseff, is it possible you're experiencing this issue due to the RStudio Keymap Extension? https://github.com/posit-dev/positron/issues/3993

**Comment by MGousseff** [comment]
Oh yes, sorry, I didn't find it when searching. You can close this one, sorry for the trouble.
