### ISSUE TITLE
Pressing spacebar with delete confirmation modal is generating duplicate modals

### ISSUE THREAD

**Issue by petetronic** [posit-dev/positron#4765]
#### Positron and OS details:
Positron Version: 2024.09.0 (Universal) build 45

#### Interpreter details:
Any runtime should do

## Describe the issue:
Pressing the spacebar while the modal is open from the Delete all objects option in the Variables pane seems to create a duplicate modal dialog.

## Steps to reproduce the issue:

1. Create any variable in any runtime so there is an entry in the Variables Pane
2. Click the Delete all objects button 
3. While the modal is open, press the spacebar multiple times
4. Note the modal does not close, and the app background gets dimmer each time
5. Press the Cancel button, note the app background gets lighter each time

## Expected or desired behavior:
Perhaps that the default action would be selected, per the request in https://github.com/posit-dev/positron/issues/383, or do nothing.

## Were there any error messages in the UI, Output panel, or Developer Tools console?
No, the issue may be the Delete all objects button still has focus, and the spacebar is triggering a duplicate modal each time?

**Comment by petetronic** [comment]
<img width="1425" alt="Screenshot 2024-09-19 at 5 29 27 PM" src="https://github.com/user-attachments/assets/211ad7df-49f4-446b-828e-698ce991e5f3">

**Comment by softwarenerd** [comment]
This is addressed in: https://github.com/posit-dev/positron/pull/4807.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-95
    OS Version          : OSX

### Test scenario(s) 

Cannot repro according to filing description

Link(s) to TestRail test cases run or created:
