### ISSUE TITLE
Provide Ctrl+Enter shortcut for Quarto to execute code consistently on all platforms

### ISSUE THREAD

**Issue by yak-liu-NEU** [posit-dev/positron#4767]
#### Positron and OS details:

Positron Version: 2024.09.0 (Universal) build 45
Code - OSS Version: 1.92.0
Commit: b0ec249b20455499f9e79ffe0bec35a5ff602ea4
Date: 2024-09-16T02:45:13.900Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.2.0

#### Interpreter details:

R 4.4.1

## Describe the issue:

Hi all, I'm new to the Positron from RStudio. Trying to run a line of code in the chunk in .Rmd file , with Ctrl + enter, but get the error message:

Cannot execute code. Unable to start a runtime for the Quarto language.

<img width="909" alt="image" src="https://github.com/user-attachments/assets/a82e7522-0e80-45d8-bfba-d244c824ac9f">

The same procedure is also tried with .qmd file and output the same msg. 

I tried crtl + enter to run code in .R file and works fine. Run code chunks in .Rmd also works. Preview in Positron works and output the .html and .md file.

Any suggestions:) ?

**Comment by petetronic** [comment]
Hi @yak-liu-NEU, thank you for trying out Positron. I tried this scenario and can confirm that on Mac, Ctrl+Enter does not run a line of code in an R cell in a .Rmd, however, Cmd+Enter does execute the line in the R session.

**Comment by yak-liu-NEU** [comment]
Hi @petetronic, thanks for replying. This so hilarious lol. Btw, I find both ctrl + enter and cmd + enter are bond to "R: Run Selection in Console". Btw, just curious, How can Positron tell the priority of the keybindings if you have multiple keybindings to one command?

**Comment by jennybc** [comment]
Relevant: #1192. I think we addressed this for `.R` files, but it would probably need attention in the Quarto extension to also be solved in `.Rmd`.

**Comment by yak-liu-NEU** [comment]
I also notice this topic was brought up in #1518. Hope there'll be a patch for this. Got used to Ctrl + enter for years, thanks for the info @jennybc

**Comment by midleman** [comment]
### Verified Fixed
Positron Version(s) : 2024.11.0 - build 129
OS Version(s) : MacOS

### Test scenario(s) 
Confirmed I was able to send code from cell to console with:
* Cmd/Ctrl + Enter - cell line
* Cmd/Ctrl + Shift + Enter - entire cell

### Link(s) to TestRail test cases run or created: 
n/a
