### ISSUE TITLE
Can't create a folder on a remote server

### ISSUE THREAD

**Issue by apcamargo** [posit-dev/positron#4776]
When I try to create a folder through Positron's GUI (New → New Folder) in a remote server I get the error message below:

```
Error: ENOTSUP: operation not supported on socket, mkdir '/home/ubuntu'
```

I'm using an EC2 instance in which my user has admin privileges.

#### Positron and OS details:

```
Positron Version: 2024.09.0 (Universal) build 45
Code - OSS Version: 1.92.0
Commit: b0ec249b20455499f9e79ffe0bec35a5ff602ea4
Date: 2024-09-16T02:45:13.900Z (4 days ago)
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin x64 24.0.0
```

```
$ cat /etc/os-release

PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

**Comment by petetronic** [comment]
Thank you @apcamargo - that may be a limitation of the /home directory itself, though I ran into other issues with directories that should have been owned by the sshuser. We'll investigate.

**Comment by apcamargo** [comment]
Another detail that I forgot to mention is that creating the folder though the left sidebar worked just fine.

**Comment by petetronic** [comment]
Ah, so on the latter, I see the confusion in terminology. I'll log a separate issue for this, as the menu New -> New Folder is equivalent to new workspace root folder. The button in the Explorer side bar is to create a new subfolder at the level of focus in the tree view of the file explorer.

**Comment by petetronic** [comment]
On the confusing terminology, I spoke with PM today and we logged https://github.com/posit-dev/positron/issues/4787 to track that.

**Comment by juliasilge** [comment]
Related to #4840
