### ISSUE TITLE
R 4.4.1 exited unexpectedly after using brms

### ISSUE THREAD

**Issue by WillemSleegers** [posit-dev/positron#4779]
#### Positron and OS details:

Positron Version: 2024.09.0 (Universal) build 27
Code - OSS Version: 1.92.0
Commit: d996153f3be6bcc9af460300e61103425323b973
Date: 2024-09-11T02:38:46.408Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin x64 24.0.0

#### Interpreter details:

R 4.4.1

## Describe the issue:

After I run a model using the `brm()` function from the brms package, the R terminal restarts.

## Steps to reproduce the issue:

Run this example from the brms documentation:
```
library(brms)
fit1 <- brm(
  count ~ zBase * Trt + (1|patient),
  data = epilepsy, family = poisson(),
  prior = prior(normal(0, 10), class = b) +
  prior(cauchy(0, 2), class = sd), backend = "cmdstanr"
)
```

## Expected or desired behavior:

The R terminal not restarting.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

The R terminals say: R 4.4.1 exited unexpectedly: killed with signal 6 (SIGABRT). I've attached the log.
[log.txt](https://github.com/user-attachments/files/17095066/log.txt)

**Comment by strengejacke** [comment]
Possibly related to #4686?

**Comment by lionel-** [comment]
yep, should be fixed in the next version of Positron!
