### ISSUE TITLE
Notebook/kernel stops after executing a cell ending with a commented line

### ISSUE THREAD

**Issue by apcamargo** [posit-dev/positron#4789]
#### Positron and OS details:

```
Positron Version: 2024.09.0 (Universal) build 77
Code - OSS Version: 1.93.0
Commit: 9b6f7c066546a4c7f104368fc769fb3768b08bfd
Date: 2024-09-23T02:43:50.589Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin x64 24.0.0
```

Remote session in:

```
$ cat /etc/os-release

PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

#### Interpreter details:

- R (4.4.1), installed through `rig`.
- Python (3.12), installed with `pixi`.

## Describe the issue:
I'm experiencing an issue in my R Jupyter notebook where the kernel stops working whenever I execute a cell that ends with a commented line. Here's an example:

<img width="339" alt="image" src="https://github.com/user-attachments/assets/9ceb8821-53a9-4ade-8d71-5ac819b41a46">

In this notebook, the first two cells execute as expected. However, when I try to execute the third cell, which ends with a commented line, the notebook becomes unresponsive. This is evident from the execution time of the third and fourth cells.

I don't have this issue when running Python notebooks (`ipykernel` version 6.29.5), so maybe the underlying problem is in Ark?

**Comment by jmcphers** [comment]
Thanks for reporting this! We'll look into it. I don't think it's related to the remote environment you're using as I can reproduce it on a plain macOS build of Positron. 

<img width="722" alt="image" src="https://github.com/user-attachments/assets/170c0aa2-b590-44db-bb22-10cab1e4570e">

**Comment by juliasilge** [comment]
I believe this is the same as #3919, although I don't think we realized at the time it is _also_ a problem on the next line.

**Comment by jmcphers** [comment]
ahh, yes it is! Thanks, @juliasilge.
