### ISSUE TITLE
Links and Cross References in Help hard to read with dark theme

### ISSUE THREAD

**Issue by strengejacke** [posit-dev/positron#4790]
#### Positron and OS details:

Positron Version: 2024.09.0 (system setup) build 77
Code - OSS Version: 1.93.0
Commit: 9b6f7c066546a4c7f104368fc769fb3768b08bfd
Date: 2024-09-23T02:44:07.418Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

#### Interpreter details:

R 4.4.1

## Describe the issue:

With the _Positron Dark_ theme (Default Positron Dark), links/cross references in help files are hard to read. I can't remember this was also the case in older Positron versions, maybe this was related to #4762? (but that's just a guess, I haven't checked anything)

![image](https://github.com/user-attachments/assets/ffa33989-1a38-41a4-afc2-237a409c6bef)

**Comment by jmcphers** [comment]
You're right, this is a regression. In the previous build, these links were bright blue and easy to read.

<img width="598" alt="image" src="https://github.com/user-attachments/assets/f56a5c59-2945-46a3-ae22-c4a04f64da64">

```
Positron Version: 2024.09.0 (Universal) build 45
Code - OSS Version: 1.92.0
Commit: b0ec249b20455499f9e79ffe0bec35a5ff602ea4
Date: 2024-09-16T02:45:13.900Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

We'll get this fixed up. Thanks for reporting!

**Comment by jmcphers** [comment]
Reported again in https://github.com/posit-dev/positron/issues/5227.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-55
    OS Version          : OSX

### Test scenario(s) 

Welcome and Help are now very legible in dark mode.

Link(s) to TestRail test cases run or created:
