### ISSUE TITLE
Color preview doesn't render if the file or Jupyter cell starts with the color code

### ISSUE THREAD

**Issue by apcamargo** [posit-dev/positron#4809]
#### Positron and OS details:

```
Positron Version: 2024.09.0 (Universal) build 77
Code - OSS Version: 1.93.0
Commit: 9b6f7c066546a4c7f104368fc769fb3768b08bfd
Date: 2024-09-23T02:43:50.589Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin x64 24.0.0
```

Remote session in:

```
$ cat /etc/os-release

PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

#### Interpreter details:

Interpreter-independent.

## Describe the issue:

The color preview doesn't render if the file or Jupyter cell starts with the color representation (hexadecimal or `rgb()`).

## Steps to reproduce the issue:

Write a color code at the beginning of a file or Jupyter cell:

<img width="208" alt="image" src="https://github.com/user-attachments/assets/abbc4019-d41c-4d97-8a2a-3ef058ce7305">

If I add a space before the `#`, the preview will render. Apparently this only happens when the first line starts with the color.

This happens for the `rgb()` notation as well (see below). Other color representations (`oklch()`, `hsl()`, etc.) don't render at all, but this is likely a separate issue.

<img width="269" alt="image" src="https://github.com/user-attachments/assets/13a992c7-1266-43a1-9e06-610b6dfd5da4">

## Expected or desired behavior:

Colors should be presented in a consistent manner and not depend on their position in the file.

**Comment by jmcphers** [comment]
This behavior comes from the upstream project, VS Code. Here's a screenshot from VS Code:

<img width="310" alt="image" src="https://github.com/user-attachments/assets/13429fd1-f0f4-4ef1-89ae-cc33561c4641">

Note that (unlike Positron) VS Code does not always show color decorators by default; you need to turn it by checking "Color Decorators" (to enable the feature) and "Default Color Decorators" (to show them in all file types).

<img width="455" alt="image" src="https://github.com/user-attachments/assets/da561e65-1e61-40a2-bb23-15ffa35ca6db">

It wouldn't be impossible to fix it in Positron by patching the behavior, but we'd encourage you to report it upstream. https://github.com/microsoft/vscode/issues

**Comment by apcamargo** [comment]
Thanks for the answer! I first suspected this could be a VScode thing, but since color previews were not showing up there (and I didn't know of this option), I decided to open the issue here.

I'll create another one in the VScode repo.

**Comment by juliasilge** [comment]
Thank you so much for opening the upstream issue! We will plan to track the problem there.
