### ISSUE TITLE
Missing R kernel should cause a build failure

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#4815]
We had a build "succeed" across all platforms today even though the R kernel was missing. This produced a version of Positron that could not run R. Example Positron log output:

```
  ERR Creating session for language runtime e0f5a4e62ac703e2ea49c2bf1102f8b1 (language: R name: R 4.3.3 version: 4.3.3) failed. Reason: Error: Unable to find R kernel
workbench.desktop.main.js:130687   ERR Unable to find R kernel: Error: Unable to find R kernel
	at t.createJupyterKernelSpec (/Applications/Positron.app/Contents/Resources/app/extensions/positron-r/dist/extension.js:1:486610)
	at t.RRuntimeManager.createSession (/Applications/Positron.app/Contents/Resources/app/extensions/positron-r/dist/extension.js:1:484504)
	at $5Ec.$createLanguageRuntimeSession (/Applications/Positron.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92529:62)
```

Example build log snippet:

```
No locally built Ark found in C:\a\positron-builds\positron-builds\ark; checking downloaded version.
package.json version: 0.1.139 
Downloaded ark version: Not found 
Using Github PAT from environment variable POSITRON_GITHUB_PAT.
Could not find Ark with asset name ark-0.1.139-windows-x64.zip in the release.
```

Full build logs of "succeeded" build across all platforms that was missing ark: https://github.com/posit-dev/positron-builds/actions/runs/11025193729

This is probably the behavior we want in *dev* builds because even if we failed to download Ark for some reason (you specified the wrong number? connectivity issue? rate limiting? bad GH token?) you can still use most of Positron without it.

However, in CI and in release builds, a failure to download Ark should cause the whole build to fail, since we never want to produce a release of Positron without R support, and tests will fail later.

**Comment by lionel-** [comment]
On our end we're taking steps to make sure we don't create partial/incomplete releases: https://github.com/posit-dev/ark/pull/546

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-103
    OS Version          : OSX

### Test scenario(s) 

Marking as verified, but we don't really have a test case for this.  Need to wait until an issue naturally comes up, if that happens, and see it in action.

Link(s) to TestRail test cases run or created:
