### ISSUE TITLE
Ark: Modernize GHA workflows and remove warnings

### ISSUE THREAD

**Issue by DavisVaughan** [posit-dev/positron#4821]
- [x] [mukunku/tag-exists-action@v1.3.0](https://github.com/posit-dev/ark/blob/main/.github/workflows/release.yml#L38) could be upgraded to 1.6.0

- [x] [actions/create-release@v1](https://github.com/posit-dev/ark/blob/main/.github/workflows/release.yml#L93) was long since deprecated, and could be replaced with [softprops/action-gh-release@v2](https://github.com/softprops/action-gh-release/releases/tag/v2.0.8) with a little bit of extra effort, we have been using this on Positron builds today

- [x] [actions/upload-release-asset@v1](https://github.com/posit-dev/ark/blob/main/.github/workflows/release.yml#L138) also deprecated, and also can be replaced with [softprops/action-gh-release@v2](https://github.com/softprops/action-gh-release/releases/tag/v2.0.8) as it allows files to be specified as additional assets even if a release already exists, and we use this on Positron builds today

- [x] Upstream r-lib/actions needs to drop usage of `save-always` https://github.com/r-lib/actions/pull/934. We will get that for free when they do

To see all the warnings look at the Annotations under a release workflow like https://github.com/posit-dev/ark/actions/runs/11036546624

Notably GitHub is going to force node 20 very soon, so we should prioritize this

**Comment by lionel-** [comment]
Looks like our slack report job is broken, should also update it: https://github.com/posit-dev/ark/actions/runs/11054417985/job/30711190350?pr=546
