### ISSUE TITLE
Resizing the Data Explorer is broken

### ISSUE THREAD

**Issue by softwarenerd** [posit-dev/positron#4834]
## System details:

<img width="280" alt="image" src="https://github.com/user-attachments/assets/19e53a8e-ee4b-4f9d-8e20-4ea4eb28b898">

#### Positron and OS details:

Positron Version: 2024.09.0 (Universal) build 45
Code - OSS Version: 1.92.0
Commit: b0ec249b20455499f9e79ffe0bec35a5ff602ea4
Date: 2024-09-16T02:45:13.900Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

#### Interpreter details:

N/A

## Describe the issue:

I broke resizing the Data Explorer. 

In this build, or at some point before it, and subsequent builds, you can make the Data Explorer larger, and it will respond to the resizing appropriately by updating the scrollbars. However, when you make the Data Explorer smaller, it does not respond to the resizing appropriately and the scrollbars are not updated.

Here's a screen recording of the issue:

https://github.com/user-attachments/assets/99ee13bc-d007-456e-a9fc-dbaadf9e620f

## Steps to reproduce the issue:

This is easy to reproduce by adjusting the height of the Data Explorer:

1. Resize the Data Explorer to be taller, note that the vertical scrollbar updates.
2. Resize the Data Explorer to be shorter, note that the vertical scrollbar does not update.

## Expected or desired behavior:

The vertical scrollbar should update appropriately. Here's a screen recording of this working properly:

https://github.com/user-attachments/assets/a67bddad-7461-48b0-a8be-a0b6f25eea55

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.09.0-103
    OS Version          : OSX

### Test scenario(s) 

Scrollbars behaving normally again.

Link(s) to TestRail test cases run or created:
