### ISSUE TITLE
Positron Web: Help does not work (404)

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#4847]
#### Positron and OS details:

Main on 9/30/24

#### Interpreter details:

Any

## Describe the issue:

Attempts to open help with:
Python:
?load
R:
?load()

result in "Not found." in the Help pane

## Steps to reproduce the issue:

1. Use ?load (Python) or ?load() (R) to attempt to open Help
2. Note that it does not open

## Expected or desired behavior:

Help should still work in web mode.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by sharon-wang** [comment]
@testlabauto Do you recall which commit on `main` this was tested with? There was a fix merged in e51332d5baa59b72f5e8b28861bbb751f25452ea a few hours ago to resolve some Help proxy issues for both python and R.

**Comment by sharon-wang** [comment]
Woohoo! I'll close this -- we'll want to test Help in Workbench once https://github.com/posit-dev/positron/issues/4274 is done.
