### ISSUE TITLE
Test: Console output in a loop with short pauses in R

### ISSUE THREAD

**Issue by DavisVaughan** [posit-dev/positron#4849]
Issue: https://github.com/posit-dev/positron/issues/4519
PR: https://github.com/posit-dev/positron/pull/4848

Reprex:

```r
tokens <- c(
  "",
  "Why",
  " do",
  " programmers",
  " prefer",
  " dark",
  " mode",
  "?\n\n",
  "Because",
  " light",
  " attracts",
  " bugs",
  "!"
)

for(token in tokens) {
  cat(token)
  Sys.sleep(0.01)
}
```

See the before/after videos for expected behavior:
https://github.com/posit-dev/positron/pull/4848#issue-2557353017

Mostly I'd like to get a test added to ensure that our Console isn't "dropping" any output in this particular case. The `Sys.sleep(0.01)` is important here!

**Comment by testlabauto** [comment]
Added test and its in regular suite
