### ISSUE TITLE
Positron Web: Terminal text is very small

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#4853]
#### Positron and OS details:

Main on 9/30/24 as of about 2:00 PM MST

#### Interpreter details:

R 4.3.3 & Python 3.10.12

## Describe the issue:

Terminal text is very small.  I am repro'ing by running a Shiny app but am not sure if that is required.

<img width="1206" alt="image" src="https://github.com/user-attachments/assets/a62d6e4a-884d-465c-8793-debed2d2e802">

## Steps to reproduce the issue:

1. Run Shiny app
2. Observe terminal text size 

## Expected or desired behavior:

Readable terminal text

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No

**Comment by timtmok** [comment]
@testlabauto What happens if you try to reset the terminal font size or the editor font size?

![Image](https://github.com/user-attachments/assets/a3b119ed-66b1-4ad8-8f07-b2565dee1fdd)

**Comment by testlabauto** [comment]
I am actually no longer able to repro.  I have been playing with my terminal settings quite a lot trying to get a Dash app to display and may have changed something but this no longer repros.

**Comment by timtmok** [comment]
I'll close for now
