### ISSUE TITLE
Epic: Quarto Improvements for 2024.11 & 2024.12

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#4858]
## Config and preferences
- [x] #1376 
- [x] #1435 
- [x] #1436 
- [x] #1955
- [x] #2933

## Code execution

- [x] #1572 
- [x] #1646
- [x] #4767
- [x] #3945 
- [x] #3792

## Misc

- [x] #4097 
- [x] #4511 
- [x] #3714

**Comment by juliasilge** [comment]
We got roughly half of this done in 2024.11 and I am moving the epic forward to 2024.12 to finish out the remaining work.

**Comment by juliasilge** [comment]
This epic is now completed! 🎉 

I did take a look briefly at https://github.com/quarto-dev/quarto/issues/596; there _is_ currently a way to set your default but we could make it easier in the future if folks don't tend to find that easily.
