### ISSUE TITLE
New window shortcut (Shift + Cmd + N) rather opens new text file 

### ISSUE THREAD

**Issue by matthewgson** [posit-dev/positron#4862]
It might be macOS only but I found the shortcut to open a new window (Shift + Cmd + N) doesn't work, but opens new text file.

**Comment by petetronic** [comment]
Is it possible that you have the RStudio Keymap Extension enabled? It registers the following shortcut:
https://github.com/posit-dev/positron/blob/4351851a817dabac0b7859172bb07d261af8b69d/extensions/positron-rstudio-keymap/package.json#L52-L59

If you've found that the wrong shortcut is mentioned in menus, even with that extension disabled, it may also be issue #3993.

**Comment by matthewgson** [comment]
RStudio keybinding was enabled and it works, thank you. It's a bit unexpected though.

**Comment by timtmok** [comment]
Glad that you found the cause! This is expected since the RStudio keybindings were enabled to accommodate those that want to use more familiar keybindings.

**Comment by matthewgson** [comment]
@timtmok Oh I meant by this picture. It shows the default positron's shortcut even though RStudio keybinding is enabled.
![Image](https://github.com/user-attachments/assets/96c2dd77-7426-4be0-a771-d953c961f8fb)

**Comment by jennybc** [comment]
I think we are tracking this in #2150.

See https://github.com/posit-dev/positron/issues/2150#issuecomment-2313382741 specifically:

> We have collected a number of issues that are related to this problem where the UI always shows a built-in keybinding, even when that keybinding does not apply to that action. The user might end up looking at the UI and trying that keybinding, but it does something completely different. So far this has come up in situations like "when": "isRPackage" or when the RStudio Keymap is enabled. Let's use this issue to track this problem and close the others.
