### ISSUE TITLE
Intermittent "Socket disposed" when starting up python

### ISSUE THREAD

**Issue by jonvanausdeln** [posit-dev/positron#4863]
## System details:
Ubuntu 22 - Github Runner
#### Positron and OS details:
All recent versions

#### Interpreter details:
Python 3.10.12

## Describe the issue:

When running our automated UI/Smoke tests there is occasionally a failure that reports "Error: Socket disposed" when trying to start up Python.  We've only seen this when running automated tests.  It happens perhaps 5% of the time...

![image](https://github.com/user-attachments/assets/7afe6bb7-6978-4a3b-8710-4651627268cc)

## Steps to reproduce the issue:

1. Try to start a Python interpreter 

## Expected or desired behavior:

Python to start

**Comment by jonvanausdeln** [comment]
Moving to triage because this is happening more frequently

**Comment by midleman** [comment]
Ran into this error on nightly run of `Data Explorer - Large Data Frame` (Web). Attaching all logs for reference.[largeDataFrame.test.js.zip](https://github.com/user-attachments/files/17295043/largeDataFrame.test.js.zip)

**Comment by midleman** [comment]
Ran into it again. [variablespane.test.js.zip](https://github.com/user-attachments/files/17346966/variablespane.test.js.zip)

**Comment by jonvanausdeln** [comment]
While the % of tests that hit this is low... the occurrence rate is probably 1 or 2 times a day (we hit it in a PR job today as well).

I'd would advocate that we bump this to a sooner release...

**Comment by testlabauto** [comment]
Bumping back to triage to consider moving to a sooner release.

**Comment by juliasilge** [comment]
In #5262 we plan to move away from the Jupyter Adapter extension, which is where this error is arising.

**Comment by jmcphers** [comment]
Now that we are using the new supervisor by default, this codepath shouldn't be active, so we shouldn't see this error any more. QA, can you confirm?

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) :Main on 11/13/24
    OS Version          : OSX

### Test scenario(s) 

No longer seeing this in smoke tests

Link(s) to TestRail test cases run or created:
