### ISSUE TITLE
Rename browser state IndexedDB database names

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#4864]
## Background
Positron saves browser state in several IndexedDBs, each named `vscode-web-{DB_NAME}`, which may result in unexpected behaviour if a user opens a folder in Positron and then later opens the same folder in VS Code, or vice versa.

To avoid such collisions, we should rename positron's IndexedDBs, perhaps something like `positron-web-{DB_NAME}`.

## Possible Solution

In particular, we may want to rename 
https://github.com/posit-dev/positron/blob/e51332d5baa59b72f5e8b28861bbb751f25452ea/src/vs/workbench/browser/web.main.ts#L466
to `positron-web-db`; and

https://github.com/posit-dev/positron/blob/e51332d5baa59b72f5e8b28861bbb751f25452ea/src/vs/workbench/services/storage/browser/storageService.ts#L342
to `positron-web-state-db`.

There are other databases which have the prefix `vscode` that we may want to rename to `positron` as well.

## Considerations

Currently, since our databases are the same name as VS Code, there may be some convenient state sharing that we would lose after renaming the databases to be specific to Positron. At the same time, not renaming the databases may result in unexpected behaviour due to the shared state.

**Comment by sharon-wang** [comment]
Implemented in https://github.com/posit-dev/positron/pull/5035

**Comment by jonvanausdeln** [comment]
IndexDB now has positron prefix names
