### ISSUE TITLE
Plotnine and Matplotlib 

### ISSUE THREAD

**Issue by nbradovc** [posit-dev/positron#4868]
Type: <b>Bug</b>

I am not able to import plotnine or matplotlib. I keep getting an error that says "no module named 'matplotlib' " and "no module named 'plotnine'". I am not sure what I am doing wrong

VS Code version: Positron 1.93.0 (Universal) (9b6f7c066546a4c7f104368fc769fb3768b08bfd, 2024-09-23T02:43:50.589Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
pyright|ms-|1.1.382
debugpy|ms-|2024.11.0-dev

</details>

**Comment by timtmok** [comment]
Thanks for filing this bug report!

@nbradovc What happens if you run `pip install plotnine` in the Console? Are you using an environment manager? What Python version are you using? This is an odd issue so any extra information you can provide will be helpful!

**Comment by jonvanausdeln** [comment]
@nbradovc , we are closing this issue for now. If you have more information and/or are still seeing the issue, please feel free to re-open it.
