### ISSUE TITLE
Move connections pane to core positron

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#4874]
In order to implement new planned UI for the connections pane we'll need the connections pane implementation to move to core positron components instead of a standalone extension.

### QA

I think we should wait a little longer to add automated tests as the UI will still change in the next 2 or 3 PRs.

Demo:

https://github.com/user-attachments/assets/9e7b7905-3c1b-421d-a9e4-6c8e5d3b3b94

Must be enabled with:

![image](https://github.com/user-attachments/assets/b3870a00-9fe2-4144-b54e-d74b7521945f)

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-60
    OS Version          : OSX

### Test scenario(s) 

Existing functionality still good and experimental mode functions well.

Link(s) to TestRail test cases run or created:
