### ISSUE TITLE
Linux Manjaro install has file that conflicts with VS Code

### ISSUE THREAD

**Issue by timtmok** [posit-dev/positron#4875]
#### Positron and OS details:
2024.09.103

## Describe the issue:
This was originally reported in a [discussion post](https://github.com/posit-dev/positron/discussions/4871). Installing Positron on Linux Manjaro when VS Code has already been installed fails due to a file conflict.

Extracting the DEB file downloaded from the Positron releases shows that it will try to install `/usr/share/pixmaps/com.visualstudio.code.oss.png`, which is actually the Positron logo.

I think the file name is coming from here: https://github.com/posit-dev/positron/blob/fd9bb6fe33b211a8c38921a333849c4741ede38f/product.json#L33

## Steps to reproduce the issue:

1. Install VS Code using `pamac build visual-studio-code-bin` on Linux Manjaro (
2. Install Positron using `pamac build positron-ide-devel-bin`

Workaround is to rename that file, which will allow the install to complete successfully.

For verification, extracting the DEB with `ar x <Positron deb file>` and the tar with `tar -xvf data.tar.gz`. Or viewing what would be installed with `dpkg -c <Positron deb file`.

## Expected or desired behavior:
The install should be successful

## Were there any error messages in the UI, Output panel, or Developer Tools console?
```
positron-ide-devel-bin: /usr/share/pixmaps/com.visualstudio.code.oss.png already exists
```

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.11.0-140](https://github.com/posit-dev/positron-builds/releases/tag/2024.11.0-140)
OS Version(s) : Ubuntu 24

### Test scenario(s) 
Extracted .deb file and I see

```
co.posit.positron.png
```

as expected


### Link(s) to TestRail test cases run or created:
