### ISSUE TITLE
Positron web: mouse scrolling up and down doesn't work with interpreter dropdown

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#4888]
#### Interpreter details:

[2024.10.0-5](https://github.com/posit-dev/positron-builds/releases/tag/2024.10.0-5)
Interpreter - N/A

## Describe the issue:

When you drop down the interpreter dropdown you have to point, click and grab the scrollbar to move down the list.  With desktop, scrolling use the mouse works (I happen to be using a magic mouse).

## Steps to reproduce the issue:

1. Run positron web
2. Dropdown interpreter selector
3. Attempt to scroll using the mouse

## Expected or desired behavior:

Would be nice for scrolling with the mouse to work.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No

**Comment by timtmok** [comment]
I noticed this as well when trying out something in web.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : Main on 10/22/24 at noon MST
    OS Version          : OSX

### Test scenario(s) 

Tested with the interpreter dropdown

Link(s) to TestRail test cases run or created:
