### ISSUE TITLE
Jupyter notebook change cell type loses language of code cell

### ISSUE THREAD

**Issue by kevbaer** [posit-dev/positron#4898]
#### Positron and OS details:

Positron Version: 2024.09.0 (Universal) build 103
Code - OSS Version: 1.93.0
Commit: 8274fe26a1582fa0dd0096d6631b500f591416c4
Date: 2024-09-30T02:46:33.741Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

#### Interpreter details:

Python 3.12.6

## Describe the issue:

Switching Jupyter notebook cells between markdown and code formats leads to "plain text" language instead of actual language being used

## Steps to reproduce the issue:

1. In Jupyter notebook, using Python or even R it looks like, switch a code cell with the selected language to markdown using M shortcut or dropdown menu
2. Then switch back to code cell using Y shortcut or dropdown menu
3. In bottom right hand corner, plain text is demonstrated and code typed will not autocomplete/have styling but will run

## Expected or desired behavior:

The language in use (in my case Python) should be kept when switching back and forth.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No.

Video can be found on this discussion: https://github.com/posit-dev/positron/discussions/4883

**Comment by midleman** [comment]
### Verified Fixed
Positron Version(s) : 2024.11.0-49
OS Version(s) : MacOS

### Test scenario(s) 

Confirmed able to switch between markdown and R/Python in cell with shortcut key as expected.

### Link(s) to TestRail test cases run or created: 

n/a
