### ISSUE TITLE
Undo in Customize Layout doesn't revert Side Bars or Panels to previous state

### ISSUE THREAD

**Issue by mkcaulfield** [posit-dev/positron#4918]
#### Positron and OS details:

Positron Version: 2024.09.0 (Universal) build 1
Code - OSS Version: 1.92.0
Commit: f37f4f5044a2a619e73d5db61a31e37fbd3faf18
Date: 2024-09-03T02:37:20.474Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0

#### Interpreter details:

Python 3.8.13 and R 4.3.2 (but I think these are irrelevant)

## Describe the issue:
Undo in Customize Layout does not Restore previous visibility state for Primary Side Bar, Secondary Side Bar, or Panel

## Steps to reproduce the issue:

1. Click the Customize Layout Icon at the top right
2. Toggle Visibility of [Activity Bar and / or Status Bar] and [Primary Side Bar, Secondary Side Bar, and / or Panel]; toggle Left / Right alignment of Panel or Primary Side bar
3. Hit Undo 

## Expected or desired behavior:
Expectation: Hitting the Undo icon will undo all the layout customizations and return all to previous state
What actually happens: Activity Bar, Status Bar, and Alignment items return to previous state; Primary Side Bar, Secondary Side Bar, and Panel do not return to previous state

## Were there any error messages in the UI, Output panel, or Developer Tools console?
No

**Comment by juliasilge** [comment]
FWIW this looks to be also the case in VS Code. I could not find an open issue on their repo, but I see the same behavior in VS Code for the Panel, Primary Side Bar, etc.

**Comment by juliasilge** [comment]
Would you feel comfortable opening an issue on this [upstream](https://github.com/microsoft/vscode/issues) @mkcaulfield? i.e. do you also have VS Code installed to see the behavior there as well?

**Comment by juliasilge** [comment]
I opened https://github.com/microsoft/vscode/issues/231161 so we can track this problem upstream. Thanks again @mkcaulfield!
