### ISSUE TITLE
Some R plots are not working on Windows

### ISSUE THREAD

**Issue by jonvanausdeln** [posit-dev/positron#4930]
#### Positron and OS details:
Windows 11
[2024.10.0-13](https://github.com/posit-dev/positron/releases/tag/2024.10.0-13)

#### Interpreter details:
 R 4.4.1

## Describe the issue:

At least some plots are not working windows any longer, but were previously (e.g. worked on 2024.07-100)

## Steps to reproduce the issue:

```
library(leaflet)
m = leaflet() %>% addTiles()
m = m %>% setView(-93.65, 42.0285, zoom = 17)
m %>% addPopups(-93.65, 42.0285, 'Here is the <b>Department of Statistics</b>, ISU')
```

No plot is shown

## Expected or desired behavior:

Plot to be shown

## Were there any error messages in the UI, Output panel, or Developer Tools console?
From the DevTools console

![Image](https://github.com/user-attachments/assets/f140a09e-97ab-492a-a51d-1dab0f62cccf)

**Comment by jmcphers** [comment]
I can also reproduce this reliably on Windows.

Possibly related to https://github.com/posit-dev/positron/pull/4855.

**Comment by jonvanausdeln** [comment]
The last build it worked on was [2024.09.0-107](https://github.com/posit-dev/positron-builds/releases/tag/2024.09.0-107)

**Comment by sharon-wang** [comment]
I was able to reproduce and have opened up a PR to fix this! https://github.com/posit-dev/positron/pull/4939

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.11.0-23](https://github.com/posit-dev/positron-builds/releases/tag/2024.11.0-23)
OS Version(s) : Windows 11

### Test scenario(s) 
These plots now work in windows!


### Link(s) to TestRail test cases run or created:
