### ISSUE TITLE
HTML-pages no longer displayed in the Viewer panel

### ISSUE THREAD

**Issue by strengejacke** [posit-dev/positron#4940]
#### Positron and OS details:

Positron Version: 2024.10.0 (system setup) build 13
Code - OSS Version: 1.93.0
Commit: 34b5c57cf211bcaf1bc48f75a8cd8d0b4378e5f5
Date: 2024-10-03T16:22:24.120Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

#### Interpreter details:

R 4.4.1

## Describe the issue:

HTML tables/pages are no longer displayed in the Viewer pane.

## Steps to reproduce the issue:

`gt::gt(iris)`

## Expected or desired behavior:

Opens the view, like in VSCode or previous Positron versions:

![Image](https://github.com/user-attachments/assets/cc3d0f12-f1dc-48b7-9f1c-9ab2d87a77fc)

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No

**Comment by jonvanausdeln** [comment]
@strengejacke , thank you for reporting!  This could be related to a recently found regression #4930 .  Hopefully we will have a fix soon!

**Comment by juliasilge** [comment]
I'm going to move this to verification to see if it is in fact fixed by #4939. If not, feel free to bump back to triage! 🙌

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.10.0-14](https://github.com/posit-dev/positron/releases/tag/2024.10.0-14)
OS Version(s) : Windows 11, Ubuntu 22

### Test scenario(s) 
Pages now appear as expected


### Link(s) to TestRail test cases run or created:

**Comment by jonvanausdeln** [comment]
@strengejacke , the new [2024.10.0-14](https://github.com/posit-dev/positron/releases/tag/2024.10.0-14) should fix this for you!

**Comment by strengejacke** [comment]
Yes, works! Thanks!
