### ISSUE TITLE
Use Jupyter supervisor by default on Workbench (and perhaps everywhere)

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#4941]
The Jupyter kernel supervisor added in #4910 is a required component to complete several Workbench workflows, including #1243, #4577, and https://github.com/posit-dev/positron/issues/3148.

This supervisor should become the default for Posit Workbench for the 2024.11 release; if the supervisor is sufficiently stable, we could also make it the default for other environments like Positron Desktop.

**Comment by jmcphers** [comment]
@jonvanausdeln noticed that the current configuration makes Jupyter Adapter failures cause problems even when Kallichore is set as the supervisor.

![Image](https://github.com/user-attachments/assets/e40e4efd-025b-48e4-8ca8-596b5999c41e)

As part of this change we need to make the Jupyter Adapter a soft dependency rather than a hard one, if we can't get rid of it entirely.

**Comment by sharon-wang** [comment]
QA note for testing on Workbench:

For the `kallichoreSupervisor.showTerminal` setting to take, a user needs to enable/disable it in one Positron session in Workbench and then create a new Positron session. The new Positron session will have the setting updated and the terminal enabled/disabled based on the user's selection.

**Comment by jonvanausdeln** [comment]
Kallichore is enabled by default on both the dev Positron server and release builds (both server and inside workbench)
