### ISSUE TITLE
Set `terminal.integrated.defaultProfile.linux` to `bash`

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#4946]
## Background

The recently added "Run App in Terminal" functionality (https://github.com/posit-dev/positron/issues/4557) relies on shell integration. On Linux, the shell may default to `sh`; however, `sh` is not supported. If the user has `sh` as their default shell, when they run an app, they'll get a notification toast that they'll need to change their default shell to a supported one in order to view their app in Positron.

## Proposed Solution

Set `terminal.integrated.defaultProfile.linux` to `bash` (a supported shell), to avoid what may be a common default to `sh` on Linux (`sh` is not a supported integrated terminal shell).

## For Reference

`terminal.integrated.defaultProfile.linux` only accepts strings like the ones in the supported shells list from the description for setting `terminal.integrated.shellIntegration.enabled`:

![Image](https://github.com/user-attachments/assets/53ee0c8b-afad-4993-8186-5283ff272639)

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.12.0-15](https://github.com/posit-dev/positron-builds/releases/tag/2024.12.0-15)
Workbench Version: 2024.11.0+338.pro1
OS Version(s) : Ubuntu 24.04

### Test scenario(s) 
Terminal now defaults to bash as expected


### Link(s) to TestRail test cases run or created:
