### ISSUE TITLE
`testthat::snapshot_review()` Shiny app no longer working

### ISSUE THREAD

**Issue by jennybc** [posit-dev/positron#4955]
I just ran `testthat::snapshot_review('aaa')` to look at some failing snapshot tests. The Shiny app launches successfully, but when I click on "Accept", I see this in the R Console:

```
> testthat::snapshot_review('aaa')
Starting Shiny app for snapshot review
ℹ Use Ctrl + C to quit
Loading required package: shiny
Accepting snapshot: 'tests/testthat/_snaps/aaa.md'
Review complete
Run `rlang::last_trace()` to see where the error occurred.
Error in `.Call()`:
! "ps_ui_evaluate_when_clause" not available for .Call() for package "(embedding)"
Hide Traceback
    ▆
 1. └─testthat::snapshot_review("aaa")
 2.   └─testthat:::rstudio_tickle()
 3.     └─rstudioapi::executeCommand("vcsRefresh")
 4.       └─rstudioapi::callFun(...)
 5.         ├─base::do.call(f, args)
 6.         └─`<fn>`(commandId = "vcsRefresh", quiet = FALSE)
 7.           └─.ps.ui.evaluateWhenClause("config.git.enabled && gitOpenRepositoryCount > 0") at modules/rstudio/commands.R:12:13
 8.             └─.ps.Call("ps_ui_evaluate_when_clause", whenClause) at modules/positron/frontend-methods.R:78:5
```

## Steps to reproduce the issue:

In an R package, arrange things such that a snapshot test is failing. For example, this test is guaranteed to fail over and over again:

```r
test_that("snapshot", {
  expect_snapshot(rnorm(1))
}
```

Run tests at least once to store a snapshot. The test will fail from that point on since you'll never generate the same random number. Now do `testthat::snapshot_review()` on the indicated file and click "Accept".

**Comment by strengejacke** [comment]
Possible duplicate of #4843?

**Comment by jennybc** [comment]
I suppose they could be related? But my current hunch is that these are not duplicates.

**Comment by juliasilge** [comment]
I just ran this with 2024.10.0 (Universal) build 13 on Mac and it works for me. @jennybc can you say more about the specific build or platform where you see this failing?

**Comment by jennybc** [comment]
I am seeing this in a *dev build* (in the run and debug sense). I was going to come back to elaborate before I fell down a rabbit hole with other stuff not working in bleeding edge release builds.

**Comment by juliasilge** [comment]
I just tried with a dev build (and downloaded ark binary, not locally built, if that matters) and I see `testthat::snapshot_review()` still working, including being able to accept changes. So weird!

**Comment by jennybc** [comment]
I now think this was an artefact of me having dev positron + a local, outdated ark build. But once I updated ark, I ran into new problems (which became #4973), so I was not able to get current with everything. I'm pretty convinced I now understand what was going on and I can run this Shiny app when I build ark locally from https://github.com/posit-dev/ark/pull/580. Closing.
