### ISSUE TITLE
Interpreter drop-down not finding all R versions

### ISSUE THREAD

**Issue by EllaKaye** [posit-dev/positron#4957]
#### Positron and OS details:

Positron Version: 2024.10.0 (Universal) build 13
Code - OSS Version: 1.93.0
Commit: 34b5c57cf211bcaf1bc48f75a8cd8d0b4378e5f5
Date: 2024-10-03T16:46:35.447Z (5 days ago)
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

#### Interpreter details:

Multiple (see below)

## Describe the issue:

I have *many* versions of R installed, including (currently) 6 versions of R 4.5.0. One of these is the official r-devel and the other five are for creating patches for different bug fixes. However, the drop-down interpreter selector only lists two of them. (Similarly, I have four versions of R 4.4, of which the interpreter drop-down only lists three).

![Image](https://github.com/user-attachments/assets/de5ca3b6-65dd-4781-a340-e37401bf10d9)

On a related-note, it would also be good if the drop-down made it more obvious which version was which (at the moment can only see this when hovering over the path). I've already discussed this briefly with @DavisVaughan. 

## Steps to reproduce the issue:

1. Check out multiple versions of R-devel (e.g. by following [these steps](https://github.com/r-devel/rcwg/blob/main/working_documents/install_r_macos.md), giving each one a different name).
2. Open the Positron interpreter drop-down - not all the versions are available.

## Expected or desired behavior:

Interpreter lists *all* installed versions of R (and makes it easier to see which is which)

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No

**Comment by EllaKaye** [comment]
Ah, just figured out what was going on here. Not all my versions were orthogonal. I just ran `rig system make-orthogonal` and now I see them all. Also, I've now learned about the `R: Select R Interpreter` command palette option, which shows the fulls paths.

**Comment by jennybc** [comment]
Yeah we've definitely identified this infelicity with how the binary path is displayed before:

https://github.com/posit-dev/positron/issues/692#issuecomment-1639539120

> A side observations is that, in this particular case, it would be better to truncate the full binary path on the left or in the middle, in the name of showing the truly interesting and disambiguating part, which is on right.

This problem sort of lives in the back of my mind, but is not a huge pressing issue, as I think the vast majority of R users don't have so many R installations that they need disambiguation, but it comes up for devs.

**Comment by EllaKaye** [comment]
Agreed, definitely not a pressing issue. Going through the command palette is a good enough to see the full paths.
