### ISSUE TITLE
Jupyter supervisor does not show content of error messages when startup fails

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#4960]
#### Positron and OS details:

```
Positron Version: 2024.11.0 (Universal) build 23
Code - OSS Version: 1.93.0
Commit: 9c57708e62a1ce5db9f26a4de3e5dc2dca168724
Date: 2024-10-09T02:45:16.388Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

#### Interpreter details:

Any broken interpreter

## Describe the issue:

When using the Jupyter supervisor, if an interpreter's process fails to start entirely (e.g. a bad path, exec format errors, no permission, etc.), the error is correctly reported and shown in Positron.

However, if the process starts successfully, but then reports errors and exits, the errors are not shown in Positron. You can only see the exit code.

![Image](https://github.com/user-attachments/assets/4960ac30-6f95-4eb1-ad7c-ed0ab4a9dee1)

These error messages are often vital to diagnose startup problems.

## Steps to reproduce the issue:

To reproduce this, you need to use a broken interpreter. One way you can simulate this is by replacing the kernel executable with a shell script that emits errors and then exits with a nonzero code, e.g. you could replace `ark` with this:

```bash
#!/bin/bash

echo "Oh no. Something awful has occurred."
exit 2
```

## Expected or desired behavior:

Any output emitted during startup should be shown to the user if startup fails.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-60
    OS Version          : OSX

### Test scenario(s) 

In /Applications/Positron.app/Contents/Resources/app/extensions/positron-r/resources/ark
created the script mentioned in ticket and put it in place of the ark executable
Turned on the supervisor
Restarted positron
Saw the message from the script on failure

Link(s) to TestRail test cases run or created:
