### ISSUE TITLE
Initial "headless" / DuckDB-based in-memory Data Explorer backend implementation as vscode extension

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#4963]
Initial spike for epic #2187 to be able to open Parquet and CSV/TSV files by clicking on the file explorer in the user's workspace.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-65
    OS Version          : OSX

### Test scenario(s) 

Verified with flights.parquet and flights.parquet saved as csv.  Also checked tsvs.

Link(s) to TestRail test cases run or created:
