### ISSUE TITLE
Force quitting reticulate python terminates Positron IDE

### ISSUE THREAD

**Issue by matthewgson** [posit-dev/positron#4982]
#### Positron and OS details:

Positron 10.0.13

#### Interpreter details:
R 4.4.1
Python 3.12

## Describe the issue:
Force quitting reticulate python terminates Positron IDE

## Steps to reproduce the issue:

1. library(reticulate)
2. repl_python()
3. exit
4. force quit

https://github.com/user-attachments/assets/3e2c1ffb-5aaf-41aa-9d48-b9640673842c

## Expected or desired behavior:

Force quit Python terminal, not entire IDE

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No.

**Comment by dfalbel** [comment]
@matthewgson Thanks for reporting! I'll work on it soon.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-140
    OS Version          : OSX

### Test scenario(s) 

Positron does not crash when repro steps followed.

Link(s) to TestRail test cases run or created:
