### ISSUE TITLE
Jupyter supervisor does not work on all Linux distributions

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#4994]
The Jupyter supervisor is a native binary component that has builds for Windows, macOS, and Linux. To support Positron on Workbench, this component needs to be built for all Linux distributions supported by Workbench. It is currently built on the latest version of Ubuntu, and is expected to work there, but may not work on other distributions.

Of particular concern is the fact that the supervisor currently links against `libcrypto`, part of OpenSSL and a system component with ABI compatibility issues that makes it very difficult to produce a single binary that works across platforms.

```
ldd kcserver
	linux-vdso.so.1 (0x00007fffff51a000)
	libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007c50f638d000)
	libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007c50f4e00000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007c50f636d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007c50f6286000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007c50f4a00000)
	/lib64/ld-linux-x86-64.so.2 (0x00007c50f6442000)
```

The R kernel has exactly the same problem (and is built using a similar toolchain). Here's how it resolved the issue: https://github.com/posit-dev/ark/pull/486

Because Workbench already has an SSL dependency, one approach we might take is producing desktop builds only for recent versions of Linux (so that we don't have multiple builds of Positron itself), but building additional flavors for Workbench that it can inject into Positron. This is less desirable than just getting rid of the dependency, though.

**Comment by jmcphers** [comment]
I investigated this on Rocky Linux 8 and Rocky Linux 9 and found Good News and Bad News. The Good News is that the supervisor works as-is on RL9, which I think is sufficient for our preview phase.

The bad news is that it appears almost impossible to produce a build from an Ubuntu machine that works with both RL8 and RL9.
- Building on Ubuntu 20 produces a build that does not work on RL8 (due to glibc issues) or RL9 (due to OpenSSL issues)
- Building on Ubuntu 22 produces a build that does not work on RL8 (due to glibc _and_ OpenSSL issues) but does on RL9

We will need to do additional work in the supervisor and/or the build environment to enable a build compatible with RL8.

QA, please verify that things are copacetic on RL9.

**Comment by jonvanausdeln** [comment]
Tested on several flavors open issues separately.
