### ISSUE TITLE
Cannot load R packages

### ISSUE THREAD

**Issue by tm-89** [posit-dev/positron#5015]
## System details:

macOS Sequoia (Version 15.0.1)

#### Positron and OS details:

Positron Version: 2024.10.0 (Universal) build 14
Code - OSS Version: 1.93.0
Commit: 901ab5d11d694212d32e53b97f771c5d601e428e
Date: 2024-10-09T15:26:55.363Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

#### Interpreter details:

R 4.4.1

## Describe the issue:

So far I mainly used R via RStudio. Trying to use it via Positron leads to issues when trying to load packages. See the corresponding output below.

## Steps to reproduce the issue:

1. Install package (via install.packages command).
2. Load package (gives the above error message).

## Expected or desired behavior:

Package to be loaded successfully. If possible I'd like to directly use the packages I installed via RStudio (which uses the same R version).

## Were there any error messages in the UI, Output panel, or Developer Tools console?

![Image](https://github.com/user-attachments/assets/786ec2f9-36e8-474e-bc62-fd803fea5745)

**Comment by jmcphers** [comment]
Judging from the screenshot, it looks like the problem is that there's some crosstalk between R 4.4 and R 4.3 on your machine. The `vctrs.so` file in the R 4.4 package library is linking to R 4.3's `libr.dylib` file, which is wrong.

Could you provide a little more info?

- How did you install R on your machine?
- Do you have multiple R versions installed?
- What does `.libPaths()` return for you in Positron and in RStudio?

**Comment by tm-89** [comment]
Thanks for the reply! One thing I forgot to mention is that I can load certain packages (e.g. terra).

- Originally I downloaded the package from [CRAN](https://cran.r-project.org/bin/macosx/), since then I updated it two times (from 4.2 to 4.3 and then 4.4).
- Yes, 4.2, 4.3 and 4.4.
- Both RStudio and Positron return `"/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library"`.

**Comment by juliasilge** [comment]
Can you say more about how/why you say you have installed R 4.2, 4.3, and 4.4 all on your machine? Do you mean all at the same time, or first you installed R 4.2, then later replaced it with R 4.3, etc? It is not typically possible or recommended to install and use multiple regular R installations from CRAN, especially on macOS. 

(If you are interested in managing multiple R versions on the same machine, we recommend [rig](https://github.com/r-lib/rig).)

**Comment by tm-89** [comment]
> Can you say more about how/why you say you have installed R 4.2, 4.3, and 4.4 all on your machine? Do you mean all at the same time, or first you installed R 4.2, then later replaced it with R 4.3, etc? It is not typically possible or recommended to install and use multiple regular R installations from CRAN, especially on macOS. 
> 
> (If you are interested in managing multiple R versions on the same machine, we recommend [rig](https://github.com/r-lib/rig).)

I just updated R and the old versions weren't deleted. I'm just using the latest one.

**Comment by jennybc** [comment]
Something feels confused/dysfunctional around your R installation. For example, did you upgrade R but then somehow keep using the previous package library? Whenever you go from one minor version to the next, such as 4.3 to 4.4, you need to reinstall all add-on packages.

To reiterate:

> What does .libPaths() return for you in Positron and in RStudio?

I'll also add: what does `sessionInfo()` show?

We are interested in seeing the exact output of these functions. E.g. for me it's:

``` r
sessionInfo()
#> R version 4.4.1 (2024-06-14)
#> Platform: aarch64-apple-darwin20
#> Running under: macOS Ventura 13.7
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib 
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> time zone: America/Vancouver
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_4.4.1    fastmap_1.2.0     cli_3.6.3         tools_4.4.1      
#>  [5] htmltools_0.5.8.1 withr_3.0.1       fs_1.6.4          glue_1.8.0       
#>  [9] yaml_2.3.10       rmarkdown_2.28    knitr_1.48        reprex_2.1.1.9000
#> [13] xfun_0.47         digest_0.6.37     lifecycle_1.0.4   rlang_1.1.4      
#> [17] evaluate_1.0.0

.libPaths()
#> [1] "/Users/jenny/Library/R/arm64/4.4/library"                            
#> [2] "/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library"
```

<sup>Created on 2024-10-16 with [reprex v2.1.1.9000](https://reprex.tidyverse.org)</sup>

**Comment by tm-89** [comment]
@jennybc, if I remember correctly the installed packages were moved to the new R installation and I kept using the old installations (and at least in RStudio I haven't come across any issues in the last months).

Output for RStudio:
```
> .libPaths()
[1] "/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library"
> sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: aarch64-apple-darwin20
Running under: macOS 15.0.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Vienna
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.4.1 rgdal_1.6-7    tools_4.4.1    sp_2.1-4       grid_4.4.1     pacman_0.5.1   lattice_0.22-6
```

Output for Positron:
```
> .libPaths()
[1] "/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library"
> sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: aarch64-apple-darwin20
Running under: macOS 15.0.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Vienna
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.4.1 tools_4.4.1   
```

**Comment by DavisVaughan** [comment]
> the installed packages were moved to the new R installation and I kept using the old installations

I recognize that _sometimes_ this works in RStudio, but this is 100% unsafe to do when upgrading minor versions in R, i.e. 4.3 to 4.4 (this is the official stance of R, not us). Our recommendation for you is to remove all packages installed this way and reinstall them

**Comment by tm-89** [comment]
> > the installed packages were moved to the new R installation and I kept using the old installations
> 
> I recognize that _sometimes_ this works in RStudio, but this is 100% unsafe to do when upgrading minor versions in R, i.e. 4.3 to 4.4 (this is the official stance of R, not us). Our recommendation for you is to remove all packages installed this way and reinstall them

Thanks! Then I will do that and see whether it works then (which it should). I assume it should not make a difference whether I install the packages via RStudio or Positron?

**Comment by DavisVaughan** [comment]
That's correct, as long as you do the installation from R 4.4!

**Comment by juliasilge** [comment]
Let us know if you have followup questions on this @tm-89!

**Comment by tm-89** [comment]
> Let us know if you have followup questions on this [@tm-89](https://github.com/tm-89)!

Thanks, will do! I haven't had the chance yet to reinstall everything, but I'll report back once I got to it.
