### ISSUE TITLE
Using radian as an alternative to R console

### ISSUE THREAD

**Issue by amael-ls** [posit-dev/positron#5021]
Many thanks for developing an IDE inspired by vscode, but more dedicated to R and Python! I would like to use radian instead of the R console, but so far it seems impossible as there is no `r.rterm` option in Positron. Would it be possible to implement it?

Two ways could work:
1. either we could choose which console to start, or
2. we start radian in the terminal and cmd/ctrl + enter send to active terminal rather than console

#### Positron and OS details:

Positron Version: 2024.10.0 build 14
Code - OSS Version: 1.93.0
Commit: 901ab5d11d694212d32e53b97f771c5d601e428e
Date: 2024-10-09T15:20:07.922Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-45-generic

#### Interpreter details:

R 4.4.1

**Comment by ntluong95** [comment]
Radian might be a very bad option that's why Positron might get away from it and develop a new, native R console I think.

**Comment by jmcphers** [comment]
Syntax highlighting for previously executed code is tracked as a feature request here (please comment/upvote!): https://github.com/posit-dev/positron/issues/243

Can you share an example of the output highlighting you're looking for?

**Comment by jmcphers** [comment]
Currently no plans to support Radian in Positron, but please feel free to open issues for any feature gaps you see between Radian and Positron's console.
