### ISSUE TITLE
Reticulate: typing `exit` at the python console freezes the session

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#5022]
Steps to reproduce:

1. Start a reticulate Python session
2. Type `exit` in the Python console

Observe that the session is freezed.

The reason for this is the same for why we need:

https://github.com/posit-dev/positron/blob/4a849834de7c81aa0e14f511267664cf343c394b/extensions/positron-reticulate/src/extension.ts#L524-L537

Exiting the Python kernel, doesn't cause the process to exit, and thus doesn't clean up socket connections.

A possible solution is making sure the Positron IPykernel clean it's threads when the kernel exits. However this might still not fully fix the problem when the kernel crashes for some reason.

**Comment by dfalbel** [comment]
This is actually very similar to https://github.com/posit-dev/positron/issues/4982

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-140
    OS Version          : OSX

### Test scenario(s) 

Session no longer freezes when exit typed in python reticulate console.

Link(s) to TestRail test cases run or created:
