### ISSUE TITLE
App Frameworks on Workbench: Streamlit websocket issue when SSL enabled

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#5026]
#### Positron and OS details:

Latest on main.

#### Interpreter details:

Any supported Python. I've used 3.12 and 3.10.

## Describe the issue:
Streamlit apps work in Positron on Workbench when running in a localhost environment or when SSL is not enabled. However, when SSL _is_ enabled, there's an issue with establishing the secure websocket connection.

## Steps to reproduce the issue:

1. Run [this app](https://github.com/posit-dev/qa-example-content/tree/main/workspaces/streamlit-py-example) in Positron on Workbench with SSL enabled 
2. App opens in Viewer, but appears to be loading indefinitely
    ![Image](https://github.com/user-attachments/assets/63d53144-b1f1-4a33-852d-c53a17fd7918)

4. Many Console errors

## Expected or desired behavior:
Streamlit apps should work in Positron on Workbench when SSL is enabled.

### Developer Tools console

```
[Extension Host] [HPM] Proxy created: /  -> http://localhost:8501/ workbench.web.main.js:62288

DEBUG Webview(9f0ed350-aec3-4f0c-8d6c-a7be67c2324e): will update content workbench.web.main.js:130524

...

[Extension Host] [HPM] Upgrading to WebSocket workbench.web.main.js:62288

WebSocket connection to 'wss://sslenabledurl.com/s/session/p/port/_stcore/stream' failed:
    connectToWebSocket @ main.33ba0d1c.js:19

WebsocketConnection WebSocket onerror
    a                 @ main.33ba0d1c.js:10
    websocket.onerror @ main.33ba0d1c.js:19

```

## Related issues

https://github.com/posit-dev/positron/issues/4769

**Comment by jmcphers** [comment]
Workbench requires SSL to be turned on to use Positron or VS Code sessions, so we need to address this to support Positron in Workbench. Please mark for re-triage if the fix/investigation appear too costly.

**Comment by sharon-wang** [comment]
This was verified with `Positron 2024.11.0-140` and SSL-enabled `Positron Workbench 2024.11.0-daily+338.pro14` on Ubuntu 24 by running these example apps:
- https://github.com/posit-dev/qa-example-content/tree/main/workspaces/streamlit-py-example
- https://github.com/posit-dev/qa-example-content/tree/main/workspaces/python_apps/streamlit_example

Both apps successfully loaded in the Viewer.
