### ISSUE TITLE
App Frameworks on Workbench: Fastapi root path issues

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#5027]
#### Positron and OS details:

Latest on main.

#### Interpreter details:

Any supported Python. I've used 3.12 and 3.10.

## Describe the issue:
Fastapi apps can't be loaded in the Viewer in Positron on Workbench. Either a `404 Not Found` or `504 Gateway Timeout` error shows in the browser Network tab and Console output after we click the Run App button.

The issue may be a problem with the positron proxy, another proxy, the way we run fastapi apps, and/or a conflict with Workbench's custom handling for Fastapi apps.

The current hunch is that Workbench setting `UVICORN_ROOT_PATH` at session start is interfering with how we run the fastapi app with uvicorn. The `UVICORN_ROOT_PATH` is set based on the default fastapi port 8000, however I think we want the proxied app url as the root path, which is provided by the Positron Proxy. But, when setting `--root-path` in the fastapi app command to the proxied root path, it does not work in Server Web or Desktop. TBD if this resolves the issue on Workbench. More investigation needed.

## Steps to reproduce the issue:

1. Run [this app](https://github.com/posit-dev/qa-example-content/tree/main/workspaces/python_apps/fastapi_example) in Positron on Workbench
    - alternative app example
    ```
    import uvicorn
    from fastapi import FastAPI
    
    app = FastAPI()
    
    @app.get("/")
    async def root():
        return {"message": "Hello World"}
    
    # at last, the bottom of the file/module
    if __name__ == "__main__":
        uvicorn.run(app, host="127.0.0.1") 
    ```
2. Viewer shows that an error occurred while trying to proxy the request
3. Console errors

## Expected or desired behavior:
Fastapi apps should work in Positron on Workbench.

### Developer Tools console

```
[Extension Host] [HPM] Proxy created: /  -> http://localhost:8000/docs workbench.web.main.js:62288

...

ERR [Extension Host] [HPM] Error occurred while proxying request workbench_url.com/?_positronRender%3D1 to http://127.0.0.1:8000/docs [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors) workbench.web.main.js:62288

Failed to load resource: the server responded with a status of 504 (Gateway Timeout)

```

## Related things

- https://github.com/posit-dev/positron/issues/4769

- how we run fastapi apps
    https://github.com/posit-dev/positron/blob/10183fa8d9a8495b5d52cafd252cfa5a44b05599/extensions/positron-python/src/client/positron/webAppCommands.ts#L163-L183

**Comment by jmcphers** [comment]
@melissa-barca Will this work with the VS Code approach to app proxying?

**Comment by sharon-wang** [comment]
I found a way to get this working (https://github.com/posit-dev/positron/pull/5138) without dealing with `UVICORN_ROOT_PATH` or needing custom logic on the Workbench side, but it involves the Run App extension checking that Positron is running in Workbench and applying slightly different logic. Hopefully that's reasonable!

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.11.0-140](https://github.com/posit-dev/positron-builds/releases/tag/2024.11.0-140)
OS Version(s) : Ubuntu 24, with Workbench [2024.11.0-daily+338.pro1](https://dailies.rstudio.com/version/2024.11.0-daily+338.pro1)

### Test scenario(s) 
Tested all the support python apps.



### Link(s) to TestRail test cases run or created:
