### ISSUE TITLE
R: Comment lines with only hashtags (#)  break down the outline pane

### ISSUE THREAD

**Issue by kv9898** [posit-dev/positron#5036]
## System details:

Windows 11

#### Positron and OS details:

Positron Version: 2024.10.0 (system setup) build 14
Code - OSS Version: 1.93.0
Commit: 901ab5d11d694212d32e53b97f771c5d601e428e
Date: 2024-10-09T15:24:43.348Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

ark: 0.1.144
#### Interpreter details:

R 4.4.1

## Describe the issue:

If there is a line in R with only hashtags (#), the outline pane will not display anything. (A bug that I wrote myself)

## Steps to reproduce the issue:

1. Start an R document (ark version must be 0.1.144)
2. Type `# comment section ####`
3. The outline pane shows the desired output
![Image](https://github.com/user-attachments/assets/e976d575-7e1f-4f4a-98ca-b246ea88643e)
4. Add an additional line of `##############`
5. Now the output pane does not detect any symbols
![Image](https://github.com/user-attachments/assets/6e49e85a-47cb-4eed-953e-7a5f41bd8885)

## Expected or desired behavior:

lines with hashtags only should not break the output pane.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No

**Comment by kv9898** [comment]
Merging my pull request should fix it!

**Comment by kv9898** [comment]
Shall I close this issue since it has been fixed?

**Comment by midleman** [comment]
#### Verified Fixed
Positron Version(s) : 2024.11.0 - 116
OS Version(s) : MacOS

### Test scenario(s) 
Confirmed RMD properly generates outline even with presence of `##############` in file.

### Link(s) to TestRail test cases run or created: 
n/a
