### ISSUE TITLE
Positron unable to find R interpreter

### ISSUE THREAD

**Issue by saptarishipandey** [posit-dev/positron#5038]
#### Positron and OS details:

Positron 2024.08.0 build 31
OSS version 1.91.0

#### Interpreter details:

 

R 4.1.3

## Describe the issue:

![Image](https://github.com/user-attachments/assets/f9ee1842-52a3-447d-a668-179289d72f8e)

Positron does not detect R interpreter, it only detects Python interpreter. Already added my R installation to path as per another thread (Issue #4280), and it is still not working.  I installed the latest and earlier versions of Positron and faced the same issue. RStudio seems to work fine and I have a version of R installed correctly.

![Image](https://github.com/user-attachments/assets/458fd388-01dc-45e5-a606-fb17b2ddebcc)

## Steps to reproduce the issue:

1. Open .R file.
2. Run code

## Expected or desired behavior:

Code should run

## Were there any error messages in the UI, Output panel, or Developer Tools console?

"Cannot execute code. Unable to start a runtime for the R language"

**Comment by jmcphers** [comment]
Positron currently requires R 4.2 as documented in our [R prerequisites](https://github.com/posit-dev/positron/wiki#r-prerequisites); that's why it isn't using the R 4.1 version on your system.

Also recommend updating to the newest version; we've made a lot of improvements in the last couple of months!

**Comment by saptarishipandey** [comment]
@jmcphers this worked! Thank you! 
![Image](https://github.com/user-attachments/assets/88f08b9a-8633-495a-b1ab-1ee5e7816a9a)
