### ISSUE TITLE
Positron Web: Cannot create new folder

### ISSUE THREAD

**Issue by timtmok** [posit-dev/positron#5045]
#### Positron and OS details:
Positron Web - 2024.10.0

#### Interpreter details:
n/a

## Describe the issue:
Attempt to create a new folder and an error is shown that no file system handle is registered.

![Image](https://github.com/user-attachments/assets/db090448-3682-42e0-94f0-dfda1a5e7b7d)

## Steps to reproduce the issue:

1. Command palette (Cmd+Shift+P) > Workspaces: New Folder (not File: New Folder)
2. Try to create a folder from the dialog

## Expected or desired behavior:
The browse button should be a remote file system browser, not the local file system. A folder should be created on the server.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-90
    OS Version          : OSX

### Test scenario(s) 

Was able to create new desktop folder from command palette operation.

Link(s) to TestRail test cases run or created:
