### ISSUE TITLE
Positron Web: Cannot create new folder from git

### ISSUE THREAD

**Issue by timtmok** [posit-dev/positron#5048]
#### Positron and OS details:
Positron Web - 2024.10.0

#### Interpreter details:
n/a

## Describe the issue:
Attempt to create a new folder from git and an error is shown that the file system is read only. Using the default location allows the clone but only if it can do so on the local file system.

![Image](https://github.com/user-attachments/assets/22b71356-91f1-4dd3-8279-1005eb36361c)

![Image](https://github.com/user-attachments/assets/aa9d10e9-13c9-4050-962b-a70291494d2a)

## Steps to reproduce the issue:

1. Command palette (Cmd+Shift+P) > Workspaces: New Folder from Git (not File: New Folder)
2. Browse for a location to clone the git repo into
3. Click OK to clone the repo

## Expected or desired behavior:
The browse button should be a remote file system browser, not the local file system. The repo should be cloned on the server.

**Comment by timtmok** [comment]
The git extension has code that only works with local file systems. It looks like it wasn't meant to be used with the web so it'll need some fixing.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : Main on 10.23.24 at 2 PM MST
    OS Version          : OSX

### Test scenario(s) 

Made new folder with qa-example-content on my desktop

Link(s) to TestRail test cases run or created:
