### ISSUE TITLE
Shutting down the Reticulate Python kernel should restore the original sys.stdout and sys.stderr

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#5057]
Steps to reproduce:

1. Start the reticulate Python kernel
2. Shutdown the reticulate Python kernel
3. Execute `reticulate::py_eval("print('Hello world')")`

The output should be visible in the R console.

This happens because when starting an IPykernel, `sys.stdout` is redirected to a different location.
We need to restore `sys.stdout` to the R stdout once the kernel exits.

## QA

A fix was pushed to the reticulate package, so in order to verify that you'll need to install the dev version of reticulate.
You can do so with:

```
remotes::install_github("rstudio/reticulate")
```

**Comment by testlabauto** [comment]
Wait on https://github.com/posit-dev/positron/pull/5056 for validation.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-140
    OS Version          : OSX

### Test scenario(s) 

Post shutdown of reticulate Python kernel, running:
reticulate::py_eval("print('Hello world')")
shows output in R console.

Link(s) to TestRail test cases run or created:
