### ISSUE TITLE
Positron notebooks should truncate extra-long cell output

### ISSUE THREAD

**Issue by nstrayer** [posit-dev/positron#5058]
Right now when you have a cell output that contains a _lot_ of text (or other media technically), the output never gets truncated and can make it maddening to navigate the notebook. Take for instance running this code that generates some long text:
```python
n = 400  # Change this value to control the number of lines
output = "\n".join(f"Line {i+1}" for i in range(n))
print(output)
```
![Image](https://github.com/user-attachments/assets/4070cb52-df44-447d-a054-61fd5f1a96a6)

You now have to scroll through 400 lines of text to see a plot beneath. 

The vscode notebooks deal with this by truncating the output. 
![Image](https://github.com/user-attachments/assets/86ff020c-0079-4137-8541-bab3d84c0de9)

How much is done for truncating is done by this setting which we can probably reuse:
![Image](https://github.com/user-attachments/assets/dbc949cd-78f0-43b8-bf5f-65c70e1d1e15)

**Comment by testlabauto** [comment]
Moving directly to backlog as Nick has self assigned already.

**Comment by midleman** [comment]
### Verified Fixed
Positron Version(s) : Positron Version: 2024.12.0-96
OS Version(s) : MacOS

### Test scenario(s) 

Confirmed that truncation works as expected. Just note, this is not configurable although it is slightly implied in the settings hyperlink.

### Link(s) to TestRail test cases run or created: 

n/a
