### ISSUE TITLE
`Int64` (Uppercase 'I') in Python Not Handled by Data Explorer, While `int64` (Lowercase 'i') Is

### ISSUE THREAD

**Issue by msberends** [posit-dev/positron#5066]
#### Positron and OS details:

Positron Version: 2024.10.0 (Universal) build 14
Code - OSS Version: 1.93.0
Commit: 901ab5d11d694212d32e53b97f771c5d601e428e
Date: 2024-10-09T15:26:55.363Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

#### Interpreter details:

Python 3.9.6

## Describe the issue:

`Int64` (uppercase I) is not handled by the data explorer, while `int64` (lowercase i) is.

## Steps to reproduce the issue:

```python
df.dtypes
# USMER                    Int64
# MEDICAL_UNIT             int64
# SEX                      Int64
# PATIENT_TYPE             Int64
# DATE_DIED               object
# INTUBED                  Int64
# PNEUMONIA                Int64
```

No histograms for the `Int64` columns, but instead question marks:

![Image](https://github.com/user-attachments/assets/cb0640db-a865-4055-8f96-23b759504f35)

Filter options for numeric `int64` column:

![Image](https://github.com/user-attachments/assets/3055ba57-0184-4e0f-98d0-feb4521a7047)

But not for numeric `Int64` column:

![Image](https://github.com/user-attachments/assets/01b5884d-4884-4fbe-90c7-f30c09957c31)

## Expected or desired behavior:

One could argue that `Int64` was wrongly coded, but the problem is that Python does support this (as opposed to R). So I believe the Positron data explorer should support this uppercase 'I' for numeric columns as well.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No, UI problem.

**Comment by testlabauto** [comment]
Hi!  Thank you for your bug report.  I am able to repro with:

```
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'col1': np.random.randint(1, 10, 5),
    'col2': np.random.randint(10, 20, 5)
}, dtype='Int64')

print(df)
```

I am moving this issue to triage for prioritization.

**Comment by jmcphers** [comment]
Triage: we think this will be relatively straightforward to address, please kick back if it turns out to be otherwise.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-103
    OS Version          : OSX

### Test scenario(s) 

```
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'col1': np.random.randint(1, 10, 5),
    'col2': np.random.randint(10, 20, 5)
}, dtype='Int64')

print(df)
```

Link(s) to TestRail test cases run or created:

**Comment by msberends** [comment]
You guys are absolutely awesome 🤩🤩

Just took an AI Bootcamp where I briefly took the liberty to show(case) Positron in front of the group, it’s easy for many to fall in love instantly!
