### ISSUE TITLE
plot window hides elements in a matplotlib chart

### ISSUE THREAD

**Issue by JosephBARBIERDARNAL** [posit-dev/positron#5068]
#### Positron and OS details:

Positron Version: 2024.08.0 (Universal) build 48
Code - OSS Version: 1.91.0
Commit: ed616b36655fb24d116108bdd833f1321704315b
Date: 2024-08-19T04:26:51.868Z
Electron: 29.4.0
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.6.0

#### Interpreter details:

Python 3.12.5

## Describe the issue:

For example, when I add an annotation to a matplotlib graph, if its position is outside certain values, it will not be displayed in the plot window.

The values in question appear to be outside 0 and 1 in the coordinates of the figure for the x and y axis.

## Steps to reproduce the issue:

```bash
pip install matplotlib==3.9.2
```

```python
import matplotlib.pyplot as plt

# not visible
fig, ax = plt.subplots()
fig.text(
    x=0.5, y=1, s='title'
)
plt.show()


# visible
fig, ax = plt.subplots()
fig.text(
    x=0.5, y=0.9, s='title'
)
plt.show()
```

![Image](https://github.com/user-attachments/assets/a02525e3-cf90-4831-9a89-825f3852bca9)

## Expected or desired behavior:

Ideally, the plot window should zoom out (or similar) to ensure that it fits all the elements of the matplotlib figure.

**Comment by testlabauto** [comment]
Hi!  Thanks for using Positron.

I am not 100% sure if this is an issue with Positron or perhaps just an issue with usage.  Could you try this and see if it meets your needs?

```
import matplotlib.pyplot as plt

fig = plt.figure()
ax1 = fig.add_subplot()

ax1.title.set_text('Title')

plt.show()
```

I ask because when i try to repro your original snippet outside Positron, I get the same result and with the snippet I provided, the title looks good.

A larger example: https://stackoverflow.com/questions/25239933/how-to-add-a-title-to-each-subplot

**Comment by JosephBARBIERDARNAL** [comment]
It's strange that this works when adding a title, but not when using `text()`.

To be clearer about what I meant in the first place, ideally I should see on the plot window what I would see in a normal notebook or if I saved the plot as a png.

For example, this:

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
fig.text(
    x=0.5, y=1, s='title', size=20
)
plt.tight_layout()
plt.savefig('positron.png', bbox_inches='tight')
plt.show()
```

gives me 2 differents results. `positron.png` (or what I would have had in a notebook) looks like:

![Image](https://github.com/user-attachments/assets/b72894aa-2784-4f1e-89e4-25f3604a47f7)

But in positron the plot window gives me:

![Image](https://github.com/user-attachments/assets/d002457b-0843-4f62-94c6-0635ef467258)

**Comment by JosephBARBIERDARNAL** [comment]
Interestingly, this works perfectly:

```python
import matplotlib.pyplot as plt

fig = plt.figure()
ax1 = fig.add_subplot()

ax1.set_title('title', y=1.3) # higher position

plt.show()
```

![Image](https://github.com/user-attachments/assets/05aea335-e244-41a4-99df-9f390b134ce6)

**Comment by testlabauto** [comment]
Thank you for the additional example!  I do see what you mean when comparing to a notebook (with the savefig line commented out).

I will move this issue to triage for prioritization.

**Comment by jmcphers** [comment]
Triage: @JosephBARBIERDARNAL does this repro with the latest release of Positron for you? https://github.com/posit-dev/positron/releases

**Comment by JosephBARBIERDARNAL** [comment]
> Triage: [@JosephBARBIERDARNAL](https://github.com/JosephBARBIERDARNAL) does this repro with the latest release of Positron for you? https://github.com/posit-dev/positron/releases

I installed it a few days before opening my issue, so yes!

**Comment by seeM** [comment]
This issue is a result of our chosen defaults to try to work around limitations in matplotlib's layout system. I posted more in-depth about the limitations and our decisions in [the Layout section of this comment](https://github.com/posit-dev/positron/issues/4040#issuecomment-2271586405) but let me try to summarise what's relevant here.

In short, in matplotlib we can only choose **one** of the following default behaviors:

1. Produce an image of the exact requested pixel size.
2. Produce an image that contains all of the figure elements.

We originally opted for 1, but I'm wondering if we should use 2 _when the intrinsic sizing policy is used_ (i.e. "Matplotlib (6in x 4in)" is selected). It would mean that our plots exactly match Jupyter Notebooks in that case. @petetronic curious to hear your thoughts.

**Comment by JosephBARBIERDARNAL** [comment]
I’m not sure if this will help, but here are a few things that matter (or don’t) to me as a heavy user of Matplotlib who really likes Positron, and ideally plans to continue using it in the future:

- The issue mentioned here happens almost every time I use Matplotlib: text placement rarely looks well-positioned in the plot window. As a result, I rarely pay attention to it and usually just close it. My current workaround is saving the plot as a PNG and reviewing the changes from there. It works, but it may not be the best experience.

- Personally, I almost always use the “intrinsic/matplotlib” size setting, since I typically set the width-to-height ratio for my plots. To clarify, I consistently use this setting:
![Image](https://github.com/user-attachments/assets/597964c2-11f6-47c8-8324-c942d13d7399)

- While my experience might not be typical, I suspect many heavy Matplotlib users are in a similar situation. Matplotlib’s layout management feels a bit unintuitive, and it’s easier (at least for me) to manually control everything.

**Comment by seeM** [comment]
@JosephBARBIERDARNAL thank you very much for sharing, this is very helpful!

I think the correct move is to update our matplotlib backend to produce images that match those produced via the Jupyter Notebook matplotlib backend when the intrinsic size is used, using whichever layout engine / `bbox_inches` setting is required for that.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-88
    OS Version          : OSX

### Test scenario(s) 

No longer seeing any truncation

Link(s) to TestRail test cases run or created:
