### ISSUE TITLE
Misleading outline symbol for R variables

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#5071]
(from https://github.com/posit-dev/positron/discussions/5065)

Currently, the outline symbol for variables looks like this:
code:
a <- 1

outline:
![Image](https://github.com/user-attachments/assets/2f82588a-adf6-47ea-9988-2a1d6d7f0b66)

This kind of hints at a "function" to me.

I wonder a VARIABLE symbol rather than the current OUTLINE symbol would be more appropriate. An example of VARIABLE symbols would be:
![Image](https://github.com/user-attachments/assets/7120736f-c177-4f71-9972-8e4c12db45a0)

Note that the suggested symbol is consistent with what we show for Python and with what VSCode shows for Typescript.

**Comment by lionel-** [comment]
> This kind of hints at a "function" to me.

I think it's supposed hint at a Javascript object, i.e. an hashtable/struct type with fields and methods that is represented with `{` in the JS syntax. The closest thing in R would be an R6 object or an environment. Rust-analyzer uses OBJECT to represent `impl`s.

I agree in that VARIABLE is a better representation in general.

**Comment by kv9898** [comment]
I believe this problem has been fixed after ark was bumped to 0.1.146.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-90
    OS Version          : OSX

### Test scenario(s) 

Looks good now:
![Image](https://github.com/user-attachments/assets/10597f1f-ea5e-46c5-bc8e-b73ca70cbc46)


Link(s) to TestRail test cases run or created:
