### ISSUE TITLE
Command/Control-P plus filename should also open parquet, csv, & tsv files on macOS

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#5076]
#### Positron and OS details:

Positron Version: 2024.11.0 (Universal) build 65

#### Interpreter details:

N/A

## Describe the issue:

Double clicking a parquet, csv, or tsv in the file tree will now automatically open it into data explorer.  This same functionality should be available with Command/CTRL-P {filename}

## Steps to reproduce the issue:

1. Open a parquet file from the file tree.  Note that it opens in data explorer
2. Attempt to open the same file with (Command/CTRL)-P {filename}.  Note that you receive:

![Image](https://github.com/user-attachments/assets/f9673e36-d678-4564-bc63-a181d34a7ced)

## Expected or desired behavior:
File opens in data explorer.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

None other than whats included in above screenshot

**Comment by wesm** [comment]
I tried this out locally on the main branch today (Fedora Linux) and it worked for me:

https://github.com/user-attachments/assets/14b20932-243a-45e5-87ee-751490ce165f

We'll have to investigate more if there are scenarios where this doesn't work properly (it seems odd to me that opening a file from the explorer would hit a different code path from the command palette, but you never know!)

**Comment by testlabauto** [comment]
Yes, I same the same thing on Ubuntu.  The binary file warning is only coming up for me on OSX.  @jonvanausdeln, can you try Windows?

**Comment by testlabauto** [comment]
Also, please note that a release build on OSX is necessary to reproduce.

**Comment by wesm** [comment]
Thanks, we can investigate on both fronts

**Comment by jonvanausdeln** [comment]
I don't see that error message on windows when opening with ctrl+p, but @testlabauto is correct the data explorer is completely empty on windows for these files. See https://github.com/posit-dev/positron/issues/5084

**Comment by wesm** [comment]
After the Windows fix, this is a macOS-only issue, so I marked it as such so we can fix

**Comment by wesm** [comment]
I created a release build based on https://github.com/posit-dev/positron/commit/63d7826e029cfe8514466981150c9e9a9d70f118 on macOS and the command palette opening seems to work, maybe it was a transient issue or something that got fixed in https://github.com/posit-dev/positron/commit/0b88fa213f240b3b433ed314a2c3dc0a429527c6?

https://github.com/user-attachments/assets/dc86d05a-b4d4-456f-aef4-931c9b2b58de

**Comment by testlabauto** [comment]
It does work smoothly on Linux.  Was your recording from a Mac?

On Mac, with [2024.11.0-90](https://github.com/posit-dev/positron-builds/releases/tag/2024.11.0-90), I am still seeing:

![Image](https://github.com/user-attachments/assets/d45c668a-7167-42cc-8a50-5e50b5f59369)

Since there is an "open anyway" link, I think we can live with this, but just wanted to be sure that is what we want.

**Comment by wesm** [comment]
I asked ChatGPT what it thought about this, and it suggested that we might change usages of `resource.path` to `resource.fsPath` in this code:

https://github.com/posit-dev/positron/blob/main/src/vs/workbench/contrib/positronDataExplorerEditor/browser/positronDataExplorerEditor.contribution.ts#L92-L101

I'm not able to reproduce the issue myself so if you can replicate the problem locally in a dev or release build, maybe you can try out this possible solution

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-90
    OS Version          : OSX

### Test scenario(s) 

Verified on @midleman's machine.  My machine shows the warning but the "open anyway" message is sufficient for me.

Link(s) to TestRail test cases run or created:

**Comment by wesm** [comment]
If this issue recurs on other machines, we should investigate further to figure out what is causing it
