### ISSUE TITLE
Positron web - new project wizard git init fails

### ISSUE THREAD

**Issue by jonvanausdeln** [posit-dev/positron#5089]
#### Positron and OS details:

Ubuntu 22
current `main` branch - the reh-web build

## Describe the issue:

Creating a new project and select to "Initialize with Git repository" fails to create the local git repository

## Steps to reproduce the issue:

1. Start new project wizard
2. Select Python or R
3. Check "Initialize with Git repository"
4. Complete wizard steps

![Image](https://github.com/user-attachments/assets/301ccf73-9858-4fe9-832c-8a7bea093146)

## Expected or desired behavior:

Git repository created successfully.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

```
2024-10-21 16:58:44.559 [warning] [vscode.git] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'git.defaultBranchName', provide the URI of a resource or 'null' for any resource.
```

**Comment by sharon-wang** [comment]
This is a similar issue to all the recent errors around creating files on Positron Web https://github.com/posit-dev/positron/issues/4893.

This line is where we construct the `projectRoot` from a file system path, which we won't be able to access on Web.

https://github.com/posit-dev/positron/blob/0931e85d4022df38ced0939352745ad34b975bd6/src/vs/workbench/services/positronNewProject/common/positronNewProjectService.ts#L330

CC @timtmok for awareness: this looks like another Web file path situation
