### ISSUE TITLE
include `"reindent"` in rstudioapi shims

### ISSUE THREAD

**Issue by simonpcouch** [posit-dev/positron#5093]
`rstudioapi::executeCommand("reindent")` currently makes no changes to the current selection and returns `NULL`.

## Steps to reproduce the issue:

1. Select some text that needs reindentation (either manually or with `rstudioapi::setSelectionRanges()`)
2. Execute `rstudioapi::executeCommand("reindent")` and observe no change
3. Execute `.ps.ui.executeCommand("editor.action.reindentselectedlines")` and observe a change

I _believe_ dropping a mapping for `"reindent" = "editor.action.reindentselectedlines"`  in this code:

https://github.com/posit-dev/ark/blob/33100a0044b9377384aa96ff1860ddc87dfd7ce5/crates/ark/src/modules/rstudio/commands.R#L2-L10

..should do the trick, as it worked as intended [here](https://github.com/simonpcouch/pal/commit/a857317b154aeb501afab430abd100bda33813dc), though I'll refrain from attemping to rebuild Ark and Positron myself to test.🤪

#### Positron and OS details:

Positron Version: 2024.11.0 (Universal) build 49
Code - OSS Version: 1.93.0
Commit: 10183fa8d9a8495b5d52cafd252cfa5a44b05599
Date: 2024-10-15T02:46:25.482Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

#### Interpreter details:

R 4.4.1

**Comment by simonpcouch** [comment]
Confirming that this does the trick for me! I’m able to interface with `editor.action.reindentselectedlines` via `rstudioapi::executeCommand("reindent")` without issue, no additional `.Rprofile` setup as in https://github.com/posit-dev/positron/issues/5094 required.

One thing that’s convenient for me but I don’t have an explanation for: when I select some code and then, via the command palette, reindent selected lines, I see the strange formatting yall have discussed in related issues. When pal does it [via package code](https://github.com/simonpcouch/pal/blob/cc7f0078f4501767750cb6554ad57ad8c62d6023/R/rstudioapi.R#L107-L109), it seems to be more functional?

https://github.com/user-attachments/assets/f496dcdb-bb0d-4389-9119-32e476dc58cd

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-111
    OS Version          : OSX

### Test scenario(s) 

Marking as verified based on Simon's comment!

Link(s) to TestRail test cases run or created:
