### ISSUE TITLE
Connections Pane: List connections screen

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#5107]
The connnections pane will have two stages. The first showing the list of active connections and previous connections.

![Image](https://github.com/user-attachments/assets/3d37f233-f3d7-4f3f-8edc-fdb1384300df)

The other displaying information from the selected connection:

![Image](https://github.com/user-attachments/assets/6101cb74-bce9-4f99-89a4-f67cb0d585a8)

Demo usage:

https://github.com/user-attachments/assets/f9a866f1-58e1-4514-9b28-967a9f982df6

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-12
    OS Version          : OSX

### Test scenario(s) 

Verified with R and Python using SQLLite db.

Link(s) to TestRail test cases run or created:
