### ISSUE TITLE
Connections Pane: Secret storage

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#5108]
Connection data is currently stored in default storage location, but we should move to the encrypted storage as it's possible that the connection data includes passwords, or other information that should be protected.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-80
    OS Version          : OSX

### Test scenario(s) 

New connections pane working normally, including reconnect.

Link(s) to TestRail test cases run or created:
