### ISSUE TITLE
Support `rstudioapi::documentPath()`

### ISSUE THREAD

**Issue by olivroy** [posit-dev/positron#5112]
It could just be `rstudioapi::getActiveDocumentContext()$path`? No need to support `id` for now? (`id` support tracked in #2571)

**Comment by juliasilge** [comment]
Incorporated in https://github.com/posit-dev/positron/pull/5665

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-50
    OS Version          : OSX

### Test scenario(s) 

rstudioapi::documentPath()
now works

Link(s) to TestRail test cases run or created:
