### ISSUE TITLE
Implement data explorer FormatOptions for get_data_values RPC in duckdb backend

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#5125]
We will implement consistent data formatting as with the R and Python kernel backends

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-103
    OS Version          : OSX

### Test scenario(s) 

Compared layouts and precision between parquet file opened with code and one opened with click.

Link(s) to TestRail test cases run or created:
