### ISSUE TITLE
Implement summary statistics and sparklines for duckdb data explorer backend

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#5128]
Provide feature parity for duckdb data explorer backend

**Comment by testlabauto** [comment]
@dfalbel believes that the difference between the tailnum representations show here:
![Image](https://github.com/user-attachments/assets/58fbb596-a900-444d-8a98-64b146c37a81)
(left is code open, right is duckdb)
is wrong on the duckdb side:
"duckdb is failing to report the 'others count'"

**Comment by jonvanausdeln** [comment]
I also noticed that it can now get into a bad state..

1. Open [flights.parquet](https://github.com/posit-dev/qa-example-content/blob/1ab86ca840be228283289089f0b03486e7b8f0f3/data-files/flights/flights.parquet)
2. Observe it opens fine & close it
3. Open [100x100.parquet](https://github.com/posit-dev/qa-example-content/blob/1ab86ca840be228283289089f0b03486e7b8f0f3/data-files/100x100/100x100.parquet)
4. Note that it just gives a blank data explorer tab
5. Go back and try to open [flights.parquet](https://github.com/posit-dev/qa-example-content/blob/1ab86ca840be228283289089f0b03486e7b8f0f3/data-files/flights/flights.parquet) again (or any other file that previously it could show)

<img src="https://github.com/user-attachments/assets/d05b731c-3bf5-4a46-b28f-da79215fd439" width=50%>

The only way to get out of this is to reload the positron window or restart positron.

@wesm , if you think this is a separate, unrelated issue, just let me know and I will open up a separate issue.

**Comment by wesm** [comment]
Thanks —- looks like the QA dataset has some edge cases that will need some special treatment. I will work on this today. 

On the frequency table: I did not initially compute the “other” count since it isn’t required by the protocol, but I will add it. 

I’ll put this issue back in In Progress and revert back when it’s ready to verify again.

**Comment by wesm** [comment]
I merged the fixes -- moved this back into verification

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-77
    OS Version          : OSX

### Test scenario(s) 

For flights, solid match to example opened with code.
100x100 opens without error.

Link(s) to TestRail test cases run or created:
