### ISSUE TITLE
Display appropriate error message when file cannot be opened in duckdb-based data explorer

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#5133]
Unlike in-memory data frames in Python or R, it may not be possible to open a corrupted .parquet or .csv file (or other supported file type) in DuckDB. In these cases, we can open a data explorer but display the error message generated by DuckDB, with a prompt to close the window like when the data explorer becomes disconnected for various reasons. 

Presently it is not straightforward to route the error information into the "disconnected state" overlay for the data explorer, so will need some help determining the right approach.

If we don't address this, then when the user tries to open a corrupt file, a blank data explorer shows up which makes the application look broken.

**Comment by wesm** [comment]
I put a broken file that you can use for QA/verification here:

https://github.com/posit-dev/qa-example-content/blob/main/data-files/100x100/100x100_broken.parquet

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.11.0-140](https://github.com/posit-dev/positron-builds/releases/tag/2024.11.0-140)
OS Version(s) : Windows 11, Ubuntu 24

### Test scenario(s) 

using https://github.com/posit-dev/qa-example-content/blob/main/data-files/100x100/100x100_broken.parquet

<img src="https://github.com/user-attachments/assets/9fb3b4b6-1f01-45e3-a9c3-9de4761b8062" width=30%>




### Link(s) to TestRail test cases run or created:
