### ISSUE TITLE
Shutting down the Reticulate repl should return focus to R repl

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#5144]
Steps to reproduce:

1. Open the reticulate Python repl.
2. Shut it down
3. Focus should be given back to the R session instead of displaying the restart button:

![Image](https://github.com/user-attachments/assets/39426d0b-9afc-4ce3-aa9c-5dd8cc4e2b6f)

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-140
    OS Version          : OSX

### Test scenario(s) 

Shutting down reticulate repl returns focus to R repl

Link(s) to TestRail test cases run or created:
