### ISSUE TITLE
Filtering in data explorer causes column profiles to be computed twice instead of only once

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#5150]
On the current main branch, as discussed in #5148, the `get_column_profiles` method for the visible summary stats is being called twice (rather than only once as is needed) after applying a filter:

https://github.com/user-attachments/assets/c361f0b3-c919-431d-852b-fd73f2f5f04e

I'm using a 25x larger version of flights.parquet

```
flights = pd.read_parquet('/home/wesm/code/testingstuff/flights.parquet')
flights_big = pd.concat([flights] * 25, ignore_index=True)
```

Here are the console logs 

https://gist.githubusercontent.com/wesm/dc4f9c3195d37ee34c2dced21b7cfce8/raw/186381aeb327eb6cf36d3a592553d7b7c8e20d78/gistfile1.txt

You can see that get_column_profiles is computed once at 2024-10-23 17:18:22.983 and then again 5 seconds later at 2024-10-23 17:18:27.992 (after the cache is cleared and the sparklines are blanked out)

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-111
    OS Version          : OSX

### Test scenario(s) 

Only see 1 call to get_column_profiles for filtration in logs

Link(s) to TestRail test cases run or created:
