### ISSUE TITLE
Positron Build Number is `0` in DEB and RPM package version info

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#5159]
#### Positron and OS details:

Builds containing 9a8f07a0ffdf58ba6bce82559c02595ad4715055. Prior to this commit, we didn't include the `BUILD_NUMBER` in the package version info. Now that we include it, it revealed that we need to pass the calculated `BUILD_NUMBER` instead of the static value in product.json which is always `0`.

#### Interpreter details:

N/A

## Describe the issue:

Build number always shows `0` in DEB/RPM package version info output.

This is a follow-up to #1373.

#### DEB
1. Run `dpkg --info <POSITRON_BINARY>.deb`
2. Version field in the output shows `<POSITRON_VERSION>+0-<LINUX_REVISION>`

Sample Output:
```
<SOME_INITIAL_INFO>
Package: positron
Version: 2024.11.0+0-1729709839
<REST_OF_INFO>
```

#### RPM
1. Run `rpm -qi <POSITRON_BINARY>.rpm`
2. Version field in the output shows `<POSITRON_VERSION>+0`

Sample Output:
```
Name        : positron
Version     : 2024.11.0+0
<REST_OF_INFO>
```

## Expected or desired behavior:

Version info should contain the correct build number, which usually is not 0.

#### DEB
1. Run `dpkg --info <POSITRON_BINARY>.deb`
2. Confirm the Version field in the output shows `<POSITRON_VERSION>+<BUILD_NUMBER>-<LINUX_REVISION>`

Sample Output:
```
<SOME_INITIAL_INFO>
Package: positron
Version: 2024.11.0+999-1729709839
<REST_OF_INFO>
```

#### RPM
1. Run `rpm -qi <POSITRON_BINARY>.rpm`
2. Confirm the Version field in the output shows `<POSITRON_VERSION>+<BUILD_NUMBER>`

Sample Output:
```
Name        : positron
Version     : 2024.11.0+999
<REST_OF_INFO>
```

## Were there any error messages in the UI, Output panel, or Developer Tools console?

N/A

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-129
    OS Version          :  Ubuntu 24

### Test scenario(s) 

dpkg --info <POSITRON_BINARY>.deb
returns version information.

Link(s) to TestRail test cases run or created:
