### ISSUE TITLE
ark: Vignette hyperlinks are broken

### ISSUE THREAD

**Issue by jennybc** [posit-dev/positron#5171]
cli's hyperlinks to vignettes are broken. PR incoming.

To experience it, do this:

```r
cli::cli_text("{.vignette fs::function-comparisons}")
```

and click on the resulting hyperlink. You get this (why can I not copy this text? 🤔)

![Image](https://github.com/user-attachments/assets/588829d9-c1aa-4d25-a48e-48fc468f592d)

**Comment by jennybc** [comment]
QA: Execute this code in the R console:

```r
cli::cli_text("{.vignette fs::function-comparisons}")
```

(any `pkg::vignette-name` will do FWIW).

And click on the vignette-opening link. It should open that vignette in the help pane.

**Comment by juliasilge** [comment]
Ark has been bumped since this was merged, so we can verify this now.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.11.0-140
    OS Version          : OSX

### Test scenario(s) 

Vignette opens as expected.

Link(s) to TestRail test cases run or created:
