### ISSUE TITLE
ERROR RENDERING PLOT

### ISSUE THREAD

**Issue by GonzaloLloncon** [posit-dev/positron#5173]
Type: <b>Performance Issue</b>

cant render a rpart.plot:
Error rendering plot to 'Auto' size: RPC timed out after 30 seconds: {"jsonrpc":"2.0","method":"render","params":{"size":{"height":578,"width":699},"pixel_ratio":2,"format":"png"}} (-32603)

VS Code version: Positron 1.93.0 (Universal) (4cde19a003d09cf75114ec8650020b132bbc5554, 2024-10-21T02:48:15.195Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   123	  6367	positron main
    0	    49	  6368	   gpu-process
    0	    16	  6369	   utility-network-service
    0	   287	  6370	window [1] (ejercicios Tidy Model.R)
    0	    66	  6387	shared-process
    0	     0	  6753	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    33	  6388	fileWatcher [1]
    0	    74	  6389	extensionHost [1]
    0	    33	  6460	     electron-nodejs (lsp.js )
    0	    33	  6428	ptyHost
    0	     0	  6461	     electron-nodejs (connection.js )
   99	   377	  6467	       electron-nodejs (connection.js )
    0	     0	  6463	     /bin/zsh -i
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
pyright|ms-|1.1.386
debugpy|ms-|2024.12.0
js-debug|ms-|1.95.0
quarto|qua|1.116.0

(5 theme extensions excluded)

</details>

**Comment by juliasilge** [comment]
Can you share details of what code you are running to see this error? If I run code like this:

```r
library(rpart)

fit <- rpart(Kyphosis ~ Age + Number + Start, data = kyphosis)
plot(fit)
```

I see a result like this, which is the same as RStudio or from the terminal:

![Image](https://github.com/user-attachments/assets/c8136852-b6dd-4114-bf4c-34a3fb48dc24)

**Comment by sharon-wang** [comment]
I ran this code with R 4.3.3 and got a blank plot, but I didn't see any errors:

```r
# Install and load the necessary packages
install.packages("rpart")
install.packages("rpart.plot")
library(rpart)
library(rpart.plot)

# Using the built-in iris dataset
data(iris)

# Fit a decision tree model
model <- rpart(Species ~ ., data = iris, method = "class")

# Plot the decision tree
rpart.plot(model)
```

![Image](https://github.com/user-attachments/assets/97ca28c0-93de-455c-8db8-ebb4c082b47b)


For comparison, in RStudio, running the same code gets me this plot image:

![Image](https://github.com/user-attachments/assets/df59e742-a5aa-45d9-8ae6-3727ae025b38)

**Comment by juliasilge** [comment]
Let us know if you are able to share details on the code you ran to see this error!

**Comment by GonzaloLloncon** [comment]
Gracias por responder. Efectivamente lo que no se vé en POSITRON, me aparece sin problemas en RSTUDIO. Desconozco por qué no aparece, teniendo las mismas librerías instaladas. Saludos desde Chile

**Comment by juliasilge** [comment]
This looks like another `par()` problem so I added this example to #4593.
