### ISSUE TITLE
Data explorer: recent performance degradation

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#5176]
#### Positron and OS details:

Main in CI, ongoing

#### Interpreter details:

N/A

## Describe the issue:

Since smooth scrolling was introduced, we have had to bump the timers which time from:
    click of a variable row for a data frame
to
    stop of dataframe loading spinner

by 700%

## Steps to reproduce the issue:

This reproduces in CI with the Very Large Data Frame Test.  It opens a 20x1million data frame.

## Expected or desired behavior:

Ideally the introduction of smooth scrolling would have had a negligible effect on load performance

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No

### 
QA NOTES - See https://github.com/posit-dev/positron/pull/5199, need to turn tests back on once this is resolved

**Comment by jonvanausdeln** [comment]
Another interesting note.. this only happens on Python, and when it finishes "loading" I don't see the summary/sparklines automatically.

<img src="https://github.com/user-attachments/assets/9bd22c84-f715-45f8-9729-53a7c15c75bb" width=50%>

However, in R, they populate automatically after loading

<img src="https://github.com/user-attachments/assets/8c869f95-4a0f-4c60-87b7-7caf38e19c3c" width=50%>

Also in Python, they will show if I manually expand the column summary.

**Comment by wesm** [comment]
Taking a look at this

**Comment by wesm** [comment]
I was able to track this down to a bug in NumPy: https://github.com/posit-dev/positron/pull/5207. The error happening when computing a histogram was also being swallowed and causing the column profile task handler to fail and never return a result to the frontend, so that has also been fixed to avoid that class of timeouts.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.11.0-129](https://github.com/posit-dev/positron-builds/releases/tag/2024.11.0-129)
OS Version(s) : Windows 11

### Test scenario(s) 

The verylargeDataFrame test now passes.


### Link(s) to TestRail test cases run or created:
