### ISSUE TITLE
Source R file command should use `echo = TRUE`

### ISSUE THREAD

**Issue by lionel-** [posit-dev/positron#5191]
Reported in https://github.com/posit-dev/positron/discussions/5185

Take this R file:

```r
1

print(2)

3
```

The "Source R file" command (`r.sourceCurrentFile`) currently produces this output:

```
> source("/Users/lionel/test.R")
[1] 2
```

RStudio uses `echo = TRUE` which allows to see all outputs interleaved with inputs:

```
> source("/Users/lionel/test.R", echo = TRUE)

> 1
[1] 1

> print(2)
[1] 2

> 3
[1] 3
```

**Comment by IvanSortino97** [comment]
Is there a way to set back ECHO = FALSE ? By default RStudio use the latest selected source option not always the ECHO = T.

It would be grate to modify the parameters from the settings.json file directly

**Comment by juliasilge** [comment]
Yes @IvanSortino97 I realized the same thing and made a followup PR in https://github.com/posit-dev/positron/pull/5237. This is not in the [currently available public build](https://github.com/posit-dev/positron/releases), but will be in the next one that we promote (expected sometime this week). Apologies for the inconvenience!
