### ISSUE TITLE
New Folder, New Folder from Git and New Project modals erroring on Windows

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#5195]
Originally reported in https://github.com/posit-dev/positron/discussions/5188

#### Positron and OS details:

Positron Version: 2024.11.0 (user setup) build 116
Code - OSS Version: 1.93.0
Commit: 8b1688ababfa228db515a739050c466f3bb3089f
Date: 2024-10-28T02:49:37.855Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26100

#### Interpreter details:

Any

## Describe the issue:

On Windows, the New Folder, New Folder from Git and New Project modals all error due to Windows file path issues. As a result, users cannot create new projects from these modals.

### New Folder

1. New > New Folder
2. Type in a folder name
3. Click <knd>OK</kbd>

> @JeffreySumner:
> ![image](https://github.com/user-attachments/assets/c6e0591a-ee7f-4bbe-9bb9-fae0cf83f9a5)

### New Folder from Git

1. New > New Folder from Git
2. Type in a folder name
3. Click <knd>OK</kbd>

> @JeffreySumner:
> When testing git, I get the following error:
> ![Image](https://github.com/user-attachments/assets/eeaf5635-5f49-41b3-8c3b-aada7b41c9e1)
> This occurs when using the default pathing options. When I adjust the path an I take the /c: off, it works.

### New Project
1. New > New Project
2. Select a Project Type and <knd>Next</kbd>
3. Click <knd>Next</kbd> on the project name and location step
4. Click <knd>Create</kbd> and nothing seems to happen; see error message in Dev Console

https://github.com/user-attachments/assets/14eb9233-5507-43ec-b7b5-cde9ecd6bc04

Console Error:
```js
  ERR Error: EINVAL: invalid argument, mkdir 'c:\Users\sharon\c:\Users\sharon\myPythonProject': Unknown (FileSystemError): Error: EINVAL: invalid argument, mkdir 'c:\Users\sharon\c:\Users\sharon\myPythonProject'
    at $rl.create (C:\Users\sharon\AppData\Local\Programs\Positron\resources\app\out\vs\code\electron-main\main.js:30453:35)
    at $sl (C:\Users\sharon\AppData\Local\Programs\Positron\resources\app\out\vs\code\electron-main\main.js:30464:20)
    at $Er.hb (C:\Users\sharon\AppData\Local\Programs\Positron\resources\app\out\vs\code\electron-main\main.js:35547:36)
    at $Er.mkdir (C:\Users\sharon\AppData\Local\Programs\Positron\resources\app\out\vs\code\electron-main\main.js:35341:28)
```

## Expected or desired behavior:

Users should be able to create new folders and projects using any of the New Folder, New Folder from Git and New Project modals on Windows.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

See notes above.

**Comment by jonvanausdeln** [comment]
@sharon-wang , this seems to have broken the release build.  I can't create a new project at all on [2024.11.0-129](https://github.com/posit-dev/positron-builds/releases/tag/2024.11.0-129)

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.11.0-140](https://github.com/posit-dev/positron-builds/releases/tag/2024.11.0-140)
OS Version(s) : Windows 11

### Test scenario(s) 

Modals work and projects created as expected.


### Link(s) to TestRail test cases run or created:
