### ISSUE TITLE
Run App: Running Shiny app doesn't open in Viewer on Workbench

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#5197]
#### Positron and OS details:

Positron on Workbench, latest release or build from `main`. Ubuntu 24 x86_64.

#### Interpreter details:

Any

## Describe the issue:

The Shiny app is run successfully, but it does not automatically show in the Viewer. A user can workaround this by ctrl+clicking on the app url in the Terminal output, and choosing to open it in the Viewer from the Command Prompt that appears.

https://github.com/user-attachments/assets/66ab2b0a-499f-4f9f-b74e-44dbd041a5dd

## Steps to reproduce the issue:

1. Run the Shiny Python app from https://github.com/posit-dev/qa-example-content/tree/main/workspaces/shiny-py-example by clicking on the Run App play button
2. The app will run successfully in the Terminal, but it will not be loaded into the Viewer pane

## Expected or desired behavior:

The Shiny app should automatically preview in the Viewer pane once the app is ready.

The issue is that the regex used to determine the url to load in the Viewer only expects local urls:

https://github.com/posit-dev/positron/blob/a0bda6599794e3a79db5ceee224b8e43fa70818b/extensions/positron-run-app/src/api.ts#L14-L15

However, when running a Python Shiny app in Positron on Workbench, Workbench has some url handling which results in a non-local url outputted to the terminal, e.g. `https://mypositworkbench.posit.co/s/89nd2984n294n2/p/hsdu032`, which doesn't get matched by the regex.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Positron Run App Output

```
[warning] Failed to preview URL using shell integration
[warning] Timed out waiting for server URL in terminal output
```
---

### Relevant PRs

- fix in `main`: https://github.com/posit-dev/positron/pull/5349
- fix in `prerelease/2024.11`: https://github.com/posit-dev/positron/pull/5336
    - follow-up fix https://github.com/posit-dev/positron/pull/5362

**Comment by sharon-wang** [comment]
@seeM I think I'll look for a node library to match any url, not just localhost/127.0.0.1, since hosted URLs are sometimes used on Workbench, and outside of Workbench a user could set their own non-local URL where their app is served.

Do you know off-hand if this won't play well with the frameworks we support or future frameworks? It seems like the first url printed in the Terminal output is the url we want to load in the Viewer, but there are probably exceptions.

**Comment by seeM** [comment]
@sharon-wang That sounds reasonable. I'm not sure if there are frameworks that won't play well. I suggest we design for the current set of frameworks for now.

An alternative could be let callers specify a regex pattern for the line containing the URL. For example, all uvicorn-based frameworks could specify something like `Uvicorn running on https://\.*/ (Press Ctrl+C to quit)`. That's how the existing `debug-server-ready` builtin extension works. Currently, we just open the first matched localhost URL.

It would make us slightly more tied to each framework e.g. it would break if a framework changes their wording, but there'll be fewer cases where we open the wrong URL, and it'll also address this issue.

I don't have a strong preference either way.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.11.1-9](https://github.com/posit-dev/positron-builds/releases/tag/2024.11.1-9), [2024.12.0-33](https://github.com/posit-dev/positron-builds/releases/tag/2024.12.0-33)
Workbench Version(s): [2024.11.0-daily+336.pro2](https://dailies.rstudio.com/version/2024.11.0-daily+336.pro2)
OS Version(s) : Ubuntu 24

### Test scenario(s) 
Shiny app now opens in Workbench

### Link(s) to TestRail test cases run or created:
