### ISSUE TITLE
Hyperlinks don't work for package dev tasks sent to a terminal

### ISSUE THREAD

**Issue by jennybc** [posit-dev/positron#5218]
I am about to make a PR (well, 2 PRs, one here and one in cli) to address this problem:

positron-r carries out certain package dev tasks in a separate terminal (as opposed to in the active R session in the console). This terminal is our *de facto* nod to the build pane in RStudio. It's sad that cli hyperlinks do not currently work in this context, because you often really do want to navigate directly to a troubled test file or launch the Shiny app to review snapshot changes. I know from personal experience and talking to other package devs that many of us are avoiding the formal tasks for this reason, choosing to interactively execute the same "by hand" in the console.

![Image](https://github.com/user-attachments/assets/e30fd20f-ba5c-4753-b70b-4d73fbab1bad)

**Comment by jennybc** [comment]
Update: I'm designating this issue to be just about run (or help or vignette) hyperlinks and _not_ about file hyperlinks. These require two different solutions and I'm going to open a second issue about file hyperlinks.

W.r.t. the screenshot above, this issue is about making `testthat::snapshot_accept('aaa')` and `testthat::snapshot_review('aaa')` clickable. That should execute the associate code in the R console.

(It is _not_ about what happens when you click `test-aaa.R:10:3`.)

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-80
    OS Version          : OSX

### Test scenario(s) 

Verified according to instructions at: https://github.com/posit-dev/positron/commit/9084df0131c0dbed78fb756b0de3344a85601951

Link(s) to TestRail test cases run or created:
