### ISSUE TITLE
Resume connections modal should use a Text Editor

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#5219]
The Resume Connection modal should have a text editor that allows the user to quickly edit the connections code.

![Image](https://github.com/user-attachments/assets/a41fe61a-9f6d-4d62-9866-9021985c0ea9)

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-66
    OS Version          : OSX

### Test scenario(s) 

Modal connection editor is now present.

Link(s) to TestRail test cases run or created:
