### ISSUE TITLE
Documentation: R discovery

### ISSUE THREAD

**Issue by jennybc** [posit-dev/positron#5222]
Document the general flow of R discovery and the configuration points.

**Comment by dskard** [comment]
We should mention in the documentation that, at least on Linux, you should give a full path to the R installation if you are manually setting the location through Settings > Extensions > R > Positron R Language Path (advanced). I don't think things like `~` and `${HOME}` are recognized.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : N/A
    OS Version          : N/A

### Test scenario(s) 

Scanned added documentation

Link(s) to TestRail test cases run or created:
