### ISSUE TITLE
Help hyperlinks illegible in dark theme

### ISSUE THREAD

**Issue by kv9898** [posit-dev/positron#5227]
## System details:

Windows 11

#### Positron and OS details:

Positron Version: 2024.11.0 (system setup) build 116
Code - OSS Version: 1.93.0
Commit: 8b1688ababfa228db515a739050c466f3bb3089f
Date: 2024-10-28T02:47:45.218Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26100

#### Interpreter details:

R 4.4.1

## Describe the issue:

When in dark themes, the hyperlinks in the Help panel are not legible.

![Image](https://github.com/user-attachments/assets/6510ee4e-6d52-4a90-a2d8-88424afd4921)

## Steps to reproduce the issue:

1. ?summary

## Expected or desired behavior:

A lighter colour maybe?

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No

**Comment by jmcphers** [comment]
Thank you for reporting this! We're tracking this issue in https://github.com/posit-dev/positron/issues/4790.

**Comment by kv9898** [comment]
> Thank you for reporting this! We're tracking this issue in https://github.com/posit-dev/positron/issues/4790. 

Oh thank you I'll close this then.
