### ISSUE TITLE
Merge 1.95 from VS Code upstream

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#5228]
Integrate the 1.95 version of VS Code from `microsoft/vscode` when it is released. Note that this will be more work than usual to integrate since it includes a sweeping reorganization to use ESM (https://github.com/microsoft/vscode/pull/227184).

**Comment by ntluong95** [comment]
This patch of VSCode bundled heavily with AI features and data analysis. Wondering if Positron can have something similar

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-104
    OS Version          : OSX

### Test scenario(s) 

Marking verified as process is complete.  Issues have been raised as a result but are filed separately.

Link(s) to TestRail test cases run or created:
