### ISSUE TITLE
Data explorer appears to show placeholder row labels temporarily when scrolling through a filtered table

### ISSUE THREAD

**Issue by AdAstraAbyssoque** [posit-dev/positron#5230]
#### Positron and OS details:
- Positron: 2024.11.0-116
- Distributor ID: Ubuntu
- Description: Ubuntu 24.10
- Release: 24.10
- Codename: oracular

#### Interpreter details:
- Python: 3.12.5
- R: 4.4.1 (2024-06-14)

## Describe the issue:
In Jupyter Notebook, the data preview feature (accessed via variables) experiences overflow when scrolling through large index numbers (greater than 32768). This results in data overflow, as shown in the attached video.https://github.com/user-attachments/assets/507dc8fa-d150-487b-9b84-8bcb2a396420

## Steps to reproduce the issue:
1. Read the trimmed PISA data:
   ```R
   pisa_data <- read_sav("~/workplace/xxx/xxx/PISA2018_top10_new.sav")
   ```
Due to it is the sav file, the Google Drive Link is attached.
https://drive.google.com/file/d/1E6DWznTlg8y2UbgRGKh-T_mCnrR7YuQZ/view?usp=sharing

## Expected or desired behavior:
The expected behavior is to not experience overflow when scrolling through the data preview.

## Were there any error messages in the UI, Output panel, or Developer Tools console?
No error messages were observed.

**Comment by jthomasmock** [comment]
Howdy @AdAstraAbyssoque 

Can you clarify the overflow in this scenario? 

I think I saw the rownames jump but I wanted to confirm that's what you were indicating. 

If so, do you know if your data has manually assigned rownames or that was just the row index?

**Comment by AdAstraAbyssoque** [comment]
Row index actually, I haven't modified that sav file manually with index.
It seems that it's the data explorer displaying issue. When rolling process starts, the index will overflow.@jthomasmock

**Comment by jthomasmock** [comment]
Thanks!

I'm not able to reproduce this on a reprex dataset with 40,000 rows:

```r
library(haven)
library(dplyr)

# Set the number of rows
n_rows <- 40000

# Create a data frame with random data
df <- data.frame(
  id = 1:n_rows,
  group = sample(LETTERS[1:5], n_rows, replace = TRUE),
  value1 = rnorm(n_rows, mean = 50, sd = 15),
  value2 = runif(n_rows, min = 0, max = 100),
  date = sample(seq(as.Date('2022/01/01'), as.Date('2023/12/31'), by="day"), n_rows, replace = TRUE),
  logical = sample(c(TRUE, FALSE), n_rows, replace = TRUE),
  categorical = factor(sample(c("Low", "Medium", "High"), n_rows, replace = TRUE)),
  char_var = sample(c("Apple", "Banana", "Cherry", "Date"), n_rows, replace = TRUE)
)

# Introduce some missing values (around 5% in each variable)
df$value1[sample(1:n_rows, n_rows * 0.05)] <- NA
df$value2[sample(1:n_rows, n_rows * 0.05)] <- NA
df$date[sample(1:n_rows, n_rows * 0.05)] <- NA
df$logical[sample(1:n_rows, n_rows * 0.05)] <- NA
df$categorical[sample(1:n_rows, n_rows * 0.05)] <- NA
df$char_var[sample(1:n_rows, n_rows * 0.05)] <- NA



# Ensure categorical variables are factors (important for SPSS)
df$group <- as_factor(df$group)
df$categorical <- as_factor(df$categorical)
df$char_var <- as_factor(df$char_var) # Treat the character variable as categorical in SPSS


# Save the data frame to a .sav file
file_path <- "my_dataset.sav" # Specify the desired file path

haven::write_sav(df, file_path)

#Optional: Read back in for verification
read_df <- haven::read_sav(file_path)
```

https://github.com/user-attachments/assets/1d81c890-f4e1-474c-b051-6e47e61ca103

**Comment by AdAstraAbyssoque** [comment]
I think it's a loading issue. You can notice that during mouse movement, yours is very smooth and the data appears instantly, while mine lags causing blanks and gaps (actually I just retested your code and review my own dataset and they were also very smooth). This incomplete loading is confusing. 

In the original video, we got this "Showing 22,679 rows (28.34%of 80,016 total)436 columns":  (in video):
![Image](https://github.com/user-attachments/assets/47b45ef8-403c-47a9-a25a-339de0c41b39)

But now we have (right now test): 
![Image](https://github.com/user-attachments/assets/14b99e0b-7ff9-4fe4-8db8-5558bda879ca)
and 
![Image](https://github.com/user-attachments/assets/8a0f1248-b6aa-4625-ad9f-38b5240b304d)

How could this "Showing 22,679 rows (28.34%of 80,016 total)436 columns" happens

> My code is shown below:

```R
library(haven)
library(car)

pisa_data <- read_sav("/PISA2018_top10_new.sav")
```

**Comment by AdAstraAbyssoque** [comment]
Sorry for not mentioning you @jthomasmock

**Comment by wesm** [comment]
I'm able to reproduce this issue on the main branch as of today:

https://github.com/user-attachments/assets/4c13576d-7578-481e-84ed-f267d58ca0e5

My guess is that that placeholder row labels relative to index 0/1 are being shown while the actual row labels in the filtered dataset are being loaded, when it would be more correct to show a blank label while waiting for the row labels from the backend. I'll update the title

**Comment by wesm** [comment]
It also appears from the video that the `haven_labelled` type columns are not supported for computing histograms / frequency tables. Seems like we should implement this

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-50
    OS Version          : OSX

### Test scenario(s) 

Unable to repro with original data set and:
```
library(haven)
library(car)

pisa_data <- read_sav("PISA2018_top10_new.sav")
```

Link(s) to TestRail test cases run or created:
