### ISSUE TITLE
R pipe keyboard shortcut inserts base pipe instead of magrittr pipe

### ISSUE THREAD

**Issue by mfauzaanshareef** [posit-dev/positron#5232]
#### Positron and OS details:   
Positron release: 2024.11.0-116. 
OS: macOS Sonoma 14.5. 

## Describe the issue:
The keyboard shortcut to insert the R pipe (Cmd+Shift+M) inserts the base pipe |>. I want the command to insert the magrittr pipe %>%. I have enabled RStudio key mappings for Positron but this doesnt seem to have an effect. Is there any way to change which type of pipe is inserted?

**Comment by jennybc** [comment]
This is configurable here:

First: Cmd/Ctrl + Shift + P to open command palette.

*Extensions > R > Positron R Language Pack > Pipe
