### ISSUE TITLE
Positron Server: Interpreters hung after browser reload and reconnect

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#5235]
#### Positron and OS details:

2024.11.0-140

#### Interpreter details:

Any

## Describe the issue:

When reloading the browser, the interpreters reconnect, but are non-interactive.

## Steps to reproduce the issue:

1. Start some interpreters
2. Reload the browser

The interpreters appear busy and most RPCs time out.

![Image](https://github.com/user-attachments/assets/dc5f2bfb-be69-452a-8a81-2223182fb339)

## Expected or desired behavior:

The interpreters should work as before the reload.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Both R and Python appear to have this issue, but more investigation is needed. R panics with this error:

```
[R]   2024-10-31T00:39:52.639721Z ERROR  Panic! In file 'crates/ark/src/lsp/main_loop.rs' at line 450: called `Option::unwrap()` on a `None` value
[R] 
[R] Backtrace:
[R]    0: std::backtrace::Backtrace::create
[R]    1: ark::main::{{closure}}::{{closure}}
[R]    2: ark::main::{{closure}}
[R]    3: std::panicking::rust_panic_with_hook
[R]    4: std::panicking::begin_panic_handler::{{closure}}
[R]    5: std::sys::backtrace::__rust_end_short_backtrace
[R]    6: _rust_begin_unwind
[R]    7: core::panicking::panic_fmt
[R]    8: core::panicking::panic
[R]    9: core::option::unwrap_failed
[R]   10: ark::lsp::main_loop::GlobalState::start::{{closure}}
[R]   11: tokio::runtime::task::harness::Harness<T,S>::poll
[R]   12: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
[R]   13: tokio::runtime::scheduler::multi_thread::worker::Context::run
[R]   14: tokio::macros::scoped_tls::ScopedKey<T>::set
[R]   15: tokio::runtime::scheduler::multi_thread::worker::run
[R]   16: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
[R]   17: tokio::runtime::task::core::Core<T,S>::poll
[R]   18: tokio::runtime::task::harness::Harness<T,S>::poll
[R]   19: tokio::runtime::blocking::pool::Inner::run
[R]   20: std::sys::backtrace::__rust_begin_short_backtrace
[R]   21: core::ops::function::FnOnce::call_once{{vtable.shim}}
[R]   22: std::sys::pal::unix::thread::Thread::new::thread_start
[R]   23: __pthread_joiner_wake
[R] 
[R]     at crates/ark/src/main.rs:278
[R] 
```

Likely related to #4959 for R, but this issue feels separate since Python also has it.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.12.0-7](https://github.com/posit-dev/positron-builds/releases/tag/2024.12.0-7) - `main` branch as of this version
OS Version(s) : Ubuntu 24.04

### Test scenario(s) 

Dev builds of server reconnect to Python as expected.

R is seeing #4959 as mentioned in PR #5245 



### Link(s) to TestRail test cases run or created:
