### ISSUE TITLE
Positron Web: New Python project venv env won't start

### ISSUE THREAD

**Issue by jonvanausdeln** [posit-dev/positron#5236]
#### Positron and OS details:

Positron web (main branch as of 10/31/2024)
Ubuntu 24.04

#### Interpreter details:

Python 3.10.10

## Steps to reproduce the issue:

1. Start Positron Web
2. Go through New Project workflow for Python, accepting defaults

After new project loads, and tries to start the interpreter:
<img src="https://github.com/user-attachments/assets/bebba6b2-6d4a-4b88-9a0e-d75d6849137e" width=60%>

## Expected or desired behavior:
For the interpreter to start up correctly.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

I didn't see any error message in log nor dev tools

**Comment by juliasilge** [comment]
I saw a related problem with R starting today, but it went away after I did a full rebuild. Maybe try doing `./rebuild.sh` to see if the problem persists? Mine is all fine now.

**Comment by jonvanausdeln** [comment]
> I saw a related problem with R starting today, but it went away after I did a full rebuild. Maybe try doing `./rebuild.sh` to see if the problem persists? Mine is all fine now.

That did the trick.. move along.. nothing to see here..
