### ISSUE TITLE
Cannot find data in variable section after installing Data Wrangler

### ISSUE THREAD

**Issue by GorunNova** [posit-dev/positron#5239]
Type: <b>Bug</b>

After  installing Data Wrangler in Vs Code, the Variables section does not show any data now. Even I uninstalled that extension in Vs code. The Data section cannot work now.

VS Code version: Positron 1.91.0 (ed616b36655fb24d116108bdd833f1321704315b, 2024-08-19T03:30:12.447Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
pyright|ms-|1.1.387
debugpy|ms-|2024.8.0
jupyter|ms-|2024.6.0
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
js-debug|ms-|1.95.1

</details>

**Comment by lionel-** [comment]
Is this with R or Python? Can you provide us with all the steps that you do to produce this unexpected behaviour?

Can you please provide us with log output as well: https://positron.posit.co/troubleshooting.html#python-and-r-logs

**Comment by juliasilge** [comment]
Let us know if you are able to share more details on the steps you took to produce this problem!

To record for the future, almost all of us on the team do have the Data Wrangler extension installed in VS Code and are not observing problems in Positron.
