### ISSUE TITLE
set the language of the UI interface

### ISSUE THREAD

**Issue by triple-y** [posit-dev/positron#5250]
Hello, how to set the language of the UI interface, such as setting the language to Chinese？Thank you

**Comment by petetronic** [comment]
Hi @triple-y and thank you for testing Positron! The command "Change Language Display" will change the core display language of the IDE, where `zh-cn` is currently an option that can be downloaded, though note we have not yet localized Positron specific text in the UI.

**Comment by testlabauto** [comment]
Hello again, @triple-y, by chance did this resolve your issue?

**Comment by juliasilge** [comment]
Let us know if you have further problems with setting the language of the UI!
