### ISSUE TITLE
Every new line in an R script automatically indents by one space

### ISSUE THREAD

**Issue by jack-davison** [posit-dev/positron#5258]
#### Positron and OS details:

Positron Version: 2024.11.0 (user setup) build 140
Code - OSS Version: 1.93.0
Commit: e0d844b031f95acbf89f234a2cce2af9b6721f6c
Date: 2024-10-31T14:22:13.808Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

#### Interpreter details:

R 4.4.3

## Describe the issue:

Whenever I go to a new line in a .R file a space is automatically added.

I have tried to disable and re-enable extensions, but it's still happening.

## Steps to reproduce the issue:

1. Open R Script
2. Add new line
3. Note the addition of the indents.

![Image](https://github.com/user-attachments/assets/c7f9bcf0-36cb-445a-bebb-0cfdd30c73a7)

## Expected or desired behavior:

I would imagine there would not be any indentation.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

N/A

**Comment by testlabauto** [comment]
Hi, thank you for using Positron!  Unfortunately, we are not able to reproduce this issue locally so we are hoping you can provide some more diagnostic information.  

Is it correct to assume that you tried to repro with all user installed extensions disabled (and it still repros)?

Could you perhaps capture your settings.json as a file and share it?  Here is an image showing where the button is to go from the visual editor to the file view:

![Image](https://github.com/user-attachments/assets/3f0b11f9-fe25-4e47-81a1-4a48d700ef6b)

If you want to try it, you can also cut out all your settings, save the json elsewhere, and retest with no all default settings.  Then you would be able to paste back in your settings from the saved location after the test.

**Comment by jack-davison** [comment]
Hi Christopher, 

Thanks for getting back.

> Is it correct to assume that you tried to repro with all user installed extensions disabled (and it still repros)?

Yes, that's right.

> Could you perhaps capture your settings.json as a file and share it? Here is an image showing where the button is to go from the visual editor to the file view:

My settings seem quite lightweight:

```js
{
    "rstudio.keymap.enable": true,
    "git.confirmSync": false,
    "python.defaultInterpreterPath": "C:\\Users\\JD38\\AppData\\Local\\Programs\\Python\\Python312\\python.exe"
}
```

I've deleted these and the situation persists:

![Image](https://github.com/user-attachments/assets/06b4f8ba-a9cf-436d-8d63-d37f57f07365)

**Comment by jack-davison** [comment]
I'll also note a fresh install doesn't fix it.

If I'm quick, when Positron first loads it doesn't have this issue, but after a second or so it kicks in, which makes me think its an extension problem.

**Comment by sharon-wang** [comment]
@jack-davison if you disable the extensions, then click one of the <kbd>Restart Extensions</kbd> buttons, wait for the reload and try again, are you still seeing the issue?

![Image](https://github.com/user-attachments/assets/e2f6ae88-02df-4119-9149-a376c3cbff6f)

The Extensions Host needs to be restarted for the extension disable to take. If the issue still persists after disabling and reloading extensions, then something else could be the culprit.

If the issue is gone after disabling and reloading extensions, we could try a bit of a tedious task of disabling individual extensions and checking which one is resulting in this issue. Additionally, if you're willing to share the output of running `positron --list-extensions` in a Terminal, that could help us discern which extensions to take a closer look at.

**Comment by lionel-** [comment]
> If I'm quick, when Positron first loads it doesn't have this issue, but after a second or so it kicks in, which makes me think its an extension problem.

Could you please shut down the R session that automatically starts and see if the issue persists?

![Image](https://github.com/user-attachments/assets/76ff8d1d-574a-470e-8c44-3b2850315c47)


The problem might come from the LSP running in the R session.

**Comment by strengejacke** [comment]
I also see this issue, but it I couldn't figure out a systematic reason - sometimes, it happens, sometimes not, is my impression.

https://github.com/user-attachments/assets/97b17811-d42a-404e-9d0b-9f27d4b0aa34

Setup:

```
Positron Version: 2024.11.0 (system setup) build 140
Code - OSS Version: 1.93.0
Commit: e0d844b031f95acbf89f234a2cce2af9b6721f6c
Date: 2024-10-31T14:14:22.699Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```

Here's my setup:
https://gist.github.com/strengejacke/2a785f8e096d94bc84fb6b877aad4fb1

**Comment by lpembleton** [comment]
Same issue here on a fresh install with no extra extensions installed. Issue also persists even after running 'Reload With Extensions Disabled' from the command palette.

**Comment by jack-davison** [comment]
Hi @juliasilge,

When I disable the R session via the console, the error stops and the indents do not occur. When I turn it back on, the issue reoccurs.

The issue doesn't happen in `.qmd` files regardless of whether the R console is active or stopped.

Cheers,
Jack

**Comment by lpembleton** [comment]
Yes same here, error goes away if R is not running, and does not occur in .qmd .Rmd or any python related files regardless of whether R is running or not.

Thanks for looking into this, I understand its difficult when you cannot replicate it on your end.

Cheers,
Luke

**Comment by lionel-** [comment]
Could y'all please open a new positron session, trigger the wrong indents a few times, and give us your R logs? You can find them by following the steps in https://positron.posit.co/troubleshooting.html#python-and-r-logs. I'm especially interested in the logs for the language server but also the runtime.

**Comment by DavisVaughan** [comment]
I managed to reproduce on a windows vm based on these comments. It's a tree-sitter-r issue, tracking here https://github.com/r-lib/tree-sitter-r/issues/151, thanks all!

**Comment by testlabauto** [comment]
Hello @jack-davison, would you mind trying out the new release
[2024.12.0-41](https://github.com/posit-dev/positron/releases/tag/2024.12.0-41)
and see if it is now working for you?

**Comment by jack-davison** [comment]
Hi @testlabauto - seems to be working now!

Thanks for everyone's help here!
