### ISSUE TITLE
Update prerelease/2024.11 branch to patch 1

### ISSUE THREAD

**Issue by petetronic** [posit-dev/positron#5259]
For the Workbench preview of Positron, any additional changes needed to be made to Positron 2024.11 will be made on the `prerelease/2024.11` branch first, so we should update the version on this branch to reflect it would be patch 1 of this series to form 2024.11.1 builds.

**Comment by petetronic** [comment]
Changes made to this prerelease branch should then be forward merged to main.

**Comment by jonvanausdeln** [comment]
Not sure how to verify this until we get a build.

**Comment by jonvanausdeln** [comment]
I see the new version build now!
