### ISSUE TITLE
2024.12 Pre-Release Plan

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#5260]
## Target Dates
* Kick-off: 2024-10-31
* December Pre-Release: 2024-12-04

## Core and Posit Workbench stability

* #5228 
* https://github.com/posit-dev/positron/issues/4925
* https://github.com/posit-dev/positron/issues/5187
* https://github.com/posit-dev/positron/issues/5262

## Quarto and UI
* https://github.com/posit-dev/positron/issues/2085
* https://github.com/posit-dev/positron/issues/4858

## ARK
* https://github.com/posit-dev/positron/issues/5264

## Connections Pane
* https://github.com/posit-dev/positron/issues/2925
* Experimental Connections Pane <--> Data explorer

**Comment by juliasilge** [comment]
As we wrap up this milestone, some notable successes include finishing up our current Quarto work, major progress in our new formatter for R, and making some important fixes for Workbench. Some misses this milestone that are getting moved forward to our December work for 2025.01 include the challenging merge of VS Code 1.95 and the new editor action bar.
