### ISSUE TITLE
Use new Jupyter supervisor by default in desktop mode

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#5262]
Currently, the experimental Jupyter kernel supervisor ("Kallichore") is used as the default in Positron Workbench, but we use a totally different supervisor (the "Jupyter Adapter") by default in Positron Desktop. We should make the new supervisor the default in Positron Desktop, too; it is expensive to maintain two different supervisors, and the old supervisor has some known issues we don't plan to fix.

Details:

- The old supervisor should remain in place for awhile so we can have folks revert to it for debugging purposes (i.e. if they are seeing a problem, we need to be able to tell if it is caused by the new supervisor or is unrelated.)
- Logs for the new supervisor need to be moved out of a terminal and into an Output tab so they can be collected by desktop users for issue reporting.
- The codename "Kallichore" needs to be eliminated (in settings, etc.) now that the supervisor is mature enough to be the default. We should just call it the "Jupyter supervisor" or similar in the UI, and may also want to rename the extension itself for clarity.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-23
    OS Version          : ubuntu, osx, windows

### Test scenario(s) 

Looking good locally and in automation runs

Link(s) to TestRail test cases run or created:
