### ISSUE TITLE
R: Navigating to assigned objects

### ISSUE THREAD

**Issue by lionel-** [posit-dev/positron#5274]
The new OO system S7 (https://github.com/RConsortium/S7)  is currently not well supported by Positron's navigation features. See here for an example usage: https://github.com/tidyverse/elmer/blob/a7b55f39890a544d0d2897ca3a357b6dbfa4e70b/R/provider.R#L15-L39

The main reason for this lack of support is that we currently only index functions as workspace symbols. Since S7 generics and classes are not functions, they are currently not indexed.

What's missing:

- For classes and generics: Go to symbol
- For classes and generics: Go to definition
- For generics: Go to implementations (to find `method(gen, class) <-` calls)

Since generics and classes are simple objects, a general way to fix this would be to index all assigned objects, including e.g. data frames and vectors. This would improve the experience in user scripts as users will be able to navigate to these objects using "Go to" commands.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.12.0-44](https://github.com/posit-dev/positron-builds/releases/tag/2024.12.0-44)
OS Version(s) :  Windows 11

### Test scenario(s) 

Verified symbols/references can be found in 
* Nominal case `x <-1`
* More complicated methods & objects as mentioned in the issue description.

### Link(s) to TestRail test cases run or created: 

None
