### ISSUE TITLE
Backport #5187 to 2024.11.1 Pre-Release Patch

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#5281]
Backport #5187 to the [2024.11.1 Pre-Release Patch](https://github.com/posit-dev/positron/milestone/16).

## QA Notes
Please verify the fix in a build from the https://github.com/posit-dev/positron/tree/prerelease/2024.11 branch.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.11.1-4](https://github.com/posit-dev/positron-builds/releases/tag/2024.11.1-4)
Workbench Version(s):[2024.12.0-daily+364.pro2](https://dailies.rstudio.com/version/2024.12.0-daily+364.pro2)
OS Version(s) : Ubuntu 24

### Test scenario(s) 
fastapi tests run as expected.

### Link(s) to TestRail test cases run or created:
