### ISSUE TITLE
Merge upstream vscode-server changes (2024.11.1 / Kousa Dogwood)

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#5282]
The upstream merge will include a workbench extension version bump to bring in https://github.com/rstudio/rstudio-workbench-vscode-ext/issues/269 as well as some session-related fixes from https://github.com/rstudio/vscode-server/pull/142.

- [x] merge upstream changes into positron [prerelease/2024.11](https://github.com/posit-dev/positron/tree/prerelease/2024.11) branch @melissa-barca https://github.com/posit-dev/positron/pull/5293
- [x] cherry-pick the upstream changes into positron `main` as well @sharon-wang https://github.com/posit-dev/positron/pull/5298

**Comment by sharon-wang** [comment]
## QA Notes

On the `main` and `prerelease/2024.11` branches:
- please confirm that the version of the Workbench extension bundled with reh-web/workbench Positron is now version `1.5.16`
    - the fix in the Workbench extension itself can only be tested in Positron on Workbench and is covered in https://github.com/rstudio/rstudio-workbench-vscode-ext/issues/269
- other changes are not yet verifiable as some state management pieces are in progress in Workbench

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.11.1-4](https://github.com/posit-dev/positron-builds/releases/tag/2024.11.1-4)
Workbench Version(s):[2024.12.0-daily+364.pro2](https://dailies.rstudio.com/version/2024.12.0-daily+364.pro2)
OS Version(s) : Ubuntu 24

### Test scenario(s) 

Posit workbench extension now at `1.5.16`

### Link(s) to TestRail test cases run or created:
