### ISSUE TITLE
R Console: Shutdown error when attempting to restart console

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#5285]
#### Positron and OS details:

Various versions, post inclusion of Kallichore for web.
(Web only issue)

#### Interpreter details:

R 4.4.0

## Describe the issue:

Smoke tests fail during attempt to restart R post shutdown with:

![Image](https://github.com/user-attachments/assets/513930bb-c9b8-4fa7-9a59-692493e712fd)

[r-console.test.js.zip](https://github.com/user-attachments/files/17652776/r-console.test.js.zip)

## Steps to reproduce the issue:

1. Run the R console smoke test many times (not sure if there is an easier way)
2. Observe occasional failure

## Expected or desired behavior:

Should be possible to restart R post shutdown

## Were there any error messages in the UI, Output panel, or Developer Tools console?

 ERR An unknown error occurred. Please consult the log for more details.

**Comment by jmcphers** [comment]
Triage: Seems to be failing ~25% of the time. We either need to address this or disable the test.

**Comment by jonvanausdeln** [comment]
We are no longer seeing this in CI
