### ISSUE TITLE
Variable Label Viewer

### ISSUE THREAD

**Issue by yihunzeleke** [posit-dev/positron#5288]
#### Interpreter details:

Variable Label 

## Describe the issue:
**RStudio** has a feature to view the labels of variables in the data viewer. However, ***Positron*** doesn't show the variable label; instead, it shows the variable type *str, int*.  

## Steps to reproduce the issue:

```{r}
mtcars_df <- mtcars
data_dict_cars  <- data.frame( Variable_Names = names(mtcars_df), Vaiable_Label = names(mtcars_df))


dict_labels <- data_dict_cars |> 
  deframe() |> 
  as.list()

mtcars_df_with_label <- mtcars_df |> 
  labelled::set_variable_labels(.labels = dict_labels, .strict = FALSE) 

mtcars_df_with_label |>
View()
```
## Expected or desired behavior:
![Image](https://github.com/user-attachments/assets/84d5894d-fdbe-4fd6-bd10-b84d4861105c)

***RStudio*** dataframe viewer 

## Were there any error messages in the UI, Output panel, or Developer Tools console?
```{r}
mtcars_df <- mtcars
data_dict_cars  <- data.frame( Variable_Names = names(mtcars_df), Vaiable_Label = names(mtcars_df))


dict_labels <- data_dict_cars |> 
  deframe() |> 
  as.list()

mtcars_df_with_label <- mtcars_df |> 
  labelled::set_variable_labels(.labels = dict_labels, .strict = FALSE) 

mtcars_df_with_label |>
View()
```
![Image](https://github.com/user-attachments/assets/a0cbfe8c-3295-4a1a-8144-6d03cf90ebad)

***Positron*** Data Explorer viewer

**Comment by jmcphers** [comment]
Thanks for reporting this! We're tracking this feature request in https://github.com/posit-dev/positron/issues/2971.
