### ISSUE TITLE
F1 to bring up Python Help hangs runtime

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#5290]
#### Positron and OS details:

Positron Version: 2024.11.0 (Universal) build 140
Code - OSS Version: 1.93.0
Commit: e0d844b031f95acbf89f234a2cce2af9b6721f6c
Date: 2024-10-31T14:24:19.540Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

#### Interpreter details:

From what I can tell, any Python runtime

## Describe the issue:

Help works if invoked from the console by the magic `?`, but if you use <kbd>F1</kbd> it hangs the runtime in a busy state.

## Steps to reproduce the issue:

1. Have some Python code, such as:

```python
import numpy as np
rng = np.random.default_rng()
```

2. Use <kbd>F1</kbd> to try to bring up help for some bit of code.
3. The Python runtime hangs indefinitely:

![Image](https://github.com/user-attachments/assets/d5333651-4b5a-43f2-92c1-1fa76b0a1717)

This does not happen for R; that is working correctly.

## Expected or desired behavior:

I am fairly sure we had <kbd>F1</kbd> working for both R and Python at some point, although we have had trouble in the past i.e. https://github.com/posit-dev/positron/issues/2523.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

I don't believe so

**Comment by juliasilge** [comment]
We should write a smoke text for this, because we have broken <kbd>F1</kbd> multiple times.

**Comment by isabelizimm** [comment]
If it's helpful for debugging I am not seeing a full breakage, but rather:

```
An error occurred while looking up the help topic: ValueError: `column` parameter (11) is not in a valid range (0-0) for line 285 ('\n').
```

on `Positron Version: 2024.11.0 (Universal) build 140`

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : Main on 11/19/24 with automation
    OS Version          : OSX, ubuntu

### Test scenario(s) 

Added passing automated test case

Link(s) to TestRail test cases run or created:
