### ISSUE TITLE
Errors don't stop queued cell executions

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#5295]
#### Positron and OS details:

Positron Version: 2024.12.0 (Universal) build 12
Code - OSS Version: 1.93.0
Commit: 13986d5fa2eb2ecb7580d62a9e91aa76ab7e87ce
Date: 2024-11-07T02:43:29.573Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

#### Interpreter details:

Any.

## Describe the issue:

Errors don't stop queued cell executions. This is a regression of #1624.

## Steps to reproduce the issue:

1. Create a notebook with the following cells: `import time; time.sleep(3); raise Exception` and `print()`.
2. Quickly run both cells in order (e.g. by selecting the first and quickly pressing Shift+Enter twice).
3. The second will show as "successful" (the ✔️ icon), but it should show as unevaluated.

## Expected or desired behavior:

An error in a cell should stop any queued cell executions.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-23
    OS Version          : OSX

### Test scenario(s) 

Verified with repro instructions

Link(s) to TestRail test cases run or created:
