### ISSUE TITLE
Changing a notebook's Python interpreter also changes the console's

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#5305]
#### Positron and OS details:

Positron Version: 2024.12.0 (Universal) build 12
Code - OSS Version: 1.93.0
Commit: 13986d5fa2eb2ecb7580d62a9e91aa76ab7e87ce
Date: 2024-11-07T02:43:29.573Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
#### Interpreter details:

Any Python interpreter.

## Describe the issue:

Changing the Python kernel for a notebook also changes the selected kernel for the console.

## Steps to reproduce the issue:

1. Open a Jupyter notebook.
2. Change the selected kernel to another Python kernel.
3. The console's interpreter will also change.

## Expected or desired behavior:
The console interpreter should be unaffected by notebooks.

## Were there any error messages in the UI, Output panel, or Developer Tools console?
Nope.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-23
    OS Version          : OSX

### Test scenario(s) 

<!-- List the testing steps for verification.

Changing notebook interpreter does not also change console interpreter.

Link(s) to TestRail test cases run or created:
