### ISSUE TITLE
Notebooks use the globally preferred interpreter rather than the last used

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#5310]
#### Positron and OS details:

Positron Version: 2024.12.0 (Universal) build 12
Code - OSS Version: 1.93.0
Commit: 13986d5fa2eb2ecb7580d62a9e91aa76ab7e87ce
Date: 2024-11-07T02:43:29.573Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
#### Interpreter details:

Any.
## Describe the issue:
Notebooks use the globally preferred interpreter rather than the last used.

## Steps to reproduce the issue:

1. Open a notebook. Select an interpreter for the notebook.
2. Select a different interpreter for the language in the console.
3. Close and reopen the notebook. It'll use the console's interpreter.

## Expected or desired behavior:
The notebook should use the last used interpreter for the notebook.

## Were there any error messages in the UI, Output panel, or Developer Tools console?
No.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-23
    OS Version          : OSX

### Test scenario(s) 

Verified according to filing instructions.

Link(s) to TestRail test cases run or created:
