### ISSUE TITLE
New Editor Action Toolbar provides existing editor actions, including editor actions from extensions

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#5316]
The experimental Editor Action Bar was first added in https://github.com/posit-dev/positron/pull/5181, and is currently off by default.

One of the first steps for this Editor Action Bar is to mirror existing editor actions, including both ones that are contributed by Positron itself and by extensions.

For this first step, we should expect

- editor actions for `.R` and `.py` files to be consistent on the new bar compared to their original location, including their behavior
- editor actions for Quarto files and Shiny apps (when the Shiny extension is installed) to be consistent on the new bar with previous behavior/appearance

**Comment by midleman** [comment]
### Verified Fixed
Positron Version(s) : 2024.12.0 - 77
OS Version(s) : MacOS

### Test scenario(s) 

Ran through multiple scenarios (`.py`, `.r`, `.html`, `.qmd`), etc and found a handful issues. All of have been tagged for 2025.01 release.
https://github.com/posit-dev/positron/issues/5498
https://github.com/posit-dev/positron/issues/5500
https://github.com/posit-dev/positron/issues/5501

Using this ticket as a check point and will be re-validated after updates have been made. Closing out.

### Link(s) to TestRail test cases run or created:
