### ISSUE TITLE
Positron Pane Layout

### ISSUE THREAD

**Issue by cordeiroitamar** [posit-dev/positron#5317]
Hello everyone,

I'm starting with Positron and would like to know if there's a way to rearrange the panels, as we do in RStudio (Tools > Global Options > Pane Layout), to set up the layout as follows:

Top left: Console
Top right: Source
Bottom left: Environment
Bottom right: Plots

**Comment by juliasilge** [comment]
The layout in Positron doesn't work exactly the same as in RStudio; in fact, it is very flexible and you can drag stuff around with a lot of freedom. We have made some layout presets available from the command palette and the top right of the top bar:

![Image](https://github.com/user-attachments/assets/b9b2fd78-9185-4bb7-812f-8eb887e32d39)

You may want to start with "Side-by-side" and then change the Primary Side Bar position to the left. That gets you this:

![Image](https://github.com/user-attachments/assets/d430b64e-67cf-46e6-b2d9-f4d74c82e87a)

**Comment by LDalby** [comment]
Uhh, this so close to how I been trying to set my workspace up also! But I simply can't figure out how to this pane layout, but with the file explorer, git, extensions etc. (what in @juliasilge's screenshot is the blue ribbon in the RHS) appear on the left. 
Can this be done?

**Comment by cordeiroitamar** [comment]
Great. Thank you @juliasilge 

It worked. It turned out exactly the way I wanted.


![Image](https://github.com/user-attachments/assets/1e32c9c0-eb4c-446d-a69d-c2867eae800e)

**Comment by juliasilge** [comment]
Glad this works for you @cordeiroitamar!

Unfortunately @LDalby I don't believe there is a way to switch right-to-left for the main editing area plus the secondary side bar (holding the plots, console, etc in this layout) without _also_ moving the activity bar (blue ribbon with file explorer, etc) to the right.
