### ISSUE TITLE
Python extension: Stop logging environment variables

### ISSUE THREAD

**Issue by petetronic** [posit-dev/positron#5320]
There should be a way to opt in to the logging of environment variables in the python extension initialization.

Update this to not dump the environment by default:
https://github.com/posit-dev/positron/blob/3a8dbb149949148cc30924bbb7ae242991107eac/extensions/positron-python/src/client/common/variables/environmentVariablesProvider.ts#L75

**Comment by jmcphers** [comment]
We also need to address this in the kernel supervisor, since by default it logs all the metadata used to start a session (which includes an environment dump from positron-python, since positron-python forwards a huge number of env vars by default)

**Comment by petetronic** [comment]
Addressed the logging from the positron-python extension, but will sync up with you on the kernel supervisor next.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-80
    OS Version          : OSX

### Test scenario(s) 

Do not see env vars logged to `Python A.B.C:  Console`

Link(s) to TestRail test cases run or created:
