### ISSUE TITLE
R first

### ISSUE THREAD

**Issue by drbenedictpaul** [posit-dev/positron#5325]
Type: <b>Feature Request</b>

Hi,

The interface is really superb. I have a suggestion though.

When we select the dropdown at the right top corner, it lists Python and R. But, because posit is originally an R company, I suggest that R be loaded first in the list.

Thanks.

VS Code version: Positron 1.93.0 (e0d844b031f95acbf89f234a2cce2af9b6721f6c, 2024-10-31T14:13:53.873Z)
OS version: Linux x64 6.6.50-05083-g5a8e7e69b744
Modes:

**Comment by juliasilge** [comment]
I don't think we're likely to invest in the short term in making this menu, say, responsive to the last interpreter you chose or similar. However, we do have https://github.com/posit-dev/positron/issues/3575 where we are tracking an easy way to disable a certain language, for example, to disable Python if you are solely an R user.

As a workaround for now, you can disable the Python extension in Positron from the Extensions tab, and then you won't see Python interpreters at all:

![Image](https://github.com/user-attachments/assets/7712da46-c5ad-4954-90fa-1cd01109421e)

**Comment by drbenedictpaul** [comment]
Ok. Thank you
Dr. Benedict Paul C
​BSc (Medical Lab Technology), MSc ​(​Biotech​)​, PhD
Assistant Professor
Dept of Biotechnology
Faculty of Biomedical Sciences & Technology
Sri Ramachandra Institute of Higher Education and Research
Porur, Chennai - 600116.
Tamilnadu, India.
Website: www.drpaul.cc
Mobile/WhatsApp: +91 7010972354
