### ISSUE TITLE
Key bindings does not work in console

### ISSUE THREAD

**Issue by EdenGoldfarb** [posit-dev/positron#5330]
Positron Version: 2024.11.0 (system setup) build 140
Code - OSS Version: 1.93.0
Commit: e0d844b031f95acbf89f234a2cce2af9b6721f6c
Date: 2024-10-31T14:14:22.699Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

R 4.4.2

**Key bindings such as "Insert the pipe operator" does not work in console.**

{
  "key": "ctrl+shift+m",
  "command": "r.insertPipeConsole",
  "when": "editorTextFocus && editorLangId == 'quarto' || editorTextFocus && editorLangId == 'r'"
}

Can this be locally fixed through changing When Expression?

Many thanks.

**Comment by juliasilge** [comment]
We aren't able to reproduce this on our end in the R console, including on Windows. We do contribute the keybinding for the console specifically, with `"when": "editorLangId == r"`:

https://github.com/posit-dev/positron/blob/d753d0dce92a116a0c6fe6e70cf7822b8e4243a2/extensions/positron-r/package.json#L379

Could you say in more detail what your setup is like and what steps you are taking?

**Comment by EdenGoldfarb** [comment]
Windows 11 pro 10.0.22631 Build 22631
I'm simply trying to insert a pipe "|>" using the key binding "ctrl+shift+m.". While I can insert it in the main editor (R, QMD), nothing happens when I try it in the CONSOLE. 

I hope the snip below will help. 
what other details should provide?

![Image](https://github.com/user-attachments/assets/dac04501-8006-4722-b86a-521de68a1872)

**Comment by juliasilge** [comment]
Wow, so strange! Can you try this for us:

- Run "Developer: Toggle Developer Tools" from the command palette and open up the developer tools console
- Run "Developer: Inspect Context Keys" from the command palette (this will bring up a red highlight area that will move with your mouse)
- Click in the R console:

![Image](https://github.com/user-attachments/assets/707a360a-4c86-4d91-9edd-b2b34be39d2e)

This will bring print some output in the developer tools console that you can click to expand. It will show you _all_ the context keys that are set, and we are particularly interested in finding what you have for `positronConsoleFocused`. I have `positronConsoleFocused: true`, which is what is expected here and [what makes the command available](https://github.com/posit-dev/positron/blob/461485e83d704c615a498e196c4ec55a78015322/extensions/positron-r/package.json#L43):

![Image](https://github.com/user-attachments/assets/bfe73d72-aae5-4b20-96b9-6be37db6e5a5)

**Comment by EdenGoldfarb** [comment]
Well, it is also set to "true"  - 


![Image](https://github.com/user-attachments/assets/05a6ef00-248b-43ca-9b5f-81fe30ab7016)

**Comment by juliasilge** [comment]
Can you successfully clear the console via <kbd>Ctrl</kbd>+<kbd>L</kbd> and/or paste into the console via <kbd>Ctrl</kbd>+<kbd>V</kbd>? Those are other keybindings that are set to apply only when `PositronConsoleFocused`.

**Comment by jennybc** [comment]
I'm wondering if someone else (eg an extension) is squatting on the keyboard shortcut.

Go to the command pallette and do *Preferences: Open Keyboard Shortcuts*.

Click on the little keyboard icon and then use the shortcut of interest (ctrl + shift + m, in your case, cmd + shift + m, in my case). What do you see? Here's what I see:

![Image](https://github.com/user-attachments/assets/09e9b839-2101-4859-a847-6642c357764e)

**Comment by EdenGoldfarb** [comment]
> Can you successfully clear the console via Ctrl+L and/or paste into the console via Ctrl+V? Those are other keybindings that are set to apply only when `PositronConsoleFocused`.

Yes, clearing and pasting do work.


> I'm wondering if someone else (eg an extension) is squatting on the keyboard shortcut.
> 
> Go to the command pallette and do _Preferences: Open Keyboard Shortcuts_.
> 
> Click on the little keyboard icon and then use the shortcut of interest (ctrl + shift + m, in your case, cmd + shift + m, in my case). What do you see? Here's what I see:
> 
> ![Image](https://github.com/user-attachments/assets/09e9b839-2101-4859-a847-6642c357764e)


![Image](https://github.com/user-attachments/assets/89e5f05e-224d-443f-bfb0-0d3a7b720051)


Seems ok to me.

**Comment by EdenGoldfarb** [comment]
> Can you successfully clear the console via Ctrl+L and/or paste into the console via Ctrl+V? Those are other keybindings that are set to apply only when `PositronConsoleFocused`.

Yes, clearing and pastid do work in console.



> I'm wondering if someone else (eg an extension) is squatting on the keyboard shortcut.
> 
> Go to the command pallette and do _Preferences: Open Keyboard Shortcuts_.
> 
> Click on the little keyboard icon and then use the shortcut of interest (ctrl + shift + m, in your case, cmd + shift + m, in my case). What do you see? Here's what I see:
> 
> ![Image](https://github.com/user-attachments/assets/09e9b839-2101-4859-a847-6642c357764e)


![Image](https://github.com/user-attachments/assets/0a4a496b-8f72-4fa5-82b5-6c730d794a70)

Seems ok,

**Comment by jennybc** [comment]
Your screenshot shows that the keybinding for inserting the pipe operator in the Console is missing! From my screenshot, that's the one where the When clause starts like `positronConsoleFocused && ...`. So that is the real problem. I can't immediately think of a reason that the other commands would successfully register, but this one would not 🤔

**Comment by juliasilge** [comment]
"View: Toggle Problems" is also missing, and that one is contributed by VS Code itself! 😱 

@EdenGoldfarb have you done anything to remove keybindings, like [this](https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule)? Can you share what's in your `settings.json` and especially `keybindings.json`?

**Comment by EdenGoldfarb** [comment]
@juliasilge, I haven't done anything like that.

> "View: Toggle Problems" is also missing, and that one is contributed by VS Code itself! 😱
> 
> [@EdenGoldfarb](https://github.com/EdenGoldfarb) have you done anything to remove keybindings, like [this](https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule)? Can you share what's in your `settings.json` and especially `keybindings.json`?


![Image](https://github.com/user-attachments/assets/9a13ecce-7d21-4ba3-a4b8-e6230fd5ab7a)

**Comment by EdenGoldfarb** [comment]
update: 
Normal Windows uninstalling and installing again didn't help, as uninstalling won't remove many registry leftovers.

I used Revo Uninstaller to completely remove Positron and reinstalled it and the issue was fixed. 

I'm going to reinstall all extensions that were previously installed and see if any lead to that bug.

Thank you both for the input and help.

**Comment by juliasilge** [comment]
Ah, see in your `keybindings.json` where it has `-r.insertPipeConsole`? With the `-`? This was the problem; at some point (probably by accident) you did something that removed this keybinding. You can get back to the default state by removing this entry from that JSON.
