### ISSUE TITLE
Add Positron context key

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#5339]
## Background
We currently set `POSITRON=1` in our Terminals, but there are areas where we may want to interface with a context key instead of an environment variable to determine that we're running in Positron.

For example, `when` clauses could make use of an `isPositronContext` context key to enable contributions:

https://github.com/posit-dev/positron/blob/d753d0dce92a116a0c6fe6e70cf7822b8e4243a2/extensions/positron-python/package.json#L89-L96

Similarly, `enablement` clauses could leverage the context key.

https://github.com/posit-dev/positron/blob/d753d0dce92a116a0c6fe6e70cf7822b8e4243a2/extensions/positron-python/package.json#L302-L308

Extensions may want to contribute commands or UI based on if the extension is run in Positron or not.

## Proposal

- Create a new context key, such as `IsPositron` or `IsPositronContext` 
    - Maybe here? https://github.com/posit-dev/positron/blob/main/src/vs/platform/contextkey/common/contextkeys.ts
- These files are also related:
    - https://github.com/posit-dev/positron/blob/main/src/vs/workbench/browser/contextkeys.ts
    - https://github.com/posit-dev/positron/blob/main/src/vs/workbench/common/contextkeys.ts

## Notes

- where we set `POSITRON=1`
    https://github.com/posit-dev/positron/blob/d753d0dce92a116a0c6fe6e70cf7822b8e4243a2/src/vs/platform/terminal/node/terminalEnvironment.ts#L144-L153
    - Search for `'POSITRON': '1'` for other instances where we set the environment variable
    - Extensions such as Quarto and Workbench use this environment variable to check if the extensions are running in Positron to apply customized behaviour.
- https://code.visualstudio.com/api/references/when-clause-contexts

**Comment by juliasilge** [comment]
Related to https://github.com/posit-dev/positron/issues/526, and maybe a better way to address that need than something in the Positron API

**Comment by timtmok** [comment]
Note: Testing the context key is tough when no extensions use it. However, there will be a unit test that covers it. QA could add a custom test extension later if desired.

**Comment by timtmok** [comment]
I'll also open a PR to update the website so others know how to write an extension to use the context key.

**Comment by juliasilge** [comment]
When this is verified in a release build, we should merge https://github.com/posit-dev/positron-website/pull/27.

**Comment by jonvanausdeln** [comment]
Unit tests have been passing.  In the future we will look at creating a tests extension to further tests api related issues like this.
