### ISSUE TITLE
Interpreter fails to restart

### ISSUE THREAD

**Issue by jonvanausdeln** [posit-dev/positron#5356]
#### Positron and OS details:

On current `main` branch, Ubuntu 22

## Describe the issue:

In some CI smoke tests the interpreter fails to restart. It appears to just hang. We see this in both R & Python

Run with  R failure: https://github.com/posit-dev/positron/actions/runs/11821042852/
Run with Python failure: https://github.com/posit-dev/positron/actions/runs/11821745434/job/32937189702

Seems to occur most frequently in R console test.
 
![Image](https://github.com/user-attachments/assets/af73ccfe-7e9e-48b6-8c60-f95eff5926ba)

## Steps to reproduce the issue:

The beginning of most tests, restart/start up the interpreter.  The failure appears during this step.

## Expected or desired behavior:
Interpreter to restart

## Were there any error messages in the UI, Output panel, or Developer Tools console?

We didn't see anything pertinent in the logs, but they are attached to the above mentioned CI runs.

### !!! QA NOTES !!! 
[R console restart tests](https://github.com/posit-dev/positron/blob/64e113ad734224951ba51501fe4def732ed3e9ab/test/smoke/src/areas/positron/console/r-console.test.ts) are turned off due to this (https://github.com/posit-dev/positron/pull/5371)
Please remember to turn back on when this is fixed.

**Comment by jonvanausdeln** [comment]
I just tried to manually restart R on my windows box, with `main` build.  It just hangs.

![Image](https://github.com/user-attachments/assets/9111f69e-10f6-47d3-a261-c725231a3cfd)

**Comment by jonvanausdeln** [comment]
Same is true for [2024.12.0-23](https://github.com/posit-dev/positron-builds/releases/tag/2024.12.0-23) .. R won't restart, just hangs

**Comment by jonvanausdeln** [comment]
Starting with [2024.12.0-18](https://github.com/posit-dev/positron-builds/releases/tag/2024.12.0-18) on windows, I can't restart R in the console (same behavior as above)

**Comment by jonvanausdeln** [comment]
Just an FYI.. I'm holding off promoting any more builds/releases from `main` until this gets in.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-41
    OS Version          : OSX

### Test scenario(s) 

Verified with automation on main same day as 41 release was made.

Link(s) to TestRail test cases run or created:
