### ISSUE TITLE
Not possible to open same folder twice

### ISSUE THREAD

**Issue by JosiahParry** [posit-dev/positron#5395]
#### Positron and OS details:

Positron Version: 2024.09.0 (Universal) build 27
Code - OSS Version: 1.92.0
Commit: d996153f3be6bcc9af460300e61103425323b973
Date: 2024-09-11T02:38:46.408Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

## Describe the issue:

I want to be able to open the same folder twice. 

## Steps to reproduce the issue:

Open a folder in positron

1. cmd + shift + n
2. select the folder that is already open from top right drop down
3. observe the active window switch to the same project
4. go back to the new empty window
5. open command prompt go to File: open folder
6. select the folder that is already open
7. observe active window switch to the already open project

## Expected or desired behavior:

Much like RStudio I would like to be able to have another session open for the same folder. This will let me run multiple tests for the same project. 

Alternatively, if i could have multiple interpreters that may satisfy the need.

**Comment by isabelizimm** [comment]
Thank you so much for this feedback 🙌 fwiw: the "only one folder open at a time" behavior is something inherited from VSCode, but we do have plans for multi-interpreter sessions!

**Comment by juliasilge** [comment]
We're tracking the need for multiple consoles/interpreters (like for running multiple tests) in https://github.com/posit-dev/positron/issues/3173, and for now if you want to have multiple instances of a workspace, go ahead and use "Duplicate as Workspace".
