### ISSUE TITLE
Execute Current Code Block Without Selection

### ISSUE THREAD

**Issue by cordeiroitamar** [posit-dev/positron#5448]
Hello,

I noticed a difference in behavior between Positron and RStudio regarding code execution in an "R File", which has impacted my workflow.

In RStudio, if I place the cursor anywhere within a code block (even at the end of a line with a pipe operator |>), I can execute the entire block by pressing Ctrl + Enter, without needing to manually select all the lines.

In Positron, however, when working in an "R File", if I place the cursor at the end of a line with a pipe operator and press Ctrl + Enter, I get an error

To make it work in Positron, I must manually select the entire block before pressing Ctrl + Enter.

Would it be possible to implement a behavior similar to RStudio's, where the entire block of code is executed automatically based on the cursor's position in an "R File"?

**Comment by juliasilge** [comment]
Can you share some example R code where you are not seeing a statement being detected as you expect? We do expect <kbd>Cmd/Ctrl</kbd>+<kbd>Enter</kbd> to detect the current statement in an `.R` file and then send it to a console, so if you are observing a problem, it would be great to have some details. Thanks!

**Comment by cordeiroitamar** [comment]
Ok! Everything is working perfectly. I had to close and reopen Positron to create an example, and everything worked fine.  
It must have been some bug from having Positron open for several days (including closing and reopening the laptop).  
Sorry about that.  
Best regards.
