### ISSUE TITLE
Simple Gradio sample crashes after loading

### ISSUE THREAD

**Issue by testlabauto** [posit-dev/positron#5459]
#### Positron and OS details:

Positron Version: 2024.12.0 (Universal) build 41
OSX

#### Interpreter details:

Python 3.10.12

## Describe the issue:

This simple Gradio sample no longer stays running:
```
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
demo.launch()   
```

It dies with:
```
~/.pyenv/versions/3.10.12/bin/python /Users/christophermead/posit/qa-example-content/workspaces/python_apps/gradio_example/gradio_example.py
(base) ➜  qa-example-content ~/.pyenv/versions/3.10.12/bin/python /Users/christophermead/posit/qa-example-content/workspaces/python_apps/gradio_example/gradio_exam
ple.py
* Running on local URL:  http://127.0.0.1:7860
Traceback (most recent call last):
  File "/Users/christophermead/posit/qa-example-content/workspaces/python_apps/gradio_example/gradio_example.py", line 5, in <module>
    demo.launch()
  File "/Users/christophermead/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gradio/blocks.py", line 2582, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.
```

## Steps to reproduce the issue:

1. Run simple Gradio sample above
2. Note that it will run but will quickly die

## Expected or desired behavior:

Gradio continues to run.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Did not see any

**Comment by sharon-wang** [comment]
Yeah, looks like https://github.com/gradio-app/gradio/pull/9822 is causing the relative CSS paths to be used instead of an absolute path, which we rely on. I reverted the change in https://github.com/gradio-app/gradio/pull/9822 by modifying the minified JS in the gradio libary in my venv and the CSS loads from the correct absolute path.

**Comment by sharon-wang** [comment]
Opened PR: https://github.com/posit-dev/positron/pull/5590, but keeping it as a draft, as we'll need to wait on the release of `gradio@5.8.0`.

**Comment by juliasilge** [comment]
Just so I am clear, does this mean that Positron will work with newer versions of gradio but will _not_ work with older versions of gradio?

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-50
    OS Version          : OSX

### Test scenario(s) 

Gradio app no longer crashing locally or in CI.  Tested with newest and second newest gradio versions as of today.

Link(s) to TestRail test cases run or created:
