### ISSUE TITLE
Restarting a notebook always times out

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#5460]
#### Positron and OS details:

Positron Version: 2024.12.0 (Universal) build 55
Code - OSS Version: 1.93.0
Commit: a181837fc1d5fd55f7ed377d89d3fce286a318d7
Date: 2024-11-22T02:46:25.203Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

#### Interpreter details:

Any.

## Steps to reproduce the issue:

1. Create a notebook of any language and wait for the session to start.
2. Restart the notebook.
3. It'll show a timeout error.

## Expected or desired behavior:
No errors.

## Were there any error messages in the UI, Output panel, or Developer Tools console?
No.

**Comment by midleman** [comment]
#### Verified Fixed
Positron Version(s) : [2024.12.0-80](https://github.com/posit-dev/positron-builds/releases/tag/2024.12.0-80)
OS Version(s) : MacOS

### Test scenario(s) 

Confirmed able to restart notebook without any errors.

### Link(s) to TestRail test cases run or created: 

n/a
