### ISSUE TITLE
Web: scrolling in the Variables view doesn't work

### ISSUE THREAD

**Issue by timtmok** [posit-dev/positron#5473]
#### Positron and OS details:
2024.11.0

#### Interpreter details:

Either Python or R

## Describe the issue:
Create enough variables to cause the Variables view to require scrolling. The view can be shrunk vertically to help achieve this.

```R
x <- 5
xx <- 5
xxx <- 5
yyy <- 5
yy <- 5
y <- 5
z <- 1
zz <- 1
zzz <- 1
```

https://github.com/user-attachments/assets/f1ef17a7-2eca-4bd9-9fdc-627935d16d06

The video attempted to scroll but it only worked by using the scroll bar.

The div that requires scrolling should be wrapped in a Scrollable or listen to the wheel event in order to forward the scroll values.

## Expected or desired behavior:
Scrolling with a mouse wheel works

## Were there any error messages in the UI, Output panel, or Developer Tools console?
none

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.12.0-88 in workbench
    OS Version          : OSX

### Test scenario(s) 

Scrolling works with mouse in variables now.

Link(s) to TestRail test cases run or created:
