### ISSUE TITLE
`?` and `??` should not be detected as syntax errors

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#5483]
#### Positron and OS details:

Positron Version: 2024.12.0 (Universal) build 55
Code - OSS Version: 1.93.0
Commit: a181837fc1d5fd55f7ed377d89d3fce286a318d7
Date: 2024-11-22T02:46:25.203Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

#### Interpreter details:

Any Python.
## Steps to reproduce the issue:

1. Create a Python Jupyter notebook with a cell containing `help?` or `help??`.

The language server diagnostics will show a syntax error on the `?`.

## Expected or desired behavior:
`obj?` and `obj??` are supported by IPyKernel and should not highlight as syntax errors.

## Were there any error messages in the UI, Output panel, or Developer Tools console?
No.

**Comment by seeM** [comment]
`?` and `??` are technically syntax errors in Python scripts since they're IPyKernel extensions, so we may need to special case the fix for notebook sessions.

**Comment by midleman** [comment]
### Verified Fixed
Positron Version(s) : [2025.01.0-32](https://github.com/posit-dev/positron-builds/releases/tag/2025.01.0-32)
OS Version(s) : MacOS

### Test scenario(s) 

Confirmed there is no syntax highlighting.
![Image](https://github.com/user-attachments/assets/131bceb5-9fd9-4aed-8035-b8f2f8b77204)


### Link(s) to TestRail test cases run or created: 

n/a
