### ISSUE TITLE
Very first message when opening Positron: Positron wants to use your confidential information stored in "Positron Safe Storage" in your keychain.

### ISSUE THREAD

**Issue by ASaragga** [posit-dev/positron#5485]

**Comment by jonvanausdeln** [comment]
@ASaragga , thank you for reporting what you are seeing.  Could you please provide some information about your system?  What operating system are you using? What version of Positron are you trying to use? Also could you please provide a screenshot of what you are seeing?

**Comment by ASaragga** [comment]
![Image](https://github.com/user-attachments/assets/6cebb9dc-c6df-408d-a627-38e5a3215735)
Certainly!

Model Name:	MacBook Pro
MacOS: Sequoia version 15.0.1
Chip: Apple M1
Memory:	8 GB
System Firmware Version:	11881.1.1
OS Loader Version:	11881.1.1
Activation Lock Status:	Enabled

Updated Positron to a new version before reading your reply. About which was the version of Positron I was  trying to use  I am unable to get that information, since, apparently and thankfully,  in the present version -  2024.12.0 (Universal) build 41 - this problem does not arise!
  
My present Positron version (no issue) is:
Positron Version: 2024.12.0 (Universal) build 41
Code - OSS Version: 1.93.0
Commit: 39536c265d6828a68291984d0d359170316d055e
Date: 2024-11-18T02:47:29.611Z (1 wk ago)
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

Thank you very much for your quick reply. Congratulations to the Positron Team for all the excellent work they are doing!

**Comment by jonvanausdeln** [comment]
@ASaragga , glad it's working for you now!

**Comment by jonvanausdeln** [comment]
Closing this issue, as it's tracked in a different issue now.
