### ISSUE TITLE
Add clear-output button

### ISSUE THREAD

**Issue by nstrayer** [posit-dev/positron#5492]
The only bulk action button we have at the top of our notebooks is one to run-all cells. Need to add a clear all outputs button as well. 

![Image](https://github.com/user-attachments/assets/d6572a00-dc3e-4dcc-bf3f-f97e30897602)

**Comment by midleman** [comment]
### Verified Fixed
Positron Version(s) : 2024.12.0-88
OS Version(s) : MacOS

### Test scenario(s) 

Confirmed that clearing outputs works as expected (tested, closing/opening notebooks, large file with excessive outputs, etc).

### Link(s) to TestRail test cases run or created:
