### ISSUE TITLE
editor action toolbar [quarto]: `open changes` button doesn't work (visual mode only)

### ISSUE THREAD

**Issue by midleman** [posit-dev/positron#5498]
#### Positron and OS details:

Positron Version: 2024.12.0 (Universal) build 77
Code - OSS Version: 1.93.0
Commit: 4c20d05c4623284f3720deaeb1cec202ef4a0194
Date: 2024-11-25T18:29:19.908Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

## Describe the issue:
In Quarto **Visual Mode (only)** the "Open Changes" button does not work.

## Steps to reproduce the issue:

1. Create and save a new `.qmd` file:
```
---
title: "Dummy QMD File"
author: "A Person"
date: "2024-11-06"
format: html
---
```
2. Select to `Edit in Visual Mode`
4. In default toolbar, click `Open Changes` button
5. VERIFY file changes open without issue - PASS
6. Close file changes
7. In editor action toolbar, click `Open Changes` button 
8. VERIFY file changes open without issue - FAIL## Expected or desired behavior:
`File Changes` button behavior should work in the editor action toolbar.

## Actual Results
`File Changes` button does not work in Editor Action toolbar.

## Expected Results
`File Changes` button behavior should mimic default toolbar.

**Comment by isabelizimm** [comment]
I am able to repro this on `Positron Version: 2025.01.0 (Universal) build 87`, but it seems to be fixed on dev. Let's retry this on the next release!

**Comment by midleman** [comment]
### Verified Fixed
Positron Version(s) : 2025.01.0 (Universal) build 124
OS Version(s) : MacOS

### Test scenario(s) 

Manually verified  `open changes` now works for QMD file.

### Link(s) to TestRail test cases run or created: 

Also added e2e test coverage for this scenario: https://github.com/posit-dev/positron/pull/5836
