### ISSUE TITLE
Ibis expressions are eagerly evaluated

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#5499]
> What I am noticing in positron is that when operating interactively with ibis, positron will eagerly fetch results (i suspect for the data explorer or variable views possibly via a `repr` called somewhere?). This negates one of the key advantages of the whole "lazily executed"  query, especially when building up a complex query because that eager fetch will take quite a bit of time making interactive work much less useful.
> 
> This is reproduced on version [2024.09.0-1](https://github.com/posit-dev/positron/releases/tag/2024.09.0-1).  A good way to see this is run this in a vscode notebook and then run the same notebook in positron. The chunk of code that creates the query below executes much more quickly in vscode. If one comments out this line `ibis.options.interactive = True`, it appears as though `repr` remains fast. However running ibis in interactive mode is definitely the optimal development experience hence reporting this for positron. 

## reprex
```python
import ibis
from ibis import _
import time

ibis.options.interactive = True

con = ibis.duckdb.connect()
taxi = con.read_parquet("s3://voltrondata-labs-datasets/nyc-taxi")

start_time = time.time()
large_parties_with_cash = (
    taxi
    .filter(_.passenger_count > 3)
    .filter(_.payment_type == "Cash")
)
end_time = time.time()

print(f"Run the query in {end_time - start_time:.4f} seconds")
```

_Originally posted by @boshek in https://github.com/posit-dev/positron/discussions/4574_

**Comment by jthomasmock** [comment]
Positron Version: 2024.12.0 (Universal) build 77
Code - OSS Version: 1.93.0
Commit: 4c20d05c4623284f3720deaeb1cec202ef4a0194
Date: 2024-11-25T18:29:19.908Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

I confirmed the reprex is working, albeit with the slower speeds as @boshek indicates.

I'm assuming that this is related to either the variables pane or Data Explorer eagerly evaluating Python objects.

**Comment by boshek** [comment]
Thanks for opening this @jthomasmock. Also seeing https://github.com/posit-dev/positron/issues/5544 which likely is a duplicate.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-32
    OS Version          : OSX

### Test scenario(s) 

Query in initial filing is very fast regardless of interactive setting:
Run the query in 0.0021 seconds

Link(s) to TestRail test cases run or created:

**Comment by jthomasmock** [comment]
@boshek -- do you want to try this out as well? Thanks!

**Comment by boshek** [comment]
@jthomasmock - would love to. Any suggestions on how to build/install a dev version? I am seeing all these [here](https://github.com/posit-dev/positron/tags) post merge but nothing built. Also trying to grok how there is a 2025-01 version already 🤔

**Comment by boshek** [comment]
Can confirm that this fixes my issue. So grateful for this work. Genuine QOL improvement.
