### ISSUE TITLE
Cannot see failures when installing ipykernel

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#5506]
When installing ipykernel, we get this little progress dialog:

![Image](https://github.com/user-attachments/assets/732ee1f4-205e-4023-9601-afbb01641591)

If the installation fails, however, all that you can see is the message "Failed to install ipykernel" in the Console. Since the install can fail for many reasons, this makes ipykernel installation errors difficult to debug.

It's not amazing UX, but one thing we could do to improve this in the short term is use a terminal to show the command we are running to install the kernel and its output. This is an option in the machinery that installs the module:

https://github.com/posit-dev/positron/blob/c3c489641477362638b2a80d94355a86a63eeb21/extensions/positron-python/src/client/common/installer/moduleInstaller.ts#L47

We might set that as the default, or add an option to enable it so we could understand where these failures are coming from.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2024.12.0-96](https://github.com/posit-dev/positron-builds/releases/tag/2024.12.0-96)
Workbench Version(s):
OS Version(s) : 

### Test scenario(s) 

From new Project wizard & creating a new venv.. all show logs in terminal (if "show logs" is clicked in the toast)

### Link(s) to TestRail test cases run or created:
