### ISSUE TITLE
R: Use Posit Package Manger repository on Linux for (at least) Posit Workbench

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#5509]
Positron currently uses Posit's [basic CRAN mirror](https://posit.co/blog/rstudio-cran-mirror/), `cran.rstudio.com`:

```
> getOption("repos")
                       CRAN 
"https://cran.rstudio.com/" 
attr(,"IDE")
[1] TRUE
```

On Linux machines, installing the tidyverse (or any other package that has a lot of native code) from this mirror is extremely time-consuming and requires a system with good compute resources as well as a functioning gcc toolchain, since the mirror contains only the sources.

Posit also maintains a public package manager that contains a CRAN mirror hosting pre-built binaries:

https://packagemanager.posit.co/client/

We should consider using this mirror in Positron, if it's available and the user has not set a different one in e.g. `.Rprofile`.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2025.01.0-32](https://github.com/posit-dev/positron-builds/releases/tag/2025.01.0-32)
Workbench Version(s): 2024.12.0+463.pro4
OS Version(s) : Ubuntu22

### Test scenario(s) 

Tested using default CRAN, and a connect PPM.  Worked as expected.

### Link(s) to TestRail test cases run or created:
