### ISSUE TITLE
viewer: clicking on `open content in editor tab` should focus to editor tab if already open

### ISSUE THREAD

**Issue by midleman** [posit-dev/positron#5527]
#### Positron and OS details:

Positron Version: 2024.12.0 (Universal) build 80
Code - OSS Version: 1.93.0
Commit: c3c489641477362638b2a80d94355a86a63eeb21
Date: 2024-11-26T02:46:47.938Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

## Describe the issue:

The Viewer should behave similarly to the Data Explorer and Plots when they are opened in the editor area. Repeatedly clicking on it should focus the existing tab rather than opening a new one.

## Steps to reproduce the issue:

1. Right-click on any HTML and select Open in Viewer.
2. Verify that the Viewer displays as expected — PASS.
3. Click the `Open the Content in the Editor` button.
4. Verify that the content opens in the editor — PASS.
5. Click the `Open the Content in the Editor` button again.
6. Verify that another editor tab does NOT open — FAIL.

## Expected behavior:

If the content is already displayed in the editor, clicking the button should switch focus to the existing tab instead of opening a new one.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-104
    OS Version          : OSX

### Test scenario(s) 

Verified according to filing steps.

Link(s) to TestRail test cases run or created:
