### ISSUE TITLE
New kernel supervisor handles promises too soon (`r.packageInstall` command is never getting around to `library()` call)

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#5532]
Something has gone wrong with our `r.packageInstall` command. It is supposed to install the local package, restart R, and then load the package via `library()`. The first two happen, but we never get to this:

https://github.com/posit-dev/positron/blob/54cbc06c099bc8910011bc31c3586fb1882d2fd2/extensions/positron-r/src/commands.ts#L102-L105

#### Positron and OS details:

Positron Version: 2024.12.0 (Universal) build 51
Code - OSS Version: 1.93.0
Commit: 59b5b0c3c0a3de2068753811d7b19843d39437cf
Date: 2024-11-21T02:46:07.218Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

#### Interpreter details:

R 4.4.0

## Describe the issue:

We have [a test](https://github.com/posit-dev/positron/blob/main/test/smoke/src/areas/positron/r-pkg-development/r-pkg-development.test.ts) for this command but it tests that R restarts, not all the way to the `library()` call.

_QA Note - might be worth updating the test to check for the library() call_
## Steps to reproduce the issue:

1. Open up an R package as a workspace
2. Run "R: Install R Package and Restart R" from the command palette
3. The R package will get installed locally and R will restart, but no `library()`

## Expected or desired behavior:

We should also run `library()` for the package.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Yep, we see this timeout:

https://github.com/posit-dev/positron/blob/54cbc06c099bc8910011bc31c3586fb1882d2fd2/extensions/positron-r/src/commands.ts#L101

> [Extension Host] rejected promise not handled within 1 second: Timeout while waiting for R to be ready
> ERR Timeout while waiting for R to be ready

**Comment by juliasilge** [comment]
I just did the math on this three times so hopefully I am correct, but the timeout specified in this command is 10 sec, but the extension host is rejecting it after 1 sec.

If I turn the new kernel supervisor _off_, then it works as expected and the timeout is allowed to go until 10 sec as specified.

**Comment by jmcphers** [comment]
A somewhat-recent change to the supervisor is that its start/restart APIs do not return until the start/restart is finished. So (although I have not debugged this) I suspect that the problem here is that the kernel is _already_ `Ready` after a restart, and therefore we're waiting for a `Ready` state change that will never arrive.

If this is the case, we could:
- skip the wait for "ready" entirely, or
- start listening for "ready" _before_ we ask for a restart, or
- check the kernel status to see if it's already "ready" before we start waiting for ready

**Comment by juliasilge** [comment]
I'm moving this back to triage since #5554 is a partial fix and we still observe the same type of problem (never getting to `library()`).

**Comment by midleman** [comment]
### Verified Fixed
Positron Version(s) : [2025.01.0-32](https://github.com/posit-dev/positron-builds/releases/tag/2025.01.0-32)
OS Version(s) : MacOS

### Test scenario(s) 

Confirmed that `library()` now runs after restart as expected.

### Link(s) to TestRail test cases run or created: 

Updated existing test coverage to check for `library()` in the console output: https://github.com/posit-dev/positron/pull/5641
