### ISSUE TITLE
R code formatting

### ISSUE THREAD

**Issue by strengejacke** [posit-dev/positron#5534]
I'm not sure if I'm missing something, but is it possible to format R code? I have enabled settings:

```
  "editor.defaultFormatter": "positron.positron-r",
  "editor.formatOnType": true,
```

And there are some defined keybindings:

![Image](https://github.com/user-attachments/assets/3e29cb8e-f579-47c9-8204-c3da76865570)

But it doesn't seem to work.

## Setup

Positron Version: 2024.12.0 (system setup) build 80
Code - OSS Version: 1.93.0
Commit: c3c489641477362638b2a80d94355a86a63eeb21
Date: 2024-11-26T02:46:23.686Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26100

R 4.4.2

E.g. this code can't be formatted.

```r
data(mtcars)
if(mtcars$mpg>5) {
  print("hi")
}
```

Result in VSCode and RStudio:

```r
data(mtcars)
if (mtcars$mpg > 5) {
  print("hi")
}
```

**Comment by lionel-** [comment]
Do you have styler installed? We currently depend on it (https://github.com/posit-dev/positron/issues/2251).

**Comment by strengejacke** [comment]
Yes:

```r
packageVersion("styler")
#> [1] ‘1.10.3’
```

**Comment by strengejacke** [comment]
This also happens when I press Shift+Alt+F:

![Image](https://github.com/user-attachments/assets/0751b286-1157-43af-b4e7-ca64975a4e85)

**Comment by zwallen** [comment]
I am also running into this problem. I have the same version of `styler` installed as well.

Additionally, when I have my cursor within an R chunk and try to format it via Ctrl + K and then Ctrl + F I get an error message which seems to stem from Quarto (I have it as the default formatter for notebooks).
![Image](https://github.com/user-attachments/assets/a7ed43fb-00be-4c2c-97c0-e9cf927032f8)

The `.vdoc.r` intermediate file is produced but it only shows the code of the chunk as is and additionally shows flags over certain functions like the following
![Image](https://github.com/user-attachments/assets/35951029-d2f8-4003-8b2c-8cda4747efd9)

**Comment by juliasilge** [comment]
I noticed that this report plus #5531 were both on Windows, so I just tried formatting ("Format Document" and "Format Selection") with:

Positron Version: 2024.12.0 (system setup) build 80
Code - OSS Version: 1.93.0
Commit: c3c489641477362638b2a80d94355a86a63eeb21
Date: 2024-11-26T02:46:23.686Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

This did work for me correctly. So no clue yet!

## Question 1

Can you make sure your R kernel log level is debug?

![Image](https://github.com/user-attachments/assets/d5457f30-d347-4f32-bbf9-24b604035603)

And then can try to format and visit the Output channel for "R 4.4.0: Kernel" (or your equivalent) to confirm you don't see any messages like:

> [R]   2024-11-27T21:34:11.410104Z  INFO  Received shell notification: JupyterMessage { zmq_identities: [[112, 111, 115, 105, 116, 114, 111, 110, 45, 115, 104, 101, 108, 108]], header: JupyterHeader { msg_id: "f3039d98-a7db-45ec-aa7a-6b845618e4fb", session: "7348364a16fb77d781f954f7237f3b19", username: "juliasilge", date: "2024-11-27T21:34:11.409Z", msg_type: "comm_msg", version: "5.0" }, parent_header: None, content: CommWireMsg { comm_id: "positron-ui-r-1-408692b6", data: Object {"jsonrpc": String("2.0"), "method": String("call_method"), "params": Object {"method": String("packageVersion"), "params": Array [String("styler"), Null]}} } }
> [R]     at crates/amalthea/src/socket/shell.rs:232
> [R] 
> [R]   2024-11-27T21:34:11.412644Z  INFO  Received shell request: JupyterMessage { zmq_identities: [[112, 111, 115, 105, 116, 114, 111, 110, 45, 115, 104, 101, 108, 108]], header: JupyterHeader { msg_id: "7a2926b4-62d9-42b2-a70f-a84369293e64", session: "7348364a16fb77d781f954f7237f3b19", username: "juliasilge", date: "2024-11-27T21:34:11.412Z", msg_type: "execute_request", version: "5.0" }, parent_header: None, content: ExecuteRequest { code: "styler::style_file('/var/folders/hv/hzsmmyk9393_m7q3nscx1slc0000gn/T/styler-b003adf1-82bb-4929-938e-5ef446e45cea.R')", silent: true, store_history: false, user_expressions: Object {}, allow_stdin: false, stop_on_error: false } }
> [R]     at crates/amalthea/src/socket/shell.rs:185


## Question 2

Can you confirm it is _only_ the formatter that isn't working? We set that up [here](https://github.com/posit-dev/positron/blob/c5ce275dc502f6b15433b271802cb33e1ba5ef68/extensions/positron-r/src/extension.ts#L35), so I'd be interested in knowing if both commands and tasks are provided correctly. Can you confirm that you can successfully use:

- The command "R: New R File"
- Something that is a task, such as "R: Render document with R Markdown"

**Comment by lijiaqi-github** [comment]
I am reporting some of my confirmations here. Sorry I don't quite understand some of the instructions you gave, so I can only confirm the parts I understand.

## Question 1

My previous R kernel log level is warn (default), I change it to info.

I downloaded the R 4.4.0, but I donot know how to visit the Output channel for "R 4.4.0: Kernel" (or your equivalent) . so I cannot confirm this instruction.

## Question 2

I do not have enough knowledge to understand those code you give in that new link. so I cannot comfirm this instruction.
 
But ctrl + shift + n for creating New R File is working for me. Also, ctrl + shift + c  and alt + - are working for me. Those are shortcuts I often used, so I can confirm that they work well.

## Question 3

I turned off kernel supervisor and restarted Positron.

This is my settings.json:, you can find that I changed R kernel log level and turned off kernel supervisor.
> {
>     "workbench.colorTheme": "Default Positron Dark",
>     "quarto.visualEditor.spelling": true,
>     "js/ts.implicitProjectConfig.checkJs": true,
>     "python.analysis.diagnosticMode": "workspace",
>     "git.confirmSync": false,
>     "explorer.confirmDelete": false,
>     "problems.defaultViewMode": "table",
>     "problems.showCurrentInStatus": true,
>     "workbench.editorAssociations": {
>         "*.tiff": "default"
>     },
>     "editor.renderWhitespace": "all",
>     "files.exclude": {
>         "**/*.doc": true,
>         "**/*.docx": true,
>         "**/*.xlsx": true,
>         "**/*.pptx": true,
>         "**/*.pdf": true,
>         "**/*.PDF": true,
>         "**/*.jpg": true,
>         "**/*.png": true,
>         "**/*.tiff": true,
>         "**/*.RData": true,
>         "**/.git": true,
>         "**/.Rproj": true,
>         "**/.Rproj.user": true,
>         "**/.gitignore": true
>     },
>     "editor.autoClosingBrackets": "beforeWhitespace",
>     "editor.autoClosingDelete": "never",
>     "positron.r.pipe": "%>%",
>     "editor.rulers": [
>         80,
>         100
>     ],
>     "editor.minimap.enabled": true,
>     "editor.minimap.maxColumn": 200,
>     "application.experimental.positronPlotsInEditorTab": true,
>     "rstudio.keymap.enable": true,


>     "positron.r.kernel.logLevel": "info",
>     "positronKernelSupervisor.enable": false
> }

Unfortunately, after doing all this, ctrl + shift + a is still not working. Hopefully someone else can bring good news.

**Comment by strengejacke** [comment]
I'm not sure if my keyboard shortcut is recognized at all? I can't "format selection", only the document, which then pop ups the window saying no formatter is installed. Ctrl+Shift+A doesn't do anything.

When I press Ctrl+K, Ctrl+F, it says:
![Image](https://github.com/user-attachments/assets/2fb4c857-4c6c-4a2d-8148-5f233d54c111)

Although this is supposed to happen:
![Image](https://github.com/user-attachments/assets/1d0c6428-2495-425b-84f9-4bcda1d7e236)
![Image](https://github.com/user-attachments/assets/78f597d9-8ac8-4338-bb5c-c6ece3b59cdc)


Question 2: Creating new R files and rendering R markdown works

Question 3: yes, still nothing happens

Question 1: I tried Ctrl+Shift+A, Ctrl+K & Ctrl+F, and Shift+Alt+A, output did not change:

![Image](https://github.com/user-attachments/assets/0bece74d-4c42-4076-95d4-168ac56e9a08)

Here's my settings file:

```
{
  // this is the settings.json file

  // file behaviour
  "files.hotExit": "onExitAndWindowClose",
  "files.defaultLanguage": "r",
  "files.insertFinalNewline": true,
  "files.trimFinalNewlines": true,
  "files.trimTrailingWhitespace": true,
  "positron.r.diagnostics.enable": false,
  "positron.r.kernel.logLevel": "debug",
  "positronKernelSupervisor.enable": false,

  // editor settings
  "editor.fontFamily": "'Fira Code', Consolas, 'Courier New', monospace",
  "editor.fontLigatures": true,
  "editor.guides.bracketPairs": "active",
  "editor.guides.indentation": false,
  "editor.cursorBlinking": "phase",
  "editor.renderWhitespace": "trailing",
  "editor.defaultFormatter": "positron.positron-r",
  "editor.formatOnType": true,
  "editor.rulers": [
    {
      "column": 80,
      "color": "#5a5a5a80"
    }, // right rule
    {
      "column": 95,
      "color": "#5a5a5a30"
    }, // right rule
    {
      "column": 120,
      "color": "#5a5a5a40"
    } // extra right rule
  ],
  "application.experimental.positronPlotsEditor": true,

  // todo tree
  "todo-tree.highlights.customHighlight": {
    "TODO": {
      "background": "#F5910044",
      "foreground": "#fffc00FF"
    },
    "BUG": {
      "icon": "bug",
      "background": "#D3262655",
      "foreground": "#FF3300FF"
    },
    "HACK": {
      "icon": "tools"
    },
    "FIXME": {
      "icon": "flame",
      "background": "#00996844",
      "foreground": "#25D366FF"
    }
  },

  // git settings
  "git.autofetch": true,
  "git.confirmSync": false,
  "git.suggestSmartCommit": false,

  // github settings
  "githubPullRequests.fileListLayout": "tree",
  "githubPullRequests.defaultMergeMethod": "squash",
  "githubPullRequests.pullBranch": "never",
  "githubIssues.queries": [
    {
      "label": "My Issues",
      "query": "is:open assignee:${user} repo:${owner}/${repository}",
      "groupBy": [
        "milestone"
      ]
    },
    {
      "label": "Created Issues",
      "query": "author:${user} state:open repo:${owner}/${repository} sort:created-desc"
    },
    {
      "label": "Recent Issues",
      "query": "state:open repo:${owner}/${repository} sort:created-desc"
    }
  ],

  // Codesnap
  "codesnap.boxShadow": "rgba(0, 0, 0, 0.55) 0px 20px 60px",
  "codesnap.backgroundColor": "#6090a0",
  "codesnap.containerPadding": "1em",
  "codesnap.showWindowControls": false,
  "codesnap.shutterAction": "copy",

  // Wrap at 80 columns with the "Rewrap" extension
  "rewrap.wrappingColumn": 80,

  // Debugger
  "debug.toolBarLocation": "docked",
  "chatgpt.lang": "en",
  "workbench.colorTheme": "Default Positron Dark"
}
```

**Comment by juliasilge** [comment]
@zwallen Can you share if you can format regular `.R` files? Your problem with Quarto may be different, and it looks from your logs like the kernel _is_ successfully formatting... something.

**Comment by juliasilge** [comment]
@strengejacke and @lijiaqi-github are you all working with an untitled `.R` file or an `.R` file that is saved to disk?

**Comment by strengejacke** [comment]
It seems to work for saved files, despite the indention is not correct:

https://github.com/user-attachments/assets/ce92d101-85cf-449f-91bb-055b3b1be0d8

For unsaved files, nothing happens.

**Comment by lijiaqi-github** [comment]
> [@strengejacke](https://github.com/strengejacke) and [@lijiaqi-github](https://github.com/lijiaqi-github) are you all working with an untitled `.R` file or an `.R` file that is saved to disk?

Yes, I tested this in a new unsaved R file, Like @strengejacke said, formatting in a saved file seems to work.

**Comment by juliasilge** [comment]
Ah gotcha, OK! It's quite a coincidence that we have had multiple folks run into this at once, but yep, currently the styler-based formatter only works on "real" files, not on untitled files that have never been saved to disk. This is currently as expected.

We have some MAJOR improvements in formatting coming along shortly, so I don't think we're going to put much more effort into our stopgap solution using styler in the meantime. Thank you so much for the reports, and keep your eyes open for some major steps forward in R formatting soon! 🙌
