### ISSUE TITLE
Misleading error message when a restart is required before a table can be viewed

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#5535]
1. Create a new environment, or delete pandas/polars in the current environment and restart the session.
2. Create and view a dataframe:
  
  ```python
  import pandas as pd
  df = pd.DataFrame({'a': [0]})
  ```
  
  ```python
  %view df
  ```

You'll see the error in the console:

```
UsageError: cannot view object of type 'pandas.core.frame.DataFrame'
```

We should show a more informative error message in the console.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-2
    OS Version          : OSX

### Test scenario(s) 

Seeing:

UsageError: Pandas was installed after the session started. Please restart the session to view the table in the Data Explorer.

Link(s) to TestRail test cases run or created:
