### ISSUE TITLE
Headless/DuckDB Data Explorer tab opens empty if <10 rows in file

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#5552]
_Originally posted by @boshek in https://github.com/posit-dev/positron/discussions/5550_:

Using latest positron: 
```
Positron Version: 2024.12.0 (Universal) build 80
Code - OSS Version: 1.93.0
Commit: c3c489641477362638b2a80d94355a86a63eeb21
Date: 2024-11-26T02:46:47.938Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

Using R 4.4.1 

Something odd happens with the data explorer where a nine row csv (or parquet file) is not viewable where a 10 row one is. 🤷 
I doubt this is desired behaviour. I can open an issue but wanted to check here first. 

```r
## Empty data in file explorer
write.csv(data.frame(foo = 1:9), "foo_nine.csv")
## populated data in file explorer
write.csv(data.frame(foo = 1:10), "foo_ten.csv")
```

replicated in Python as well:

```python
import pandas as pd

# Create 9 rows - empty in explorer
pd.DataFrame({'foo': range(1, 10)}).to_csv('pd_foo_nine.csv', index=False)

# Create 10 rows - shows data in explorer
pd.DataFrame({'foo': range(1, 11)}).to_csv('pd_foo_ten.csv', index=False)
```

**Comment by wesm** [comment]
It turns out there is code that makes a hard-coded request for 10 rows of data and the DuckDB backend errors when there is less than that available:

https://github.com/posit-dev/positron/blob/67e4835c81f64b6551c335b74cd0b33b4e9fbea2/src/vs/workbench/services/positronDataExplorer/common/tableDataCache.ts#L288-L296

I'll relax this to not error since there being less than 10 rows returned is not problematic for this code path

**Comment by jonvanausdeln** [comment]
This fix appears to cause an issue caught in our [automated test run](https://github.com/posit-dev/positron/actions/runs/12203491850), where the entire file doesn't display in the data explorer grid.
See results:
https://d38p2avprg8il3.cloudfront.net/playwright-report-12203491850/index.html

Repro:
1. Open [flights.parquet](https://github.com/posit-dev/qa-example-content/blob/5224c22bd3bc1d91c1171f3d4af127019fadbee4/data-files/flights/flights.parquet) or [flights.csv](https://github.com/posit-dev/qa-example-content/blob/5224c22bd3bc1d91c1171f3d4af127019fadbee4/data-files/flights/flights.csv)
2. Scroll to the bottom ... or click the bottom right corner of the grid to jump to the end (and far right) of view
3. Observer that the grid is empty

<img src="https://github.com/user-attachments/assets/b6a6f78e-e4c9-4dba-963e-0510326450fb" width=60%>

**Comment by wesm** [comment]
I’ll investigate and fix, thank you!

**Comment by wesm** [comment]
Sorry about the regression, should be able to verify this now

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2025.01.0-50](https://github.com/posit-dev/positron-builds/releases/tag/2025.01.0-50)
Workbench Version(s):
OS Version(s) : Windows 11

### Test scenario(s) 
Example code works.. and other duckdb data explorer tests pass.

### Link(s) to TestRail test cases run or created:
