### ISSUE TITLE
Positron breaks after almost any package installation

### ISSUE THREAD

**Issue by Upipa** [posit-dev/positron#5563]
#### Positron and OS details:

Positron Version: 2024.12.0 (system setup) build 80
Code - OSS Version: 1.93.0
Commit: c3c489641477362638b2a80d94355a86a63eeb21
Date: 2024-11-26T02:46:23.686Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26100

#### Interpreter details:
R 4.4.2

## Describe the issue:

Positron keeps broking during package installation. My record was installing 2 packages in a row after breaking Positron. Most of the time during installation R stops, the restart button doesn't work. After closing and reopening Positron he can't find the R interpreter and this is my view on the console

![Image](https://github.com/user-attachments/assets/81d2b9b8-f886-42fd-b6a4-56f1eb2df73d)

Following the suggestion of starting the interpreter from the menù on the top right, it's possible to see all the R installation in the systems but clicking on them doesn't cause anything to happen. The only thing that i saw working is to reinstall positron. After that i have to remove the LOCK00 folder from the library and then i can finally try to reinstall the package. So at the end for installing one package i have to try first, then reinstall positron, delete the LOCK00 folder and reinstall the package, almost everytime.

## Steps to reproduce the issue:

Just install any package from the console. I think it might happen with everything but last time it happened with:

```{r}
install.packages("dotwhisker")
```

## Expected or desired behavior:
That it actually install it, or if don't, that at least let me restart the interpreter to retry the installation

## Were there any error messages in the UI, Output panel, or Developer Tools console?

I already lost my session so i don't knkow right now, but if it feels necessary to have it i will reproduce again the bug next week and check better the log.

**Comment by lionel-** [comment]
Can you provide us with logs please? Here is how to get at them: https://positron.posit.co/troubleshooting.html#python-and-r-logs

**Comment by Upipa** [comment]
Unfortunately (or not), it seems that today the problem disappeared. I succeeded to install a lot of packages without any problem. I'll keep trying during the day and post the logs whenever an error occurs

**Comment by jennybc** [comment]
I'm going to optimistically close this, since @Upipa has not returned in a week to report a recurrence of the problem. Hopefully this holds 🤞
