### ISSUE TITLE
Avoid eagerly importing expensive modules when importing positron_ipykernel

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#5596]
Currently, we execute a bunch of third party package imports when loading positron_ipykernel, see places where we import the `positron_ipykernel.third_party` module:

```
❯ ack "from .third_party"
extensions/positron-python/python_files/positron/positron_ipykernel/connections.py
27:from .third_party import pd_, sqlalchemy_

extensions/positron-python/python_files/positron/positron_ipykernel/inspectors.py
44:from .third_party import np_, pd_, torch_

extensions/positron-python/python_files/positron/positron_ipykernel/data_explorer.py
100:from .third_party import (

extensions/positron-python/python_files/positron/positron_ipykernel/positron_ipkernel.py
40:from .third_party import RestartRequiredError

extensions/positron-python/python_files/positron/positron_ipykernel/ui.py
19:from .third_party import np_, pd_, pl_, torch_
```

These imports have a non-trivial cost that will slow down kernel starts/restarts, even when these modules aren't in use, e.g.:

```
❯ time python -c "import torch, numpy, polars, pandas, sqlalchemy, pyarrow"
python -c "import torch, numpy, polars, pandas, sqlalchemy, pyarrow"  
2.43s user 0.20s system 184% cpu 1.430 total
```

Aside from the performance penalty, they also use extra RAM, about 400MB for me on Linux and 4GB of virtual memory. 

This presents a slight conundrum since the Positron kernel does various things with these third party modules, like configuring them for better behavior in the console.

It would be best to refactor things so that we avoid getting into a situation where positron_ipykernel imports any of these modules before the user does in their code. If the user does not use them directly or indirectly (via a transitive dependency), it would be better to never import them.

**Comment by jonvanausdeln** [comment]
Automated test suites have been passing since the merge, so closing.
