### ISSUE TITLE
Cannot view long Jupyter cell outputs as a scrollable element

### ISSUE THREAD

**Issue by joscani** [posit-dev/positron#5603]
#### Positron and OS details:

Versión: Positron Version: 2024.12.0 build 96
Code - OSS Version: 1.93.0
Commit: c5ce275dc502f6b15433b271802cb33e1ba5ef68
Date: 2024-11-28T02:42:33.973Z
Confirmar: 30.4.0
Fecha: 124.0.6367.243
Electron: 20.15.1
ElectronBuildId: 12.4.254.20-electron.0
Chromium: Linux x64 5.15.0-125-generic
Node.js: undefined
V8: undefined
SO: undefined

#### Interpreter details:

<Python 3.9.13> -->

## Describe the issue:

In cellouput , when output is big, click scrollable element doesn't work

**Comment by joscani** [comment]
Hi @juliasilge  and thanks for your fast answer. 

Sure. In a ipynb notebook, if you have this code

```python
  # code with error
def divide_numbers(numbers):
    result = []
    for num in numbers:
        result.append(10 / num)
    return result

numbers_to_divide = [2, 4, 0, 5, 7]

try:
    divide_numbers(numbers_to_divide)
except Exception as e:
    error_message = f"Error: {e}\n" * 50  # Repeat error message
    raise RuntimeError(error_message)
```

You get a large error message, 
But if I click on scrollable element the output cells doesn't show the displacement bar, and I don't see the complete error message.
Thanks.

**Comment by juliasilge** [comment]
Thanks for the example! 🙌 

This "scrollable element" link doesn't do anything currently:

![Image](https://github.com/user-attachments/assets/c46c4e19-092e-41e8-b685-a234fc00235b)

**Comment by seeM** [comment]
The "Notebook: Toggle scrollable element" command is also not working and should be checked when we QA this issue.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-81
    OS Version          : OSX

### Test scenario(s) 

Link and command both work now

Link(s) to TestRail test cases run or created:
