### ISSUE TITLE
R help pages are not displayed

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [posit-dev/positron#5604]
#### Positron and OS details:

Positron Version: 2024.12.0 (user setup) build 96
Code - OSS Version: 1.93.0
Commit: c5ce275dc502f6b15433b271802cb33e1ba5ef68
Date: 2024-11-28T02:53:40.010Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22621

#### Interpreter details:

<pre>
> sessioninfo::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.4.2 Patched (2024-11-29 r87412 ucrt)
 os       Windows 11 x64 (build 22621)
 system   x86_64, mingw32
 ui       Rgui
 language (EN)
 collate  German_Germany.utf8
 ctype    German_Germany.utf8
 tz       Europe/Berlin
 date     2024-12-04
 pandoc   NA

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 cli           3.6.3   2024-06-21 [1] RSPM
 sessioninfo   1.2.2   2021-12-06 [1] RSPM

 [1] C:/Users/[Redacted]/AppData/Local/Programs/R/R-4.4.2patched/site-library
 [2] C:/Users/[Redacted]/AppData/Local/Programs/R/R-4.4.2patched/library

────────────────────────────────────────────────────────────────────────────────────────────────────
</pre>

<pre>
> Sys.getenv() |> (\(.x) .x[grepl("^R_", names(.x))])()
R_ARCH                                             /x64
R_COMPILED_BY                                      gcc 13.3.0
R_DOC_DIR                                          C:/Users/[Redacted]/AppData/Local/Programs/R/R-4.4.2patched/doc
R_HOME                                             C:/Users/[Redacted]/AppData/Local/Programs/R/R-4.4.2patched
R_INCLUDE_DIR                                      C:/Users/[Redacted]/AppData/Local/Programs/R/R-4.4.2patched/include
R_LIBS_SITE                                        C:/Users/[Redacted]/AppData/Local/Programs/R/R-4.4.2patched/site-library
R_LIBS_USER                                        ~/R/win-library/4.4.2
R_RTOOLS44_PATH                                    C:\Users\[Redacted]\R\rtools\44/x86_64-w64-mingw32.static.posix/bin;C:\Users\[Redacted]\R\rtools\44/usr/bin
R_SHARE_DIR                                        C:/Users/[Redacted]/AppData/Local/Programs/R/R-4.4.2patched/share
R_USER                                             C:\Users\[Redacted]\OneDrive - [Redacted]\Personal Data
</pre>

## Describe the issue:

When invoking the R help, the help pane opens but remains unpopulated.

![Image](https://github.com/user-attachments/assets/b5b502c1-1f14-4e9b-99a2-379a9151b176)

## Steps to reproduce the issue:

1. Start R interpreter
2. Invoke help, e.g. `?file`

## Expected or desired behavior:

Help page is presented.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

From *Developer Tools console*:
<pre>
connections.html:1 
        
        
       Failed to load resource: the server responded with a status of 502 (Bad Gateway)
</pre>

**Comment by juliasilge** [comment]
I believe this is the same as #3543. Want to take a look and see if you have anything additional to add? Are you able to reproduce this every single time you open Positron?

**Comment by HenningLorenzen-ext-bayer** [comment]
> I believe this is the same as [#3543](https://github.com/posit-dev/positron/issues/3543). Want to take a look and see if you have anything additional to add?
Sure.

> Are you able to reproduce this every single time you open Positron?
Yes
