### ISSUE TITLE
When supervisor does not start, show its output and provide an explanatory error

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#5611]
When the Jupyter kernel supervisor fails to start, the UX is not great. You get a toast letting you know that the terminal failed to start, and a message in the console that says we "failed to connect to Kallichore." That's not super helpful for most users.

It should be rare that the supervisor fails to start, but it is possible, so we should make sure that the experience isn't bad. Specifically, we should:

1. Show any output that was emitted during the launch, so the user can see the error that led to the launch failing. In the example below, this would have shown a glibc or openssl error due to OS level incompatibility. Since VS Code's Terminal API doesn't provide a way to show the output of failed commands, this will require running the server under a wrapper script to capture its output, as we used to do for Jupyter kernels.
2. Have the Console show a more reasonable message that doesn't use code names.

Originally via discussion (see below); in this case, it was expected that the server won't start due to Linux incompatibility (https://github.com/posit-dev/positron/issues/3854). 

### Discussed in https://github.com/posit-dev/positron/discussions/5605

<div type='discussions-op-text'>

<sup>Originally posted by **fabian-s** December  4, 2024</sup>
Error message:

> The terminal process "/usr/share/positron/resources/app/extensions/positron-supervisor/resources/kallichore/kcserver '--port', '62076', '--token', '/tmp/kallichore-d532b7ab.token', '--log-level', 'debug', '--log-file', '/tmp/kallichore-d532b7ab.log'" failed to launch (exit code: 127).

Screenshot:

![image](https://github.com/user-attachments/assets/d1fb2451-d56c-4abf-ba05-a5674dd62e3b)

This is on Linux Mint 20.
</div>

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-104
    OS Version          : OSX

### Test scenario(s) 

<img width="789" alt="Image" src="https://github.com/user-attachments/assets/27319a2a-8ea0-40b1-b9df-0e09bd76a2d6" />

Used same kcserver contents as Pete

<img width="464" alt="Image" src="https://github.com/user-attachments/assets/749ca692-ce19-4800-bb3e-4d7800c8e075" />


Link(s) to TestRail test cases run or created:
