### ISSUE TITLE
Favicon missing when running Positron in Chromium-based browsers

### ISSUE THREAD

**Issue by sharon-wang** [posit-dev/positron#5619]
#### Positron and OS details:

Latest on `main`.

#### Interpreter details:

N/A

## Describe the issue:

Chrome:

![Image](https://github.com/user-attachments/assets/b649cb7c-224d-4a1d-b79a-9b212cf598f3)

Firefox:

![Image](https://github.com/user-attachments/assets/b147dc13-a7b1-43b0-baf6-066e39b11d61)

Safari:

![Image](https://github.com/user-attachments/assets/9907881b-375b-4c61-9c24-bc81c4071c32)

## Steps to reproduce the issue:

1. Open Positron Server Web dev build in a Chromium-based browser like Chrome, Edge, Arc, etc.
2. Notice that the favicon tab icon is missing

## Expected or desired behavior:

Icon should be present in all supported browsers.

Possible solution: favicon.ico in Positron seems to be at a very high 1024x1024 resolution for this resource type, but the max resolution for favicons in Chrome is 256x256. Try reducing the resolution?

We will need to update this file with the updated image:
- https://github.com/posit-dev/positron/blob/main/resources/server/favicon.ico

We should leave the Windows positron.ico as-is:
- https://github.com/posit-dev/positron/blob/main/resources/win32/positron.ico

## Were there any error messages in the UI, Output panel, or Developer Tools console?

N/A

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : Main on 12/20/24, 1:30 PM MST
    OS Version          : OSX

### Test scenario(s) 

Looks good in Chrome now.

Link(s) to TestRail test cases run or created:
