### ISSUE TITLE
Positron doesn't run jupyter cells in Quarto doc.

### ISSUE THREAD

**Issue by davidjayjackson** [posit-dev/positron#5622]
Type: <b>Bug</b>

Hey,
When I click on a Python cell in a Quarto/jupyter document nothing happens? I can render the whole document using the icon at the top right.
TX
David

Positron Version: 2024.12.0 (user setup) build 96
Code - OSS Version: 1.93.0
Commit: c5ce275dc502f6b15433b271802cb33e1ba5ef68
Date: 2024-11-28T02:53:40.010Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

VS Code version: Positron 1.93.0 (c5ce275dc502f6b15433b271802cb33e1ba5ef68, 2024-11-28T02:53:40.010Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.70GB (23.29GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
pyright|ms-|1.1.390
black-formatter|ms-|2024.4.0
debugpy|ms-|2024.12.0
duck-vscode|duc|0.0.2
jupyter|lum|2022.3.108
rainbow-csv|mec|3.3.0

</details>

**Comment by juliasilge** [comment]
Can you say more about the problem you are running into? If I have a Python `.qmd` document like this and I click "Run Cell", I see the code then executed in the console:

![Image](https://github.com/user-attachments/assets/05e0ec63-6e0f-404c-9d71-6ff6c0bb449a)

**Comment by davidjayjackson** [comment]
Julia,
It seems to be working fine now.
Your can close the ticket

**Comment by juliasilge** [comment]
Glad to hear that!
