### ISSUE TITLE
Shiny 'runApp' button takes forever to start

### ISSUE THREAD

**Issue by ntluong95** [posit-dev/positron#5636]
#### Positron and OS details:

Positron Version: 2024.12.0 (system setup) build 96
Code - OSS Version: 1.93.0
Commit: c5ce275dc502f6b15433b271802cb33e1ba5ef68
Date: 2024-11-28T02:50:45.229Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22621

#### Interpreter details:

R 4.4.2

## Describe the issue:

![Image](https://github.com/user-attachments/assets/cc6b7d36-0487-4655-a360-f2d7564fc6ca)

## Steps to reproduce the issue:

Open any shinyApp project

## Expected or desired behavior:
If I run the script normally `runApp()`, it works

![Image](https://github.com/user-attachments/assets/0f4002a5-3062-4a1b-b556-7fba64a5a9a3)

Also, the project run normally in Rstudio, so I assume that it should not come from my code
## Were there any error messages in the UI, Output panel, or Developer Tools console?

N/A

**Comment by jmcphers** [comment]
This message comes from the Shiny extension.

- Which version of the Shiny extension are you using?
- Do you also see this problem when using the Shiny extension in VS Code with the same Shiny application?

**Comment by ntluong95** [comment]
The version of Shiny extension that I am using is `v1.1.0`
I open VSCode and have the same error, so it might be problem with Shiny extension rather?

**Comment by juliasilge** [comment]
Yep, seems like that is the right place to report this! Can you open an issue:
<https://github.com/posit-dev/shiny-vscode/issues>

You might include how long it takes for the app to come up via `runApp()`. If it truly just takes that long for the app to come up, then the timeout might need to be configurable by the user.
