### ISSUE TITLE
Trying to open a CSV/Parquet file with DuckDB while Positron is still loading errors as the command isn't available yet

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#5655]
If you click on a data file as Positron is loading, it will open a broken data explorer with an error that the command `positron-duckdb.dataExplorerRpc is not found`. We should add retry logic so wait for the command to become available

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-81
    OS Version          : OSX, ubuntu, windows

### Test scenario(s) 

Verified and automation updated to continuously check.

Link(s) to TestRail test cases run or created:
