### ISSUE TITLE
mathplotlib animation in python 3.13

### ISSUE THREAD

**Issue by grimli** [posit-dev/positron#5662]
Type: <b>Bug</b>

I cannot reproduce mathplotlib animation in python.  
Only the first frame is shown. 
I'm not an expert but it seams to me it doesn't work the script in the mathplotlib tutorial. 
The same script works as expected if executed outside positron but in the same python virtual environment. 
The script is reported below and should be sufficient to reproduce the problem.

---
import matplotlib.pyplot as plt
import numpy as np

import matplotlib.animation as animation

fig, ax = plt.subplots()
t = np.linspace(0, 3, 40)
g = -9.81
v0 = 12
z = g * t**2 / 2 + v0 * t

v02 = 5
z2 = g * t**2 / 2 + v02 * t

scat = ax.scatter(t[0], z[0], c="b", s=5, label=f'v0 = {v0} m/s')
line2 = ax.plot(t[0], z2[0], label=f'v0 = {v02} m/s')[0]
ax.set(xlim=[0, 3], ylim=[-4, 10], xlabel='Time [s]', ylabel='Z [m]')
ax.legend()

def update(frame):
    # for each frame, update the data stored on each artist.
    x = t[:frame]
    y = z[:frame]
    # update the scatter plot:
    data = np.stack([x, y]).T
    scat.set_offsets(data)
    # update the line plot:
    line2.set_xdata(t[:frame])
    line2.set_ydata(z2[:frame])
    return (scat, line2)

ani = animation.FuncAnimation(fig=fig, func=update, frames=40, interval=30)
plt.show()

--------------- 
python version: 3.13.0

pip freeze:
asttokens==3.0.0
colorama==0.4.6
comm==0.2.2
contourpy==1.3.1
cycler==0.12.1
debugpy==1.8.9
decorator==5.1.1
executing==2.1.0
fonttools==4.55.0
iniconfig==2.0.0
ipykernel==6.29.5
ipython==8.30.0
jedi==0.19.2
jupyter_client==8.6.3
jupyter_core==5.7.2
kiwisolver==1.4.7
matplotlib==3.9.3
matplotlib-inline==0.1.7
mpmath==1.3.0
nest-asyncio==1.6.0
numpy==2.1.3
packaging==24.2
pandas==2.2.3
parso==0.8.4
pillow==11.0.0
platformdirs==4.3.6
pluggy==1.5.0
prompt_toolkit==3.0.48
psutil==6.1.0
pure_eval==0.2.3
Pygments==2.18.0
pyparsing==3.2.0
pytest==8.3.3
python-dateutil==2.9.0.post0
pytz==2024.2
pywin32==308
pyzmq==26.2.0
six==1.16.0
stack-data==0.6.3
Tcl==0.2
tk==0.1.0
tornado==6.4.2
traitlets==5.14.3
tzdata==2024.2
wcwidth==0.2.13

-----

VS Code version: Positron 1.93.0 (c5ce275dc502f6b15433b271802cb33e1ba5ef68, 2024-11-28T02:53:40.010Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1260P (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.64GB (3.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
pyright|ms-|1.1.390
debugpy|ms-|2024.12.0
js-debug|ms-|1.96.0

</details>

**Comment by isabelizimm** [comment]
Hello there! Thank you so much for trying out Positron 🌻 You'll need to update one `matplotlib` setting to make sure the output is displayed correctly. In a Jupyter Notebook or in Console, run `%matplotlib ipympl` before executing your animation. You may need to `pip install ipympl` into your environment as well.

After that, you should be able to run everything else as-is, but please let us know if that is not the case!

**Comment by jennybc** [comment]
I'm going to assume that @isabelizimm's helpful reply has resolved this.
