### ISSUE TITLE
Outline view for Markdown file (without opening a folder or workspace)

### ISSUE THREAD

**Issue by Soumyadipta2020** [posit-dev/positron#5663]
Type: <b>Feature Request</b>

Outline based on markdown like we have in rstudio would be the best feature which I strongly miss in here and vs code too. 

VS Code version: Positron 1.93.0 (c5ce275dc502f6b15433b271802cb33e1ba5ef68, 2024-11-28T02:50:45.229Z)
OS version: Windows_NT x64 10.0.26100
Modes:

**Comment by juliasilge** [comment]
Can you share more details of what kind of outline you are looking for? We do support outlines using markdown-like comments in R:

![Image](https://github.com/user-attachments/assets/f2389d03-b201-4465-ac41-39b26a58bd77)

What additionally are you wanting to see?

**Comment by Soumyadipta2020** [comment]
I can't see them. attached the image below.

Expecting check 1, check 2 as outline

![Image](https://github.com/user-attachments/assets/cb73ddcb-e8ed-4ea0-9ef7-a5aa520f437c)

**Comment by jennybc** [comment]
The "NO FOLDER OPENED" message is giving you a good diagnosis. The file explorer does not come fully alive until/unless one opens a *folder* in Positron (inherited behaviour from VS Code). And the outline view is a feature of the file explorer. So this is a good example of the type of feature you can't really enjoy when opening a free-range file in Positron.

**Comment by Soumyadipta2020** [comment]
That something I am expecting as we do in rstudio

![Image](https://github.com/user-attachments/assets/d7d82d7a-d983-497b-b202-1ef7175747e5)

**Comment by jennybc** [comment]
Yes, this may end up being an aspect where Positron and RStudio are just different.

**Comment by juliasilge** [comment]
Is the problem just that you don't have the markdown-like comments set up correctly @Soumyadipta2020? They need to be specified like `# title0 ----` or `# title0 ####`, like you show in your RStudio screenshot.

I see these working in all cases, such as in an untitled file or without a folder open (no workspace):

![Image](https://github.com/user-attachments/assets/daf1d514-04b3-4603-9ff9-583d91b58a84)

**Comment by juliasilge** [comment]
Let us know if you run into further problems!
