### ISSUE TITLE
selection range is off-by-one in rstudioapi shims when selection ends in a newline

### ISSUE THREAD

**Issue by simonpcouch** [posit-dev/positron#5682]
#### Positron and OS details:

Positron Version: 2025.01.0 (Universal) build 39
Code - OSS Version: 1.93.0
Commit: c7ef34fc7078ac7ecf13ff3328605dfba93f3eea
Date: 2024-12-09T02:49:50.608Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.1.0

#### Interpreter details:

R 4.4.1

## Describe the issue:

When the active selection ends in a newline, the `$selection[[1]]$range$end` slot in `rstudioapi::getActiveDocumentContext()` and `rstudioapi::getSourceEditorContext()` output is off-by-one.

https://github.com/user-attachments/assets/9fa49ece-7ae0-40b2-9a9e-cb2c32ab474d

## Steps to reproduce the issue:

1. Open a .R file and paste the following in:

```r
fn <- function() {
  "hey there"
}
```

2. Select `"hey there"` only and observe that `$selection[[1]]$range$end` is row 2, column 14.
3. Select `"hey there"` to the end of the line by dragging to the start of row 3 and observe that `$selection[[1]]$range$end` row 3, column 15.

## Expected or desired behavior:

I would have expected that slot to be row 3, column 1 or row 2, column 15. (It's the former in RStudio!)

## Were there any error messages in the UI, Output panel, or Developer Tools console?

No.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-81
    OS Version          : OSX

### Test scenario(s) 

Verified according to filing instructions.  Final case looks like:
```
rstudioapi::getActiveDocumentContext()
Document Context: 
- id:        ''
- path:      '/Users/christophermead/posit/qa-example-content/junk.R'
- contents:  <3 rows>
Document Selection:
- [2, 3] -- [3, 1]: '"hey there"\n'
>
```
Link(s) to TestRail test cases run or created:
