### ISSUE TITLE
UI for the new connections modals

### ISSUE THREAD

**Issue by dfalbel** [posit-dev/positron#5687]
Mockups:

![Image](https://github.com/user-attachments/assets/02af6ce8-f5e8-4ec6-82e7-f3dcca4100c4)

![Image](https://github.com/user-attachments/assets/6923fd98-c48c-4b7d-a8be-2ed7570c4dec)

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-104
    OS Version          : OSX

### Test scenario(s) 

Looks good for R Postgres.  I don't have a lot of options available but can confirm the basics of the mockups.

Link(s) to TestRail test cases run or created:
