### ISSUE TITLE
Terminal process failed to launch (exit code: 127)

### ISSUE THREAD

**Issue by billytcl** [posit-dev/positron#5704]
#### Positron and OS details:

Positron Version: 2024.12.0 (Universal) build 96
Code - OSS Version: 1.93.0
Commit: c5ce275dc502f6b15433b271802cb33e1ba5ef68
Date: 2024-11-28T02:47:29.898Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin x64 24.1.0

#### Interpreter details:

N/A, although it seems to not be able to find the existing R 4.1 install that's on /usr/bin/, but not sure if this issue is related.

## Describe the issue:

I'm a newbie to Positron, and I'm trying to start a remote SSH session by clicking the bottom left button then connecting to a remote server. I get this error popup on the bottom right. The log file also doesn't exist but the token file does.

<img width="447" alt="Image" src="https://github.com/user-attachments/assets/b3bf2f99-be4c-4fc9-b513-dbeceb533985" />

## Steps to reproduce the issue:

1. Click bottom left connection button
2. Connect to remote server

**Comment by jennybc** [comment]
Can I see the content of the logs in the Positron R Extension output channel?

Instructions for navigating to various output channels are here:

https://positron.posit.co/troubleshooting.html

---

I note that this sounds a lot like #5605. And the definitive issue about issuing a more informative error, in that case, is #5611.

**Comment by billytcl** [comment]
Oh, I see. It looks like the R version wants to be 4.2.0 or higher. Is that a strict requirement?

```
2024-12-11 15:40:00.730 [info] Log level: Debug
2024-12-11 15:40:00.730 [info] Refreshing testthat status
2024-12-11 15:40:00.730 [info] Not working in an R package
2024-12-11 15:40:00.730 [info] Context key 'testthatIsConfigured' is 'false'
2024-12-11 15:40:00.730 [info] Context key 'testthatHasTests' is 'false'
2024-12-11 15:40:01.011 [info] Skipping registry check on non-Windows platform
2024-12-11 15:40:01.025 [info] Possibly found R on PATH: /usr/bin/R.
2024-12-11 15:40:01.025 [info] Resolved R binary at /usr/bin/R
2024-12-11 15:40:01.026 [info] Candidate R binary at /usr/bin/R
2024-12-11 15:40:01.026 [info] R installation discovered: {
  "valid": true,
  "supported": false,
  "binpath": "/usr/bin/R",
  "homepath": "/usr/lib/R",
  "semVersion": {
    "options": {},
    "loose": false,
    "includePrerelease": false,
    "raw": "4.1.0",
    "major": 4,
    "minor": 1,
    "patch": 0,
    "prerelease": [],
    "build": [],
    "version": "4.1.0"
  },
  "version": "4.1.0",
  "arch": "x86_64",
  "current": true,
  "orthogonal": true
}
2024-12-11 15:40:01.026 [info] Filtering out /usr/bin/R: version is < 4.2.0
```

**Comment by jennybc** [comment]
https://positron.posit.co/start.html#r-prerequisites

> R prerequisites
> 
> Positron requires R 4.2 or higher. To install R, follow the instructions for your operating system at https://cloud.r-project.org/.

Yes, R >= 4.2 is a hard requirement.

**Comment by billytcl** [comment]
Got it! Will look at other threads on how to manage different versions of R.
