### ISSUE TITLE
Can't use Quarto on SSH host

### ISSUE THREAD

**Issue by pbousquets** [posit-dev/positron#5723]
#### Positron and OS details:

Positron Version: 2024.12.0 (system setup) build 96
Code - OSS Version: 1.93.0
Commit: c5ce275dc502f6b15433b271802cb33e1ba5ef68
Date: 2024-11-28T02:50:45.229Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

#### Interpreter details:

 R 4.4.2 

## Describe the issue:

I've SSH'ed to a server, through which I want to perform an analysis with Quarto. As soon as I open a .qmd file, it crashes. I tried to manually install Positron in the server as well, but didn't help. In my local computer it works nicely.

## Steps to reproduce the issue:
1. SSH to host
2. Create or open new quarto document

## Were there any error messages in the UI, Output panel, or Developer Tools console?

I get two errors. One directly on a warning window: 
```
The terminal process "/home/pbousquets/.positron-server/bin/c5ce275dc502f6b15433b271802cb33e1ba5ef68/extensions/positron-supervisor/resources/kallichore/kcserver '--port', '48091', '--token', '/tmp/kallichore-891faa1c.token', '--log-level', 'debug', '--log-file', '/tmp/kallichore-891faa1c.log'" failed to launch (exit code: 127)
```
In the console:
```
Kallichore server did not start after 1923ms
```

**Comment by jmcphers** [comment]
What Linux distribution and version are you using on the remote SSH host?

Note that some older Linux distributions are not supported (see #3854).

**Comment by pbousquets** [comment]
Hi! Thanks for the quick response. The system is debian 11. So it seems to be the problem according to the issue you cross referenced. 

Thanks a lot for your help

Pablo

**Comment by juliasilge** [comment]
Thanks for that info @pbousquets! We have #5700 to track showing a better error message in this situation, and #3854 to track supporting these older Linux distributions if possible.
