### ISSUE TITLE
Red square ("busy indicator") missing?

### ISSUE THREAD

**Issue by strengejacke** [posit-dev/positron#5724]
Not sure if this was intentional, but in previous Positron versions, there was a res square in the upper right corner, indicating when R console was busy:

![Image](https://github.com/user-attachments/assets/bafc59a5-1dee-466a-850e-5a2bae78df5f)

This is missing in the latest version - was this change intentional?

Positron Version: 2025.01.0 (system setup) build 39
Code - OSS Version: 1.93.0
Commit: c7ef34fc7078ac7ecf13ff3328605dfba93f3eea
Date: 2024-12-09T02:44:40.379Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26100

**Comment by jennybc** [comment]
Yes, I agree it seems to have gone missing. I'm going to initiate a search for the 🟥 button!

Sidebar: it is sort of a busy indicator, but its real purpose is to try to interrupt the computation, if the user clicks it.

**Comment by strengejacke** [comment]
> but its real purpose is to try to interrupt the computation

Yes, you're right. The body indicator is more the green border left of the console. It's the equivalent to the RStudio stop button.

**Comment by jennybc** [comment]
I did a manual bisect investigation using the private pre-release builds. I can narrow it down to these 3 commits, of which 59b5b0c3c0a3de2068753811d7b19843d39437cf sure looks the most related to this matter 🧐:

https://github.com/posit-dev/positron/compare/3d0cc4120c986c64ba7f3871ade3854654c32477...59b5b0c3c0a3de2068753811d7b19843d39437cf

Button is last present in 2024.12.0-48:
Positron Version: 2024.12.0 (Universal) build 48
Code - OSS Version: 1.93.0
Commit: 3d0cc4120c986c64ba7f3871ade3854654c32477
Date: 2024-11-20T02:45:46.693Z

In the next pre-release build, 2024.12.0-51, button is gone:
Positron Version: 2024.12.0 (Universal) build 51
Code - OSS Version: 1.93.0
Commit: 59b5b0c3c0a3de2068753811d7b19843d39437cf
Date: 2024-11-21T02:46:07.218Z

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-104
    OS Version          : OSX

### Test scenario(s) 

Works with a simple sleep.
Also validated in automation now.

Link(s) to TestRail test cases run or created:
