### ISSUE TITLE
Python Project using existing venv won't start interpreter

### ISSUE THREAD

**Issue by jonvanausdeln** [posit-dev/positron#5730]
#### Positron and OS details:

```
Positron Version: 2025.01.0 (system setup) build 71
Code - OSS Version: 1.93.0
Commit: bb6af9753b5342227aa1d4406897951048fba044
Date: 2024-12-12T02:43:50.411Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26100
```

#### Interpreter details:

Python 3.10.10 (but version doesn't matter)

## Describe the issue:
The interpreter doesn't start in a new project when selecting an existing venv. nor when opening an existing project with a venv.

This is seen in our automated [New Project with ipykernel installed](https://github.com/posit-dev/positron/blob/476ac29b36cd38017ca7befb85a11c3a97876fd2/test/e2e/features/new-project-wizard/new-project-python.test.ts#L64) test. causing it to fail.

## Steps to reproduce the issue:

1. Create a new Python project selecting to create a new venv
2. Let the new project load, and console interpreter session start.. installing ipykernel as needed.
3. Close the folder
4. Re-open the project 

<img src ="https://github.com/user-attachments/assets/50d093d8-35a7-4634-a714-fb6acc174efd" width=50%>

Note that the interpreter doesn't start up.  However you can manually start the interpreter. It used to auto start the interpreter. This is causing our test to fail. 

## Expected or desired behavior:
Console interpreter starts up automatically

### QA NOTES
Two tests skipped will need to be turned back on when resolved. See https://github.com/posit-dev/positron/pull/5731

**Comment by sharon-wang** [comment]
Reminds me of: https://github.com/posit-dev/positron/issues/5286

Some console output from a failed run:
```js
  ERR Creating session for language runtime 991fdf617151cbb9d45a4e4c00c795a9 (language: Python name: Python 3.10.12 (Global) version: 3.10.12) failed. Reason: Error: Interpreter /bin/python3.10 (path: /bin/python3.10) not found in available Python interpreters: 
DEBUG Error starting runtime session: Error: Interpreter /bin/python3.10 (path: /bin/python3.10) not found in available Python interpreters: 
  ERR Interpreter /bin/python3.10 (path: /bin/python3.10) not found in available Python interpreters: : Error: Interpreter /bin/python3.10 (path: /bin/python3.10) not found in available Python interpreters: 
	at new PythonRuntimeSession (/home/runner/work/positron/positron/extensions/positron-python/out/client/positron/session.js:72:19)
	at PythonRuntimeManager.createSession (/home/runner/work/positron/positron/extensions/positron-python/out/client/positron/manager.js:144:16)
	at async ExtHostLanguageRuntime.$createLanguageRuntimeSession (/home/runner/work/positron/positron/out/vs/workbench/api/common/positron/extHostLanguageRuntime.js:82:33)
```
- odd that no interpreters were listed at all
- this feels like a timing issue where we check for the interpreter we want to start before we've completed runtime discovery

**Comment by sharon-wang** [comment]
This could have the same root cause as https://github.com/posit-dev/positron/issues/5718?

**Comment by jonvanausdeln** [comment]
This also repros locally.. I can try to get some log.ss.

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2025.01.0-141](https://github.com/posit-dev/positron-builds/releases/tag/2025.01.0-141)
Workbench Version(s):
OS Version(s) : 

### Test scenario(s) 
venv now starts as expected. There seem to still be something causing some CI failures, but don't seem to be related to this issue. I'm investigating that separately.

### Link(s) to TestRail test cases run or created:
