### ISSUE TITLE
Missing function to horizontally customize the size of Viewer

### ISSUE THREAD

**Issue by sammo3182** [posit-dev/positron#5738]
#### Positron and OS details:

Positron Version: 2024.12.0 (user setup) build 96
Code - OSS Version: 1.93.0
Commit: c5ce275dc502f6b15433b271802cb33e1ba5ef68
Date: 2024-11-28T02:53:40.010Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

#### Interpreter details:

R 4.5.0

## Describe the issue:

I am using Positron to produce quarto revealjs slides.
The viewer shows the output on the right-hand side filling the entire space. 
I can't see where the bottom edge of the slide is to determine if I've filled too much stuff in a slide unless opening the output in an external browser (as shown in the following screenshot).

![Image](https://github.com/user-attachments/assets/d32c0008-823f-4af2-903b-2d1e8f246b21)

## Expected or desired behavior:

Rstudio has the function of customizing the size of the viewer horizontally.
Hope Positron to equip the same function.

**Comment by juliasilge** [comment]
You may want to check out the options I outline here for working with slides in Positron:

https://github.com/posit-dev/positron/discussions/4836#discussioncomment-11476672
