### ISSUE TITLE
More robust type inference for exceptional CSV files with DuckDB data explorer backend

### ISSUE THREAD

**Issue by wesm** [posit-dev/positron#5746]
As described in https://github.com/posit-dev/positron/discussions/5707, certain large CSV files can pose type inference difficulties for the default settings with DuckDB's `read_csv` scan function. 

The Tad data viewer (MIT licensed) uses DuckDB and will disable data sampling for type inference if loading the whole CSV file fails after the initial attempt at type inference. We can probably take a similar approach: https://github.com/antonycourtney/tad/blob/master/packages/reltab-duckdb/src/csvimport.ts#L78.

**Comment by wesm** [comment]
In the meantime, I also opened https://github.com/duckdb/duckdb/issues/15376 also to see if this is the behavior that DuckDB intends, or whether there might be a missing option to disable numeric type inference for quoted fields in the CSV reader.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-135
    OS Version          : OSX

### Test scenario(s) 

https://s3.amazonaws.com/data.patentsview.org/download/g_patent.tsv.zip
loads without issue


Link(s) to TestRail test cases run or created:
