### ISSUE TITLE
Positron not loading after attempting switching projects in same window after v1.95 upstream merge

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#5749]
#### Positron and OS details:

Positron Version: 2025.01.0 (Universal) build 87
Code - OSS Version: 1.95.0
Commit: 240e51fa165f6c512e586f0af105a0c8fc092607
Date: 2024-12-16T02:50:00.442Z
Electron: 32.2.1
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

## Describe the issue:

Project switching never loads when trying to switch projects in the same window. Popping into a new window does work as expected.

## Steps to reproduce the issue:

1. Open a new instance of Positron, and attempt to launch an existing project.
2. Note the screen doesn't load.

https://github.com/user-attachments/assets/c5caac2f-2d22-4526-9269-fca538ff379f

## Expected or desired behavior:

Project switching works.

**Comment by jmcphers** [comment]
I can reproduce. This is a React load failure.

<img width="1345" alt="Image" src="https://github.com/user-attachments/assets/8d65d3c6-1647-4096-bfee-eb94704e616d" />

**Comment by jennybc** [comment]
I just experienced this on Windows as well FWIW. Not a surprise, but just noting for completeness. Developer Console looks just like above.

**Comment by softwarenerd** [comment]
This is addressed in https://github.com/posit-dev/positron/pull/5808.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-124
    OS Version          : OSX

### Test scenario(s) 

Looks great.  Reopened qa-example-content without issue

Link(s) to TestRail test cases run or created:
