### ISSUE TITLE
Console attempts to reconnect and 404s when connecting to an existing project after 1.95 merge

### ISSUE THREAD

**Issue by jthomasmock** [posit-dev/positron#5750]
#### Positron and OS details:

Positron Version: 2025.01.0 (Universal) build 87
Code - OSS Version: 1.95.0
Commit: 240e51fa165f6c512e586f0af105a0c8fc092607
Date: 2024-12-16T02:50:00.442Z
Electron: 32.2.1
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

#### Interpreter details:

R 4.4 or Python 3.12.0 `.venv`

## Describe the issue:

Opening a new window for an existing projects leads to consoles 404 error and stuck in a "Reconnecting" state. Shutting down the runtime and then restarting seems to get it out of this state.

## Steps to reproduce the issue:

1. Open a new instance of Positron
2. Launch an existing project in a new Window
3. Observe the 404 failures in the console

https://github.com/user-attachments/assets/14adeb33-5f3c-4f38-9d2d-0b6a5860db44

## Expected or desired behavior:

Console successfully starts on first launch and not display a 404 error to user.

## Were there any error messages in the UI, Output panel, or Developer Tools console?

Kallichore seems to be looking for an existing process:

```
2024-12-16 10:24:15.326 [info] Positron Kernel Supervisor activated
2024-12-16 10:24:15.326 [info] Kallichore server PID 42356 is not running
2024-12-16 10:24:15.326 [info] Could not reconnect to Kallichore server at http://localhost:47616. Starting a new server
2024-12-16 10:24:15.326 [info] Starting Kallichore server /Applications/Positron.app/Contents/Resources/app/extensions/positron-supervisor/resources/kallichore/kcserver on port 54134
2024-12-16 10:24:15.326 [info] Waiting for Kallichore server to start (attempt 1, 164ms)
Kallichore 0.1.22 server online with 0 sessions
Kallichore server started in 292ms
Streaming Kallichore server logs from /var/folders/dr/jx6dh4ss7cqc111rf64bxqw40000gn/T/kallichore-66b7a860.log (log level: debug)
16:24:15 [INFO] Starting Kallichore server at 127.0.0.1:54134
Failed to reconnect to session r-dbc936d0: HTTP 404. 
Failed to reconnect to session python-138d6fe1: HTTP 404. 
16:24:15 [INFO] get_session("r-dbc936d0") - X-Span-ID: "123ad90b-379a-454d-b331-2e9d6da8d99a"
16:24:15 [INFO] get_session("python-138d6fe1") - X-Span-ID: "42ad6333-6d1b-4554-bba2-fc3315fd3e46"
```

**Comment by jmcphers** [comment]
@jthomasmock I have not been able to reproduce this and the video doesn't show how you got into this state. Can you elaborate on this step?

> Launch an existing project in a new Window

What UI gesture did you use to do this? 

Does it happen for all projects?

**Comment by juliasilge** [comment]
I can reproduce the problem Tom describes with this UI from the top bar workspace switcher:

![Image](https://github.com/user-attachments/assets/ffacfeaa-eac3-460c-a21d-741ab2b6d368)

**Comment by juliasilge** [comment]
I see this also in:

Positron Version: 2025.01.0 (Universal) build 71
Code - OSS Version: 1.93.0
Commit: bb6af9753b5342227aa1d4406897951048fba044
Date: 2024-12-12T02:49:20.848Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.1.0

So maybe not related to the merge after all?

**Comment by jmcphers** [comment]
I found a reliable repro! Notes in #5817.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-124
    OS Version          : OSX

### Test scenario(s) 

Verified with Jonathan's instructions on https://github.com/posit-dev/positron/pull/5817

Link(s) to TestRail test cases run or created:
