### ISSUE TITLE
Supervisor: Reconnect to kernel websocket if disconnected

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#5788]
We do not have a reproducible case for this, but at least one user has reported that after a long idle period, the kernel supervisor and Positron lose their Websocket connection, with the result that the kernel can no longer service requests and appears hung.

https://github.com/posit-dev/positron/discussions/5753

Here are some relevant log bits. On the Positron side, it's clear that the kernel was idle, and then the next day we found the websocket closed.

```
2024-12-16 11:41:59.513 [debug] State: busy => idle (execute_request)
2024-12-17 08:56:57.826 [info] Websocket closed with kernel in status idle: {}
```

On the supervisor side:

```
16:41:59 [DEBUG] (21) kcserver::kernel_state: [session r-f0d0ee72] status 'busy' => 'idle' (execute_request)
Session 'R 4.4.0' disconnected while in state 'idle'. This is unexpected; checking server status.
Kallichore server PID 15032 is still running
13:56:57 [WARN] [client r-f0d0ee72-0] Lost connection with client; websocket pong counter is behind by 4 pings
```

In the case where the websocket connection is broken but the supervisor is still running, we should attempt to reconnect the websocket. Right now if we verify that the server is still running, we don't do anything.

https://github.com/posit-dev/positron/blob/74611abf612601fdff47ea97c77934c949d6f75b/extensions/positron-supervisor/src/KallichoreAdapterApi.ts#L537-L540

**Comment by jonvanausdeln** [comment]
### Verified Fixed
Positron Version(s) : [2025.01.0-141](https://github.com/posit-dev/positron-builds/releases/tag/2025.01.0-141)
OS Version(s) : Windows 11

### Test scenario(s) 
We haven't seen any issues in CI.. and `reconnect` in a dev build works as expected (as suggested in #5832 )

### Link(s) to TestRail test cases run or created:
