### ISSUE TITLE
Remove confusing wording in New Project Wizard

### ISSUE THREAD

**Issue by juliasilge** [posit-dev/positron#5814]
In the New Project Wizard, we tell folks that they are not locked in to their choice here:

![Image](https://github.com/user-attachments/assets/5737762a-38a9-4f38-92a3-780a1ddc0cef)

This is intended to be about the running console; you can definitely switch the interpreter running in the console at any time. However, this wording is a bit misleading and/or confusing in most common situations.

- If you are making a Python venv or conda env, it is _extremely_ not easy to switch out the base interpreter in the environment. Basically someone who is about to click "Create" in the screenshot as shown actually is locked into their current choice.
- If you are making a new R project, the wording doesn't make any sense for the vast majority of R users who only have one R installed.

Let's just remove that wording.

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2025.01.0-124
    OS Version          : OSX

### Test scenario(s) 

Wording is gone:
<img width="697" alt="Image" src="https://github.com/user-attachments/assets/876686b3-2b3a-4d7c-a42d-60e907b65308" />


Link(s) to TestRail test cases run or created:
