### ISSUE TITLE
New feature - Labels on collapsed blocks using Quarto

### ISSUE THREAD

**Issue by Cidree** [posit-dev/positron#5826]
Hello. I was wondering if you would find this feature useful to implement in Positron.

When I write the label next to the language of the chunk, the label is shown in a collapsed chunk:

<table>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/4392078d-5939-420d-a3c3-41740b2a1044" alt="Image" width="300"></td>
    <td><img src="https://github.com/user-attachments/assets/147648ed-07ed-40f5-a628-403bc5c1ec73" alt="Image" width="300"></td>
  </tr>
</table>

However, if I use `#| label` syntax, the label is not shown is a collapsed chunk:

<table>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/684bcd13-38ac-4788-bff8-8c7816173fc7" alt="Image" width="300"></td>
    <td><img src="https://github.com/user-attachments/assets/279f8322-2a68-4a46-a86b-625d23a25b57" alt="Image" width="300"></td>
  </tr>
</table>

Although the workaround works well, I think it could be beneficial.

**Comment by nstrayer** [comment]
I believe that this is functionality that would be implemented in the Quarto extension, not Positron. I can check though!

**Comment by juliasilge** [comment]
What @nstrayer says is correct, yep! 

@Cidree would you be up for opening this feature request at <https://github.com/quarto-dev/quarto/issues>? We cannot transfer the issue since it is in a different GH org.

**Comment by Cidree** [comment]
Thank you @juliasilge and @nstrayer .

I will open this issue in Quarto.
