### ISSUE TITLE
Console: Prompt flickers on execute

### ISSUE THREAD

**Issue by seeM** [posit-dev/positron#705]
Frame before execute:

<img width="231" alt="image" src="https://github.com/rstudio/positron/assets/559360/eae3f5c4-86e6-4403-ba56-4a71865f8c26">

Immediately after execute:

<img width="231" alt="image" src="https://github.com/rstudio/positron/assets/559360/ac1e0aed-14ad-495e-94b0-937396882863">

Following that:

<img width="231" alt="image" src="https://github.com/rstudio/positron/assets/559360/18d25654-18fc-4a3a-9a72-6409287035c0">

**Comment by testlabauto** [comment]
### Verified Fixed
    Positron Version(s) : 2024.07.0-97
    OS Version          : OSX

### Test scenario(s) 

I tried many times and was never able to observe the flicker.

Link(s) to TestRail test cases run or created: 
N/A
