### ISSUE TITLE
Bundle Quarto extension with Positron

### ISSUE THREAD

**Issue by jmcphers** [posit-dev/positron#808]
Many customers have asked us to bundle Quarto with the Positron IDE. 

To accomplish this, we need to do the following:

- Include the Quarto extension (https://github.com/quarto-dev/quarto/tree/main/apps/vscode) as a pre-bundled extension. (This Issue)

- Bundle the Quarto CLI itself with the IDE: https://github.com/quarto-dev/quarto-cli (Issue #3705)

**Comment by petetronic** [comment]
Re-opening this issue after many customers have requested we make it simpler to use Quarto out of the box.

**Comment by cboettig** [comment]
I realize this was discussed a lot already. As an instructor I'd love to see quarto bundled.  I've seen many first-reactions to positron now suggesting "it doesn't yet work with quarto".

**Comment by jonthegeek** [comment]
If you want/need to keep a more-minimal bundle, I think quarto is important enough to warrant a set of alternative "Positron with Quarto" assets. I definitely missed it at first along with everyone else, and was very disappointed that ctrl-shift-k didn't work.
